### ISSUE TITLE
error while selecting the source image

### ISSUE THREAD

**Issue by stat2k16** [C0untFloyd/roop-unleashed#102]
While selecting a image for source the error arising. I've attached the file for your reference.

**Details**
What OS are you using?
Answer- Windows 

**Are you using a GPU?**
Answer- Yes, NVIDIA

**Which version of roop unleashed are you using?**
 Answer- 2.0.3

**Screenshot**
![Capture](https://github.com/C0untFloyd/roop-unleashed/assets/142242497/a1722766-3727-415f-a937-a858a716c19a)

**Comment by phineas-pta** [comment]
try lower `--execution-threads`
