### ISSUE TITLE
Error opening Roop - Please see screenshot below

### ISSUE THREAD

**Issue by garna107** [C0untFloyd/roop-unleashed#1025]
Hello, I get this error when trying to launch Roop, even if I click no updates, this still tries to install and does not successfully install. This is the error code: 
![error](https://github.com/user-attachments/assets/1497e041-1a34-43b4-a9dc-46e4bc5c37a8)
Downloading https://huggingface.co/countfloyd/deepfake/resolve/main/GFPGANv1.4.onnx:  97%|▉| 316M/324M [03:23<00:05, 1.
Traceback (most recent call last):
  File "D:\roop-unleashed\roop-unleashed\run.py", line 6, in <module>
    core.run()
  File "D:\roop-unleashed\roop-unleashed\roop\core.py", line 396, in run
    if not pre_check():
  File "D:\roop-unleashed\roop-unleashed\roop\core.py", line 139, in pre_check
    util.conditional_download(download_directory_path, ['https://huggingface.co/countfloyd/deepfake/resolve/main/GFPGANv1.4.onnx'])
  File "D:\roop-unleashed\roop-unleashed\roop\utilities.py", line 217, in conditional_download
    urllib.request.urlretrieve(url, download_file_path, reporthook=lambda count, block_size, total_size: progress.update(block_size))  # type: ignore[attr-defined]
  File "D:\roop-unleashed\installer_files\env\lib\urllib\request.py", line 280, in urlretrieve
    raise ContentTooShortError(
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 330912905 out of 340256688 bytes>

**Comment by C0untFloyd** [comment]
https://github.com/C0untFloyd/roop-unleashed/issues/633#issuecomment-2076614910

**Comment by garna107** [comment]
Hello, it did not work, I manually downloaded and extracted them and still got the same error. When I try to launch Roop and it asked for updates, I say 'n' for no however it still starts downloading something unsuccessfully, is there a way for it to not look for any updates. Below is the screenshot of the error:
![error](https://github.com/user-attachments/assets/1030d9c4-120c-4662-996f-4ee3e427389a)

**Comment by C0untFloyd** [comment]
If you look closely, this is another file which needs to be downloaded. All of them need to be present in your model folder.

**Comment by garna107** [comment]
Hello, 
Thank you for your reply, it is still not working, I get the same error message, can you please tell me which file or files I am missing from the model folder, below is a screenshot of my model folder. Thank you for your help
![models](https://github.com/user-attachments/assets/c6cc8eb1-b112-4539-ba10-be2db2ab9000)

**Comment by C0untFloyd** [comment]
The easy way would be to just copy/paste every failing url into a browser of your choice and download them. Like in your first post https://huggingface.co/countfloyd/deepfake/resolve/main/GFPGANv1.4.onnx
or just download them from the assets I linked previously https://github.com/C0untFloyd/roop-unleashed/issues/633#issuecomment-2076614910

**Comment by garna107** [comment]
Thank you for your help, today when I restarted my pc and opened it again it worked. I wanted to ask one last question, is everything we make on roop shared or downloaded to another server or is it private?

**Comment by garna107** [comment]
I launch Roop, the source images of facesets do not stay or upload? However the target files stay, do you know why this is?

Thank you for your help

**Comment by C0untFloyd** [comment]
> or is it private?

local only, it's your own server after all

 > the source images of facesets do not stay or upload?

The source image will be scanned for all faces, the faces will be displayed in the input faces gallery, afterwards the "box" will be cleared to allow you to add even more images with faces.
There is a wiki here https://github.com/C0untFloyd/roop-unleashed/wiki

**Comment by garna107** [comment]
Hello, 
Thank you for confirming. I have used roop before but a long time ago, the input face does not upload is there a file I am missing? Everything else works, it dectects my GPU etc and uploads target file, I have tried with many different pictures
