### ISSUE TITLE
"Selected face" doesn't work

### ISSUE THREAD

**Issue by mammuthus** [C0untFloyd/roop-unleashed#105]
**Describe the bug**
"Selected face" is set, but it takes face which is not selected

**To Reproduce**
1. Load two face sources and one output source
2. Select second one (in my case I selected female face)
3. Set "Selected face" param in "Select face swapping method" section
![image](https://github.com/C0untFloyd/roop-unleashed/assets/1700286/26158c46-9069-4367-ab21-0e49ca6ab8cf)
5. Start the app and check the result (in my case the roop took male face)
![image](https://github.com/C0untFloyd/roop-unleashed/assets/1700286/400e3a1f-ef1a-436f-b0d0-cf805f0e5893)

**Details**
What OS are you using?
- Windows 

Are you using a GPU?
- NVIDIA

**Which version of roop unleashed are you using?**
Latest

**Screenshots**
In-line

**Comment by C0untFloyd** [comment]
Selected Face means the selected **target face** if there are several.
It's a 1 to 1 relationship with input & target faces, if you would have the female one as first source image, you would have that on the target. This is to be able to swap multiple faces in 1 go.
For Example:

1. SF1
2. SF2

would be swapped to

1. TF1
2. TF2

Input and Target Face Order needs to be the same.

**Comment by eniora** [comment]
Actually this is one of the best features of the new web UI unleashed, to be able to swap multiple faces in one go.😄 and it works really good and easy once you get used to it.
