### ISSUE TITLE
Clearing of output folder upon new generation initiation

### ISSUE THREAD

**Issue by mammuthus** [C0untFloyd/roop-unleashed#106]
**Describe the bug**
Roop-unleashed clears the output folder each time you press 'Start'. This behavior is puzzling. Why does it work this way? I wanted to compare results using different parameters. Now, to prevent the app from deleting them, I have to manually move the output files to another folder.

**To Reproduce**
1. Load sources
2. Start the generation (you must have some files in the `output` folder)
3. The app will remove all files in `output` folder

Test: I have the output file from previous generation (SdKpkS2_fake.mp4) and several empty files created for test.
![image](https://github.com/C0untFloyd/roop-unleashed/assets/1700286/7b4da7f8-754a-42e3-a32e-281fa1dbb24d)

After initiating a new generation, it clears everything in the output folder:
![image](https://github.com/C0untFloyd/roop-unleashed/assets/1700286/adcf0fd7-1a8d-4a0e-a377-e09ea10cb0b9)

**Details**
What OS are you using?
- Windows 

Are you using a GPU?
- NVIDIA

**Which version of roop unleashed are you using?**
Latest

**Screenshots**
In-line

**Comment by eniora** [comment]
You can turn this off by unchecking "Clear output folder before each run" in settings.

**Comment by mammuthus** [comment]
`You can turn this off by unchecking "Clear output folder before each run" in settings. Don't forget to click apply settings after unchecking it.`
Can't see this checkbox, can you help?
