### ISSUE TITLE
Error while using OpenVINOExecutionProvider

### ISSUE THREAD

**Issue by C0untFloyd** [C0untFloyd/roop-unleashed#108]
### Discussed in https://github.com/C0untFloyd/roop-unleashed/discussions/107

<div type='discussions-op-text'>

<sup>Originally posted by **rahulch4nd3l** August 14, 2023</sup>
EP Error C:\Users\intel\Documents\saurabh\onnxruntime\onnxruntime\core\session\provider_bridge_ort.cc:1196 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\Private\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_openvino.dll"
 when using ['OpenVINOExecutionProvider']
Falling back to ['CPUExecutionProvider'] and retrying.
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Private/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
EP Error C:\Users\intel\Documents\saurabh\onnxruntime\onnxruntime\core\session\provider_bridge_ort.cc:1196 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\Private\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_openvino.dll"
 when using ['OpenVINOExecutionProvider']
Falling back to ['CPUExecutionProvider'] and retrying.
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Private/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
EP Error C:\Users\intel\Documents\saurabh\onnxruntime\onnxruntime\core\session\provider_bridge_ort.cc:1196 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\Private\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_openvino.dll"
 when using ['OpenVINOExecutionProvider']
Falling back to ['CPUExecutionProvider'] and retrying.
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Private/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
EP Error C:\Users\intel\Documents\saurabh\onnxruntime\onnxruntime\core\session\provider_bridge_ort.cc:1196 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\Private\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_openvino.dll"
 when using ['OpenVINOExecutionProvider']
Falling back to ['CPUExecutionProvider'] and retrying.
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Private/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
EP Error C:\Users\intel\Documents\saurabh\onnxruntime\onnxruntime\core\session\provider_bridge_ort.cc:1196 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\Private\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_openvino.dll"
 when using ['OpenVINOExecutionProvider']
Falling back to ['CPUExecutionProvider'] and retrying.
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Private/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)

and there is one path that doesn't belong to my pc
 C:\Users\intel\Documents\saurabh\onnxruntime\onnxruntime\core\session\provider_bridge_ort.cc:1196</div>

**Comment by C0untFloyd** [comment]
My first guess would be a broken install. Did you follow the installation from the original roop?

pip uninstall onnxruntime onnxruntime-openvino
pip install onnxruntime-openvino==1.15.0

Is that provider available in the GUI Settings?

**Comment by rahulch4nd3l** [comment]
> My first guess would be a broken install. Did you follow the installation from the original roop?
> Yes I followed all the steps from original roop.

> pip uninstall onnxruntime onnxruntime-openvino pip install onnxruntime-openvino==1.15.0
> did this many times but after uploading image i face that error and Execution provider changes to CPU after image upload.

> Is that provider available in the GUI Settings?
> Yes Provider available in GUI  settings and I select that still facing same.

When I execute run.py, It runs and show this
Using provider ['OpenVINOExecutionProvider'] - Device:cpu
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

After Uploading Image, the above error appears, which switch provider.

**Comment by phineas-pta** [comment]
u need install OpenVino separatedly

https://docs.openvino.ai/install

**Comment by C0untFloyd** [comment]
Yes, it's missing in the roop wiki that of course you need to install the specific runtime (and the PATH need to to be set).

**Comment by rahulch4nd3l** [comment]
Not Working. I think I should stay on Colab.

**Comment by phineas-pta** [comment]
same error or new error ?

provide info about hardware & installation & error, "not working" doesnt tell anything

**Comment by rahulch4nd3l** [comment]
Sorry @phineas-pta , I really appreciate your help, but I deleted all dependencies and build tools. I was using Colab before so I think Colab is best for my personal chores because we can use it on phone too. But I really appreciate your work here.

**Comment by phineas-pta** [comment]
no prob i didnt do anything

just curious if it can work, so other people can use it

**Comment by phineas-pta** [comment]
the full command seem to be:
`pip install openvino onnxruntime-openvino`

**Comment by hornetstimpack** [comment]
Also have same error.

I think the problem is from here

"C:\Users\intel\Documents\saurabh\"

It's also appear to my computer too. And I'm not have user name "intel" or "saurabh".

I think it's bug from hardcode of path somewhere in the code.
