### ISSUE TITLE
Remember EACH FOLDER's Last used: Source and Target - AFTER closing the GUI

### ISSUE THREAD

**Issue by AlonDan** [C0untFloyd/roop-unleashed#11]
### The simple explanation:
Each of the 2 options browsing buttons: Source (face) / Target (video) 
will remember it's OWN last used directory, that was wonderful in MELT and it could be AWESOME in Roop Unleashed :)

---

### The detailed explanation:
At the moment when launching Roop it only remember "Last Folder" used on last session before closing the GUI.

The problem is that, no matter on which one you used: Source (face) or Target (video)
when you press ANY of them it will go to the LATEST used folder in general.

It will be MUCH helpful if it will REMEMBER each specific:
- Remember last folder used of SOURCE 
- Remember last folder used of TARGET

I saw this when it was used on "MELT" the repository that was deleted but was very similar to the original Roop (the first to use InsightFace for face swap) but it's no longer available.

The idea is that you make a Directory for FACES so it's ALWAYS the same directory you don't need to browse to it every time you press "Select image with face(s)" because by default it will remember what you used in the last Roop session (even after closing it)

While TARGET also will remember the directory for itself, in case you have a specific directory where you put Targets, and even if not it will REMIND YOU what target video you used last session based on that "remembered" directory.

**Comment by C0untFloyd** [comment]
Yes, I'm all for this but I would like to have a settings tab and a configuration file where this would be saved among other things. I'm also thinking to move away from the customtkinter GUI over to Gradio however it would be difficult to create modal dialogues like the face selection screen.

I also remember Melt and while researching roop I found a lot of similarities in code and results. So either the guy who created it is the same or it is pretty much a rip-off. This is one of the reason why I started my own fork.

**Comment by AlonDan** [comment]
I don't know much about Tkinter, all I know is that people dislike it when it comes to GUI 😅
Gradio is great and also supporting Drag & Drop (probably Tkinter is well but harder to do or something, I don't know I'm not a programmer).

You have a point! because a bit after Melt disappeared, Roop came out... 🤔

In Melt the all default folders for each was great and it also supported Drag & Drop so it was so easy.

But still, the improvements you've update and fixes from the community makes the current Roop better, I just love how you add all the "upcoming" features to Unleashed already and most of them works very nice! I appreciate your work on it, thank you!💙

**Comment by C0untFloyd** [comment]
Don't want you to leave my repo alone but I recently stumbled over this Gradio enabled roop version -> [https://github.com/harisreedhar/Swap-Mukham](https://github.com/harisreedhar/Swap-Mukham). It even has a HF Space Demo.
Oh and do you know [this](https://github.com/ai-forever/ghost) one? It perfectly retains gaze directions etc., I still would prefer this over SimSwap. My dream swapping tool would have a modular architecture where you could experiment with different engines.

**Comment by AlonDan** [comment]
Thanks for sharing, hehe I'm not leaving your Repo I really love what you do and curious how you'll improve it as things improves 💙

I should look and try it, my problem is that sometimes I can't use Gradio machine because I only have 4GB VRAM on this old rusty machine and Browser uses sometimes more than need. I mean, 32GB on my machine is enough but I'm not planning on using Roop with CPU.. it will take years to render even few seconds.

Maybe you can use Qt instead of Gradio? 
maybe I'll be able to help with some graphic buttons and UI (I'm more into GUI Design, but I'm not a programmer)

---

I heard of Ghost, but it seems like SimSwap, which was my favorite swapping face tool but compare to ROOP... it's not as good or accurate.
I don't think that Ghost used insightFace but probably same approach of SimSwap I'm not sure. Roop is much better in my opinion.

Ghost is impressing with the **emotions**, **gaze** and such which we can't do in Roop but I think it's not up to date, I may be wrong... 

Roop can't use the EXACT emotions, also it's training is limited in eyes for example ROOP won't allow COMPLETLY CLOSED EYES from what I've tested, it uses "eyes looking down" instead, at least in most cases.

---
Roop's problem in my opinion at the moment is that we can't TRAIN our own models,
So we have a small resolution 128x128 (If I'm not wrong) and with all the respect to GFPGAN / GPEN / etc.. they are not supporting interpolated frames so teeth, eyes and other face details flicker and changes during the frames.

It's nice for Stills, for sure! but for videos... I'm not a fan.

The only advantage of SimSwap on Roop is that their trained model MASKING is much more forgiving, for example if we want to swap a face for a person who eats an apple... the apple will be "GHOSTED" over the face, and roop will start to get confused and the face will get shaky etc..

I wish you could use SAM-HQ (or other masking tools you think that may help) so we can do EXTRA MASKING that could be insane!  

The only other solution is if we will be able to TRAIN our own model including BETTER MASKING cases such as "person eating an apple" and other examples to train, because I believe if a hand is over the face ROOP's current model understand that MASKED part because it was part of the database it was trained on, you can see that if somebody pass a hand over the face, it's "trying" it's best, but still not good as SimSwap in that area.

**Comment by C0untFloyd** [comment]
Yes masking the face is biggest problem besides the low resolution of the inpaint model. Thanks for the link to SAM btw. I only knew it from Stable Diffusion before. For masking occluded areas I took a look into Deppface Lab obstruction handling already, but they have their own system where I don't know how hard it would be to port only the segmentation/masking over to roop.

**Comment by AlonDan** [comment]
I believe that DeepFaceLab uses Xseg, which is a very powerful way to manually assign the areas to include / exclude mask areas, but it make sense for training because that's how it works from my experience, you need to do it on some of the SPECIFIC dataset you train.
Unless there are other ways to use Xseg because I'm not up to date, I didn't use it for some years.

The whole idea of Roop and the other "Quick-Swapping" solutions is to not Train every data per result since it's a very long time to do, so Pre-Train which is what we use at the moment based on a low-res model is what we have.

If we'll have a way to TRAIN our own model and share it with the community it will be GREAT! because we can train: Higher Resolution Model, Wider Dataset to contain more angles, light, emotions, etc.. and of course MASKING pre-trained could be AMAZING!

**BUT!**
Since we don't have a way to TRAIN our own models (at least not yet).

My idea was to use **SAM-HQ** because it's not just saying that it segment **ANYTHING**... it does it VERY WELL!
So if we can use it in a way, if you'll find some interesting way to implement it to **ROOP UNLEASHED**... that will be INSANE! 😎

One last thing, if you'll start experiment with "Segment Anything" make sure you're using **[SAME-HQ](https://github.com/SysCV/sam-hq)** and not the first SAM... because the HQ version is **MUCH MORE ACCURATE** you can see the difference in their examples compare to the older SAM.

Also, maybe you should [play with some tests in Meta's demo page](https://segment-anything.com/demo) to see how powerful it is, maybe it will give you some ideas how to implement it to ROOP UNLEASHED.

Please update if you find something it's very exciting and could be super interesting to help testing and give you feedback if you'll manage to work with SAM-HQ :)

Once again, thank you for your hard work! 🙏
