### ISSUE TITLE
No face detected issue

### ISSUE THREAD

**Issue by stat2k16** [C0untFloyd/roop-unleashed#110]
**Describe the bug**
While selecting the source image, an error keeps popping up that no face detected. I've already tried with different faces. Still have the same issue. Please help me out. For your reference I attached a screenshot.

**Details**
What OS are you using?
- [ ] Windows 

Are you using a GPU?
- [ ] NVIDIA

**Which version of roop unleashed are you using?**
2.7.3

**Screenshots**
![Capture1](https://github.com/C0untFloyd/roop-unleashed/assets/142242497/6e9d7ffd-f0c6-4125-8e92-88264a59f695)

**Comment by eniora** [comment]
I used the same pic from your screenshot (which ended up being only 200x300 resolution) and it still detected the face from it. Not sure what's wrong with your roop unleashed. Try reinstalling the requirements again.

![Screenshot 2023-08-15 151853](https://github.com/C0untFloyd/roop-unleashed/assets/116663473/2e3f33d9-6ec0-4556-98bb-a622099f4975)

**Comment by stat2k16** [comment]
I tried reinstalling. But still the same issue. Any solution ?

**Comment by C0untFloyd** [comment]
Can you paste parts of the terminal output here? I suspect the face detection model isn't downloaded or corrupted. It's definitely something with your installation.

**Comment by stat2k16** [comment]
Microsoft Windows [Version 10.0.19045.3324]
(c) Microsoft Corporation. All rights reserved.

C:\Users\KK\Documents\Deepfake\roop-unleashed\venv\Scripts>activate

(venv) C:\Users\KK\Documents\Deepfake\roop-unleashed\venv\Scripts>cd ..

(venv) C:\Users\KK\Documents\Deepfake\roop-unleashed\venv>cd ..

(venv) C:\Users\KK\Documents\Deepfake\roop-unleashed>python run.py --execution-provider cuda
Using provider ['CUDAExecutionProvider'] - Device:cuda
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\KK/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\KK/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\KK/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\KK/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\KK/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
2023-08-15 20:57:03.5663831 [E:onnxruntime:, sequential_executor.cc:514 onnxruntime::ExecuteKernel] Non-zero status code returned while running Resize node. Name:'Resize_124' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device
Traceback (most recent call last):
  File "C:\Users\KK\Documents\Deepfake\roop-unleashed\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\KK\Documents\Deepfake\roop-unleashed\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\KK\Documents\Deepfake\roop-unleashed\venv\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\KK\Documents\Deepfake\roop-unleashed\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\KK\Documents\Deepfake\roop-unleashed\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\KK\Documents\Deepfake\roop-unleashed\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\KK\Documents\Deepfake\roop-unleashed\venv\lib\site-packages\gradio\utils.py", line 706, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\KK\Documents\Deepfake\roop-unleashed\roop\ui.py", line 386, in on_srcimg_changed
    raise gr.Error('No faces detected!')
gradio.exceptions.Error: 'No faces detected!'

**Comment by stat2k16** [comment]
Yes. It's 940MX.

**Comment by C0untFloyd** [comment]
This is not supported, it's just too old, I'm afraid. You can still face swap using your CPU though.

**Comment by Hanzalah-Adalan** [comment]
> You can still face swap using your CPU though.

how can I switch to CPU mode? my GPU is unsupported too :)

**Comment by elverg0n1** [comment]
yo tengo el mismo problema que el bro mi tarjeta grafica  es bastante mala es de una notebook es una UHD GRAPICS 620 y en la parte de provedor pongo cpu aplico los cambios y reinicio el servidor y aun asi me  sigue dando el errorr de deteccion de rostros y la verdad no se que hacer :c

**Comment by senseirain** [comment]
same problem here,..  it worked early but didn't save the output file when i refreshed it can't detect the input photo AMD GPU here
