### ISSUE TITLE
is there a way to free the cache memory?

### ISSUE THREAD

**Issue by StefanAC99** [C0untFloyd/roop-unleashed#112]
**Describe the bug**
i'm getting the out of memory message "CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 6.00 GiB total capacity; 1.25 GiB already allocated; 0 bytes free; 1.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF"

**To Reproduce**
run it

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
v2.7.0
**Screenshots**
non

**Comment by PradeepBirare** [comment]
"CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 4.00 GiB total capacity; 1.25 GiB already allocated; 0 bytes free; 1.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF"
A clear and concise 

ce_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=LAPTOP-MFL69LGQ ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=168 ; expr=cublasCreate(&cublas_handle_);

what to do i am getting the above error nvidia gpu ,windows?

**Comment by C0untFloyd** [comment]
Either lower threads to just 1 or switch to use CPU. 4 Gb VRAM is honestly too little for most needs.

**Comment by PradeepBirare** [comment]
> Either lower threads to just 1 or switch to use CPU. 4 Gb VRAM is honestly too little for most needs.

Then why my PC can handle high end games with this much gpu

**Comment by phineas-pta** [comment]
AI need more VRAM
