### ISSUE TITLE
does not work on CPU or AMD GPU

### ISSUE THREAD

**Issue by jaki444** [C0untFloyd/roop-unleashed#120]
when I try to make any faceswap does not work because it puts me cuda and if I try to change it from the gui with the server restart or opening and closing the program back in cuda and then become useless for AMD GPU with acceleration and for a cpu. Can you help me? How do I run it in cpu or AMD GPU?

What OS are you using?
Windows 

Are you using a GPU?
AMD and CPU amd ryzen 5 5600

Which version of roop unleashed are you using? 
2.7.3

**Comment by chakaflus** [comment]
Hi, you closed this issue, how did you fixed it? I'm having the same problem.
Thanks
