### ISSUE TITLE
[Feature Suggestion]: Auto-Load + Presets

### ISSUE THREAD

**Issue by AlonDan** [C0untFloyd/roop-unleashed#126]
One of the things that I would like to see is either a PRESET or AUTO-LOAD for Source Faces.
The idea is simple:
In my tests I mostly use different faces on specific directories, so I pretty much use groups of faces, for example: Female only, Male only, Celebs, Generated Faces, etc..

Instead of Load every single time One face by One, drag and drop... again and again.
Can we get these features?

- **AUTO-LOAD**: 
This feature could work either for LAST USED Faces (from latest session) 
or based on a Specific Default Folder (Settings could be helpful to choose which one will be the default).

- **Presets**: 
Adding a Button or Dropdown to Save / Load and Presets:
The idea is to Drag & Drop the Faces you want, Save as Preset, in the future LOAD or just flip to other group of Source Faces, instead of Drag & Drop every single time.

I originally noticed how helpful it is in ROPE, but **they don't use presets** but only keep a "model" that basically save these directories.

TIP:
Since it means we'll need to make multiple Folders I highly suggest that it will allow us to make MAIN folder, and each SUB-FOLDER will be it's own, it's just easier to maintain, update, and organize everything in one place.

---

Last thing:
Presets could be for OTHER sections on the Gradio interface, for example what if we're using the SAME values or options of anything on the GUI, why not making a preset that can be save and loaded.
Maybe in Settings - to allow a toggle from: "Load latest used parameters" when launch
or "Reset to Factory Default" which is what we currently have.

I hope you'll consider these suggestions, Thank you for your hard work! 🙏

**Comment by C0untFloyd** [comment]
Saved Presets are nice to have ff course, allows for better usability it's just so boring to code and test. Do you guys know [this](https://glucauze.github.io/sd-webui-faceswaplab/features/) ? Scroll down to **Face Reuse Via Checkpoints** to see what I mean. This creates very small checkpoint files from the facial features, which can then used as some kind of preset for any other face. Also it's possible to blend several faces together. I didn't check this out, did one of you?

Btw. @AlonDan is https://replicate.com/arielreplicate/robust_video_matting something you desired?

**Comment by eniora** [comment]
This would indeed be helpful!

> Do you guys know [this](https://glucauze.github.io/sd-webui-faceswaplab/features/)

Yah I tested it a week ago, it works very good and can make really good and funny swaps but it's mostly a face merger/blender and not simply a swapper from what I tested. I didn't test it good enough to use the checkpoints feature though which seems really interesting now that you mentioned it.

**Comment by AlonDan** [comment]
> Saved Presets are nice to have ff course, allows for better usability it's just so boring to code and test. Do you guys know [this](https://glucauze.github.io/sd-webui-faceswaplab/features/) ? Scroll down to **Face Reuse Via Checkpoints** to see what I mean. This creates very small checkpoint files from the facial features, which can then used as some kind of preset for any other face. Also it's possible to blend several faces together. I didn't check this out, did one of you?
> 
> Btw. @AlonDan is https://replicate.com/arielreplicate/robust_video_matting something you desired?

Sorry for the late reply I just saw your message,
I used RVM as soon as it was a new thing (waaay before SAM and NAM) 
even on it's evolution that called something like background Matte and v2 which where nice... unfortunately it's not as good as it looks in the DEMO you need a VERY CRISP SHARP High Quality video with Humans only (full body or portfolio) the dataset it was trained is very limited to that purpose unlike SAM-HQ which doesn't care what segment I want even if it's just a tree or a dog, or even a Hat... it could be any segment.

I gave up on RVM a long time ago after months of tests, sometimes it's ok, most of the cases it will not do a nice job and a lot of flickering and bad segment parts won't even count so it's not the solution.

Thanks for remember! I'm still looking for SAM-HQ friendly for video matting, I did ran into some, but couldn't even understand how to make them work so I'll keep looking, probably someone eventually will understand the easy job it can do without rotoscoping manually, especially with SAM-HQ and NAM (not sure which is better to be honest, but it's the same spirit.

**Comment by C0untFloyd** [comment]
I'm still interested in this. Making a batch processing version out of the Sam HQ Demo using grounding dino would be a piece of cake. What is NAM? Googled for it but only found vietnamese restaurants 😅

**Comment by AlonDan** [comment]
> I'm still interested in this. Making a batch processing version out of the Sam HQ Demo using grounding dino would be a piece of cake. What is NAM? Googled for it but only found vietnamese restaurants 😅

Sounds cool, I'm glad you're interested in such tool!
If you'll make this either as extra feature or it's own App I'll be sure help testing it and give you feedback!

Sorry it's MAM, for some reason I typed NAM... 
From my understanding it is "Matting Anything Model" which supposed to give better more efficient results than SAM but... that was before SAM-HQ so I don't know which one gives better result... worth testing or even better:

In most SAM supported apps, you can choose from different models:
The Lite one (for mobile phone, I never liked it's results), the Medium, and High
The same goes for SAM-HQ = this should be your target with MAM anything below is too old or won't do better job.
Just like SAM model improved to SAM-HQ (larger data + extra training) it may keep getting improved and more accurate, efficient, faster, etc.. 

My point is, that at the moment from what I've tried at least is:
SAM-HQ + MAM are the best out there for matting, but my impression is that MAM is more efficient for MATTING which could be more efficient (or not, I never compared)

You can see a comparison in the "[**Matting-Anything**](https://github.com/SHI-Labs/Matting-Anything)" repository and also read about the technical stuff (I'm not a programmer I only know the theory as a post-production user)

If you're wondering why I just didn't use that repository, I tried it was super confusing to me and I couldn't get it to work, so maybe you'll be able to make it work and **FORK** something better for us "simple" users ;)

I highly recommend to make it it's **own APP** if possible, maybe later you can merge it as extra option... I just think it could serve by itself as a very simplistic GUI with less confusing options first, cleaner, 1-2-3 steps kind of App. (just a suggestion)

---
Allow me to help with a basic approach / design of this APP (I hope it's ok with you)
As a user I know what are the needs, but I'll do my best to start simple as possible because I won't lie there are more ideas to ADD later... first we need the basic structure and flow of what this App can do and how to use it (UX at least)

### It may be a good start for you to start.
Maybe you should make a dedicated Gradio (or GUI) since the idea supposed to be simple:

1. The MAIN WORK AREA for the Video / Footage:
- Drag & Drop the SOURCE: video or Image Sequences.
It's important to be able to Drag Forward / Backwards freely

- Toggle ON/OFF to see with Segments above footage / Without sometimes while drawing segments you like to see the original and compare.

- Extra options to toggle modes ON/OFF to show SEGEMENTS ONLY / ALPHA ONLY etc..

- Split from start to LEFT / RIGHT Previews: (this is a "maybe" UI design choice)
1 - LEFFT: Original Footage (source) preview + Working area (brush, etc..)
2 - RIGHT: Result preview to Auto-Refreresh on every change
It may be more convenient to work and see instead of comparing as I suggest above.

- Drawing tools: BRUSH + ERASER for manual control (both with size / radius slider)

- UNDO / REDO for drawing the tracked areas is important (also for other things that you may find needed)

- Other tools I'm probably forgetting because I'm typing out of my head...

--

2. Options (this is where you give us users the nice controls)
A - Select what Model to use (high quality models are slower but more accurate)
SAM-HQ - usually have H, M, L or something to tell which one is HIGHER quality
MAM - I'm curious about how good it is compare to SAM-HQ 
but it will be nice to allow SELECT the model and be able to change.

B - Segment normal quality (usually edges are pixelated) not very useful
- Segment + Edge Refinement (you can see some examples of how [accurate it can get](https://github.com/hustvl/Matte-Anything))
Basically, it's a toggle ON/OFF for 

C - More to come - there are ideas, let's start simple as possible for first phase ;)

--

3. Select the Segment or Multiple Segment via DIFFERENT WAYS:
- Selection: Point to Point - Top Left to Bottom Right, creating a region box
- Selection: Box drawing - Drawing a box that will include any segment in it
- Selection: Scrap - Drawing a point or line within the Segments you want
- Ground Dino - via prompts (with positive and negative)

--

4. Like more advanced trackers:
- Track from Start to End or from End to Start (most expected feature)
- Track from MIDDLE of the video (or sequence images) to End and then from Middle to Start so if it's a LOOP or SHORTER for example it will be most accurate
- Track from ANY point (any frame) of the video FORWARD or BACKWARD
- Display probably with different color: "Already Tracked" so you know if it's tracked before moving to the next stage

--

5. Render / Start Process
- RENDER BUTTON to start "COOKING" 
- STOP BUTTON to cancel the current process
- PAUSE (optional) to resume
- Showing Estimate time to end and Progress bar % is a good start
- While rendering showing a PREVIEW will be VERY helpful to see if it does the job

---
Sorry for the long WOT, as you can see I'm very hyped about such App and since I know what users will mostly be happy with, I shared this based on my knowledge and experience in the area... just keep in mind, I'm not a programmer so I can't help much more than UI/UX and design in general.

I hope that this helped a bit, if you'll decide to work on such App, thanks ahead! 🙏
