### ISSUE TITLE
Semi-zoomed images return "No Face Detected"

### ISSUE THREAD

**Issue by ialhabbal** [C0untFloyd/roop-unleashed#127]
**Describe the bug**
Program return No Face Detected on images that are semi-zoomed or zoomed.

**Details**
What OS are you using?

- [ ] Windows 

Are you using a GPU?

- [ ] NVIDIA

**Which version of roop unleashed are you using?** Gradio

**Comment by C0untFloyd** [comment]
It's a know problem with the face swapper model.
Uncheck the `Use default det-size checkbox` to have face detection working with extreme closeups. You need a complete restart after doing this.
