### ISSUE TITLE
Select Target Folder AFTER video target is loaded = TMP file leftovers?

### ISSUE THREAD

**Issue by AlonDan** [C0untFloyd/roop-unleashed#13]
**Describe the bug**
1.  When loading a Target Video file, and then "Select Target Folder", it won't "FORGET" the previous loaded and will still create a TMP file on rendering / "start"

2. Using Preview button with "Select Target Folder" will show the latest loaded video, same like above, it needs to delete it from memory to forget it or something.

**Suggestion**
When PREVIEW on "Select Target Folder" just show the first frame on the folder (by name) or...
Even nicer idea: show a RANDOM frame from the folder each time you press Preview!

I guess this is because you can extract both Video + Folders at the moment but it's a bit confusing, maybe only ONE per time, or enable/disable for both or one of them per render.

---

**To Reproduce**
1. Load Surce Face + Target Video
2. Click on 'Preview'
3. Press: 'Select Target Folder' and browse to a folder with multiple stills
4. press 'Preview' shows the previous loaded Target Video (that's issue 1)
5. press 'Preview' do not show anything from "Select Target Folder" used (suggestion above)
6. press 'Start' creates a TMP file from the latest selected target video

**Details**
What OS are you using?
- [x] Windows 

Are you try to use a GPU?
- [x] NVIDIA

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by C0untFloyd** [comment]
Fixed in gradio branch
