### ISSUE TITLE
It uses CPU executioner even if I choose cuda in the settings for face swapping

### ISSUE THREAD

**Issue by SmoothBrainApe** [C0untFloyd/roop-unleashed#130]
**Describe the bug**
It uses CPU executioner even if I choose cuda in the settings for face swapping. It initially detects cuda when opening roop unleashed but when swapping it switches to CPUExecutionProvider automatically. I included terminal log below

**To Reproduce**
1. try swapping any face on a video

**Details**
What OS are you using?
- [ x] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
I just git pulled today so latest at this time of writing

**Screenshots**
Using provider ['CUDAExecutionProvider'] - Device:cuda
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Gtk-Message: 15:54:32.691: Failed to load module "xapp-gtk3-module"
Binubuksan sa kasalukuyang session ng browser.
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/chupz22/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/chupz22/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/chupz22/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/chupz22/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/chupz22/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
[ROOP.CORE] Processing video /home/chupz22/roop-unleashed/temp/25e5f38f10950dbdfe6e241278794f922dba5625/CP1Test.mp4
[ROOP.CORE] Creating video with 30.0 FPS...
['ffmpeg', '-hide_banner', '-hwaccel', 'auto', '-y', '-loglevel', 'error', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '1920x1080', '-pix_fmt', 'bgr24', '-r', '30.0', '-an', '-i', '-', '-vcodec', 'libx264', '-crf', '14', '-vf', 'colorspace=bt709:iall=bt601-6-625:fast=1', '-pix_fmt', 'yuv420p', '/home/chupz22/roop-unleashed/output/CP1Test_fake.mp4']
Processing:   0%|                                                                                   | 0/297 [00:00<?, ?frame/s]Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Processing:   3%|█                              | 10/297 [00:17<06:14,  1.30s/frame, memory_usage=07.79GB, execution_threads=8]

**Comment by phineas-pta** [comment]
make sure to have cuda 11.8 not 12

**Comment by SmoothBrainApe** [comment]
I have 11.8. I was using pregradio version and it was working perfectly. This only happened after git pull

**Comment by primeinc** [comment]
Have you tried a complete reset?
```
git checkout main
git fetch
git reset --hard origin/main
```
Be cautious when using this command, as it will erase all local changes and commits that aren't in the origin/main branch

It might also be worth deleting your venv and recreating it as well.

If that doesn't help, does changing from `libx264` codec to `libvpx-vp9` make a difference?

**Comment by SmoothBrainApe** [comment]
I did a complete reinstall and it is working fine now. Thanks for the help
