### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by Rynally1008** [C0untFloyd/roop-unleashed#131]
Cant launch cuz fails to find the torch module :(

Check for Updates? [y/n]n
Launching App
Traceback (most recent call last):
  File "C:\Users\Downloads\roop-unleashed-main\installer\roop-unleashed\run.py", line 3, in <module>
    from roop import core
  File "C:\Users\Downloads\roop-unleashed-main\installer\roop-unleashed\roop\core.py", line 15, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

Done!
Press any key to continue . . .

**Comment by eniora** [comment]
try in CMD:
`pip install torch==2.0.1+cu118 torch==2.0.1 torchvision==0.15.2+cu118 torchvision==0.15.2`

**Comment by sordidloam** [comment]
Check for updates and/or  re run requirements.txt from documentation. Sent from my iPhoneOn Aug 18, 2023, at 6:15 PM, eniora ***@***.***> wrote:﻿
try in CMD/terminal:
pip install torch==2.0.1+cu118 torch==2.0.1 torchvision==0.15.2+cu118 torchvision==0.15.2

**Comment by Rynally1008** [comment]
> try in CMD/terminal: `pip install torch==2.0.1+cu118 torch==2.0.1 torchvision==0.15.2+cu118 torchvision==0.15.2`

it came back as this

ERROR: Could not find a version that satisfies the requirement torch==2.0.1+cu118 (from versions: 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch==2.0.1+cu118

**Comment by Rynally1008** [comment]
> Check for updates and/or  re run requirements.txt from documentation. Sent from my iPhoneOn Aug 18, 2023, at 6:15 PM, eniora ***@***.***> wrote:﻿ try in CMD/terminal: pip install torch==2.0.1+cu118 torch==2.0.1 torchvision==0.15.2+cu118 torchvision==0.15.2 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

yes, everytime i check for update it ends like 

ERROR: Failed building wheel for insightface
Failed to build insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects

**Comment by Rynally1008** [comment]
![image](https://github.com/C0untFloyd/roop-unleashed/assets/58795466/ec1c0789-0036-432d-a146-bdd5018241bb)
it seems like all the modules after torch is missing

**Comment by eniora** [comment]
You need to install visual studio build tools, make sure to check C++ development during installation.

**Comment by davioni** [comment]
having same issue
