### ISSUE TITLE
color of the photo does not change?

### ISSUE THREAD

**Issue by amfapic** [C0untFloyd/roop-unleashed#133]
hello.
Is it possible that the color of the photo does not change and does not become the color of the video?

**Comment by C0untFloyd** [comment]
Uumm what?!? 😕

**Comment by amfapic** [comment]
> Uumm what?!? 😕

I mean that the color of the source photo should be preserved and not changed to the color of the destination video. what's the way؟

**Comment by eniora** [comment]
@amfapic Not sure if I understand you correctly but that's the idea of roop? it blends the source photo face into the target video/photo including the colors so it doesn't appear out of place.. 🤔

**Comment by amfapic** [comment]
> 

thank you .But for some purpose, I need to blend the source image with the destination video without changing its color. is it possible? What is the solution?

**Comment by eniora** [comment]
Hm nope, you can't do that with the current unleashed frame processor. I believe you would need to write your own frame processor for that and not sure if it would even work.

**Comment by amfapic** [comment]
> you can't do that with the current unleashed frame processor. I believe you would need to write your own frame processor for that and not sure if it would even work.

Is it possible to swap the full head and not just the face?

**Comment by C0untFloyd** [comment]
[This way](https://github.com/iperov/DeepFaceLab) Sir...
