### ISSUE TITLE
Flicker?

### ISSUE THREAD

**Issue by TrickleDownClown** [C0untFloyd/roop-unleashed#137]
Roop wouldn't flicker at all so I assume it's the segment stuff causing it but even frames where segments aren't used it seems to flicker now when original roop didn't.  Is there a way around it someone has found?  I know some people use deflicker in davinci. Did anyone have any luck with that?

**Comment by TrickleDownClown** [comment]
*By original roop I mean roop unleashed* sorry about that.

**Comment by C0untFloyd** [comment]
What kind of flicker are you talking about? Bouncing between faces? Wrong frame order? Something else?

**Comment by TrickleDownClown** [comment]
Bouncing between faces.

**Comment by C0untFloyd** [comment]
If you're talking about faces switching back to the original, this is very much depending on your selected face similarity. Other than the insightface model doesn't detect faces at extreme angles, this hasn't changed over time and will always be a problem, with all roops.
