### ISSUE TITLE
"Frame processor face_enhancer not found."

### ISSUE THREAD

**Issue by exnex** [C0untFloyd/roop-unleashed#14]
**Describe the bug**
Running windows_run.bat, when it gets to "Launching App", it gives the error, "Frame processor face_enhancer not found."

**To Reproduce**
1. Run windows_run.bat
2. "Frame processor face_enhancer not found."

**Details**
What OS are you using?
- [X] Windows 

Are you try to use a GPU?
- [X] NVIDIA

**Sanity Check**
- [X] I have the latest code from the github repository
- [X] I have followed the installation guide
- [X] I have confirmed "face_enhancer.py" is correctly located in frames subfolder

**Comment by MAXXXEH69** [comment]
I was just about to log this same issue

Windows 11

**Comment by C0untFloyd** [comment]
Please update and try again, I just submitted a hotfix

**Comment by alecmc20** [comment]
Also on windows, also on an nvidia gpu, and it was working for me before 2.0 - just updated and it's giving me the same error

**Comment by C0untFloyd** [comment]
Please see #20

**Comment by zharvz** [comment]
This is still happening here. #20 Didn't solved for me. I installed today so I assume it's updated. git pull shows "Already up to date.". Regular roop is working fine, this isn't. I tried to copy models folders to roop-unleashed main directory and it didn't worked too. I'm running linux with cuda 11.8 on a conda environment.
