### ISSUE TITLE
Headless does not work out of the box (index out of range)

### ISSUE THREAD

**Issue by sftpct** [C0untFloyd/roop-unleashed#140]
**Describe the bug**
Using the UI works fine. It swaps faces as intended. However, when trying to run headless, I get an "out of range" issue:

```
python run.py -s ~/Downloads/sources/source.jpeg -t ~/Downloads/targets/candidate3.mp4 -o ~/Downloads/test_output.mp4 
Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
find model: /Users/user/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
find model: /Users/user/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
find model: /Users/user/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
find model: /Users/user/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
find model: /Users/user/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Traceback (most recent call last):
  File "/Users/user/dev/roop-unleashed/run.py", line 6, in <module>
    core.run()
  File "/Users/user/dev/roop-unleashed/roop/core.py", line 385, in run
    start()
  File "/Users/user/dev/roop-unleashed/roop/core.py", line 192, in start
    roop.globals.TARGET_FACES.append(faces[roop.globals.target_face_index])
IndexError: list index out of range
```

Upon looking at the code, it seems that this is because a face was not found, so faces is an empty list. But, the UI is able to detect a face at frame 0 (the default frame) when using the "Face Swap Frame" feature.

There is a discrepancy between the behavior of the UI and headless.

**To Reproduce**
1. Install requirements in venv
2. Pick a source file and a target file that both work in the UI's face swap on frame 0.
3. Run `python run.py -s ~/Downloads/sources/source.jpeg -t ~/Downloads/targets/candidate3.mp4 -o ~/Downloads/test_output.mp4`
4. Receive error above

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [x] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [x] Mac

**Which version of roop unleashed are you using?**
2.7.7

**Screenshots**

**Comment by eniora** [comment]
It says in the [knowns issues](https://github.com/C0untFloyd/roop-unleashed/issues/81) that CLI commands don't work well and need a revamp.

**Comment by sftpct** [comment]
@eniora Apologies, you are totally right.
