### ISSUE TITLE
Using CoreML as execution provider results in memory leaks (OOM). unable to cap

### ISSUE THREAD

**Issue by sftpct** [C0untFloyd/roop-unleashed#141]
Apologies for submitting so many issues that were immediately closed- I see now that many of them were self resolvable. However, I believe I have found another issue that hopefully has not been addressed by the open issue list.

**Describe the bug**
Using the Web UI, kicking off a job with CoreML set as the execution provider results in growing memory until OOM. I see in activity manager that the RAM grows very rapidly, without bounds. Once it hits 120GB, the process self terminates with the error output below:

```
Processing took 50.1365180015564 secs
ffmpeg -hide_banner -hwaccel auto -y -loglevel error -i /Users/user/sandbox/roop-unleashed/output/candidate3_fake.mp4 -i /Users/user/sandbox/roop-unleashed/temp/36c151fa64fadac1a0cedd1271603a35646dbd62/candidate3.mp4 -c:v copy -map 0:v:0 -map 1:a:0 -y /Users/user/sandbox/roop-unleashed/output/candidate3_fake_final.mp4
[ROOP.CORE] Processing video /Users/user/sandbox/roop-unleashed/temp/dfd36ffb8e2fcaaa0a4822da2092aebc326342df/candidate4a.mp4
[ROOP.CORE] Creating video with 25.0 FPS...
['ffmpeg', '-hide_banner', '-hwaccel', 'auto', '-y', '-loglevel', 'error', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '640x360', '-pix_fmt', 'bgr24', '-r', '25.0', '-an', '-i', '-', '-vcodec', 'libx264', '-crf', '14', '-vf', 'colorspace=bt709:iall=bt601-6-625:fast=1', '-pix_fmt', 'yuv420p', '/Users/user/sandbox/roop-unleashed/output/candidate4a_fake.mp4']
Processing:  42%|█████████▏            | 911/2170 [03:29<03:26,  6.10frame/s, memory_usage=12.80GB, execution_threads=4][1]    88949 killed     python run.py
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

I see that we have a max-memory arg; however, setting this above 0 in the UI results in an integer overflow. I have tried 1, 4, 16, etc. I have 128GB of physical RAM and 100GB of free ram according to activity monitor before running.

```
  File "/Users/user/sandbox/roop-unleashed/roop/ui.py", line 626, in start_swap
    batch_process([file.name for file in target_files], use_clip, clip_text, processing_method == "In-Memory")
  File "/Users/user/sandbox/roop-unleashed/roop/core.py", line 262, in batch_process
    limit_resources()
  File "/Users/user/sandbox/roop-unleashed/roop/core.py", line 129, in limit_resources
    resource.setrlimit(resource.RLIMIT_DATA, (memory, memory))
OverflowError: Python int too large to convert to C long
^C%                                                       
```

None of these issues occur in CPU. Although monumentally slower, the memory is capped at 2.5GB the entire time. No other settings are changed to cause this.

**To Reproduce**
1. Install
2. Launch UI `python run.py`
3. In settings, set execution provider to CoreML. Restart the app
4. Launch UI again, verify in settings that CoreML is chosen.
5. Choose a target and source. Pick a large enough target (3 minutes).
6. Click Start.
7. Observe in Activity Manager that `Python` 's memory usage is growing exponentially.
8. Observe that once the memory grows to the system cap (128 GB for me), the program terminates with the message at the top of the issue.

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [x] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [x] Mac

**Which version of roop unleashed are you using?**
2.7.7
**Screenshots**

**Comment by phineas-pta** [comment]
the problem with `onnxruntime-silicon` is well known since beginning of roop, and dont upgrade to v1.15 face get distorted

solution for now is a custom built wheel https://github.com/cansik/onnxruntime-silicon/releases/tag/v1.14.2

**Comment by C0untFloyd** [comment]
Oh thank you Phineas, I wouldn't have known! This is a general onnxruntime problem with Apple Software? This needs to be in the wiki...

**Comment by phineas-pta** [comment]
unfortunately roop disable issues so i couldnt point to the discussion, and facefusion docs still show **incorrect** solution https://docs.facefusion.io/troubleshooting

in roop and facefusion discord u can still find my post about it

**Comment by sftpct** [comment]
Thank you for the swift and concise reply @phineas-pta @C0untFloyd  . After using pip to install the custom whl, the issue has been resolved. It is now hovering over 3.19GB and not increasing exponentially.

**Comment by sftpct** [comment]
Not to do a driveby, but is the Overflow error i posted above a known issue?

**Comment by phineas-pta** [comment]
the `OverflowError: Python int too large to convert to C long` when u set `--max-memory` ?

yes due to some unit conversion in the code, on macOS u cannot go above 8gb

**Comment by phineas-pta** [comment]
the `OverflowError: Python int too large to convert to C long` when u set `--max-memory` ?

yes due to some unit conversion in the code, on macOS u cannot set above 8gb

if memory leak is resolved u can get rid of it

**Comment by sftpct** [comment]
Gotcha— because the memory leak is resolved anyways, it seems I won't need to set a limit. Setting the limit to 0 to get no limit is working okay.

There's still a slight memory leak when using GFPGAN, though I don't know 
how much of it is a memory leak, or the fact that I set the memory limit to 0.

<img width="822" alt="image" src="https://github.com/C0untFloyd/roop-unleashed/assets/142684617/20cc5837-41fe-4b29-b672-47318517d753">

**Comment by sftpct** [comment]
Looking at the terminal output, it seems this is indeed a memory leak because the reported memory usage is different from actual usage

```
ate missionary.mp4
[ROOP.CORE] Creating video with 50.0 FPS...
['ffmpeg', '-hide_banner', '-hwaccel', 'auto', '-y', '-loglevel', 'error', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '2400x1080', '-pix_fmt', 'bgr24', '-r', '50.0', '-an', '-i', '-', '-vcodec', 'libx264', '-crf', '14', '-vf', 'colorspace=bt709:iall=bt601-6-625:fast=1', '-pix_fmt', 'yuv420p', '/Users/jusunglee/sandbox/roop-unleashed/output/intimate missionary_fake.mp4']
Processing:  49%|██████████▎          | 1120/2273 [23:53<31:44,  1.65s/frame, memory_usage=09.51GB, execution_threads=8]
```

Notice that it says 9.51GB here but activity monitor says 100GB +

**Comment by sftpct** [comment]
Seems what roop is reporting for memory usage is not the same as true system memory. Seems to be only growing further and further. I must admit, it is way less egregious than with the issue patched above



```
Processing:  59%|████████████▎        | 1333/2273 [29:42<26:17,  1.68s/frame, memory_usage=09.80GB, execution_threads=8]
```

**Comment by phineas-pta** [comment]
enhancer doesnt release memory

also dont do p*rn

**Comment by phineas-pta** [comment]
enhancer doesnt release memory, it's also known bug

im not moral police but keep it to yourself

**Comment by retret66** [comment]
Coreml seems like not working yet? Or was it removed? In any case I use 21-Core for processing on Mac Ultra M2 and it is almost 3.5x faster than my AMD with GPU support on Ubuntu. A 4min video only takes like 1.5Hr on my Mac instead of over 5hrs on Ubuntu..

Processing:  49%|███████████████████▉                     | 2530/5187 [43:19<45:29,  1.03s/frames, memory_usage=10.60GB, execution_threads=5

**Comment by C0untFloyd** [comment]
You're asking about CoreML being removed but tell that your Mac is processing faster than your AMD gpu?!?
Or did you mean to ask about DirectML (AMD)? In either case, no nothing was removed but of course you need to install the necessary onnxruntimes yourself.

> A 4min video only takes like 1.5Hr on my Mac instead of over 5hrs on Ubuntu..

Both is very slow. The suggested number of threads for DirectML is just 1, perhaps you should lower it for your Mac too, I think 5 is too high. Sometimes less is more 😃

**Comment by retret66** [comment]
no I already tested this and it is faster than my AMD and yes I have onnyx with no errors and a 4min video took about 45min for 1280x720 instead of 1080p. Still it is pure CPU because the coreML when selected in the settings will crash and it is in the dropdown list

**Comment by C0untFloyd** [comment]
It would be great to have a dump where it's crashing because as I said nothing's changed.
