### ISSUE TITLE
new download links for models

### ISSUE THREAD

**Issue by phineas-pta** [C0untFloyd/roop-unleashed#142]
old link is removed: https://huggingface.co/henryruhs/roop

new link: https://huggingface.co/facefusion/models

**Comment by eniora** [comment]
Unleashed uses its own [links](https://huggingface.co/countfloyd/deepfake) to download the models since the gradio update but ye should be updated for the old pre gradio build since it can still be downloaded from the github releases page.

**Comment by C0untFloyd** [comment]
Yes, but thank you for the heads up.
