### ISSUE TITLE
"ffmpeg is not installed" but it is 

### ISSUE THREAD

**Issue by WineWG** [C0untFloyd/roop-unleashed#149]
**Describe the bug**
When I press the start button I get "file not found error and I think this is related to the fact that every time I start roop it tells "ffmpeg is not installed". But ffmpeg is installed and it is on the path, i can run it from the terminal and it works. The problem must lie elsewhere. 

I also have ffprobe installed. 

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
the newest

**Comment by WineWG** [comment]
problem was caused by launching the .bat file from inside a virtual environment.

**Comment by j0keyA** [comment]
> problem was caused by launching the .bat file from inside a virtual environment.

how did you fix that? Im having a "ffmeg is not installed" error and dont know how to fix it
