### ISSUE TITLE
uses cuda even after configuring for cpu and restarting server.

### ISSUE THREAD

**Issue by davidndgoliath** [C0untFloyd/roop-unleashed#151]
**Describe the bug**
I did change provider to CPU in Gui and restarted my server. even on closing and opening again it shows CPU. also, I configured windows.bat to use CPU. however, when i run it shows error - "raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU." i also tried manually putting torch.device to 'cpu' in serialization and storage files of torch folder. 

**To Reproduce**
mentioned above.

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [x] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
2.7.9
**Screenshots**

**Comment by C0untFloyd** [comment]
Did you install the cuda toolkit etc. as described [here](https://github.com/s0md3v/roop/wiki/2.-Acceleration)?

**Comment by davidndgoliath** [comment]
kindly ignore my playing around with setting cpu manually. i have now created a fresh install and attached the error output. yes i did apply settings.

**Comment by phineas-pta** [comment]
this
> CUDA driver version is insufficient for CUDA runtime version

**Comment by goliathnddavid** [comment]
@phineas-pta i don't understand. Isnt the purpose of setting cpu to avoid using cuda entirely

**Comment by phineas-pta** [comment]
either u install cuda driver properly, or completely disable cuda
```
pip uninstall onnxruntime-gpu
pip install onnxruntime
```

**Comment by raccoon517** [comment]
I'm having the same problem with the new update trying to run on CPU. I get the same error, but was working before. Changed applied settings and restarted but still get the same error - RuntimeError: D:\a_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure...

**Comment by raccoon517** [comment]
Also get this at the very beginning...
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by goliathnddavid** [comment]
@phineas-pta  I did as you mentioned above. uninstalled onnxruntime-gpu and installed onnxruntime. now I am getting different error. 
  File "C:\Users\user\Downloads\roop-unleashed_win_v2.7.0\roop-unleashed\roop-unleashed\roop\core.py", line 98, in set_execution_provider
    longname = decode_execution_providers([execution_provider])[0]
IndexError: list index out of range


could you please just direct me how to edit the windows.bat to download a previous version. my code was working fine few days earlier.

**Comment by C0untFloyd** [comment]
#152
