### ISSUE TITLE
latest version fails to load

### ISSUE THREAD

**Issue by pudd1ng483** [C0untFloyd/roop-unleashed#152]
**Describe the bug**
Fails to boot on the latest version

**To Reproduce**

(base) mathew@mathews-mbp ~ % cd /Users/mathew/Downloads/new 
(base) mathew@mathews-mbp new % conda activate unleashed          
(unleashed) mathew@mathews-mbp new % python run.py                     
Traceback (most recent call last):
  File "/Users/mathew/Downloads/new/run.py", line 6, in <module>
    core.run()
  File "/Users/mathew/Downloads/new/roop/core.py", line 398, in run
    ui.run()
  File "/Users/mathew/Downloads/new/roop/ui.py", line 78, in run
    set_execution_provider(roop.globals.CFG.provider)
  File "/Users/mathew/Downloads/new/roop/core.py", line 98, in set_execution_provider
    longname = decode_execution_providers([execution_provider])[0]
IndexError: list index out of range

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ x] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ x] Mac

**Which version of roop unleashed are you using?**
2.7.9

**Comment by C0untFloyd** [comment]
Are you both on Mac? There seems to be no gpu provider, did you try using CoreML?
Meanwhile I'm forcing CPUExecutionprovider if there is none but I currently can't commit my dev version.

**Comment by zackabrams** [comment]
I tried specifying the GPU provider but neither worked

```
zackabrams@Zacks-MBP-2 roop-unleashed % python3.10 run.py --execution-provider cpu    
Traceback (most recent call last):
  File "/Users/zackabrams/roop-unleashed/run.py", line 6, in <module>
    core.run()
  File "/Users/zackabrams/roop-unleashed/roop/core.py", line 398, in run
    ui.run()
  File "/Users/zackabrams/roop-unleashed/roop/ui.py", line 78, in run
    set_execution_provider(roop.globals.CFG.provider)
  File "/Users/zackabrams/roop-unleashed/roop/core.py", line 98, in set_execution_provider
    longname = decode_execution_providers([execution_provider])[0]
IndexError: list index out of range
```


```
zackabrams@Zacks-MBP-2 roop-unleashed % python3.10 run.py --execution-provider coreml
Traceback (most recent call last):
  File "/Users/zackabrams/roop-unleashed/run.py", line 6, in <module>
    core.run()
  File "/Users/zackabrams/roop-unleashed/roop/core.py", line 398, in run
    ui.run()
  File "/Users/zackabrams/roop-unleashed/roop/ui.py", line 78, in run
    set_execution_provider(roop.globals.CFG.provider)
  File "/Users/zackabrams/roop-unleashed/roop/core.py", line 98, in set_execution_provider
    longname = decode_execution_providers([execution_provider])[0]
IndexError: list index out of range
zackabrams@Zacks-MBP-2 roop-unleashed % 
```

**Comment by pudd1ng483** [comment]
still getting the same after updating sorry C0untFloyd) :)

(unleashed) mathew@mathews-mbp roop-unleashed-main 3 % conda activate unleashed
(unleashed) mathew@mathews-mbp roop-unleashed-main 3 % python run.py           
Traceback (most recent call last):
  File "/Users/mathew/Downloads/roop-unleashed-main 3/run.py", line 6, in <module>
    core.run()
  File "/Users/mathew/Downloads/roop-unleashed-main 3/roop/core.py", line 398, in run
    ui.run()
  File "/Users/mathew/Downloads/roop-unleashed-main 3/roop/ui.py", line 78, in run
    set_execution_provider(roop.globals.CFG.provider)
  File "/Users/mathew/Downloads/roop-unleashed-main 3/roop/core.py", line 98, in set_execution_provider
    longname = decode_execution_providers([execution_provider])[0]
IndexError: list index out of range
(unleashed) mathew@mathews-mbp roop-unleashed-main 3 % python run.py --execution-provider cpu
Traceback (most recent call last):
  File "/Users/mathew/Downloads/roop-unleashed-main 3/run.py", line 6, in <module>
    core.run()
  File "/Users/mathew/Downloads/roop-unleashed-main 3/roop/core.py", line 398, in run
    ui.run()
  File "/Users/mathew/Downloads/roop-unleashed-main 3/roop/ui.py", line 78, in run
    set_execution_provider(roop.globals.CFG.provider)
  File "/Users/mathew/Downloads/roop-unleashed-main 3/roop/core.py", line 98, in set_execution_provider
    longname = decode_execution_providers([execution_provider])[0]
IndexError: list index out of range
(unleashed) mathew@mathews-mbp roop-unleashed-main 3 % python run.py --execution-provider coreml
Traceback (most recent call last):
  File "/Users/mathew/Downloads/roop-unleashed-main 3/run.py", line 6, in <module>
    core.run()
  File "/Users/mathew/Downloads/roop-unleashed-main 3/roop/core.py", line 398, in run
    ui.run()
  File "/Users/mathew/Downloads/roop-unleashed-main 3/roop/ui.py", line 78, in run
    set_execution_provider(roop.globals.CFG.provider)
  File "/Users/mathew/Downloads/roop-unleashed-main 3/roop/core.py", line 98, in set_execution_provider
    longname = decode_execution_providers([execution_provider])[0]
IndexError: list index out of range

**Comment by C0untFloyd** [comment]
Should work again with reverted code commit, please update. Proper fix needs to wait.

**Comment by pudd1ng483** [comment]
All fixed thankyou

**Comment by MaxTran96** [comment]
hi i'm getting this error 

Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'device_id': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_alloc': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'cudnn_conv1d_pad_to_nc1d': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'enable_cuda_graph': '0', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'enable_skip_layer_norm_strict_mode': '0', 'tunable_op_tuning_enable': '0'}}
find model: /home/ubuntu/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'device_id': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_alloc': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'cudnn_conv1d_pad_to_nc1d': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'enable_cuda_graph': '0', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'enable_skip_layer_norm_strict_mode': '0', 'tunable_op_tuning_enable': '0'}}
find model: /home/ubuntu/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'device_id': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_alloc': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'cudnn_conv1d_pad_to_nc1d': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'enable_cuda_graph': '0', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'enable_skip_layer_norm_strict_mode': '0', 'tunable_op_tuning_enable': '0'}}
find model: /home/ubuntu/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'device_id': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_alloc': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'cudnn_conv1d_pad_to_nc1d': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'enable_cuda_graph': '0', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'enable_skip_layer_norm_strict_mode': '0', 'tunable_op_tuning_enable': '0'}}
find model: /home/ubuntu/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'device_id': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_alloc': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'cudnn_conv1d_pad_to_nc1d': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'enable_cuda_graph': '0', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'enable_skip_layer_norm_strict_mode': '0', 'tunable_op_tuning_enable': '0'}}
find model: /home/ubuntu/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Traceback (most recent call last):
  File "/home/ubuntu/content/roop-unleashed/run.py", line 6, in <module>
    core.run()
  File "/home/ubuntu/content/roop-unleashed/roop/core.py", line 387, in run
    start()
  File "/home/ubuntu/content/roop-unleashed/roop/core.py", line 198, in start
    roop.globals.TARGET_FACES.append(faces[roop.globals.target_face_index])
IndexError: list index out of range


is this not fixed?

**Comment by C0untFloyd** [comment]
It is fixed, you're having another issue and it is caused by you using the commandline arguments. You don't need to use any CLI arg anymore, everything can be done in the GUI.

**Comment by MaxTran96** [comment]
would you mind fixing the CLI, i'm building a side project using the cli

**Comment by C0untFloyd** [comment]
You can access the app remotely using a browser, there's a web-server built into it. For example you can have this run on your local machine and access it with your cellphone from somewhere else in the world. It's also working with GUI in Colab, I don't know why you would still need to use the CLI?
If you insist on using CLI I suggest using the older non web version https://github.com/C0untFloyd/roop-unleashed/releases/download/v2.0.3/roop_unleashed_v2.0.3_final.zip which still gets some QoL Updates sometimes.
