### ISSUE TITLE
[Suggestion] Add option to add a timestamp to the output file name when using UI

### ISSUE THREAD

**Issue by Lordmau5** [C0untFloyd/roop-unleashed#153]
Currently not only does it delete the output folder and re-create it when it's generating a new video (which I found can be disabled by ~~changing the `settings.py` file and / or the `config_colab.yaml`~~ going to the Settings tab and unticking it), but when a video is generated it just takes the input video file name and appends `_fake` before the extension.

However, if for example I have a small clip that I'd want to test 2 or 3 faces on I need to generate the video with the first face, then copy the result elsewhere, then generate the 2nd face, copy the video, etc.

So an option to add an extra timestamp to the end of the file (e.g. `generated_fake.48273723.mp4`) would be a nice addition :)
___

Tested it locally and it seems to work perfectly fine.

I edited this line in https://github.com/C0untFloyd/roop-unleashed/blob/main/roop/core.py#L365 to the following:
`finalname = util.get_destfilename_from_path(videofinalnames[index], roop.globals.output_path, f'.{int(time())}.{roop.globals.CFG.output_video_format}')`

Instead of `_final` it will now put `.<TIMESTAMP>` into the output file

If you want to have this as the standard then I'm happy to do a PR with this, but I don't feel that's really ... necessary as it's such a small change 😁

**Comment by C0untFloyd** [comment]
Yes it's an enhancement we discussed here before, just can't find it. I would like this to be a template pattern in the settings where you have placeholders for different things you would like to include. Without thinking it could look like '{i}{o}_fake_{dt}' where i would get replaced with the current order index, o is the original name without extension and dt would be datetime short. Something like that. Not hard to code but of course it takes time and I'm in the middle of things, trying to get back the quality of the enhancers without losing the speed improvement.

**Comment by Lordmau5** [comment]
In that case I could look into doing a pull request for this.

Should be moderately simple.
Adding a new textbox into the Settings tab and writing a parser for it - plus an optional run parameter for CLI

What should the default template be in that case?

`{order_Index}.{input}_fake.{timestamp}.ext`?

Also, what would order_index be in this case?

And which parameters should we have (at least for now)?

**Comment by C0untFloyd** [comment]
Yes thanks, PRs like this are very welcome.
With order index I meant the index number of the file currently processed (if there are multiple destination files and ppl want to have some numbering). 
Well, I would suggest:

{of} = original filename without extension
{i:4} = index of this file in the destination queue (perhaps also defining the number of digits including trailing zeros)
{st} = Short time hh:mm:ss
{lt} = Long time (short time + date?)  

I'm open for other suggestions of course. My favourite initial value would be something simple like '{of}_f_{st}'. Perhaps error checking for too long paths might be important too, at least for windows users.

**Comment by Lordmau5** [comment]
Hmm I feel hh:mm:ss might not get properly saved, perhaps hh-mm-ss instead?

As for too long paths, I think Windows has lifted the long path issue sometime during the Windows 10 life-cycle but I need to look into that again

**Comment by C0untFloyd** [comment]
> Hmm I feel hh:mm:ss might not get properly saved, perhaps hh-mm-ss instead?

Yes, I'm tired and didn't mean it literally. What's the default python format?

Path length: can't hurt to normalize the path because with gradio saving all the stuff in long tempfoldernames there are bound to be problems sooner or later.
