### ISSUE TITLE
Congrats on reaching perfection!

### ISSUE THREAD

**Issue by Orchoidizer** [C0untFloyd/roop-unleashed#157]
Not an issue. I just wanted to THANK YOU!!!

My testing of the sw tonight and EVERYTHING is EXACTLY as it should be (as far as I'M concearned anyway).

CONGRATS C0untFloyd! and THANK YOU!

Any plans on opening a discord channel?

**Comment by TrickleDownClown** [comment]
I was wondering if there is a donation link or something?  The work done here by the count has been nothing short of awesome!

**Comment by C0untFloyd** [comment]
You guys seem to have low standards 😄 
No discord channel because I do this in my spare time, besides a full dev job and family.
No donations because most of the licenses don't allow commercial use and I'm standing on the shoulders of giants, so to speak.
Thanks!

**Comment by Orchoidizer** [comment]
You are an absolute star sir!
