### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by zhangjinyan888** [C0untFloyd/roop-unleashed#159]
Expecting value: line 1 column 1 (char 0)  
What's the reason for this error? Has anyone encountered it before?
![0423](https://github.com/C0untFloyd/roop-unleashed/assets/22515039/402d73d0-fe8a-4049-b233-dad5eeaf86e3)

**Comment by C0untFloyd** [comment]
?!?

**Comment by zhangjinyan888** [comment]
Error in uploading image prompt

**Comment by C0untFloyd** [comment]
Can you dump the terminal output here? I suspect a problem with a long path and/or chinese characters.

**Comment by zhangjinyan888** [comment]
The image path and image file name are both in English, without any special Chinese characters. All file names and paths are in English and do not include Chinese characters

**Comment by zhangjinyan888** [comment]
D:\soft\xun01\aaa_bbb_ccc   All the files in this folder

**Comment by zhangjinyan888** [comment]
I have installed it three times, each time uninstalling the environment and then reinstalling it, but I occasionally prompt this error, I don't know where it went wrong

**Comment by zhangjinyan888** [comment]
D:\wwwaiblvip>python run.py -s 1.jpg -t 1.mp4 -o  out.mp4
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Administrator/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Administrator/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Administrator/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Administrator/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Administrator/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Traceback (most recent call last):
  File "D:\wwwaiblvip\run.py", line 6, in <module>
    core.run()
  File "D:\wwwaiblvip\roop\core.py", line 396, in run
    start()
  File "D:\wwwaiblvip\roop\core.py", line 203, in start
    roop.globals.TARGET_FACES.append(faces[roop.globals.target_face_index])
IndexError: list index out of range

**Comment by lysxelapsed** [comment]
Please look up this thread before posting : #81 
It states:
>  CLI needs revamp (unsure, no need to use CLI anymore)

Just use python run.py and go with the web-gui ;-)

**Comment by zhangjinyan888** [comment]
The command "python run.py" is causing an error within the UI. I want to identify the specific location of the error, so I used the code execution command.

**Comment by zhangjinyan888** [comment]
def start() -> None:
    if roop.globals.headless:
        faces = extract_face_images(roop.globals.source_path,  (False, 0))
        if 0 <= roop.globals.source_face_index < len(faces):
            roop.globals.INPUT_FACES.append(faces[roop.globals.source_face_index])
        else:
            print("Invalid source_face_index")
        
        faces = extract_face_images(roop.globals.target_path,  (False, util.has_image_extension(roop.globals.target_path)))
        if 0 <= roop.globals.target_face_index < len(faces):
            roop.globals.TARGET_FACES.append(faces[roop.globals.target_face_index])
        else:
            print("Invalid target_face_index")

        if 'face_enhancer' in roop.globals.frame_processors:
            roop.globals.selected_enhancer = 'GFPGAN'
       
    batch_process(None, False, None, False)

**Comment by lysxelapsed** [comment]
Not sure what exactly you changed. However, glad that it works now :-)

**Comment by zhangjinyan888** [comment]
Still no luck. I modified the code a bit, and now it runs successfully using the command. However, when I try to log in using the http://127.0.0.1:7860/ interface, the original error still persists. It's showing the error message: "Expecting value: line 1 column 1 (char 0)."  
——————————             
core.py     
——————————
def start() -> None:
    if roop.globals.headless:
        faces = extract_face_images(roop.globals.source_path,  (False, 0))
        if 0 <= roop.globals.source_face_index < len(faces):
            roop.globals.INPUT_FACES.append(faces[roop.globals.source_face_index])
        else:
            print("Invalid source_face_index")
        
        faces = extract_face_images(roop.globals.target_path,  (False, util.has_image_extension(roop.globals.target_path)))
        if 0 <= roop.globals.target_face_index < len(faces):
            roop.globals.TARGET_FACES.append(faces[roop.globals.target_face_index])
        else:
            print("Invalid target_face_index")

        if 'face_enhancer' in roop.globals.frame_processors:
            roop.globals.selected_enhancer = 'GFPGAN'
       
    batch_process(None, False, None, False)

**Comment by zhangjinyan888** [comment]
Could it be due to my computer having CUDA 12.2 installed?

**Comment by lysxelapsed** [comment]
Not likely, I'm on 12.2 as well.
Can you post the terminal output with the "Expecting value: line 1 column 1 (char 0)" error? The one you posted with additional arguments says "IndexError: list index out of range"

**Comment by zhangjinyan888** [comment]
Now it's suddenly available again, and I've been making that kind of error for a few days now. Can you see if the code I posted above is helpful to you? That code was the result I sent the error to chatgpt, and chatgpt provided it. I hope there won't be any more errors. This error has confused me

**Comment by lysxelapsed** [comment]
It shouldn't be necessary at all to make changes to the code, much less from chatgpt in my opinion.

For testing (no worries, deleted it already), I made a snap of the face you used, cleaned up the lines and upscaled it. Doesn't recognize a face. Probably because the hair prevents the model from detecting needed facial structures.

So do you have that problem with every face, or just the one you posted here?

**Comment by zhangjinyan888** [comment]
It should be because I have started VPN. I need to change my IP address to access GitHub. If I don't start VPN, it will be normal. However, I have found that the UI interface experience is not very good and there are often errors. I hope to optimize it in the future or modify it based on the original rope,

**Comment by lapwrr** [comment]
I  meet the same problem.Is the caused by vpn?

**Comment by zhangjinyan888** [comment]
> I meet the same problem.Is the caused by vpn?

I feel like it's because I got that error when I started VPN, and when I closed it, it worked fine. Also, there were a lot of UI errors, so it would be great if I could create a demonstration tutorial

**Comment by lapwrr** [comment]
thanks
