### ISSUE TITLE
x2 Bugs: Face skips some frames + Enhancement doesn't work

### ISSUE THREAD

**Issue by AlonDan** [C0untFloyd/roop-unleashed#16]
**Describe the bug**
1 - Compare to few versions before I noticed now that in some  videos it won't recognize all the faces in all frames or just skip them on rendering.
It's not a specific video I've tried random videos but it just show the "orginal face" in some frames blinking on/off with the source frame. maybe something went wrong with the update?

2 - None of the Enhancement works, I've tried both Codeformer and GFPGAN it just render normally without doing the enhancement, I don't see any errors or sign related to it.

**To Reproduce**
1. Try some random videos 10-20 seconds long
2. Try the same videos with the version before or the stable Roop version, it will recognize ALL frames.

**Details**
What OS are you using?
- [x] Windows 

Are you try to use a GPU?
- [x] NVIDIA

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by C0untFloyd** [comment]
1. I'm using the normalized embeddings now like the original roop, perhaps not a good idea.
2. This was a bug, hopefully fixed some minutes ago

**Comment by AlonDan** [comment]
I've tried the latest version update now, 
but now Roop doesn't launch anymore, I get these lines:

```
Loading roop.processors.frame.face_swapper
Loading roop.processors.frame.face_enhancer
Frame processor face_enhancer not found.
```

**Comment by Heislerink** [comment]
I'm getting the same error.

**Comment by C0untFloyd** [comment]
Yes I can replicate the error on a fresh system. Sorry I'm investigating.

**Comment by Jasiek889** [comment]
me too

**Comment by C0untFloyd** [comment]
Please see #20

**Comment by AlonDan** [comment]
> Please see #20
First of all, thank you for your hard work ❤

I've downloaded the latest version.
I'm afraid the exact same error appears, I just double checked to be sure.

**Comment by C0untFloyd** [comment]
Seems to work for others and did for me. You might try updating again as I updated again today.

**Comment by AlonDan** [comment]
I've tried the latest update as you suggest, 
But since this last few updates these problems are the same.

I even tried a fresh install, but I get the same errors exactly.

At the moment I only use the "NEXT" version, since it works good but sadly, 
without the new features and fixes.

**Comment by C0untFloyd** [comment]
It's still there and if you look real hard you will spot the difference 😄 
The previous button seemed to confuse most people including you, so it's now a batch process toggle. If it's turned on you will be asked for a batch folder to process.

**Comment by AlonDan** [comment]
> 
Nice! I didn't see it in a rough look.
I'll give it a try later on, nice touch :)
