### ISSUE TITLE
Box on gfpgan

### ISSUE THREAD

**Issue by pudd1ng483** [C0untFloyd/roop-unleashed#161]
**Describe the bug**

On the latest build im getting the box on gfpgan, never had this problem in earlier builds, looks the same as dmdnet
**To Reproduce**

python: 3.10.12 • torch: 2.0.1 • gradio: 3.38.0

**Details**
What OS are you using?

- [x] Mac

Are you using a GPU?

- [x] Mac

**Which version of roop unleashed are you using?**
2.7.9

**Comment by pudd1ng483** [comment]
2.7.7 which is working for me has GFPGANv1.4.pth model but 2.7.9 has GFPGANv1.4.onnx, could this be what is causing a box

**Comment by C0untFloyd** [comment]
Yes and no. I'm doing a major overhaul, including the enhancers. The previous gfpgan used a pip package which used the .pth model and also included face restoring. Both didn't like threading and parallel execution so I converted it and stripped it down as an experiment. Perhaps I should have made a dev branch but I was so happy about the speed increase that I committed it. I already did the same for codeformer, which is now about 20x faster than previously and I'm rewriting a lot of the base architecture again. The next version already has video trimming, virtual camera support and face offsetting, but I want to get the basics right this time after the speed/memory desaster.

**Comment by beanzie** [comment]
I'm happy about the speed increase also and I found that if I reduce the Original/Enhanced image blend ratio to 0.5 the result will still be noticeably enhanced by GFPGAN but the box is barely noticeable. It's certainly not as bad as with DMDNet, although I prefer Codeformer it's just too slow on 2.7.9 for me

**Comment by C0untFloyd** [comment]
Resolved with latest commit. Stay tuned for unbelievable fast codeformer without artifacts soon!

**Comment by pudd1ng483** [comment]
its coreml. just ran it again with cpu and worked great!

**Comment by C0untFloyd** [comment]
Damn...don't get this with neither CPU nor CUDA...

**Comment by Lordmau5** [comment]
It's far better than the previous version but even with CUDA I can still make out a slight box... not sure if it's possible to easily improve it further though. If not then that's perfectly okay, just thought I'd mention it 😁 

https://github.com/C0untFloyd/roop-unleashed/assets/1345036/b9a6df92-da51-4fa1-99e9-321cb6475091

This is with:
- GFPGAN
- Face Similarity 0.8
- Blend Ratio 0.75
- And this image of Jerma:
![df7s72s-ff49379f-b2d7-4201-8b72-c7767b022fc3](https://github.com/C0untFloyd/roop-unleashed/assets/1345036/a27e4a0b-b96f-4465-b51a-fb4c78331784)

**Comment by Lordmau5** [comment]
> I committed a new version some minutes ago which adjusts the blending window and smoothing strength by face size

Can confirm, the fix made the box go away! 🎉 

https://github.com/C0untFloyd/roop-unleashed/assets/1345036/2965bbcb-b014-4573-b192-3c384d749132

___
And yeah, unfortunate that CoreML isn't available on other platforms so if you don't have an Apple device available then testing is pretty much impossible...
Or rather, it *is* possible, but only by proxy (new build, ask Apple user to test and report issues, repeat)

**Comment by C0untFloyd** [comment]
Couldn't test CoreML but for others it should be resolved by #203
