### ISSUE TITLE
Killed due to high swap memory usage on M2 max.

### ISSUE THREAD

**Issue by grogu19** [C0untFloyd/roop-unleashed#162]
**Describe the bug**
Keep running out of memory and causing python processes getting killed. I'm running on Mac M2 max. The app using a high swap memory upto 80 Gb and getting killed.
Output :
zsh: killed     python run.py
(roopenv) kushaltare@Kushals-MacBook-Pro-2 unleashedroop % /Users/kushaltare/anaconda3/envs/roopenv/lib/python3.11/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [.] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [.] Mac

**Which version of roop unleashed are you using?**
Latest available on main branch

**Screenshots**

**Comment by phineas-pta** [comment]
#141
