### ISSUE TITLE
No faces detected! error

### ISSUE THREAD

**Issue by Monsoonly** [C0untFloyd/roop-unleashed#163]
Traceback (most recent call last):
  File "E:\roop-unleashed-main\installer\installer_files\env\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\roop-unleashed-main\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\roop-unleashed-main\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\roop-unleashed-main\installer\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\roop-unleashed-main\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\roop-unleashed-main\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\roop-unleashed-main\installer\installer_files\env\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\roop-unleashed-main\installer\roop-unleashed\roop\ui.py", line 404, in on_srcimg_changed
    raise gr.Error('No faces detected!')
gradio.exceptions.Error: 'No faces detected!'

 **run the windows_run.bat file detect the error**

- Windows  OS

I have run it many times and still get this error 
NVIDIA-SMI 522.06       Driver Version: 522.06       CUDA Version: 11.8
nvidia card 3090ti 22g

**Comment by Monsoonly** [comment]
`Launching roop unleashed - please edit windows_run.bat to customize commandline arguments
Check for Updates? [y/n]y
Fetching origin
HEAD is now at ca6941f Bugfix: having no gpu providers caused crash
Already up-to-date.
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/, https://download.pytorch.org/whl/cu118
Ignoring torch: markers 'sys_platform == "darwin"' don't match your environment
Ignoring torchvision: markers 'sys_platform == "darwin"' don't match your environment
Ignoring onnxruntime: markers 'sys_platform == "darwin" and platform_machine != "arm64"' don't match your environment
Ignoring onnxruntime-silicon: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Requirement already satisfied: numpy==1.24.2 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 3)) (1.24.2)
Requirement already satisfied: gradio>=3.38.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 4)) (3.41.2)
Requirement already satisfied: opencv-python==4.7.0.72 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 5)) (4.7.0.72)
Requirement already satisfied: onnx==1.14.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 6)) (1.14.0)
Requirement already satisfied: insightface==0.7.3 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 7)) (0.7.3)
Requirement already satisfied: psutil==5.9.5 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 8)) (5.9.5)
Requirement already satisfied: pillow==9.5.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 9)) (9.5.0)
Requirement already satisfied: torch==2.0.1+cu118 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 10)) (2.0.1+cu118)
Requirement already satisfied: torchvision==0.15.2+cu118 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 12)) (0.15.2+cu118)
Requirement already satisfied: onnxruntime-gpu==1.15.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 16)) (1.15.0)
Requirement already satisfied: tensorflow==2.13.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 17)) (2.13.0)
Requirement already satisfied: protobuf==4.23.2 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 18)) (4.23.2)
Requirement already satisfied: tqdm==4.65.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 19)) (4.65.0)
Requirement already satisfied: codeformer-pip==0.0.4 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 20)) (0.0.4)
Requirement already satisfied: gfpgan==1.3.8 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 21)) (1.3.8)
Requirement already satisfied: ftfy in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 22)) (6.1.1)
Requirement already satisfied: regex in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 23)) (2023.8.8)
Requirement already satisfied: typing-extensions>=3.6.2.1 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from onnx==1.14.0->-r requirements.txt (line 6)) (4.5.0)
Requirement already satisfied: requests in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from insightface==0.7.3->-r requirements.txt (line 7)) (2.31.0)
Requirement already satisfied: matplotlib in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from insightface==0.7.3->-r requirements.txt (line 7)) (3.7.2)
Requirement already satisfied: scipy in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from insightface==0.7.3->-r requirements.txt (line 7)) (1.11.2)
Requirement already satisfied: scikit-learn in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from insightface==0.7.3->-r requirements.txt (line 7)) (1.3.0)
Requirement already satisfied: scikit-image in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from insightface==0.7.3->-r requirements.txt (line 7)) (0.21.0)
Requirement already satisfied: easydict in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from insightface==0.7.3->-r requirements.txt (line 7)) (1.10)
Requirement already satisfied: cython in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from insightface==0.7.3->-r requirements.txt (line 7)) (3.0.1)
Requirement already satisfied: albumentations in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from insightface==0.7.3->-r requirements.txt (line 7)) (1.3.1)
Requirement already satisfied: prettytable in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from insightface==0.7.3->-r requirements.txt (line 7)) (3.8.0)
Requirement already satisfied: filelock in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from torch==2.0.1+cu118->-r requirements.txt (line 10)) (3.12.2)
Requirement already satisfied: sympy in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from torch==2.0.1+cu118->-r requirements.txt (line 10)) (1.12)
Requirement already satisfied: networkx in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from torch==2.0.1+cu118->-r requirements.txt (line 10)) (3.1)
Requirement already satisfied: jinja2 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from torch==2.0.1+cu118->-r requirements.txt (line 10)) (3.1.2)
Requirement already satisfied: coloredlogs in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from onnxruntime-gpu==1.15.0->-r requirements.txt (line 16)) (15.0.1)
Requirement already satisfied: flatbuffers in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from onnxruntime-gpu==1.15.0->-r requirements.txt (line 16)) (23.5.26)
Requirement already satisfied: packaging in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from onnxruntime-gpu==1.15.0->-r requirements.txt (line 16)) (23.1)
Requirement already satisfied: tensorflow-intel==2.13.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from tensorflow==2.13.0->-r requirements.txt (line 17)) (2.13.0)
Requirement already satisfied: colorama in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from tqdm==4.65.0->-r requirements.txt (line 19)) (0.4.6)
Requirement already satisfied: addict in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from codeformer-pip==0.0.4->-r requirements.txt (line 20)) (2.4.0)
Requirement already satisfied: future in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from codeformer-pip==0.0.4->-r requirements.txt (line 20)) (0.18.3)
Requirement already satisfied: lmdb in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from codeformer-pip==0.0.4->-r requirements.txt (line 20)) (1.4.1)
Requirement already satisfied: pyyaml in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from codeformer-pip==0.0.4->-r requirements.txt (line 20)) (6.0.1)
Requirement already satisfied: tb-nightly in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from codeformer-pip==0.0.4->-r requirements.txt (line 20)) (2.15.0a20230825)
Requirement already satisfied: yapf in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from codeformer-pip==0.0.4->-r requirements.txt (line 20)) (0.40.1)
Requirement already satisfied: lpips in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from codeformer-pip==0.0.4->-r requirements.txt (line 20)) (0.1.4)
Requirement already satisfied: gdown in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from codeformer-pip==0.0.4->-r requirements.txt (line 20)) (4.7.1)
Requirement already satisfied: basicsr>=1.4.2 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gfpgan==1.3.8->-r requirements.txt (line 21)) (1.4.2)
Requirement already satisfied: facexlib>=0.2.5 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gfpgan==1.3.8->-r requirements.txt (line 21)) (0.3.0)
Requirement already satisfied: absl-py>=1.0.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow==2.13.0->-r requirements.txt (line 17)) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow==2.13.0->-r requirements.txt (line 17)) (1.6.3)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow==2.13.0->-r requirements.txt (line 17)) (0.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow==2.13.0->-r requirements.txt (line 17)) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow==2.13.0->-r requirements.txt (line 17)) (3.9.0)
Requirement already satisfied: libclang>=13.0.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow==2.13.0->-r requirements.txt (line 17)) (16.0.6)
Requirement already satisfied: opt-einsum>=2.3.2 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow==2.13.0->-r requirements.txt (line 17)) (3.3.0)
Requirement already satisfied: setuptools in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow==2.13.0->-r requirements.txt (line 17)) (68.0.0)
Requirement already satisfied: six>=1.12.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow==2.13.0->-r requirements.txt (line 17)) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow==2.13.0->-r requirements.txt (line 17)) (2.3.0)
Requirement already satisfied: wrapt>=1.11.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow==2.13.0->-r requirements.txt (line 17)) (1.15.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow==2.13.0->-r requirements.txt (line 17)) (1.57.0)
Requirement already satisfied: tensorboard<2.14,>=2.13 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow==2.13.0->-r requirements.txt (line 17)) (2.13.0)
Requirement already satisfied: tensorflow-estimator<2.14,>=2.13.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow==2.13.0->-r requirements.txt (line 17)) (2.13.0)
Requirement already satisfied: keras<2.14,>=2.13.1 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow==2.13.0->-r requirements.txt (line 17)) (2.13.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow==2.13.0->-r requirements.txt (line 17)) (0.31.0)
Requirement already satisfied: aiofiles<24.0,>=22.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio>=3.38.0->-r requirements.txt (line 4)) (23.2.1)
Requirement already satisfied: altair<6.0,>=4.2.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio>=3.38.0->-r requirements.txt (line 4)) (5.0.1)
Requirement already satisfied: fastapi in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio>=3.38.0->-r requirements.txt (line 4)) (0.102.0)
Requirement already satisfied: ffmpy in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio>=3.38.0->-r requirements.txt (line 4)) (0.3.1)
Requirement already satisfied: gradio-client==0.5.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio>=3.38.0->-r requirements.txt (line 4)) (0.5.0)
Requirement already satisfied: httpx in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio>=3.38.0->-r requirements.txt (line 4)) (0.24.1)
Requirement already satisfied: huggingface-hub>=0.14.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio>=3.38.0->-r requirements.txt (line 4)) (0.16.4)
Requirement already satisfied: importlib-resources<7.0,>=1.3 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio>=3.38.0->-r requirements.txt (line 4)) (6.0.1)
Requirement already satisfied: markupsafe~=2.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio>=3.38.0->-r requirements.txt (line 4)) (2.1.3)
Requirement already satisfied: orjson~=3.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio>=3.38.0->-r requirements.txt (line 4)) (3.9.5)
Requirement already satisfied: pandas<3.0,>=1.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio>=3.38.0->-r requirements.txt (line 4)) (2.0.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,<3.0.0,>=1.7.4 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio>=3.38.0->-r requirements.txt (line 4)) (1.10.12)
Requirement already satisfied: pydub in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio>=3.38.0->-r requirements.txt (line 4)) (0.25.1)
Requirement already satisfied: python-multipart in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio>=3.38.0->-r requirements.txt (line 4)) (0.0.6)
Requirement already satisfied: semantic-version~=2.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio>=3.38.0->-r requirements.txt (line 4)) (2.10.0)
Requirement already satisfied: uvicorn>=0.14.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio>=3.38.0->-r requirements.txt (line 4)) (0.23.2)
Requirement already satisfied: websockets<12.0,>=10.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio>=3.38.0->-r requirements.txt (line 4)) (11.0.3)
Requirement already satisfied: fsspec in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio-client==0.5.0->gradio>=3.38.0->-r requirements.txt (line 4)) (2023.6.0)
Requirement already satisfied: wcwidth>=0.2.5 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from ftfy->-r requirements.txt (line 22)) (0.2.6)
Requirement already satisfied: jsonschema>=3.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from altair<6.0,>=4.2.0->gradio>=3.38.0->-r requirements.txt (line 4)) (4.19.0)
Requirement already satisfied: toolz in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from altair<6.0,>=4.2.0->gradio>=3.38.0->-r requirements.txt (line 4)) (0.12.0)
Requirement already satisfied: filterpy in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from facexlib>=0.2.5->gfpgan==1.3.8->-r requirements.txt (line 21)) (1.4.5)
Requirement already satisfied: numba in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from facexlib>=0.2.5->gfpgan==1.3.8->-r requirements.txt (line 21)) (0.57.1)
Requirement already satisfied: contourpy>=1.0.1 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from matplotlib->insightface==0.7.3->-r requirements.txt (line 7)) (1.1.0)
Requirement already satisfied: cycler>=0.10 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from matplotlib->insightface==0.7.3->-r requirements.txt (line 7)) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from matplotlib->insightface==0.7.3->-r requirements.txt (line 7)) (4.42.1)
Requirement already satisfied: kiwisolver>=1.0.1 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from matplotlib->insightface==0.7.3->-r requirements.txt (line 7)) (1.4.5)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from matplotlib->insightface==0.7.3->-r requirements.txt (line 7)) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from matplotlib->insightface==0.7.3->-r requirements.txt (line 7)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from pandas<3.0,>=1.0->gradio>=3.38.0->-r requirements.txt (line 4)) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from pandas<3.0,>=1.0->gradio>=3.38.0->-r requirements.txt (line 4)) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from requests->insightface==0.7.3->-r requirements.txt (line 7)) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from requests->insightface==0.7.3->-r requirements.txt (line 7)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from requests->insightface==0.7.3->-r requirements.txt (line 7)) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from requests->insightface==0.7.3->-r requirements.txt (line 7)) (2023.7.22)
Requirement already satisfied: click>=7.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from uvicorn>=0.14.0->gradio>=3.38.0->-r requirements.txt (line 4)) (8.1.7)
Requirement already satisfied: h11>=0.8 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from uvicorn>=0.14.0->gradio>=3.38.0->-r requirements.txt (line 4)) (0.14.0)
Requirement already satisfied: qudida>=0.0.4 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from albumentations->insightface==0.7.3->-r requirements.txt (line 7)) (0.0.4)
Requirement already satisfied: opencv-python-headless>=4.1.1 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from albumentations->insightface==0.7.3->-r requirements.txt (line 7)) (4.8.0.76)
Requirement already satisfied: imageio>=2.27 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from scikit-image->insightface==0.7.3->-r requirements.txt (line 7)) (2.31.1)
Requirement already satisfied: tifffile>=2022.8.12 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from scikit-image->insightface==0.7.3->-r requirements.txt (line 7)) (2023.8.12)
Requirement already satisfied: PyWavelets>=1.1.1 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from scikit-image->insightface==0.7.3->-r requirements.txt (line 7)) (1.4.1)
Requirement already satisfied: lazy_loader>=0.2 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from scikit-image->insightface==0.7.3->-r requirements.txt (line 7)) (0.3)
Requirement already satisfied: humanfriendly>=9.1 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from coloredlogs->onnxruntime-gpu==1.15.0->-r requirements.txt (line 16)) (10.0)
Requirement already satisfied: starlette<0.28.0,>=0.27.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from fastapi->gradio>=3.38.0->-r requirements.txt (line 4)) (0.27.0)
Requirement already satisfied: beautifulsoup4 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gdown->codeformer-pip==0.0.4->-r requirements.txt (line 20)) (4.12.2)
Requirement already satisfied: httpcore<0.18.0,>=0.15.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from httpx->gradio>=3.38.0->-r requirements.txt (line 4)) (0.17.3)
Requirement already satisfied: sniffio in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from httpx->gradio>=3.38.0->-r requirements.txt (line 4)) (1.3.0)
Requirement already satisfied: joblib>=1.1.1 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from scikit-learn->insightface==0.7.3->-r requirements.txt (line 7)) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from scikit-learn->insightface==0.7.3->-r requirements.txt (line 7)) (3.2.0)
Requirement already satisfied: mpmath>=0.19 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from sympy->torch==2.0.1+cu118->-r requirements.txt (line 10)) (1.3.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from tb-nightly->codeformer-pip==0.0.4->-r requirements.txt (line 20)) (2.22.0)
Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from tb-nightly->codeformer-pip==0.0.4->-r requirements.txt (line 20)) (1.0.0)
Requirement already satisfied: markdown>=2.6.8 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from tb-nightly->codeformer-pip==0.0.4->-r requirements.txt (line 20)) (3.4.4)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from tb-nightly->codeformer-pip==0.0.4->-r requirements.txt (line 20)) (0.7.1)
Requirement already satisfied: werkzeug>=1.0.1 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from tb-nightly->codeformer-pip==0.0.4->-r requirements.txt (line 20)) (2.3.7)
Requirement already satisfied: wheel>=0.26 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from tb-nightly->codeformer-pip==0.0.4->-r requirements.txt (line 20)) (0.38.4)
Requirement already satisfied: importlib-metadata>=6.6.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from yapf->codeformer-pip==0.0.4->-r requirements.txt (line 20)) (6.8.0)
Requirement already satisfied: platformdirs>=3.5.1 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from yapf->codeformer-pip==0.0.4->-r requirements.txt (line 20)) (3.10.0)
Requirement already satisfied: tomli>=2.0.1 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from yapf->codeformer-pip==0.0.4->-r requirements.txt (line 20)) (2.0.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from google-auth<3,>=1.6.3->tb-nightly->codeformer-pip==0.0.4->-r requirements.txt (line 20)) (5.3.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from google-auth<3,>=1.6.3->tb-nightly->codeformer-pip==0.0.4->-r requirements.txt (line 20)) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from google-auth<3,>=1.6.3->tb-nightly->codeformer-pip==0.0.4->-r requirements.txt (line 20)) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from google-auth-oauthlib<1.1,>=0.5->tb-nightly->codeformer-pip==0.0.4->-r requirements.txt (line 20)) (1.3.1)
Requirement already satisfied: anyio<5.0,>=3.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from httpcore<0.18.0,>=0.15.0->httpx->gradio>=3.38.0->-r requirements.txt (line 4)) (3.7.1)
Requirement already satisfied: pyreadline3 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime-gpu==1.15.0->-r requirements.txt (line 16)) (3.4.1)
Requirement already satisfied: zipp>=0.5 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from importlib-metadata>=6.6.0->yapf->codeformer-pip==0.0.4->-r requirements.txt (line 20)) (3.16.2)
Requirement already satisfied: attrs>=22.2.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio>=3.38.0->-r requirements.txt (line 4)) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio>=3.38.0->-r requirements.txt (line 4)) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio>=3.38.0->-r requirements.txt (line 4)) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio>=3.38.0->-r requirements.txt (line 4)) (0.9.2)
Requirement already satisfied: soupsieve>1.2 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from beautifulsoup4->gdown->codeformer-pip==0.0.4->-r requirements.txt (line 20)) (2.4.1)
Requirement already satisfied: llvmlite<0.41,>=0.40.0dev0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from numba->facexlib>=0.2.5->gfpgan==1.3.8->-r requirements.txt (line 21)) (0.40.1)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from requests->insightface==0.7.3->-r requirements.txt (line 7)) (1.7.1)
Requirement already satisfied: exceptiongroup in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from anyio<5.0,>=3.0->httpcore<0.18.0,>=0.15.0->httpx->gradio>=3.38.0->-r requirements.txt (line 4)) (1.1.3)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tb-nightly->codeformer-pip==0.0.4->-r requirements.txt (line 20)) (0.5.0)
Requirement already satisfied: oauthlib>=3.0.0 in e:\roop-unleashed\installer\installer_files\env\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tb-nightly->codeformer-pip==0.0.4->-r requirements.txt (line 20)) (3.2.2)
Launching App
Using provider ['CUDAExecutionProvider'] - Device:cuda
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "E:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\roop-unleashed\installer\roop-unleashed\roop\ui.py", line 404, in on_srcimg_changed
    raise gr.Error('No faces detected!')
gradio.exceptions.Error: 'No faces detected!'
`
full error code

**Comment by lysxelapsed** [comment]
Well, the error speaks for itself: There is no face detected. And I'm missing a little context: Did you try different faces? Is something obstructing the face oder is there a lot of hair covering the face? Best results and easiest way is to have a full, frontal face picture, which is not cropped or obstructed (objects, hair...) anywhere. If it's cropped at the hairline for example, you can try my "border-workaround" I posted here: #155

**Comment by Monsoonly** [comment]
when i use the same [picture ](https://github.com/C0untFloyd/roop-unleashed/discussions/155) it still output the error 'No faces detected!'
