### ISSUE TITLE
Output video has really low quality

### ISSUE THREAD

**Issue by aaronsanchez99946** [C0untFloyd/roop-unleashed#164]
**Describe the bug**
The output video has really low quality and really small size, 

for example, the target video is 50M, but output video only has 1.4M so the quality is bad. and also the temp frame images and preview image actually has really good quality, just the output video has bad quality, dont know where went wrong. I already change the video quality to 90.

**To Reproduce**
using `GFPGAN` to post process and using Making feature

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
roop unleashed 2.7.9

**Screenshots**

**Comment by C0untFloyd** [comment]
> I already change the video quality to 90

Higher values mean worse quality. 0 would mean lossless.

**Comment by C0untFloyd** [comment]
Perhaps you have the image format set to .jpg? Use .png if that's the case. Other than that I have no clue...anybody else?

**Comment by lysxelapsed** [comment]
could it be related to this? #213
