### ISSUE TITLE
when I upload the video nothing comes out and when I command "start" it doesn't work

### ISSUE THREAD

**Issue by peepeepeepoopoopoo** [C0untFloyd/roop-unleashed#17]
it only asks me to select the folder but not the file name and it doesn't start working, I did the same with the original version of roop and if it uploads the video and it starts to work

**Comment by C0untFloyd** [comment]
Please see #20 if you used v2.0.0
Other than that, you need to specify the source and target face, then it should start to work by clicking start.
Perhaps you clicked on the target folder button, this is only needed if you want to batch process files in a folder.
