### ISSUE TITLE
Clip2Seg not taking into consideration asked for items

### ISSUE THREAD

**Issue by 6R1M4C3** [C0untFloyd/roop-unleashed#170]
**Describe the bug**
The Clip2Seg seems to genuinely not take notice of any of the terms you add other than hair, that is the only one that seems to work and produce a mask, 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to mask
2. Click on the box and type, mouth,lips,teeth,jaw,glasses,eyes etc .
3. Scroll down to the mask preview and you will see a blank screen, but if you type hair it will mask the hair.

**Details**
What OS are you using?
- [ ] Windows 

Are you using a GPU?
- [ ] NVIDIA

**Which version of roop unleashed are you using?** roop unleashed 2.7.9
**Screenshots**
![image](https://github.com/C0untFloyd/roop-unleashed/assets/129964460/99f09e20-af84-4c9b-b6d2-af31bc02ca78)
![image](https://github.com/C0untFloyd/roop-unleashed/assets/129964460/f209a824-0026-45ef-a31a-c9ee624f9076)

**Comment by C0untFloyd** [comment]
No.

![grafik](https://github.com/C0untFloyd/roop-unleashed/assets/131583554/87b71d75-45de-4431-82e4-aeeeb2dbecbf)
![grafik](https://github.com/C0untFloyd/roop-unleashed/assets/131583554/3e3bfbd8-e312-4187-b273-fd62d43b3ecc)

Someone told me even penis works...
Your image just needs to have the objects big enough to be identified, other than that the parser understands a lot of natural language.

**Comment by 6R1M4C3** [comment]
would this application not be able to incorporate something like the segmentor xseg I believe it to be called, that of which the deepfacelab uses this allows you to manually mark out areas by drawing a mask around them, because currently it doesn't see any segmentation parts on the face. as proven above, in screenshots when trying to segment mouth etc.
