### ISSUE TITLE
CoreMLExecutionProvider MAX Memory setting getting "Python int too large to convert to C long" error

### ISSUE THREAD

**Issue by righttang** [C0untFloyd/roop-unleashed#172]
**Describe the bug**
I am trying to install this on M1 Max 64G memory Laptop.
On CPU version, all good and I am able to successfully did several runs.
When I switch to CoreMLExecutionProvider, the python process start eating 60 - 100G memory and eating all swaps then be killed by the OS

I tried to set the MAX_MEMORY in the settings tab to 40G, I am getting error of 
  File "/Users/tangt4/Projects/gpt-awesome/roop-unleashed/roop/core.py", line 144, in limit_resources
    resource.setrlimit(resource.RLIMIT_DATA, (memory, memory))
OverflowError: Python int too large to convert to C long

**To Reproduce**
1. Install everything on Mac M1 python: 3.10.13 • torch: 2.0.1 • gradio: 3.41.2

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [X] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [X] Mac

**Which version of roop unleashed are you using?**
[roop unleashed 2.7.9](https://github.com/C0untFloyd/roop-unleashed)

**Screenshots**

**Comment by phineas-pta** [comment]
#141

**Comment by C0untFloyd** [comment]
Thank you again Phineas although I've seen you already forked facefusion. You don't want to cheat on us, do you? 😄 
I'd be happy to have a collaborateur, at least for documentation and you seem to be interested in this longer than me.

**Comment by phineas-pta** [comment]
im in various roop forks already, as occasional helper 🤗 but something long term i cannot commit unfortunately 😔

**Comment by C0untFloyd** [comment]
Too bad and yes, I've seen you giving lots of good advice even going back to the old refacer.
