### ISSUE TITLE
Output template update broke "Processed file(s)" and Preview

### ISSUE THREAD

**Issue by Lordmau5** [C0untFloyd/roop-unleashed#178]
**Describe the bug**
The "Processed file(s)" list is only listing files in the immediate `output` directory, but not the subdirectories.

Additionally, during testing of switching it to a recursive list, the more files are in (especially video files), the longer the load time.
(Tried loading all outputs upon loading the UI and it took over a minute with around 20 files, a mix of video and audio)

**To Reproduce**
1. Change the output template to include a subdirectory, for example the `{date}/`
2. Generate a face swap
3. The resulting file isn't showing up in the "Processed file(s)" section

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
2.8.2

**Comment by C0untFloyd** [comment]
Told you it's a bad idea to support subfolders 😛
I'll look into this later today. 
Load times: Gradio copies all the files over to its own temp folder and hashes them, which takes time (and uses twice the memory of course). Funnily the "new" roop has the same problem and I asked if we shouldn't create an issue for this https://github.com/facefusion/facefusion/issues/55#issuecomment-1700649080

**Comment by Lordmau5** [comment]
> Told you it's a bad idea to support subfolders 😛

Hey now, it's a million times better for organizational reasons 😉 
The fix is luckily easy - simply using `outdir.rglob("*")` instead of `outdir.iterdir()` includes the subdirectories 😁 
https://github.com/C0untFloyd/roop-unleashed/blob/main/roop/ui.py#L646
![image](https://github.com/C0untFloyd/roop-unleashed/assets/1345036/38fe041a-2d47-46ba-8e4f-bb35d3cc447c)
___
As for the load times and temp files, it makes sense for hosted instances of this and other models on, say, Huggingface where the models, or rather the programs, don't have access to your local file system, so uploading files is mandatory there.

But an option for local mode would be neat - perhaps an extra parameter that can be added into the `gr.Files` and `gr.Image` methods or similar

**Comment by TrickleDownClown** [comment]
Forgive me for barging but this just reminded me.  Is there a way to clear the output list? I just open the output folder directly. I might have missed the seeing if it's there but I couldn't find it when I looked. A bit ago.

**Comment by C0untFloyd** [comment]
There's a checkbox in the settings tab. The subfolder bug is taken care of in #203
