### ISSUE TITLE
Roop GUI doesn't load at all anymore with 2.0 update

### ISSUE THREAD

**Issue by Zyberetro** [C0untFloyd/roop-unleashed#18]
**Describe the bug**
I click on the windows_run.bat as per usual. It doesn't matter whether I choose to check for updates or not, it says it successfully loaded and says to press any key to continue. I do so, and the GUI never loads. I restarted my computer to see if that would fix it, and it was still busted in exactly the same way. I thought maybe a file was corrupted, so I deleted my installation and completely reinstalled it. It says it successfully installed and to press any key to continue. It does consistently say that the face enhancer failed to load, but someone else already posted an issue for that, and I don't use the built-in enhancer anyways, I use chaiNNer for that. I press a key and wait. Minutes pass, still nothing. Before the update, it was a few seconds at the slowest, so it isn't my computer (I hope). I can't even install/use the old version, as installing from the old version seems to automatically install the 2.0 version, the one that doesn't work.

**To Reproduce**
I'm not even sure what to put here other than reinstalling the program from scratch and pressing a key when it's finished installing. No GUI pops up like it should, even after several minutes pass.

**Details**
What OS are you using?
- [x] Windows 11

Are you try to use a GPU?
- [x] No. I am not using the `---gpu` flag from what I can tell, search for "gpu" yields no results.

**Sanity Check**
- [x] I'm 100% sure I have the latest code from the GitHub repository because I have it check for updates and it says I have the latest version. I don't even know how to install the old version.
- [x] I have followed the installation guide. I even deleted my installation and completely reinstalled it from scratch, it still has the same issue of the GUI never loading.

**Comment by C0untFloyd** [comment]
Please update and try again, I just submitted a hotfix
