### ISSUE TITLE
roop unleashed 2.8.2    public URL doesn't open,  504 Gateway Time-out

### ISSUE THREAD

**Issue by navasgejza** [C0untFloyd/roop-unleashed#185]
I just started a faceswap process for an about 2 ,5 minutes video with  DMDNET enhancer, but it always failed processing it and stopped with error.
Now after I reopen the roop unleashed 2.8.2 in other google accounts, the public URL doesn't open. So now it's completly unusable in gooogle colab.
Please resove this bug. Thank you, bests,  Géza.

**Comment by navasgejza** [comment]
The Publik link opens now but the swapping process still stops running after about 27 % of processing. "Error
Connection errored out". The "running python run.py" cell just stops... 
Please fix this bug. Thank you, Géza.

**Comment by navasgejza** [comment]
The bug is still not resolved. The process stops after 27% with error...

**Comment by lysxelapsed** [comment]
You do realize this is a single developer, doing this in his spare time, right? To complain after not even 24 hours, that a bug is _still_ not fixed, would be hardcore even with "multi-full-time" developers like adobe in my opinion.
Also, posting the ultimate error message is pretty slim to see what's going on in most cases. The last few lines from the the terminal output would be more helpful.
