### ISSUE TITLE
Help with Windows DML.

### ISSUE THREAD

**Issue by nuzoeto** [C0untFloyd/roop-unleashed#186]
I've tried to user the "roop-unleashed_win_v2.7.0.zip" with a  AMD GPU, so i  could'nt install the DML.
So i tried to install the common version with git clone and setting up a VENV, so i intalled DML as described at docs. when the web UI starts i select DML at settings then apply and restart, but when i try to start i receive an error.

 ` File "C:\Users\Nuzo\meuenv\lib\site-packages\torch\serialization.py", line 166, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
Creating 6953691011474410757__temp.mp4 with 30.0 FPS...
['ffmpeg', '-hide_banner', '-hwaccel', 'auto', '-y', '-loglevel', 'error', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '576x1024', '-pix_fmt', 'bgr24', '-r', '30.0', '-an', '-i', '-', '-vcodec', 'libx264', '-crf', '14', '-vf', 'colorspace=bt709:iall=bt601-6-625:fast=1', '-pix_fmt', 'yuv420p', 'C:\\Users\\Nuzo\\roop-unleashed\\output\\6953691011474410757__temp.mp4']
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
`

**Thank You For Keeping the Project!**

**Comment by phineas-pta** [comment]
try
```
pip uninstall torch torchvision
pip install torch torchvision
```

**Comment by nuzoeto** [comment]
still having some problem 

`(meuenv) C:\Users\Nuzo\roop-unleashed>python run.py
Using provider ['DmlExecutionProvider'] - Device:cpu
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Applied providers: ['DmlExecutionProvider', 'CPUExecutionProvider'], with options: {'DmlExecutionProvider': {}, 'CPUExecutionProvider': {}}
find model: C:\Users\Nuzo/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['DmlExecutionProvider', 'CPUExecutionProvider'], with options: {'DmlExecutionProvider': {}, 'CPUExecutionProvider': {}}
find model: C:\Users\Nuzo/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['DmlExecutionProvider', 'CPUExecutionProvider'], with options: {'DmlExecutionProvider': {}, 'CPUExecutionProvider': {}}
find model: C:\Users\Nuzo/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['DmlExecutionProvider', 'CPUExecutionProvider'], with options: {'DmlExecutionProvider': {}, 'CPUExecutionProvider': {}}
find model: C:\Users\Nuzo/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['DmlExecutionProvider', 'CPUExecutionProvider'], with options: {'DmlExecutionProvider': {}, 'CPUExecutionProvider': {}}
find model: C:\Users\Nuzo/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Error init processor plugin dmdnet... red
Traceback (most recent call last):
  File "C:\Users\Nuzo\roop-unleashed\chain_img_processor\image.py", line 129, in init_processor
    self.add_processor_to_list(processor_id)
  File "C:\Users\Nuzo\roop-unleashed\chain_img_processor\image.py", line 115, in add_processor_to_list
    obj.init_plugin()
  File "C:\Users\Nuzo\roop-unleashed\plugins\plugin_dmdnet.py", line 71, in init_plugin
    create(self.device)
  File "C:\Users\Nuzo\roop-unleashed\plugins\plugin_dmdnet.py", line 179, in create
    weights = torch.load('./models/DMDNet.pth')
  File "C:\Users\Nuzo\meuenv\lib\site-packages\torch\serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\Nuzo\meuenv\lib\site-packages\torch\serialization.py", line 1172, in _load
    result = unpickler.load()
  File "C:\Users\Nuzo\meuenv\lib\site-packages\torch\serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "C:\Users\Nuzo\meuenv\lib\site-packages\torch\serialization.py", line 1116, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "C:\Users\Nuzo\meuenv\lib\site-packages\torch\serialization.py", line 217, in default_restore_location
    result = fn(storage, location)
  File "C:\Users\Nuzo\meuenv\lib\site-packages\torch\serialization.py", line 182, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "C:\Users\Nuzo\meuenv\lib\site-packages\torch\serialization.py", line 166, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
Creating 6953691011474410757__temp.mp4 with 30.0 FPS...
['ffmpeg', '-hide_banner', '-hwaccel', 'auto', '-y', '-loglevel', 'error', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '576x1024', '-pix_fmt', 'bgr24', '-r', '30.0', '-an', '-i', '-', '-vcodec', 'libx264', '-crf', '14', '-vf', 'colorspace=bt709:iall=bt601-6-625:fast=1', '-pix_fmt', 'yuv420p', 'C:\\Users\\Nuzo\\roop-unleashed\\output\\6953691011474410757__temp.mp4']`

**Comment by justforthisshit** [comment]
to use Windows DML you need to do only these steps:

pip uninstall onnxruntime onnxruntime-directml (probably not even installed in the first place)
pip install onnxruntime-directml==1.15.1

start roop with the one click file windows_run

in the settings page change to dml and **VERY IMPORTANT**:

the **max number of threads** needs to be **1**

restart roop and it should work

@C0untFloyd  maybe the threads number should change automatically to 1 if you choose dml to prevent confusion.

**Comment by nuzoeto** [comment]
@justforthisshit IT WORKS! Thank You!

**Comment by cronex2011** [comment]
@justforthisshit can you help me ?
I use the windows version.

I want to implement the "onnxruntime-directml==1.15.1"
in the requirements but it dont work, the dont download DML and if i start the windows_ran.bat and say, yes update ... the requirements.txt refresh to the normal and delete my code

**Comment by Stanley154** [comment]
D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=-1516386656 ; hostname=LAPTOP-CDUDVGC5 ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=245 ; expr=cudaSetDevice(info_.device_id);

Hey guys I am facing this problem when trying to faceswap in roop unleashed, I have an amd laptop, I don't know how to fix this as I am not much into technical stuff, If you can please give me a detailed/beginner friendly solution of the problem will be much helpful and appreciated, please help

**Comment by phineas-pta** [comment]
when u say amd, u mean cpu or gpu ?

**Comment by Stanley154** [comment]
> when u say amd, u mean cpu or gpu ?

I am talking about Amd GPU but now I have somehow got Dml but when I am generating video swapping, it is showing me an error where

It says onnxruntime exception error: Not enough memory resources available to continue the process

**Comment by phineas-pta** [comment]
"not enough memory" so upgrade laptop 😵

**Comment by Stanley154** [comment]
> "not enough memory" so upgrade laptop 😵

There must be fix to it, I don't think it's talking about the hard drive space as I have like 100 gb free

**Comment by phineas-pta** [comment]
obviously memory isnt disk

the fix is upgrade memory aka upgrade laptop

**Comment by Stanley154** [comment]
> obviously memory isnt disk
> 
> the fix is upgrade memory aka upgrade laptop

I see, I tried running it on cpu but now it's showing another error

**Comment by Stanley154** [comment]
a_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:11 onnxruntime::CudaCall D:\a_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:4 onnxruntime::CudaCall CUDA failure 5: CUDA driver version is insufficient for CUDA runtime version ; GPU=121084 ; hostname=LAPTOP-CDUJKLM5 ; file=D:\a_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=245 ; expr=cudaSetDevice(info_.device_id);

When I tried running with cpu, it's showing me this error

**Comment by phineas-pta** [comment]
make sure to select cpu

**Comment by Stanley154** [comment]
> make sure to select cpu

I somehow got it running on CPU, any tutorials to get the best quality plus accuracy during video faceswap

**Comment by C0untFloyd** [comment]
@Stanley154 You're asking questions in different threads and create issues all over the place. This is not a helpdesk just for you. You will barely find any current tutorials, this is a non-profit app and a tech-heavy topic where people usually know how to google for answers. There is even a wiki here and an extra page about the face-swapping settings -> https://github.com/C0untFloyd/roop-unleashed/wiki/Face-Swap-Tab
Besides, I doubt you will have a lot of fun creating face swap videos running on cpu-only but to each their own.

**Comment by Stanley154** [comment]
> @Stanley154 You're asking questions in different threads and create issues all over the place. This is not a helpdesk just for you. You will barely find any current tutorials, this is a non-profit app and a tech-heavy topic where people usually know how to google for answers. There is even a wiki here and an extra page about the face-swapping settings -> https://github.com/C0untFloyd/roop-unleashed/wiki/Face-Swap-Tab Besides, I doubt you will have a lot of fun creating face swap videos running on cpu-only but to each their own.

I am very sorry for that, but I have no other option i guess, I need to use video faceswap and I have to do it with cpu anyways.
