### ISSUE TITLE
Roop-unleash live cam not workig

### ISSUE THREAD

**Issue by zachysaur** [C0untFloyd/roop-unleashed#189]
**Describe the bug**

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**

**Screenshots**

**Comment by C0untFloyd** [comment]
Without description one can only guess...you're missing a webcam! Yes, that must be it...
