### ISSUE TITLE
CLI not working anymore

### ISSUE THREAD

**Issue by GreenAmazing** [C0untFloyd/roop-unleashed#200]
**Describe the bug**
CLI not working with latest release, it would be great to continue support for CLI so automation with scripts could be easier 
Also adding a bitcoin/monero donation address would be a good thing to help the project in the future !

**To Reproduce**
Any CLI commands

**Details**
What OS are you using?
- [X ] Linux
- [ ] Linux in WSL
- [ X] Windows 
- [ ] Mac

Are you using a GPU?
- [ X] No. CPU FTW
- [ X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
latest

**Comment by C0untFloyd** [comment]
Please see #81...I'm unsure if I will revive the CLI arguments.
If you want to help the project, documentation is very much needed!
