### ISSUE TITLE
Full speed only when in web interface tab?

### ISSUE THREAD

**Issue by Niiickel** [C0untFloyd/roop-unleashed#201]
I got a 768x432/24fps 11:52 minute video that takes almost about 3 minutes longer to process when I browse other tabs in Google Chrome than when I process it with the localhost webui tab opened as a main tab.

Already checked Google Chrome settings, but couldn't find a setting that would improve it.

Any help would be appreciated.

**Comment by C0untFloyd** [comment]
Best guess: your other Tabs also use VRAM and your GPU is shuffling memory to shared memory slowing it down.
The app itself is running as a server/client app meaning it's totally UI independent. You can check this by yourself, start the video swapping and close your browser. The app will continue running until it's finished.
