### ISSUE TITLE
Post processing errors and couldn't save settings on v3.0.2

### ISSUE THREAD

**Issue by M4NH3X** [C0untFloyd/roop-unleashed#204]
**Describe the bug**
* DMDNet, Codeformer are throwing errors.
* Couldn't apply settings from webui.
 
**To Reproduce Post Processing errors:**
* I am running Windows, installed all dependencies via pip and everything is default except the provider is set to 'cpu' and image output to 'jpg'
*  When choosing **DMDNet** I get below error:
 `File "C:\Users\Holmes\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\serialization.py", line 166, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to ma
p your storages to the CPU.
`
* When choosing **Codeformer** I get below error:
` File "C:\Users\Admin\Documents\dfclient\roop-unleashed\roop\utilities.py", line 272, in str_to_class
    return class_ or None
           ^^^^^^
UnboundLocalError: cannot access local variable 'class_' where it is not associated with a value
`

**To Reproduce Save Settings errors:**
* When I click on "Apply Settings" from webui, I get the below error
`Error
Settings' object has no attribute 'frame_buffer_size`

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [x] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
v3.0.2

**Comment by KumarAI1** [comment]
> Fixed.

How did you fix the post processing errors?
