### ISSUE TITLE
Disconnection from colab in few minutes

### ISSUE THREAD

**Issue by aripsam** [C0untFloyd/roop-unleashed#208]
Apparently, google is doing a crackdown on stable diffusion. But I wonder how they know about roop-unleashed? 

Unless they are doing some checks on the keyword ‘roop’

**Comment by sordidloam** [comment]
I’m sure they can easily see a report with insights on which projects are utilizing the most resourcesSent from my iPhoneOn Sep 11, 2023, at 1:29 AM, aripsam ***@***.***> wrote:﻿
Apparently, google is doing a crackdown on stable diffusion. But I wonder how they know about roop-unleashed?
Unless they are doing some checks on the keyword ‘roop’

**Comment by C0untFloyd** [comment]
They only need to checksum the models used for inference and the original insightface authors are very strict when it comes to their models. They already removed all of them from github and I believe most of them from huggingface too.

**Comment by aripsam** [comment]
I have a feeling it has something gotta do with the word ‘roop’. I tried another project (think roop but not roop) and that worked with colab. Google has a history with banning based on keywords.

**Comment by navasgejza** [comment]
Now Colab disconnects at once after starts processing face swap. :(

**Comment by C0untFloyd** [comment]
Tried processing 2 short videos without problems. It's none of my business but are you people perhaps abusing the colab time by doing lots of weird videos with your mother in-law? It's very likely not roop is banned but your google account, just sayin...

**Comment by navasgejza** [comment]
I never create weird videos, nothing like that.
Thank you, Géza.

**Comment by C0untFloyd** [comment]
I ALWAYS create weird videos like that but obviously I can still use roop in a colab 😝 
Seriously, did you try again lately? Google sometimes shuts down hw-accelerated instances randomly.

**Comment by aripsam** [comment]
I also make videos with your mother in law!!! How did you know @C0untFloyd ? Lol jk. Will try again today and update. 

And yea when I created this, my video wasn’t small. It was like a 5 min clip

**Comment by navasgejza** [comment]
Google still terminates the processing randomly.
