### ISSUE TITLE
Start - End range extracts more than needed + identical frames

### ISSUE THREAD

**Issue by RoombaVoid** [C0untFloyd/roop-unleashed#211]
**Describe the bug**
Using Start - End frame extracts more than specified frames + identical frames.

**To Reproduce**
1. Use a big file (VR file in my case)
2. Set range (1000 frames in my case). I set the End range by editing the text box, not by moving the slider.
3. Set 'Extract media'
4. Way more frames are extracted (doesnt stop seems like it) + its the same frame for all

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
3.0.2

**Screenshots**
![image](https://github.com/C0untFloyd/roop-unleashed/assets/144537801/59022715-b4d0-4fa4-8d5c-69b4582ee3a3)

**Comment by C0untFloyd** [comment]
This was discussed in #199 
It's an issue with ffmpeg and I'm not even completely certain it's a bug. You could investigate yourself if it is possible to extract the exact frame number using ffmpeg. If so, please let me know what you did.

**Comment by C0untFloyd** [comment]
Solved
