### ISSUE TITLE
Progressbar goes nuts after first file when processing multiple files in batch

### ISSUE THREAD

**Issue by RoombaVoid** [C0untFloyd/roop-unleashed#212]
**Describe the bug**
Progressbar goes nuts when processing multiple files in batch after first file

**To Reproduce**
1. Batch video files
2. Start

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
3.0.2

**Screenshots**
![image](https://github.com/C0untFloyd/roop-unleashed/assets/144537801/73e655e8-3609-4576-8740-a2517bdac8b5)

**Comment by C0untFloyd** [comment]
Fixed in v3.0.5
