### ISSUE TITLE
Final video doesn't get encoded with chosen video codec

### ISSUE THREAD

**Issue by lysxelapsed** [C0untFloyd/roop-unleashed#213]
I'll cut it short because I think I saw whats missing:

**Describe the bug**
Final video gets encoded with x264, no matter what I'm chosing in the settings. Yes, applied settings and restarted.

Possible solution:
Either I'm blind, or "def restore_audio" in utilities.py is missing a "roop.globals.video_encoder" ;)

**Comment by C0untFloyd** [comment]
Did you test without audio?

**Comment by lysxelapsed** [comment]
I noticed because final video processing took forever and cpu spiked to 100%, which it doesn't with hevc_nvenc. So I looked at the console and thought "ok, that looks pretty slim compared to 2.7.*", where you definitely had the hevc_nvenc in the final processing ffmpeg argument.

**Comment by C0untFloyd** [comment]
Fixed it! The order of the arguments matters! 
Face Fusion did it the same as me, Swap Mukham uses moviepy and Hillobars Rope only supports x264.
Nevertheless only Rope does seems to do it right and what I do now is a straight copy. Committed secs ago, please check it out.

**Comment by lysxelapsed** [comment]
yup, works like a charm again 😃 thx for the quick fix!
