### ISSUE TITLE
[ONNXRuntimeError]  Can't produce any output

### ISSUE THREAD

**Issue by f10flow** [C0untFloyd/roop-unleashed#215]
Hi, 
I've selected the source image as well as the select the targeted faces for a video, But when I start the process for output, then this message pops up:

[ONNXRuntimeError] : 1 : FAIL : Load model from /content/roop-unleashed/models/inswapper_128.onnx failed:std::bad_alloc

To solve this, I ran this ode:

!wget https://huggingface.co/ezioruan/inswapper_128.onnx/resolve/main/inswapper_128.onnx -O inswapper_128.onnx
!mkdir models
!mv inswapper_128.onnx ./models

but, nothing works!

Can someone help me please!!!!

**Comment by lysxelapsed** [comment]
how much (free) RAM do you have? "std::bad_alloc" usually indicates, that there isn't enough free memory to allocate (as in: to reserve) for the inswapper model. As you can see below, my currently running roop-unleashed allocates around 14.5 GB of RAM to python / roop-unleashed.
Screenshot taken vom Sysinternals Process Explorer - I recommend the whole, free Sysinternals-suite, some handy tools in there. Windows Task-Manager will only show the current in-use value (shown here as "Working Set"
![memory alloc](https://github.com/C0untFloyd/roop-unleashed/assets/63816546/0f07c9ab-b2cf-4cbf-b66b-23669c8dfaad)

**Comment by f10flow** [comment]
Thank you @lysxelapsed , you were right! Problem solved!!
