### ISSUE TITLE
[Feature Suggestion] Persistent source image faces

### ISSUE THREAD

**Issue by M4NH3X** [C0untFloyd/roop-unleashed#216]
I often use the same source faces over and over again, was thinking if you can add a feature where the faces are saved permanently and doesn't go away on page refresh, restarts, etc. It will save users from selecting same faces again and again everytime.

Great work done on project, v3 is fast. Thank you for that. 😃

**Comment by sordidloam** [comment]
Face library, love it.Sent from my iPhoneOn Sep 12, 2023, at 5:13 PM, Jose ***@***.***> wrote:﻿
I often use the same source faces over and over again, was thinking if you can add a feature where the faces are saved permanently and doesn't go away on page refresh, restarts, etc. It will save users from selecting same faces again and again everytime.
Great work done on project, v3 is fast. Thank you for that. 😃

**Comment by C0untFloyd** [comment]
Done
