### ISSUE TITLE
Face jumping despite specifying target face.

### ISSUE THREAD

**Issue by Heislerink** [C0untFloyd/roop-unleashed#22]
**Describe the bug**
When a video clip contains a camera cut to a different angle where the position of the actors has changed, the specified target face is no longer specifically replaced and it goes back to the default of the first face on the left.

**To Reproduce**
1. Try to replace specific face in a scene that has camera cuts that put actors in different positions.

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ x] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [x ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [ x] I have the latest code from the github repository
- [ x] I have followed the installation guide

**Comment by C0untFloyd** [comment]
Just reverted back to older code which seems to work better, though when people look sideways face detection might fail.
