### ISSUE TITLE
Codeformer Problem

### ISSUE THREAD

**Issue by SDicedBlue** [C0untFloyd/roop-unleashed#221]
**Describe the bug**
For me the "Codeformer" process is broken or has some errors; heavy flickering. He is blurry/poor quality and has a square around/on his head.
Before the release of version 3.0.8 everything was fine, since 3.0+ the "Ccodeformer" in videos no longer works as it should.

**To Reproduce**
every video has the same problem; square around/on his head. poor quality
I tried to fix the problem by reinstalling but it doesn't work

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x ] Windows - 10 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x ] NVIDIA - 3060 12GB
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
I use: Roop Unleashed 3.0.8

**Comment by muemar79** [comment]
Yes I can confirm the square. It is a light one, not as strong as with dmdnet in the past, but you can see it. I set the similarity threshold very high, that reduces the flickering a little bit.

**Comment by C0untFloyd** [comment]
I think some kind of individual blur amount slider is needed, because I used values fitting for my system and I don't see any visible squares. In the meantime try decreasing the blend ratio, so more of the original image is mixed in. This should also get rid of the visible borders.

**Comment by zenimarc** [comment]
the problem it's not only related to visible borders, it seems like the codeformer image is wrongly positioned on the target face. sometimes you get also a completely different pose in the codeformer image.

**Comment by C0untFloyd** [comment]
Ah ok then it's the codeformer fidelity option which I tweaked around and don't expose so far.

**Comment by munugget** [comment]
How come the quality isn't the same compared to the normal codeformer? (based on codeformer.pth, retinaface_resnet50 etc)
Just by doing this to the final image, you get so much better results.
I was trying to find the upscaling options in this Enhanced vers. but couldn't find any ref.

```
import shutil
from codeformer.app import inference_app

def upscale_img(output_file):
    result = inference_app(
        image=output_file,
        background_enhance=False,  #True
        face_upsample=True,
        upscale=1,  #2
        codeformer_fidelity=0.7,
    )
    shutil.move(result, output_file)

```

**Comment by zenimarc** [comment]
> Ah ok then it's the codeformer fidelity option which I tweaked and don't expose so far. [This](https://github.com/C0untFloyd/roop-unleashed/blob/c6fb904385bebe4741d852d30861b66d2c288525/roop/processors/Enhance_CodeFormer.py#L32C9-L32C9) value controls how likely the appearance is to the original face (range 0.0 - 1.0). The older roop might have had another value.

I tried setting that value back to 0.8 as it was in old 2.x versions but it doesn't solve the problem.

**Comment by C0untFloyd** [comment]
You know, I'm a bit burnt out by this and taking a break from roop dev. Perhaps you like [my other new project](https://github.com/C0untFloyd/gpt4free-gradio). Anyway

> How come the quality isn't the same compared to the normal codeformer? (based on codeformer.pth, retinaface_resnet50 etc)

The answer is already in your question. Codeformer does a lot more than your average GAN standard model. With the help of at least 2 other models (which you can spot by looking in the codeformer folder in older versions) it does:
* face detection
* face parsing
* face upscaling
* background upscaling (optional)

This is a long and tedious process, can't be run parallel, uses extra models in hardcoded places and needs lots of settings (used numbers which suited me previously). AFAIK only the richard fast-fork of roop still uses codeformer for those reasons, noone else is crazy enough. And then people will [complain about the speed](https://github.com/RichardErkhov/Richard-roop/issues/18). At one point I then converted the codeformer torch model over to onnx leading to the unbelievable speed increase we have now. I actually did some binary comparisons to see if there are differences and found them to be very small. That's enough for me but the tradeoff are the missing upscaling extras some people really seem to miss. You know...this is OSS. It shouldn't be too hard to port the old crap back into the new but I'm not doing it and I think this would be a step back.

**Comment by munugget** [comment]
Thanks for the explanation and the new project link! Funny, i was thinking about writing a small api myself yesterday for chatgpt, saved me a lot of time :)
No, the speed is awesome, I was surprised that it was that fast. And by comparison like you said the differences are miniscule. I was just curious as to why i couldnt find any upscale numbers to tweak, but I understand what you mean now.
Thanks again for the great work

**Comment by lysxelapsed** [comment]
> You know, I'm a bit burnt out by this and taking a break from roop dev. Perhaps you like [my other new project](https://github.com/C0untFloyd/gpt4free-gradio). Anyway

sorry for the off-topic @C0untFloyd, but you know me a bit now: I'm a curious fella 😆 
the first part about feeling burnt out and taking a step back, I get better than you could imagine. but taking that break to invest the still charging energy in a new project? sounds like feeling burnt out won't go away (or is it your "zen-project"? 😃), and neither project will really advance. but most important - it was my first thought actually: won't you get in trouble for your other project? I'm boycotting chatgpt4 (not even used / tried once) for idealistic / personal reasons, so I actually have no clue and did a quick search. and there it was: legal problems for the original repo-creator: https://winfuture.de/news,135984.html

take your break man, you deserve it. just stay healthy and safe 😉 and as always: thank you for your great work!

**Comment by C0untFloyd** [comment]
One of these days I should expose the codeformer fidelity
