### ISSUE TITLE
Installing with windows_run.bat messes up the Windows Path.

### ISSUE THREAD

**Issue by SoftologyPro** [C0untFloyd/roop-unleashed#225]
Open the system path before installing.
Take a screenshot.
Install windows_run.bat
Check path.  Python may be removed from path entirely or the order of the path seems to be moved around.  I got dfifferent results with different installs.  Something the install does messes up the path on Windows.

**Comment by RoombaVoid** [comment]
That might explain why I had to re-add Python to my path recently. My Terminal didnt recognize Python anymore.

**Comment by C0untFloyd** [comment]
At least ffmpeg and miniconda need to be added to the windows path and their installer isn't smart enough to figure out previous installations.

**Comment by borhanrahi** [comment]
> At least ffmpeg and miniconda need to be added to the windows path and their installer isn't smart enough to figure out previous installations.

HOW?

**Comment by borhanrahi** [comment]
I did add miniconda location and script in env variables path were to find ffmpeg?

**Comment by C0untFloyd** [comment]
Don't understand what you're asking. The windows installer also installs ffmpeg and adds the path to ENV (from the installer):

if not exist "%INSTALL_FFMPEG_DIR%" (
	echo Downloading ffmpeg from %FFMPEG_DOWNLOAD_URL% to %INSTALL_DIR%
 	call curl -Lk "%FFMPEG_DOWNLOAD_URL%" > "%INSTALL_DIR%\ffmpeg.zip" || ( echo. && echo ffmpeg failed to download. && goto end )
	call powershell -command "Expand-Archive -Force '%INSTALL_DIR%\ffmpeg.zip' '%INSTALL_DIR%\'"

	cd "installer_files"
	setlocal EnableExtensions EnableDelayedExpansion

	for /f "tokens=*" %%f in ('dir /s /b /ad "ffmpeg*"') do (
		ren "%%f" "ffmpeg"
	)
	endlocal
	setx PATH "%INSTALL_FFMPEG_DIR%\bin\;%PATH%"
	echo To use videos, you need to restart roop after this installation. 
	cd ..
)

**Comment by borhanrahi** [comment]
never mind figure it out already wired shit I have ever faced

**Comment by borhanrahi** [comment]
any way that will be helpful for others 

> Don't understand what you're asking. The windows installer also installs ffmpeg and adds the path to ENV (from the installer):

anyway that will be helpful for others

**Comment by C0untFloyd** [comment]
You ain't seen nothing yet 😈

**Comment by SoftologyPro** [comment]
Try the install on WIndows.
It will add the ffmpeg path as the first entry and get rid of the 2 Python path entries (Python and Python\scripts)

**Comment by RoombaVoid** [comment]
This is definitely an issue. I reinstalled Roop yesterday, today I want to start Automatic1111 and it can't find Python.

**Comment by SoftologyPro** [comment]
Yes, install still messes with the path.  I have done multiple installs today.  I make sure the path entries for Python and Cmake are correct before install starts.  I open a new command prompt to be sure.  Then after the install either Python or Cmake or both have been removed from the path.  It seems almost random.  Sometimes just Python, sometimes just Cmake, sometimes both.

Also it would be much simpler if the installer did not launch the UI at the end of the install.  Maybe make install just an install and create a new start.bat or run.bat or whatever to start the UI.

**Comment by C0untFloyd** [comment]
Yes I also wrecked my Automatic1111 install and corrupted Python more than once while test installing.
Seems to be caused by the Miniconda install. Didn't really look into it up to now but will do.

> Maybe make install just an install and create a new start.bat or run.bat or whatever to start the UI.

Had this in one of my other projects and it was a mess! Technically challenged users then either did never update or tried to git pull / edit the .bat themselves wrecking the whole installation. Although I know that having installer/launcher in 1 file confuses people...

**Comment by SoftologyPro** [comment]
> Had this in one of my other projects and it was a mess! Technically challenged users then either did never update or tried to git pull / edit the .bat themselves wrecking the whole installation. Although I know that having installer/launcher in 1 file confuses people...

That's OK then.  I can edit out the launching from the script when installing and then restore it back in when running.

**Comment by Kamekos** [comment]
Lmao this screwed my whole stable diffusion gg

**Comment by SoftologyPro** [comment]
Until the issue is resolved, if your path does get messed up a quick repair install of Python (and CMake if you need it) will fix it.

**Comment by Kamekos** [comment]
Is it fixed now ?

**Comment by C0untFloyd** [comment]
No, not really, but if you installed it one-time you don't need to to it again. Just keep it up-to-date using the installer, updating does nothing to your python or paths.
