### ISSUE TITLE
This script relies on Miniconda which can not be silently installed under a path with spaces.

### ISSUE THREAD

**Issue by thetroll288** [C0untFloyd/roop-unleashed#227]
When attempting to run the windows_run.bat file, I get the error message that is in the subject file.

How do I get beyond this?  TIA - it has been very frustrating..

**Comment by C0untFloyd** [comment]
You're not trolling despite your name, aren't you? I mean...did you try unpacking the zip into a path WITHOUT spaces?

**Comment by borhanrahi** [comment]
fucking hell just figure it out! this has to be epic thing I have faced I so far lmao! so the thing is I put this file in a folder name "AI Tools" and funny thing is I had to change it to "AI_Tools" bang! you just cant put it in a folder that has an space! 
wired nahh ? LOL
