### ISSUE TITLE
No faces detected

### ISSUE THREAD

**Issue by thetroll288** [C0untFloyd/roop-unleashed#228]
**Describe the bug**
 It seems I was finally able to install the software, but now on the target video, it says "no face detected."

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [x ] AMD
- [ ] Intel
- [ ] Mac

**Which version of Roop Unleashed are you using?**
3.0.8
**Screenshots**
![roop problem](https://github.com/C0untFloyd/roop-unleashed/assets/65664105/fcd2fb3c-347b-41be-bf69-e74fd283d322)

**Comment by thetroll288** [comment]
No good. . . tried it with a photo and got the same result . . . 

![roop2](https://github.com/C0untFloyd/roop-unleashed/assets/65664105/b45b4efe-a7f7-4f27-b709-7545efc7fc4e)

**Comment by thetroll288** [comment]
It works when I use it on COLAB . . .

**Comment by C0untFloyd** [comment]
The error display is just the result of something not working previously. Can you paste your console output here?

**Comment by thetroll288** [comment]
Does this help?  If not, tell me how to get what you want.  I am not well-versed in working with computers.  TIA!!!

![roop3 error](https://github.com/C0untFloyd/roop-unleashed/assets/65664105/7f410240-bba4-4780-bd6c-ea0af74cdb57)

**Comment by C0untFloyd** [comment]
Yes it does help a lot. First, you could update to the latest version to get rid of the annoying first err message. Then, I'm guessing you didn't update your NVIDIA Drivers for some time? Try downloading & installing them from https://www.nvidia.com/download/index.aspx?lang=en-us
That might already be enough to make it work.

**Comment by thetroll288** [comment]
First. I must state I am a bit confused.  I do not have an NVIDIA card.  I have an AMD, the drivers for which I recently updated.

What do I do now?  (I need very explicit instruction . . . sorry).

Thanks for your help!

**Comment by thetroll288** [comment]
I changed to CPU in the Settings, but got the same result of "No faces detected."

Sounded good and I was hopeful, but thanks nonetheless.

**Comment by thetroll288** [comment]
I changed to CPU and that seems to have worked.

Am now running a faceswap tomsee how it does.  Thank you!
