### ISSUE TITLE
All Female Face Not Getting Swapped Properly

### ISSUE THREAD

**Issue by RFedz007** [C0untFloyd/roop-unleashed#229]
Hi,

I have seen this issue whenever I select All Female Face to swap, it also swaps Male Face also. Just wanted to ask how to resolve this solution, as this happens every time when I select All Female Face. Pls Assist on this...

Thank You

**Comment by RFedz007** [comment]
Thanks for the reply. I am on 3.0.8 version.

I selected All Female Face in a Video where there were 2 Male & 2 Female, as I only wanted to swap Female face, so I selected All Female Face, but in random frames the face jumps from female to male, so I posted this to know is there a solution to swap all female faces when (All Female Face) is being selected.

Thank You

**Comment by C0untFloyd** [comment]
To get a 100% swapping result you need to select/specify the faces to be swapped. The insightface swapper often makes mistakes when a face is at an angle otherwise...

> Does playing with the "Max Face Similarity Threshold" slider change things?

Face similarity is only being used when selecting target faces. All other options ignore this setting.

**Comment by RFedz007** [comment]
Thanks for your explanation :) Yes playing with max face Similarity threshold slider does change things & as you said different angles face doesn't get swapped. 

I just wanted to ask will remove All Female Face & All Male Face in your next update. 

One thing I must say slider which you added for source does help a lot for hairline. This really look Good. Thank You for that. 

I have not tried Clip after your latest update, as there was some error shown in previous version.

Thank You again
Have a Gr8 Day
Thank You
