### ISSUE TITLE
GUI opens but can't choose src face or target video

### ISSUE THREAD

**Issue by pointave** [C0untFloyd/roop-unleashed#23]
**Describe the bug**
The original roop works fine where I can select a face and video. This and actually all the other nsfw roops have gui's that wont allow me to add faces or video. I think since this fork has batch it might be allowing me to add video but I get the error "select an image for source path". 

Instead of updating the squares it remains blue with text saying select image with face and select target image/video.

**To Reproduce**
1. Go to 'win_run.bat'
2. Click on 'y to update'
3. GUI opens and I can click and select vid and face, but the GUI doesnt update.
4. Click Start
5. Choose output folder and then I get error on bottom of gui and traceback pasted at bottom of this issue page.

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [|||| ] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [||||| ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [ ||||] I have the latest code from the github repository
- [ ||||] I have followed the installation guide both on my own (create environment and install requirements) and the bat file

traceback
[ROOP.CORE] Sorting videos/images
[ROOP.CORE] ROOP.FACE-SWAPPER in progress...
Processing: |                                                                                 | 0/0 [00:00<?, ?frame/s]
[ROOP.CORE] ROOP.FACE-ENHANCER in progress...
Processing: |                                                                                 | 0/0 [00:00<?, ?frame/s]
[ROOP.FACE-SWAPPER] Select an image for source path.

**Comment by C0untFloyd** [comment]
I'm unsure if I understand. You just want to swap some source face to a target face in a video? Then you don't need batch-processing. Just click on the left button to choose the source face to be swapped in and after that click on the right button to choose the video. Don't touch the 'target-folder' button, that one is only for processing multiple videos/images! After clicking on start you will then be prompted for the output filename...

**Comment by pointave** [comment]
I'm saying batch processing is the only button to work. If i click on a face, the gui doesnt update. If i choose a video, the gui doesnt update. If you dont choose a video, you cant push start.

**Comment by pointave** [comment]
Thats obvious...
I'm saying batch processing is the only button to work. If i click on a face, the gui doesnt update. If i choose a video, the gui doesnt update. If you dont choose a video, you cant push start.

This issue isnt only with roop unleashed. It is with all roop forks I try. The gui will not update.

**Comment by pointave** [comment]
Thats obvious, and what I said I do in step 3.

I'm saying batch processing is the only button to actually work. If i click on a face, the gui doesnt update. If i choose a video, the gui doesnt update. If you dont choose a video, you cant push start (which is why I mentioned batch processing works)

This issue isnt only with roop unleashed. It is with all roop forks I try. The gui will not update with the selected face and/or video I select.
