### ISSUE TITLE
Drive with roop only working for one

### ISSUE THREAD

**Issue by Cloudaig** [C0untFloyd/roop-unleashed#235]
Now when I try use my roop on mounted drive account it just can't detect face , i tried many thing like building it from scratch but it just work for a single time 

**To Reproduce**

**Details**
What OS are you using?
- [x] Linux

Are you using a GPU?
-
- [x] NVIDIA
- 

**Which version of roop unleashed are you using?** Latest

**Screenshots**

**Comment by Cloudaig** [comment]
![Uploading Screenshot_2023-09-19-00-41-47-675_com.android.chrome.jpg…]()

**Comment by Cloudaig** [comment]
![Uploading Screenshot_2023-09-19-00-42-44-053_com.google.android.apps.docs.jpg…]()

**Comment by C0untFloyd** [comment]
Noone seems to know this issue and detecting a face has nothing to do with a mounted drive. I suspect the models can't be found/loaded but without further details 🤷‍♂️
