### ISSUE TITLE
[Feature Suggestion] Multiple Faces

### ISSUE THREAD

**Issue by Party5999** [C0untFloyd/roop-unleashed#237]
It would be great to have the ability to swap multiple faces at the same time.
This would be way better than applying one face at a time (every result would consistently worsen video quality because of compression).

**Comment by C0untFloyd** [comment]
But this is already possible?!? 
 * Open the first source image, select face or have it automatically selected if just 1, click the close button on the input image
 * ^ repeat this for as much faces as you want

Now do the same for the target faces, select the image or videoframe with your face and click on "Use face".
Rinse and repeat.

If you have 3 target faces for example you would of course need 3 input faces to map them onto. They will be swapped in the order of selection: S1 -> T1, S2 -> T2
Be sure to set the face swapping method to "selected".

**Comment by Party5999** [comment]
Holy moly I didn't know this was already possible. I'm really sorry about that.
Is it possible to change order of selection? 
Like I have S1 -> T1, S2 -> T2 and I'd like to swap S1 with S2 to become S2 -> T1, S1 -> T2 .

**Comment by C0untFloyd** [comment]
Source 1,2,3 will always be mapped to Target 1,2,3 if that's the question. But I don't see a problem here as you can are responsible for the ordering and you can remove single ones with the 'Remove selected' button.
