### ISSUE TITLE
Error loading "C:\github\roop-unleashed\installer_files\env\lib\site-packages\torch\lib\cublas64_11.dll" or one of its dependencies

### ISSUE THREAD

**Issue by jndietz** [C0untFloyd/roop-unleashed#238]
**Describe the bug**
`windows_run.bat` fails to start stating a required `dll` is missing.

**To Reproduce**
1. Run `windows_run`.bat

**Details**
What OS are you using?
- [X] Windows 
- [ ] Linux
- [ ] Linux in WSL
- [ ] Mac

Are you using a GPU?
- [X] NVIDIA
- [ ] No. CPU FTW
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
3.0.5

**Screenshots**

```
Launching roop unleashed - please edit windows_run.bat to customize commandline arguments
Check for Updates? [y/n]n
Launching App
Traceback (most recent call last):
  File "C:\github\roop-unleashed\roop-unleashed\run.py", line 3, in <module>
    from roop import core
  File "C:\github\roop-unleashed\roop-unleashed\roop\core.py", line 15, in <module>
    import torch
  File "C:\github\roop-unleashed\installer_files\env\lib\site-packages\torch\__init__.py", line 122, in <module>
    raise err
OSError: [WinError 193] %1 is not a valid Win32 application. Error loading "C:\github\roop-unleashed\installer_files\env\lib\site-packages\torch\lib\cublas64_11.dll" or one of its dependencies.

Done!
Press any key to continue . . .
```

The file definitely exists...

![image](https://github.com/C0untFloyd/roop-unleashed/assets/4515791/4e69bbde-8be3-4169-8918-edc675953f1c)

**Comment by jndietz** [comment]
I'm getting this with the base `roop` repository, too.  I'd graciously appreciate any help with this issue.

**Comment by lecrackzor** [comment]
I've had a similar issue while trying to run RVC and roop on the same partition. I usually just run the pip install requirements again depending on which project I'm working with and it clears it up.
