### ISSUE TITLE
Export as Gif

### ISSUE THREAD

**Issue by runew0lf** [C0untFloyd/roop-unleashed#24]
Instead of outputting to a movie, i would basically love a gif to gif with a faceswap. Any chance of making this happen?

**Comment by C0untFloyd** [comment]
Honestly this is not a feature I'm planning for the nearest future. You can do this already with minimal effort by using `keep frames` and feeding the images to some online gif creator website like [https://ezgif.com/maker](https://ezgif.com/maker)

**Comment by ljleb** [comment]
Would you accept a PR for this? I can just add a radio button to select the output format if it's welcome.

**Comment by C0untFloyd** [comment]
Just specifying the output format wouldn't change a lot, would it? AFAIK creating a gif needs some additional infos like looping enable and fps, which means a different call to ffmpeg. I believe this is something which currently can be done much better with specialized tools. I would like to tackle this after the change to a better UI Framework.

**Comment by ljleb** [comment]
I meant to add the related backend code as well of course, not just a radio button. Maybe it needs to toggle visible some other  (new) ui elements to keep the ui simple?

I haven't ran many generations with this extension yet, but I suspect there should be a relatively straightforward way to fit this.
