### ISSUE TITLE
Colab keep disconnecting/ banned 

### ISSUE THREAD

**Issue by Cloudaig** [C0untFloyd/roop-unleashed#240]
![Screenshot_2023-09-22-00-17-23-866_com android chrome](https://github.com/C0untFloyd/roop-unleashed/assets/141552144/ba738d4b-b7bd-4303-bf8c-afa83e110289)
**Describe the bug**

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**

**Screenshots**

**Comment by phineas-pta** [comment]
well it means google want u to pay

**Comment by C0untFloyd** [comment]
#208
