### ISSUE TITLE
upgrade dependencies

### ISSUE THREAD

**Issue by phineas-pta** [C0untFloyd/roop-unleashed#243]
**i havent tested yet**

`pillow` to v10.0.1 coz there's a critical security vulnerability with webp in chrome, see https://pillow.readthedocs.io/en/stable/releasenotes/10.0.1.html

`onnxruntime` & `onnxruntime-gpu` to v1.16, seem like there's some speed up, but need `onnx` to v1.14.1

`opencv`, `numpy` and `tqdm` can be updated but shouldnt matter much

im not sure why/how `tensorflow` can control memory 🤔, coz no packages rely on it

**Comment by C0untFloyd** [comment]
Thank you, will do.

> im not sure why/how tensorflow can control memory 🤔, coz no packages rely on it

This was more or less copy/paste from the original roop back then. I think the NSFW Filter uses/used Tensorflow.
