### ISSUE TITLE
"Connection Error Out" when trying to add a face or upload a video

### ISSUE THREAD

**Issue by samir-a-ali** [C0untFloyd/roop-unleashed#247]
Occurs when trying to upload a template face or template video

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

3.0.9 
python: 3.10.13 • torch: 2.0.1+cu118 • gradio: 3.44.4

**Comment by C0untFloyd** [comment]
If you're running locally, turn off 'public server'.

**Comment by samir-a-ali** [comment]
its already off
Samir A. Ali
New York Medical College
School of Medicine Class of 2024

**Comment by samir-a-ali** [comment]
its already off

**Comment by samir-a-ali** [comment]
Nevermind I just figured out that UBlockOrigin was affecting. turn it off for that site and now it works

**Comment by C0untFloyd** [comment]
I was just suggesting turning off Proxys or VPN but you were faster than me 😏
It's still funny because I'm using UBlock too and never had this problem...
