### ISSUE TITLE
Function for UI setting of target face similarity threshold

### ISSUE THREAD

**Issue by BFX-89** [C0untFloyd/roop-unleashed#25]
This is a brilliant project and appreciate the owner for all the efforts. 

One suggestion for new UI function: Can it be added for easier setting of DIST_THRESHOLD in the UI?

I found that for different target videos one may have to change this threshold to ensure correct selection of faces. 

If it can changed quickly in the UI for experimenting it would be much more convenient.

**Comment by C0untFloyd** [comment]
Yes indeed, something like this is needed. However it's not just about adding a slider to the gui, there has to be an additional CLI parameter and it's not only the distance threshold which needs to be specified. There is also a determination score, how sure the model is about a bounding box being a face. So this leads to more and more settings and I for one already kind of hate the cluttered, unresponsive tkinter GUI.

**Comment by Heislerink** [comment]
https://youtu.be/5K__zwBj_nY

This shows how to make a great gui easy.

**Comment by vin901** [comment]
Where can I change the DIST_THRESHOLD and determination score in the code (since it's not in the gui)?

**Comment by C0untFloyd** [comment]
Either use the new [gradio version](https://github.com/C0untFloyd/roop-unleashed/discussions/66) which has a slider for it or do a search in the .py files for that exact [word](https://github.com/C0untFloyd/roop-unleashed/blob/main/roop/processors/frame/face_swapper.py#L17)

**Comment by vin901** [comment]
Oh cool thank you, will check out the gradio version!
