### ISSUE TITLE
250 frames is a max!!

### ISSUE THREAD

**Issue by peja22** [C0untFloyd/roop-unleashed#251]
I uplaad video with more than 250 frames. But it can only proceed with 250 frames as max. Wny?

**Comment by peja22** [comment]
any one has the same problem on colab ? i can only proceed 250 frames. So it cuts my video

**Comment by peja22** [comment]
Version of roop-unleashed laded is 3.1.0

When uploaded 26 video. it proceed only 250 frames. "Processing frame range [0 - 250]" can not change to processs full movie. Can you change it as it was previously?

**Comment by C0untFloyd** [comment]
I did not change anything and checked with a longer video, working for me and seemingly everbody else. However many people reported problems on Colab #208.

**Comment by peja22** [comment]
well this is strange.I ran this colab link on chorome on mac and have 250frames  i ran this colab on chrome on windows and it is ok. ...

**Comment by peja22** [comment]
ok this was probably some issue with mp4 file strange.... file has 26 sek but when uplad was seen 8 sek..
