### ISSUE TITLE
ffmpeg Scaling mix up Height and Width. Then, Output gif have different size than target file

### ISSUE THREAD

**Issue by Laylog** [C0untFloyd/roop-unleashed#253]
**Describe the bug**
(Gif output) Scale parameters  given to ffmpeg mix up Height and Width 
If target file has Height > Width, then Output file may be larger than the initial file
If target file has Height < Width, then Output file may be smaller than initial file
Someone complained about that in a issue or discussion weeks ago.  It helped me figure out the workaround below.

**To Reproduce**
1. Target file is a .gif whose Height=400 and Width=192
2. Start processing file
3. Terminal output reads like: `Creating final GIF ... ffmpeg -hide_banner ... scale=400:-1:flags=lanczos,split[s0][s1] ...`

**Actual Result :** Output file has Height=833 and Width=400
**Expected Results :** Output file size should be: Height=400 and Width=192 (approximately)

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
3.1.0, but this issue occurred in previous versions as well

**Workaround/Fix**
I don't know much about Python coding, nor ffmpeg, nor Git management but the following works for me (use at your own risk)
1. Make sure Roop-Unleashed is not running
2. Edit file: `\roop-unleashed\roop\ffmpeg_writer.py`
    - Set the following instruction as a comment (add a # in front of it)
    - `cmd.extend(['-vf', f'scale={w}:{h}' if w != size[0] or h != size[1] else 'colorspace=bt709:iall=bt601-6-625:fast=1'])`
    - Then add this line
    - `cmd.extend(['-vf', f'scale={h}:{w}' if w != size[0] or h != size[1] else 'colorspace=bt709:iall=bt601-6-625:fast=1'])`
3. Edit file: `\roop-unleashed\roop\utilities.py`
    - Set the following instruction as a comment (add a # in front of it)
    - `run_ffmpeg(['-i', video_path, '-vf', f'fps={fps},scale={frame.shape[0]}:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse', '-loop', '0', gif_path])`
    - Then add this line
    - `run_ffmpeg(['-i', video_path, '-vf', f'fps={fps},scale={frame.shape[1]}:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse', '-loop', '0', gif_path])`
4. Delete .pyc files in `\roop-unleashed\roop\__pycache__` (they will be generated back next time you launch Roop-Unleashed)
5. Launch Roop-Unleashed (gif output will then have same size than target file)
6. Hope this helps

;-)

**Comment by sordidloam** [comment]
Nice job!Sent from my iPhoneOn Sep 26, 2023, at 5:50 PM, Laylog ***@***.***> wrote:﻿
Describe the bug
(Gif output) Scale parameters  given to ffmpeg mix up Height and Width
If target file has Height > Width, then Output file may be larger than the initial file
If target file has Height < Width, then Output file may be smaller than initial file
Someone complained about that in a issue or discussion weeks ago.  It helped me figure out the workaround below.
To Reproduce
Steps to reproduce the behavior:

Target file is a .gif whose Height=400 and Width=192
Start processing file
Terminal output reads like: Creating final GIF ... ffmpeg -hide_banner ... scale=400:-1:flags=lanczos,split[s0][s1] ...

Actual Result : Output file has Height=833 and Width=400
Expected Results : Output file size should be: Height=400 and Width=192 (approximately)
Details
What OS are you using?

 Linux
 Linux in WSL
 Windows
 Mac

Are you using a GPU?

 No. CPU FTW
 NVIDIA
 AMD
 Intel
 Mac

Which version of roop unleashed are you using?
3.1.0, but this issue occurred in previous versions as well
Workaround/Fix
I don't know much about Python coding, nor ffmpeg, nor Git management but the following works for me (use at your own risk)

Make sure Roop-Unleashed is not running
Edit file: \roop-unleashed\roop\ffmpeg_writer.py

Set the following instruction as a comment (add a # in front of it)
cmd.extend(['-vf', f'scale={w}:{h}' if w != size[0] or h != size[1] else 'colorspace=bt709:iall=bt601-6-625:fast=1'])
Then add this line
cmd.extend(['-vf', f'scale={h}:{w}' if w != size[0] or h != size[1] else 'colorspace=bt709:iall=bt601-6-625:fast=1'])


Edit file: \roop-unleashed\roop\utilities.py

Set the following instruction as a comment (add a # in front of it)
run_ffmpeg(['-i', video_path, '-vf', f'fps={fps},scale={frame.shape[0]}:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse', '-loop', '0', gif_path])
Then add this line
run_ffmpeg(['-i', video_path, '-vf', f'fps={fps},scale={frame.shape[1]}:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse', '-loop', '0', gif_path])


Delete .pyc files in \roop-unleashed\roop\__pycache__ (they will be generated back next time you launch Roop-Unleashed)
Launch Roop-Unleashed (gif output will then have same size than target file)
Hope this helps

;-)

**Comment by papagodzilla** [comment]
so now it did not lower the res but convert horizontal gif to stretch vertical gif

**Comment by papagodzilla** [comment]
> **Describe the bug** (Gif output) Scale parameters given to ffmpeg mix up Height and Width If target file has Height > Width, then Output file may be larger than the initial file If target file has Height < Width, then Output file may be smaller than initial file Someone complained about that in a issue or discussion weeks ago. It helped me figure out the workaround below.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Target file is a .gif whose Height=400 and Width=192
> 2. Start processing file
> 3. Terminal output reads like: `Creating final GIF ... ffmpeg -hide_banner ... scale=400:-1:flags=lanczos,split[s0][s1] ...`
> 
> **Actual Result :** Output file has Height=833 and Width=400 **Expected Results :** Output file size should be: Height=400 and Width=192 (approximately)
> 
> **Details** What OS are you using?
> 
> * [ ]  Linux
> * [ ]  Linux in WSL
> * [x]  Windows
> * [ ]  Mac
> 
> Are you using a GPU?
> 
> * [ ]  No. CPU FTW
> * [x]  NVIDIA
> * [ ]  AMD
> * [ ]  Intel
> * [ ]  Mac
> 
> **Which version of roop unleashed are you using?** 3.1.0, but this issue occurred in previous versions as well
> 
> **Workaround/Fix** I don't know much about Python coding, nor ffmpeg, nor Git management but the following works for me (use at your own risk)
> 
> 1. Make sure Roop-Unleashed is not running
> 2. Edit file: `\roop-unleashed\roop\ffmpeg_writer.py`
>    
>    * Set the following instruction as a comment (add a # in front of it)
>    * `cmd.extend(['-vf', f'scale={w}:{h}' if w != size[0] or h != size[1] else 'colorspace=bt709:iall=bt601-6-625:fast=1'])`
>    * Then add this line
>    * `cmd.extend(['-vf', f'scale={h}:{w}' if w != size[0] or h != size[1] else 'colorspace=bt709:iall=bt601-6-625:fast=1'])`
> 3. Edit file: `\roop-unleashed\roop\utilities.py`
>    
>    * Set the following instruction as a comment (add a # in front of it)
>    * `run_ffmpeg(['-i', video_path, '-vf', f'fps={fps},scale={frame.shape[0]}:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse', '-loop', '0', gif_path])`
>    * Then add this line
>    * `run_ffmpeg(['-i', video_path, '-vf', f'fps={fps},scale={frame.shape[1]}:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse', '-loop', '0', gif_path])`
> 4. Delete .pyc files in `\roop-unleashed\roop\__pycache__` (they will be generated back next time you launch Roop-Unleashed)
> 5. Launch Roop-Unleashed (gif output will then have same size than target file)
> 6. Hope this helps
> 
> ;-)
so now it did not lower the res but convert horizontal gif to stretch vertical gif

**Comment by C0untFloyd** [comment]
I don't think the sizes are wrong, I would have noticed by now. The impression of bad resolution could be instead caused by the colormap. I don't know what ffmpeg does but there are GIFs who re-use the palette (colormap) from the previous frame and that could lead to dithered images. If one of you has the time to investigate, the ffmpeg options are still dumped into the console. Perhaps it is just a tiny little option.
