### ISSUE TITLE
[Feature Request] DMDNet Specific Restoration

### ISSUE THREAD

**Issue by BigAdam86** [C0untFloyd/roop-unleashed#254]
Would be awesome if we could utilize the [Specific Restoration features](https://github.com/csxmli2016/DMDNet/tree/main#specific-restoration-with-several-high-quality-references-from-the-same-identity), either by using all currently uploaded Source Faces, or maybe by supplying a folder containing the specific face.

**Comment by C0untFloyd** [comment]
Yes, this is on my TODO List for quite some time. However I would like to combine this with blending of multiple source faces even for swapping (some people reported a better likeness preservation, didn't try myself so far). The coding for this isn't hard to do but the design to fit this neatly into the UI is tricky.

**Comment by C0untFloyd** [comment]
@BigAdam86 Do you have experience using this? I'm asking because I'm finished implementing it but for the life of me can't spot a difference! The reference images don't have to be aligned, do they?

**Comment by C0untFloyd** [comment]
Implemented with facesets

**Comment by BigAdam86** [comment]
> @BigAdam86 Do you have experience using this? I'm asking because I'm finished implementing it but for the life of me can't spot a difference! The reference images don't have to be aligned, do they?

I've only tried running it off of the samples included and those pictures didnt seem to be aligned and it worked. 
Will check out your implementation later ✌ Great job!
