### ISSUE TITLE
run.py: error: argument --video-encoder: invalid choice

### ISSUE THREAD

**Issue by MantisTree** [C0untFloyd/roop-unleashed#255]
Hi all, LOVE this project. Found it after ROOP died and this one is the cream of the crop.  Getting the following error on execution:

`run.py: error: argument --video-encoder: invalid choice: 'hevc_nvenc' (choose from 'libx264', 'libx265', 'libvpx-vp9')`

Please allow users to select the codec of their choice. **hevc_nvenc** uses NVIDIA GPU encoding and is significantly faster than the other options for those to whom it is available. In fact, perhaps it should be the default codec when CUDA is the execution provider.

Regards,
Mantis

**Comment by phineas-pta** [comment]
use the gradio interface, the command line is buggy

**Comment by C0untFloyd** [comment]
Disabled the CLI in the latest version, just use the setting instead.
