### ISSUE TITLE
hevc_nvenc / h264_nvcenc output format broken with v3.1.1

### ISSUE THREAD

**Issue by alexmineiro36** [C0untFloyd/roop-unleashed#256]
**Describe the bug**
If i want to use hevc_nvenc or h264_nvenc i get with the new update error "NoneType' object has no attribute 'elem_id". That Error is new and wasn't in the previous version. Can't Use NVENC Output at the moment.

**To Reproduce**
1. Go to Settings
2. Click on Video Output Format -> hevc_nvcenc or h264_nvenc
3. See error

**Details**
What OS are you using?
Windows 10

Are you using a GPU?
NVIDIA 3060 OC 12 GB 

**Which version of roop unleashed are you using?**
v3.1.1

**Comment by C0untFloyd** [comment]
Seems to be at your end only, switched between those a couple of times without problems. Perhaps try deleting 'config.yaml'?

**Comment by alexmineiro36** [comment]
thanks, delete config_colab.yaml and now it seems fine..
