### ISSUE TITLE
SELECTED FACE OPTION NOT WORKING MOST OF THE TIMES

### ISSUE THREAD

**Issue by inane-mafia** [C0untFloyd/roop-unleashed#260]
**Describe the bug**
when the image / video contain more than one person, i select the "selected face option"
most of the times it doesn't work, the 1st found face is always the priority

*IN VIDEO, if there are more than 1 female, the face is swapped only for the first person and stays on her, 
                  if there is a male and a female , there is a 50/50 chance that the face swap will keep switching between the target and 1st 
                  face

**To Reproduce**
1. Click on 'use face form this frame'
2. Click on 'selected face'
3. Click on the 2nd or 3rd face
4. Click on "use selected face and done"
5. Click on "start"
6. the output has only the 1st face swapped

**Details**
What OS are you using?

-  Windows 11

Are you using a GPU?
-  No, CPU - ryzen 

**Which version of roop unleashed are you using?**
latest 3.1.1

![Screenshot 2023-10-01 161700](https://github.com/C0untFloyd/roop-unleashed/assets/145937224/345438e0-4ab9-4bf7-b7aa-9cf7ef9b829c)

![Screenshot 2023-10-01 161725](https://github.com/C0untFloyd/roop-unleashed/assets/145937224/5bd37493-ba63-4c41-bcdc-2b065b03e7b4)

![Screenshot 2023-10-01 161741](https://github.com/C0untFloyd/roop-unleashed/assets/145937224/0ce48c85-6976-4ed0-8361-cee7611f30c5)

![Screenshot 2023-10-01 161802](https://github.com/C0untFloyd/roop-unleashed/assets/145937224/eb9524b2-9174-466a-9323-8ee0b4858bea)

![Screenshot 2023-10-01 161814](https://github.com/C0untFloyd/roop-unleashed/assets/145937224/bb210e14-7b6c-48f3-9a1e-4e29efc8b18a)

![Screenshot 2023-10-01 161836](https://github.com/C0untFloyd/roop-unleashed/assets/145937224/830ee3ca-1eff-47f8-abd0-6a7b03c4fabe)

**Comment by C0untFloyd** [comment]
In this [image](https://user-images.githubusercontent.com/145937224/271823698-eb9524b2-9174-466a-9323-8ee0b4858bea.png) you've posted there is clearly just 1 source face and 1 target face selected, of course it will only swap 1 face then. I'm not sure what you really want. Do you want to paste the 1 face on all of the girls in the group? Then you wouldn't even need to select any target face, just choose 'All faces' in the swapping selection. Perhaps you want to swap 4 different faces to the 4 target faces? Then you would of course need to select the 4 faces to swap and choose 'Selected face' as swapping mode.
The wiki I started might help you -> https://github.com/C0untFloyd/roop-unleashed/wiki/Face-Swap-Tab
