### ISSUE TITLE
Unable to expose to LAN network

### ISSUE THREAD

**Issue by poloba** [C0untFloyd/roop-unleashed#274]
**Describe the bug**
- Unable to expose to LAN network, I can't do this https://github.com/C0untFloyd/roop-unleashed/discussions/94 beacuse my server hasn't desktop, I can only get access via ssh. Another way to change this config manually in the code or config?

Thanks!

**To Reproduce**
- At launch python run.py

**Details**
What OS are you using?
- [x] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you using a GPU?
- [x] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?** 

**Screenshots**

**Comment by C0untFloyd** [comment]
Sure, the settings are exposed in the file config.yaml.
