### ISSUE TITLE
VRAM clear Auto + by demand?  + (Low Requirements Info that might help)

### ISSUE THREAD

**Issue by AlonDan** [C0untFloyd/roop-unleashed#28]
### GPU VRAM - Clear after Processing last process
Just to be clear this information is based on my MANY tests and experiments with ROOP UNLEASHED, and my hardware is the worth to test it:

At the moment since I'm using a very old GPU with only 4GB VRAM
CPU Intel core i7 4th gen with 32GB RAM and everything installed on SSD.

The good thing is that, my tests can help with understand if ROOP can run on X:
I probably have the lowest requirements in ROOP scene 😅 and still, **ROOP UNLEASHED WORKS FINE!**
Of course, it's not fast as modern PC's, it's not slow as using CPU... it's still running about x10-12 times faster than my CPU with my antique GPU.

✅ My latest tests made with: Roop Unleashed version **2.0.3**

---

After each process of a video, if I won't CLOSE and Re-Launch ROOP (which clears the VRAM)
It will just go on very low iterations per frame.

For example I can start with `9-12 /frame memory_usage=02.49`
and it remain the speed, but the moment the memory usage goes up to 03.X (because of my limited memory I can see that easily) it goes down to around 1.x /frame  

And you can imagine how slow it is, so for VERY short video it's fine but for something like 40 seconds and above (and I even tried 2 minutes videos because I like to TEST the limits of ROOP) it's hard.

SO if I do multiple videos of 10-20 seconds, I can do only 2 of them and I MUST restart Roop because it's the only way it CLEAR the VRAM, any ADDITIONAL process keeps the latest VRAM and not clearing it...

Probably most of users don't have an old GPU and can't feel these problems but even if you'll have 6GB / 8GB  and you'll do longer videos eventually you will need to RESTART ROOP to clear the memory if you want to process your next swap at the same session.

Also, if you use the Enhancement (GFPGAN / Codeformer, etc..) this will drink extra VRAM so the VRAM isn't always enough for multiple swapping videos at the same session, VRAM will be out eventually because based on my test currently it doesn't clear it.

---

### SOLUTION IDEAS:

**1** - Add a Button:  "CLEAR VRAM" 
I'm no programmer I don't know if it's possible by demand
But that way you won't need to CLOSE and Re-Launch ROOP for every new additional swap.

**2** - AUTO-CLEAR VRAM - The moment it finishes the process (including Enhancements or anything ROOP drinks).

Obviously solution 2 is more convinent, automatically, no extra buttons... but I don't know if ANY of the above solutions is possible, I hope it is... 🤞

**Comment by Heislerink** [comment]
If I understand correctly, all you have to do is add the line cuda.close() at the end of whatever function processes the video.

**Comment by AlonDan** [comment]
> If I understand correctly, all you have to do is add the line cuda.close() at the end of whatever function processes the video.

I wish I knew, as I said I'm not a programmer but if it's that simple, probably it won't be hard to add as AUTO after process is complete? :)

**Comment by Heislerink** [comment]
Actually, looking at the code it does have a function that clears resources after processing. I’m not sure why it’s not working for you. Are you using cuda and the gpu option?Jeff HeislerOn Jul 9, 2023, at 6:34 PM, AlonDan ***@***.***> wrote:﻿

If I understand correctly, all you have to do is add the line cuda.close() at the end of whatever function processes the video.

I wish I knew, as I said I'm not a programmer but if it's that simple, probably it won't be hard to add as AUTO after process is complete? :)

**Comment by AlonDan** [comment]
Yes, I use cuda and Nvidia GPU, everything installed so it is fully supported (or at least should) but for sure it is not clearing my VRAM after every process.

I think it will be nice to add a button since if like you say there is an AUTO clear, it's not working at least on my side, I wonder if it works for others but even if it is... it could be an extra solution to have a button on the GUI to clear by demand.

**Comment by Heislerink** [comment]
If the repo owner doesn’t want to add the feature I might be able to help. Let’s see what happens. Jeff HeislerOn Jul 9, 2023, at 6:46 PM, AlonDan ***@***.***> wrote:﻿
Yes, I use cuda and Nvidia GPU, everything installed so it is fully supported (or at least should) but for sure it is not clearing my VRAM after every process.
I think it will be nice to add a button since if like you say there is an AUTO clear, it's not working at least on my side, I wonder if it works for others but even if it is... it could be an extra solution to have a button on the GUI to clear by demand.

**Comment by Operator404** [comment]
I also have this problem, I have to constantly restart the program

> Roop Unleashed version 2.0.3  GTX 1050ti
