### ISSUE TITLE
Colab version cut frames to 250

### ISSUE THREAD

**Issue by peja22** [C0untFloyd/roop-unleashed#280]
When i upload video with 26 seconds. it cuts numer of frames only to 250

**Comment by peja22** [comment]
Well  it cut frames in all videos i try to proceed . why?

**Comment by C0untFloyd** [comment]
Be glad that it still works for you, other people reported Google banning roop and derivates e.g. #208

**Comment by peja22** [comment]
ohhh. ok ::)

**Comment by C0untFloyd** [comment]
I just saw you posted the same 2 weeks ago #251 
There you wrote something about a problem with just a specific video? In any case, this still isn't a problem I can fix, it's probably something with colab use and/or the video itself.
