### ISSUE TITLE
COLAB VERSION: bufsize must be an integer Press any key to continue...

### ISSUE THREAD

**Issue by peja22** [C0untFloyd/roop-unleashed#281]
In colab version, whe proceed with fila. i always see this message:

bufsize must be an integer
Press any key to continue...

Where shoould be this key pressed?

**Comment by C0untFloyd** [comment]
I don't understand, can you explain some more or dump the output here?

**Comment by peja22** [comment]
well this message shows up when in graphic interface is clicked to start and it comes to this point :

Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0', 'tunable_op_tuning_enable': '0', 'device_id': '0', 'has_user_compute_stream': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_alloc': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'cudnn_conv1d_pad_to_nc1d': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'enable_cuda_graph': '0', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0'}}
inswapper-shape: [1, 3, 128, 128]
Creating Custom dimensions 1920x1080 px11__temp.mp4 with 30.0 FPS...
Extracting frames...
ffmpeg -hide_banner -hwaccel auto -y -loglevel error -i /content/roop-unleashed/temp/ebac963e5d01e9ff356538be303c7368705169d1/Custom dimensions 1920x1080 px11.mp4 -q:v 1 -pix_fmt rgb24 -vf trim=start_frame=0:end_frame=1345,fps=30.0 -vsync 0 /content/roop-unleashed/temp/ebac963e5d01e9ff356538be303c7368705169d1/temp/Custom dimensions 1920x1080 px11/%04d.png
Processing: 100% 1345/1345 [08:58<00:00,  2.50frame/s, memory_usage=04.32GB, execution_threads=3]
bufsize must be an integer
Press any key to continue...  -> and it holds here

**Comment by peja22** [comment]
iill try to share printscreen

**Comment by C0untFloyd** [comment]
No thanks, not needed. 2 things:
* Is there a reason you're using the keep frames option instead of In-Memory?
* Could try renaming the video to a filename without blanks?

**Comment by peja22** [comment]
- no there is no special reason - ill change it and test
- yes ill do that and share today information

**Comment by peja22** [comment]
issue solved you were right name of the file was the problem :) thanks
