### ISSUE TITLE
Faceset creation is cutting the images and leads to an "no faces detected" error?

### ISSUE THREAD

**Issue by Niiickel** [C0untFloyd/roop-unleashed#285]
Face management recognizes faces from original input jpg pictures but when creating the faceset it throws an error: "no faces were detected in 0.png, 1.png etc." 

When I try to use the created png images in the output folder as single images on the face swap tab it also detects no face.

I used the black border trick on the original jpg images to make the face visible and it seems that the created png images for the faceset cuts the borders out and doesn't recognize the faces anymore.

/edit no faces detected error is also showing without the black border trick.
I tested it with another person/picture set.
The images are good quality.

Why is it even creating new png images and uses them for a faceset instead of using the original jpg images that I put in?

I hope that's understandable what I mean.

Many thanks!

**Comment by brahianrosswill** [comment]
"no faces were detected in 0.png" happens to me too however i don't know what is the problem because it looks like it somewhat detects the face and then shows that error.

**Comment by C0untFloyd** [comment]
Is this with smaller face sizes (compared to the original image) or zoomed in faces?

> Why is it even creating new png images and uses them for a faceset instead of using the original jpg images that I put in?

Because you can put in images with mutiple faces on it. The faces you use need to be cut out of the whole image.

I'm currently using the bounding box from the face detection, expand it by 25% to the top and 10% in every other dimension. This was enough in my tests so far but it seems to be not working in some cases. I will rewrite it to check the face detection after cutting out and modifying the sizes until the face detection is working.

**Comment by Niiickel** [comment]
> Is this with smaller face sizes (compared to the original image) or zoomed in faces?
> 
> > Why is it even creating new png images and uses them for a faceset instead of using the original jpg images that I put in?
> 
> Because you can put in images with mutiple faces on it. The faces you use need to be cut out of the whole image.
> 
> I'm currently using the bounding box from the face detection, expand it by 25% to the top and 10% in every other dimension. This was enough in my tests so far but it seems to be not working in some cases. I will rewrite it to check the face detection after cutting out and modifying the sizes until the face is detected again.

I don't know if I understand your question, but the created PNG files are all zoomed in.
I tried it with selfies, full and upper body images of myself as original pictures.

**Comment by ShrekLovesAll** [comment]
The problem seems to come back to the fact that it doesn't recognize faces if they're too close to the edge of the photo

**Comment by C0untFloyd** [comment]
There was a bug cropping the images again after adding more images to the facesets. Also resizing them to 512x512 afterwards was probably not my best idea. I fixed it yesterday but I didn't commit it yet because I'm not completely finished with some other stuff.

**Comment by sordidloam** [comment]
It’s cropping the images to make the face set.  I bet this needs to expand the crop?

**Comment by C0untFloyd** [comment]
There was a bug with resizing and also now there is an extra check if the face can be detected in the resized/cropped image.
Fixed and commited btw. 😃

**Comment by Niiickel** [comment]
> There was a bug with resizing and also now there is an extra check if the face can be detected in the resized/cropped image. Fixed and commited btw. 😃

works flawless now! many thanks for the quick fix
