### ISSUE TITLE
MKV not shown as supported file format

### ISSUE THREAD

**Issue by lysxelapsed** [C0untFloyd/roop-unleashed#288]
When choosing target files, MKV is not listed as supported file format.
I know that I can switch to "all files", but you can bet I forget it at least every second time 😆 

![mkv](https://github.com/C0untFloyd/roop-unleashed/assets/63816546/e0633cd9-751a-4739-9377-c78a960f092a)

**Comment by C0untFloyd** [comment]
https://github.com/C0untFloyd/roop-unleashed/blob/main/ui/tabs/faceswap_tab.py#L52
(uses gradio inbuilt video extensions) 

You don't want me to file another gradio issue, do you? 😝

**Comment by lysxelapsed** [comment]
Ah okay, gradio again. No don't, they'll take your head off 🤣 I'll add an "ALL FILES"-post-it to my monitor 😉

**Comment by C0untFloyd** [comment]
I can add extra extensions but it would be a separated item like 'All files' 😢
