### ISSUE TITLE
Video processing speed issue.

### ISSUE THREAD

**Issue by zTnCTV** [C0untFloyd/roop-unleashed#293]
I'm processing a video, but it's taking less time than the original video. 
Specifically, the original video is 3 minutes with a frame rate of 30 FPS. 
After processing, the video is just over 2 minutes, which is not enough time compared to the original. 
The frame rate seems to be faster, as if you've increased the video playback speed. 
I'm using version 3.3.3, and the same issue occurred with version 3.2.1. 
The video is processed with CUDA on an NVIDIA RTX 4090 GPU.

**Comment by C0untFloyd** [comment]
It's very likely the detected fps are wrong. You can override the detection and force it to use the correct one with the fps slider.

**Comment by lysxelapsed** [comment]
sorry for re-opening, but this doesn't seem like a small issue.
batch-processed 11 files which always came out absolutely fine a few versions back. processed the same files overnight, 5 of the 11 came out with wrong fps and sped up like hell (up to 4 times).
overriding is only an option, if every target file has the exact same fps - they usually don't. or we're back to processing one by one and check / adjust every single time to avoid wasted time and energy consumption. that would be a big step backwards in my opinion.
what could cause this? new, buggy version of ffprobe?

**Comment by zTnCTV** [comment]
Hello!
I have found the cause of the issue and I will share it with you.
The cause is your source video.
In the MediaInfo section of your source video, pay attention to the "Frame rate mode:"

"**Variable**" (This is the cause of the problem because in this mode, the video's FPS is not fixed and can fluctuate depending on the frames within the video.)
Use a video conversion software to convert the video to a standard FPS in "**Constant**" mode; this will ensure that the FPS remains at a fixed value, for example, 30 or 60.

Good luck!

**Comment by lysxelapsed** [comment]
thanks for the update. still can't be the cause in my case, since the exact same files came out fine a few versions back - stupid me forgot to write down the version again and did a git pull instead of testing in a new enviroment first ☹️ 
detecting and re-encoding all variable-fps-files (again) would be a massive pain in the ass. that may be a solution, but definitely a last-resort-solution for me.
