### ISSUE TITLE
Anyone having issues with creating face set? Seems to not work on linux.

### ISSUE THREAD

**Issue by somenewaccountthen** [C0untFloyd/roop-unleashed#295]
Anyone having issues with creating face set? Seems to not work.
Creates a folder with d--------- rights.
I think it's the funky code for getting a temp for. Mayble use tempfile import instead or it is the unzip just using 0 rights when it creates the  folder? I do own the created folder, it's just created as d---------  faceset, and it crashes on writing the 1st image from the faceset fsz.

Linux
Cuda 11.8

**Comment by C0untFloyd** [comment]
There are people using this successfully on Linux, see here:
https://github.com/C0untFloyd/roop-unleashed/discussions/276#discussioncomment-7234156

I'm using the default python folder creation method which uses permissions 777. Did you perhaps change the permission setting for newly created files in your OS? I found https://www.systutorials.com/in-python-os-makedirs-with-0777-mode-does-not-give-others-write-permission/ and could easily include it.
Before I push that change, are you on v3.3.4? If so, there is a new, better temp folder handling and you could try the new setting which uses the OS Temp folder. Also terminal output where it's crashing would help me.

**Comment by C0untFloyd** [comment]
Meanwhile I committed the change, please tell me if it's working for you.

**Comment by trevorr** [comment]
I'm having the same issue on MacOS. I pulled the code today, so it has the `mkdir_with_umask` change. Creating the `temp/faceset` folder with the correct permissions doesn't help; it just ends up getting reset back to `dr----x--x`. I think the issue is `mode=777` is decimal but you want octal `mode=0o777`:

```python
def mkdir_with_umask(directory):
    oldmask = os.umask(000)
    os.makedirs(directory, mode=777, exist_ok=True) # mode should be 0o777
    os.umask(oldmask)
```

**Comment by dnnagy** [comment]
@trevorr 's solution works perfectly. You just have to rewrite `777` to `0o777` in `roop/utilities.py` and it works like a charm

**Comment by joshkerr** [comment]
Agreed. @trevorr solution works for me on MacOS. Was getting permission errors before, now it works like a charm.
