### ISSUE TITLE
Batch-process multiple input faces

### ISSUE THREAD

**Issue by crowbait** [C0untFloyd/roop-unleashed#297]
The README lists a feature "Batch processing of images/videos".

I don't know if this is even meant this way, but I can't figure out how to batch-process multiple input (!) faces into one target video (aka we have one video in which a face should be swapped, do it in batch for multiple people so we get multiple videos with the face swapped to a bunch of different input faces).

If this is indeed not how that feature is meant, I'd like to suggest that : )

- - -
I can, however, batch-process one input into multiple target videos, so that way round it works as intended.

**Comment by crowbait** [comment]
bump

**Comment by lysxelapsed** [comment]
I've suggested that since "the early days" 😆, still waiting for it. It's on the list, but not a priority for the delevoper.

**Comment by crowbait** [comment]
> I've suggested that since "the early days" 😆, still waiting for it. It's on the list, but not a priority for the delevoper.

Well, I'll keep bumping this whenever the Github bot thinks it's stale. I think it would make a great feature.

**Comment by lysxelapsed** [comment]
I'll give this another bump, hope you don't mind ;)

**Comment by crowbait** [comment]
> I'll give this another bump, hope you don't mind ;)

Sadly, I missed the bot's notification and the issue got closed... I don't think we have any real chance on this feature after all : /
