### ISSUE TITLE
Batch File Processing

### ISSUE THREAD

**Issue by ialhabbal** [C0untFloyd/roop-unleashed#3]
Would be great if you could develop the feature to batch process files (targets mainly). User would select source image and multiple target files. The user should be able to select specific face from the multiple target files. Great work so far!

**Comment by C0untFloyd** [comment]
Thanks and yes, this isn't hard to do and probably is a feature lots of people would like. I'm unsure however how this could be done in pure CLI headless mode. This might be a GUI-only feature then.

**Comment by ialhabbal** [comment]
Right now there are two forks which feature batch processing, one without select specific face and one with select specific face but this fork only works with videos and malfunctions with photos. The other one does not feature select specific face. If your fork adds select specific face feature for both videos and photos and given how stable it is right now, it would be the go-to fork. I think you are right (GUI approach).

**Comment by C0untFloyd** [comment]
Batch processing for GUI and CLI implemented now.

**Comment by ialhabbal** [comment]
Awesome! Thank you very much!!
