### ISSUE TITLE
TensorRT Extension Nvidia possible?

### ISSUE THREAD

**Issue by Niiickel** [C0untFloyd/roop-unleashed#300]
Hi,

Nvidia released a new game ready driver, and it supports Stable Diffusion with Automatic1111 and you get way faster results.

[https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT](url)
[https://nvidia.custhelp.com/app/answers/detail/a_id/5487](url)

Is there a way to use this with roop?

**Comment by phineas-pta** [comment]
1. just some marketing, u gain speed but lost time waiting for it to compile
2. if u still want, with roop use `--execution-provider tensorrt` but u have to install cuda + cudnn + tensorrt properly

**Comment by Niiickel** [comment]
> 1. just some marketing, u gain speed but lost time waiting for it to compile
> 2. if u still want, with roop use `--execution-provider tensorrt` but u have to install cuda + cudnn + tensorrt properly

cuda and cudnn are installed properly... Do you have any guide for tensorrt?

**Comment by phineas-pta** [comment]
official docs: https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html

i write my own guide: https://github.com/phineas-pta/NVIDIA-win/blob/main/NVIDIA-win.md
