### ISSUE TITLE
KeyError: 'TEMP'

### ISSUE THREAD

**Issue by primeinc** [C0untFloyd/roop-unleashed#301]
Traceback (most recent call last):
  File "/workspace/roop-unleashed/run.py", line 6, in <module>
    core.run()
  File "/workspace/roop-unleashed/roop/core.py", line 360, in run
    main.run()
  File "/workspace/roop-unleashed/ui/main.py", line 33, in run
    prepare_environment()
  File "/workspace/roop-unleashed/ui/main.py", line 26, in prepare_environment
    os.makedirs(os.environ["TEMP"], exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'TEMP'

I was playing around the other day and checked `Use OS temp folder`. The next day I got this error when I opened it. Indeed its correct I did not have `TEMP` set. The issue in my mind is most of the time that's not set in Linux, cuz we got /tmp

quick fix: In your shell `export TEMP=/tmp` and then start roop again

Anyway, solutions.. Any reason we arn't using tempfile? 
```python
import tempfile

temp_dir = tempfile.gettempdir()
```

Oh this is probably just code from pre-OS temp dir option that didn't get fleshed out, because you used to have to always create the temp folder. Anyway if you want to give me some direction on which method you want, happy to submit a PR.

**Comment by infinitygorkem** [comment]
I just noticed this bug too. Any chance you can contact the dev to get tempfile used so I can remove the workaround i have for this?
