### ISSUE TITLE
[Feature] Skip uploading Target file and access it directly

### ISSUE THREAD

**Issue by RoombaVoid** [C0untFloyd/roop-unleashed#309]
I use big files (VR) and uploading the files to the temp directory seems kinda pointless when running it locally. So I have to slice them up.

Would love to see an option to let Roop access the Target file directly.

**Comment by Legendaryl123** [comment]
I second this request.  Would be nice to pull an entire 5gb file into the UI.  My question for you Roomba is this:  when processing footage with 3 people on screen, which is doubled to 6 faces in VR footage, are you getting errors?
I've pulled off some pretty impressive stuff so far.
