### ISSUE TITLE
Multi face input

### ISSUE THREAD

**Issue by jimaek** [C0untFloyd/roop-unleashed#31]
It would be great to allow the selection of more than 1 input face (different angles for example) of the same person for higher quality results.

Additionally there was a lot of work done on roop and declined that you could potentially reuse to speed up the development of this fork https://github.com/s0md3v/roop/wiki/5.-Workshop

**Comment by C0untFloyd** [comment]
1. This wouldn't work with the current model automatically, you would need to annotate angles by hand somehow.
2. Yeah sure, however I'm just 1 person who does it in his spare time and feature creep killed lots of devs & apps in this world. So not happening any time soon. I would happily accept PRs though if they are fitting nicely into the base.
