### ISSUE TITLE
Sporadic Performance

### ISSUE THREAD

**Issue by JuvenileLocksmith** [C0untFloyd/roop-unleashed#313]
**Perfomance appears to fluctuate dramatically**
This isn't so much a problem as it is an observation. The system's performance seems to vary significantly, initially operating at high speed. Interestingly, the system's full capabilities are leveraged only when extracting frames to media; in-memory processing is notably less efficient. My setup, featuring an AMD EPYC 74F3 24-Core Processor with approximately 3.2GHz and 450GB RAM, along with a robust GPU, is substantial. However, nvidia-smi reveals only 30% GPU usage. Have included a five minute snapshot. The CPU seems to be the main workhorse, operating in sporadic bursts. I suspect thermal throttling could be a factor. I plan to develop a script that segments a video into 20-second chunks, initiates the application, terminates it, and then restarts the process to assess performance changes. Feedback is appreciated. Kudos to the system's creators and good riddance to the problematic maintainer—I did forewarn the creator about him. 

An additional detail while going through the document is the I am invoking the application via run.py which is the recommended approach for linux while windows_run.bat is direct for windows. Will attempt the 'correct approach' and see if that results in any difference, but a quick look inside both files does not appear to indicate much of a difference apart from conda checks, ffmpeg and installer script in windows all of which are already handled.

1.37FPS Process at 1hr25min, estimating 1h436minutes to go 
C:\Users\pompous_pigeon\roop-unleashed\temp\2c996b89fd050c2c68aa06295e8975ad4bfff423\Mug_Part_01.mp4 -q:v 1 -pix_fmt rgb24 C:\Users\pompous_pigeon\roop-unleashed\temp\2c996b89fd050c2c68aa06295e8975ad4bfff423\temp\Mug_Part_01\%04d.png
Processing:  70%|█████████    | 18158/26084 [1:25:50<1:36:33,  1.37frame/s, memory_usage=04.23GB, execution_threads=34]

5.85FPS Process at 1hr33min, estimating 20minutes to go

_banner -hwaccel auto -y -loglevel error -i C:\Users\pompous_pigeon\roop-unleashed\temp\2c996b89fd050c2c68aa06295e8975ad4bfff423\Mug_Part_01.mp4 -q:v 1 -pix_fmt rgb24 C:\Users\pompous_pigeon\roop-unleashed\temp\2c996b89fd050c2c68aa06295e8975ad4bfff423\temp\Mug_Part_01\%04d.png
Processing:  73%|██████████▉    | 19042/26084 [1:33:00<20:04,  5.85frame/s, memory_usage=04.25GB, execution_threads=34]

<img width="546" alt="Screenshot 2023-10-23 at 23 19 19" src="https://github.com/C0untFloyd/roop-unleashed/assets/83825290/645a716d-5685-4c92-bb46-13c7253d1905">

**To Reproduce**

**Details**
What OS are you using?
- [x] Windows 

Are you using a GPU?

- [x] NVIDIA

**Which version of roop unleashed are you using?**

**Screenshots**
If applicable, add screenshots to help explain your probl
<img width="457" alt="Screenshot 2023-10-23 at 22 42 17" src="https://github.com/C0untFloyd/roop-unleashed/assets/83825290/eee3e5cb-e7b0-4a08-83b5-0aa46f01de83">
<img width="729" alt="Screenshot 2023-10-23 at 22 45 11" src="https://github.com/C0untFloyd/roop-unleashed/assets/83825290/f70068ae-4c63-4b68-8ec5-53a60cfb79df">
<img width="516" alt="Screenshot 2023-10-23 at 22 53 16" src="https://github.com/C0untFloyd/roop-unleashed/assets/83825290/8a687424-d442-4fb0-942b-08dc647f07ce">
em.

**Comment by phineas-pta** [comment]
virtual machine ? not sure if cuda even work

**Comment by phineas-pta** [comment]
if u r expert and setup your server properly then u can ignore me, i never see anyone share a working usecase of roop in VM that's why i doubt

i admit that im completely ignorant of cloud infrastructure, but i believe those platforms seldomly use hyper v to deploy + gpu passthrough

just a side note, inswapper license is against commercial purpose

**Comment by Fikka7** [comment]
Thanks for sharing your findings, I too would be very interested to see where this can be optimized. One thing I notice is you seem to have set the max thread count to 34 under the roop settings, can you confirm this ? 
In my test when using a thread count of 14 the GPU memory requirement exceeds 24GB (with default 2, its around 5.8GB). It seems your card has 24GB as, so I am guessing 34 would exceed your VRam and offload it to the CPU. Try setting to around 10 threads and see how much of the GPU memory is being used making sure you stay under of whats available.


https://github.com/C0untFloyd/roop-unleashed/assets/147658656/609e4ef9-64e2-4c78-a1bc-d062cb95202a


https://github.com/C0untFloyd/roop-unleashed/assets/147658656/ed92cb8e-4cfe-4492-8ca9-45dd639a5222
