### ISSUE TITLE
The livecam's frame rate is too low, not fully utilizing the computer's performance

### ISSUE THREAD

**Issue by deviljoker5200** [C0untFloyd/roop-unleashed#316]
For example, if the target video's frame rate is 24 frames per second, after using livecam, the frame rate drops to around 2 frames per second. However, both the GPU and CPU are unable to fully utilize their performance. I am using OBS Studio's virtual camera to stream a local video file to livecam.
I wonder if it's possible to use Livecam more smoothly for playing local videos.

**Comment by jorvilla84** [comment]
I am having the same issue here, I have tested all the way up to 32 threads but same results:  roughly 2fps on fake camera output, and GPU, CPU loads are 1-10% and RAM 9.7/32Gb VRAM 3.9/11Gb.

**Comment by 592429d** [comment]
> I am having the same issue here, I have tested all the way up to 32 threads but same results: roughly 2fps on fake camera output, and GPU, CPU loads are 1-10% and RAM 9.7/32Gb VRAM 3.9/11Gb.

Same with me. I found that the output livecam fps just 1-2fps even when I have not upload any image for faceswaping. I have tested up to more than 20 threads but nothing different. I think there something with the default fps of output live cam, not just GPU and CPU.

**Comment by lysxelapsed** [comment]
what are your results after restarting roop unleashed and using only a single thread? aside from the livecam feature, which I don't use, running too many threads is the very thing that cause performance issues in the first place in most cases.

**Comment by 592429d** [comment]
> what are your results after restarting roop unleashed and using only a single thread? aside from the livecam feature, which I don't use, running too many threads is the very thing that cause performance issues in the first place in most cases.
I have tried running with only 1 thread, but the result is the same.

**Comment by lysxelapsed** [comment]
😞 from what I see in the threads, nobody's gotten the livecam with acceptable fps running so far 🤷‍♂️

**Comment by mujtabashamas** [comment]
Same, I tried cant get decent fps.
