### ISSUE TITLE
ONNXRuntimeError: CUDA failure 719: unspecified launch failure

### ISSUE THREAD

**Issue by mammuthus** [C0untFloyd/roop-unleashed#32]
**Describe the bug**
I saw a black screen for approximately 10 seconds (I believe this occurred because my Nvidia driver was reloading), and then an error message appeared:
```
 File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop-unleashed\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 217, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : CUDA failure 719: unspecified launch failure ; GPU=0 ; hostname=BALYN-OMAVEL ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\gpu_data_transfer.cc ; line=73 ; expr=cudaMemcpyAsync(dst_data, src_data, bytes, cudaMemcpyDeviceToHost, static_cast<cudaStream_t>(stream.GetHandle()));
```

**To Reproduce**
1. Run roop-unleashed with:
`python run.py --execution-provider cuda --frame-processor face_swapper face_enhancer --video-encoder libvpx-vp9 -f C:\Users\omavel\Desktop\roopFake\output\unleashed`
3. Switch on "Keep fps" option
4. Choose GFPGAN as enhancement engine
5. Press "Start"
6. I saw a black screen for approximately 10 seconds (I believe this occurred because my Nvidia driver was reloading), and then an error message appeared:
```
 File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop-unleashed\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 217, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : CUDA failure 719: unspecified launch failure ; GPU=0 ; hostname=BALYN-OMAVEL ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\gpu_data_transfer.cc ; line=73 ; expr=cudaMemcpyAsync(dst_data, src_data, bytes, cudaMemcpyDeviceToHost, static_cast<cudaStream_t>(stream.GetHandle()));
```

I didn't encounter any such issues when using the original roop with my current CUDA set (no support for face enhancement because roop doesn't offer it)

```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

```
wmic path win32_VideoController get name,driverVersion
DriverVersion  Name
31.0.15.3640   NVIDIA GeForce RTX 3080 Ti
```

**Details**
What OS are you using?
✅ Windows 

Are you try to use a GPU?
✅ NVIDIA

**Screenshots**
![Untitled-1](https://github.com/C0untFloyd/roop-unleashed/assets/1700286/ab273982-e073-4ad9-ab92-4ca0ad92fdc5)
![234](https://github.com/C0untFloyd/roop-unleashed/assets/1700286/03b13be7-c083-4adc-96f5-e2ae67473829)

**Sanity Check**
✅ I have the latest code from the github repository
✅ I have followed the installation guide

**Comment by mammuthus** [comment]
Fresh `roop-unleashed` installation.
Tried with Python 3.10 instead of Python 3.9.
Also got rid of long directory paths. Failed on face-enhancement as previously: 
![image](https://github.com/C0untFloyd/roop-unleashed/assets/1700286/af8b3642-a9de-49bb-b9d9-bad6aeb04458)

**Comment by C0untFloyd** [comment]
Perhaps overheating issues on your side? How much VRAM do you have? I don't have a clue really...

**Comment by mammuthus** [comment]
Temperature is fine. I have 12GB VRAM.

**Comment by phineas-pta** [comment]
try lower `--execution-threads`

**Comment by C0untFloyd** [comment]
Closed all old issues because of new rewritten version.
