### ISSUE TITLE
CUDA Providers Issue

### ISSUE THREAD

**Issue by poepoeng** [C0untFloyd/roop-unleashed#321]
**Describe the bug**
This day.
When im upload the input faces, i got error on cuda provider .
This debug error :
`EP Error /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:121 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:114 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=-1694196224 ; hostname=n5kocnadg7 ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider.cc ; line=236 ; expr=cudaSetDevice(info_.device_id); 

 when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.`

How to fix it ?

Thanks

**Details**
What OS are you using?
- [OK ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ OK] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Comment by phineas-pta** [comment]
it's already written
```
CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version
```

**Comment by Fikka7** [comment]
> How to fix it ?

First try updating your NVidia drivers and installing CUDA 11.8 toolkit (that's the one I know works fine). If you have a recent GPU then it should work fine then on. In case you have an older GPU that is not supported. You could fallback to using CPU, that's fine for images but I won't recommend running long video operations using that. For that switch your provider to using CPU and also enable 'Force CPU for Face Analyser' under roop-unleashed settings.

**Comment by metal3d** [comment]
It's possible to fix this using `pip` to install cuda-python and nvidia-cuda-XXX-cuYY where XXX is the necessary libraries (cudnn, cublas...) and YY the version (12 for example).

I don't have the entire list but I already fixed bad distribution (like Ubuntu) installation using this. No problem with Fedora at this time.
