### ISSUE TITLE
GPU not working

### ISSUE THREAD

**Issue by farizy4n** [C0untFloyd/roop-unleashed#329]
Why always use CPU, in reality I choose to use GPU. it's like it's not working at all.

Specifications of the computer I use.

Ryzen 5 5600x
Nvidia RTX 4080
32GB DDR4

`Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'has_user_compute_stream': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]`

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ X] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**roop 3.3.4**

![image](https://github.com/C0untFloyd/roop-unleashed/assets/145122436/1adc64c7-7133-421a-a6b5-ca9dbf539269)

**Comment by alast0r** [comment]
you are only using 2 threads

**Comment by lysxelapsed** [comment]
that is strange. did you check if it indeed saved it to the config.yaml? if it even tried cuda without success, there would be an error message and a "fallback to cpu execution provider" or something like that.
I'd try an re-install if you can't make sense of it.

**Comment by farizy4n** [comment]
After several experiments, I found the main problem was because the core was set to 2. I use a computer with Ryzen 5 + RTX 4080 16Gb VRAM, the optimal setting should be to use 6 cores. This seems to refer to the physical core of the CPU. Just an assumption.

**Comment by lysxelapsed** [comment]
I'm running roop-unleashed with cuda 12.2, no problems.

- Did you have error messages when installing cuda?
- Did you have error messages when installing requirements.txt?
- Did you restart roop-unleashed after install and / or changes to the provider in the settings tab? -> needs to reload the models
- Did you check if cuda is properly integrated in PATH? Also you can install multiple cuda versions. For Checking and usage of multiple versions, see [here](https://github.com/bycloudai/SwapCudaVersionWindows)

Cuda installation throws errors when Visual Studio isn't installed properly for example.
Installing requirements threw several version dependency errors. I adjusted them one by one in requirements.txt to the versions specified in the error message, until install went without errors. This is what my adjusted requirements.txt looks in my case, working:

```
--extra-index-url https://download.pytorch.org/whl/cu118

numpy==1.24.2
gradio==3.44.2
opencv-python==4.8.0.76
onnx==1.14.1
insightface==0.7.3
psutil==5.9.5
pillow==10.0.1
torch==2.0.1+cu118; sys_platform != 'darwin'
torch==2.0.1; sys_platform == 'darwin'
torchvision==0.15.2+cu118; sys_platform != 'darwin'
torchvision==0.15.2; sys_platform == 'darwin'
onnxruntime==1.16.0; sys_platform == 'darwin' and platform_machine != 'arm64'
onnxruntime-silicon==1.13.1; sys_platform == 'darwin' and platform_machine == 'arm64'
onnxruntime-gpu==1.16.1; sys_platform != 'darwin'
protobuf==4.23.2
tqdm==4.66.1
ftfy
regex
pyvirtualcam
```

Also you can try pip uninstall onnxruntime onnxruntime-gpu, followed by pip install onnxruntime-gpu==1.16.1

In case of install sequence, this has always been my working order:
1. Visual Studio with C++
2. Cuda Toolkit and cudnn
3. roop-unleashed, adjusted until install didn't throw any error messages anymore

**Comment by lysxelapsed** [comment]
lol sorry about that. I was looking at the issue creator's post for the specs. Here's the equivalent solution for linux regarding "adding to path", actually with the exact same error message. I'd try [this](https://discuss.mxnet.apache.org/t/libcublas-so-10-cannot-open-shared-object-file-no-such-file-or-directory-mxnet/6678/2) before anything else.
