### ISSUE TITLE
Python keeps reserving VRAM after use

### ISSUE THREAD

**Issue by Niiickel** [C0untFloyd/roop-unleashed#332]
My python keeps using/reserving VRAM after rendering 1 video faceswap.
So I always have to close the console, than my VRAM goes to 0 and than I can start roop again and do another video.
Otherwise I get very slow speed because it doesn't use all VRAM cause 5GB or so are still in use with zero graphic card activity.

![2023-11-05 21_33_27-](https://github.com/C0untFloyd/roop-unleashed/assets/20993578/5d8d8f19-8588-488d-9cb2-e7dc4585d625)

**Comment by Oil3** [comment]
Can you update your video drivers?
Is there a way you can make it crash o we have a log? like running other videos until it goes "out of memory"?

**Comment by Niiickel** [comment]
> Can you update your video drivers? Is there a way you can make it crash o we have a log? like running other videos until it goes "out of memory"?

Drivers are already up to date.
How do I enable logs in Python & where do I find them?
