### ISSUE TITLE
Suggestion/requested feature

### ISSUE THREAD

**Issue by MantisTree** [C0untFloyd/roop-unleashed#335]
Love the project, just a small ask:  Can we have the option to add the name of the facefile to the video output filename? I looked in `template_parser.py` and it doesn't seem like that's an option at this time.

Also, is there a way to sponsor this project?

Thanks,
Brak

**Comment by phineas-pta** [comment]
#87

**Comment by MantisTree** [comment]
> #87

Hey friend, didn't see anything in that thread about filenames. Are you saying I should add this suggestion to that thread?
