### ISSUE TITLE
bug：AttributeError: 'NoneType' object has no attribute 'reshape'

### ISSUE THREAD

**Issue by BRUCEji1** [C0untFloyd/roop-unleashed#337]
**Describe the bug**

**To Reproduce**
1. Go to 'roop-unleashed\installer'
2. Click on 'windows_run.bat'
3. See error

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [√ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [√ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
roop unleashed 3.3.4
**Screenshots**
I was used it normally a few weeks ago. But recently it face an isssue. Here is the log：
Launching App
Using provider ['CUDAExecutionProvider'] - Device:cuda
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'has_user_compute_stream': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\Bruce/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'has_user_compute_stream': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\Bruce/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'has_user_compute_stream': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\Bruce/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
set det-size: (640, 640)
Sorting videos/images
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'has_user_compute_stream': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Creating 한솜비 babysoomii 08-06-22__temp.mp4 with 30.0 FPS...
['ffmpeg', '-hide_banner', '-hwaccel', 'auto', '-y', '-loglevel', 'error', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '1920x1080', '-pix_fmt', 'bgr24', '-r', '30.0', '-an', '-i', '-', '-vcodec', 'libx264', '-crf', '14', '-vf', 'colorspace=bt709:iall=bt601-6-625:fast=1', '-pix_fmt', 'yuv420p', 'E:\\roop-unleashed\\installer\\roop-unleashed\\output\\한솜비 babysoomii 08-06-22__temp.mp4']
Processing:   0%|                                                                        | 0/33329 [00:00<?, ?frames/s]
Traceback (most recent call last):
  File "E:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "E:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "E:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1123, in call_function
    prediction = await utils.async_iteration(iterator)
  File "E:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\utils.py", line 503, in async_iteration
    return await iterator.__anext__()
  File "E:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\utils.py", line 496, in __anext__
    return await anyio.to_thread.run_sync(
  File "E:\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\utils.py", line 479, in run_sync_iterator_async
    return next(iterator)
  File "E:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\utils.py", line 629, in gen_wrapper
    yield from f(*args, **kwargs)
  File "E:\roop-unleashed\installer\roop-unleashed\ui\tabs\faceswap_tab.py", line 503, in start_swap
    batch_process(list_files_process, use_clip, clip_text, processing_method == "In-Memory processing", progress)
  File "E:\roop-unleashed\installer\roop-unleashed\roop\core.py", line 302, in batch_process
    process_mgr.run_batch_inmem(v.filename, v.finalname, v.startframe, v.endframe, fps,roop.globals.execution_threads, skip_audio)
  File "E:\roop-unleashed\installer\roop-unleashed\roop\ProcessMgr.py", line 226, in run_batch_inmem
    future.result()
  File "E:\roop-unleashed\installer\installer_files\env\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "E:\roop-unleashed\installer\installer_files\env\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "E:\roop-unleashed\installer\installer_files\env\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\roop-unleashed\installer\roop-unleashed\roop\ProcessMgr.py", line 168, in process_videoframes
    resimg = self.process_frame(frame)
  File "E:\roop-unleashed\installer\roop-unleashed\roop\ProcessMgr.py", line 270, in process_frame
    num_swapped, temp_frame = self.swap_faces(frame, temp_frame)
  File "E:\roop-unleashed\installer\roop-unleashed\roop\ProcessMgr.py", line 296, in swap_faces
    temp_frame = self.process_face(self.options.selected_index, face, temp_frame)
  File "E:\roop-unleashed\installer\roop-unleashed\roop\ProcessMgr.py", line 341, in process_face
    fake_frame = p.Run(inputface, target_face, frame)
  File "E:\roop-unleashed\installer\roop-unleashed\roop\processors\FaceSwapInsightFace.py", line 27, in Run
    img_fake, M = self.model_swap_insightface.get(temp_frame, target_face, source_face, paste_back=False)
  File "E:\roop-unleashed\installer\installer_files\env\lib\site-packages\insightface\model_zoo\inswapper.py", line 50, in get
    latent = source_face.normed_embedding.reshape((1,-1))
AttributeError: 'NoneType' object has no attribute 'reshape'

plz help me with this!!! Thank you

**Comment by lysxelapsed** [comment]
could be a lot of things. do you have any unicode characters (ä ö ü for example) in your file or folder name, or a very long folder path? try placing your image and video in "E:\test", file names without unicode characters, and see if the error still occurs. if so, I'd try a clean re-install of roop-unleashed.

**Comment by BRUCEji1** [comment]
> could be a lot of things. do you have any unicode characters (ä ö ü for example) in your file or folder name, or a very long folder path? try placing your image and video in "E:\test", file names without unicode characters, and see if the error still occurs. if so, I'd try a clean re-install of roop-unleashed.

I tried, but it remains the same. I think the inswapper model caused it. But I can't find a way to fix it. I also try to reinstall the  roop-unleashed but almost everytime stuck in the insightface install. I delete some temp from the /temp, maybe  I accidentally delete some improtant things...

**Comment by lysxelapsed** [comment]
can you post your cmd output from the installation, where it's "stuck in the insightface install"? I had some issues too when installing, related to component version dependecies not being satisfied. This can be easily fixed by adjusting to the needed component versions (shown in the error message when installing) in "requirements.txt".
Also you shouldn't delete anything after install. I'm not using the windows_run.bat installer for a while now. But back then, I also thought I could delete the temp or installer files folder. I was wrong, at least some of the files are needed.

**Comment by BRUCEji1** [comment]
> can you post your cmd output from the installation, where it's "stuck in the insightface install"? I had some issues too when installing, related to component version dependecies not being satisfied. This can be easily fixed by adjusting to the needed component versions (shown in the error message when installing) in "requirements.txt". Also you shouldn't delete anything after install. I'm not using the windows_run.bat installer for a while now. But back then, I also thought I could delete the temp or installer files folder. I was wrong, at least some of the files are needed.

I didn't realize the temp can be deleted in settings. It takes up too much space on my disk so I need to find a way to delete it. After I deleted it, it shows the bug I mentioned before, I can sure that all the environment is OK. About the "stuck in the insightface install", it shows 
      creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
      copying insightface\thirdparty\face3d\mesh\cython\mesh_core.cpp -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
      copying insightface\thirdparty\face3d\mesh\cython\mesh_core.h -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
      copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.cpp -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
      creating build\lib.win-amd64-cpython-310\insightface\data\images
      copying insightface\data\images\Tom_Hanks_54745.png -> build\lib.win-amd64-cpython-310\insightface\data\images
      copying insightface\data\images\mask_black.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
      copying insightface\data\images\mask_blue.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
      copying insightface\data\images\mask_green.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
      copying insightface\data\images\mask_white.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
      copying insightface\data\images\t1.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
      creating build\lib.win-amd64-cpython-310\insightface\data\objects
      copying insightface\data\objects\meanshape_68.pkl -> build\lib.win-amd64-cpython-310\insightface\data\objects
      copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.c -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
      copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.pyx -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
      copying insightface\thirdparty\face3d\mesh\cython\setup.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
      running build_ext
      building 'insightface.thirdparty.face3d.mesh.cython.mesh_core_cython' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for insightface
Failed to build insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects

**Comment by lysxelapsed** [comment]
It even says, what the problem is:
> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
You need to install visual studio with the C++ package (build tools might not be enough) and everything else mentioned in the [Wiki](https://github.com/C0untFloyd/roop-unleashed/wiki/Installation) first. Then run the roop-unleashed installer again and don't delete anything afterwards, except for the temp folder after processing.
You can get visual studio (download the community version) [here](https://visualstudio.microsoft.com/de/downloads/)

But if you're have disk space issues, you'll have them even more now. Visual Studio takes another couple GB's of disk space. Free some space elsewhere or install on a bigger hard drive.

**Comment by lysxelapsed** [comment]
Then I'm out of ideas to solve it, I'm sorry 🤷‍♂️ 
But the error message upon install def. points to an issue with visual studio being either not installed or recognized properly by the roop-unleashed installer for some reason.

**Comment by BRUCEji1** [comment]
> Then I'm out of ideas to solve it, I'm sorry 🤷‍♂️ But the error message upon install def. points to an issue with visual studio being either not installed or recognized properly by the roop-unleashed installer for some reason.

Anyways, thx for ur help.
