### ISSUE TITLE
Torch not found

### ISSUE THREAD

**Issue by jriker1** [C0untFloyd/roop-unleashed#341]
Windows 11, just downloaded the 3.2.0 zip and ran the windows run batch file.  Downloaded a bunch of stuff but errored out on the Wheel module.  When i try and run the bat file again I get:

Check for Updates? [y/n]n
Launching App
Traceback (most recent call last):
  File "C:\temp\roop-unleashed-3.2.0\installer\roop-unleashed\run.py", line 3, in <module>
    from roop import core
  File "C:\temp\roop-unleashed-3.2.0\installer\roop-unleashed\roop\core.py", line 14, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

If I try running the update I get:

HEAD is now at e669f04 Permission change for facesets Tweaked readme and wiki
Already up to date.
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Ignoring torch: markers 'sys_platform == "darwin"' don't match your environment
Ignoring torchvision: markers 'sys_platform == "darwin"' don't match your environment
Ignoring onnxruntime: markers 'sys_platform == "darwin" and platform_machine != "arm64"' don't match your environment
Ignoring onnxruntime-silicon: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Collecting numpy==1.24.2 (from -r requirements.txt (line 3))
  Using cached numpy-1.24.2-cp310-cp310-win_amd64.whl (14.8 MB)
Collecting gradio==3.44.2 (from -r requirements.txt (line 4))
  Using cached gradio-3.44.2-py3-none-any.whl.metadata (17 kB)
Collecting opencv-python==4.8.0.76 (from -r requirements.txt (line 5))
  Using cached opencv_python-4.8.0.76-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting onnx==1.14.1 (from -r requirements.txt (line 6))
  Using cached onnx-1.14.1-cp310-cp310-win_amd64.whl.metadata (15 kB)
Collecting insightface==0.7.3 (from -r requirements.txt (line 7))
  Using cached insightface-0.7.3.tar.gz (439 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting psutil==5.9.5 (from -r requirements.txt (line 8))
  Using cached psutil-5.9.5-cp36-abi3-win_amd64.whl (255 kB)
Collecting pillow==10.0.1 (from -r requirements.txt (line 9))
  Using cached Pillow-10.0.1-cp310-cp310-win_amd64.whl.metadata (9.6 kB)
Collecting torch==2.0.1+cu118 (from -r requirements.txt (line 10))
  Using cached https://download.pytorch.org/whl/cu118/torch-2.0.1%2Bcu118-cp310-cp310-win_amd64.whl (2619.1 MB)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    torch==2.0.1+cu118 from https://download.pytorch.org/whl/cu118/torch-2.0.1%2Bcu118-cp310-cp310-win_amd64.whl#sha256=f58d75619bc96e4322343c030b893613701caa2d6db8017155da226c14171335 (from -r requirements.txt (line 10)):
        Expected sha256 f58d75619bc96e4322343c030b893613701caa2d6db8017155da226c14171335
             Got        e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

Launching App
Traceback (most recent call last):
  File "C:\temp\roop-unleashed-3.2.0\installer\roop-unleashed\run.py", line 3, in <module>
    from roop import core
  File "C:\temp\roop-unleashed-3.2.0\installer\roop-unleashed\roop\core.py", line 14, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

**Comment by 7duskblade7** [comment]
same here.

**Comment by lysxelapsed** [comment]
Are visual studio, cuda & cudnn properly installed?
If so: Start fresh (delete folder), unpack again, try the installer after adjusting requirements.txt (in the roop-unleashed folder) to this:

```
--extra-index-url https://download.pytorch.org/whl/cu118

numpy==1.24.2
gradio==3.44.2
opencv-python==4.8.0.76
onnx==1.14.1
insightface==0.7.3
psutil==5.9.5
pillow==10.0.1
torch==2.0.1+cu118; sys_platform != 'darwin' --no-cache-dir
torch==2.0.1; sys_platform == 'darwin'
torchvision==0.15.2+cu118; sys_platform != 'darwin'
torchvision==0.15.2; sys_platform == 'darwin'
onnxruntime==1.16.0; sys_platform == 'darwin' and platform_machine != 'arm64'
onnxruntime-silicon==1.13.1; sys_platform == 'darwin' and platform_machine == 'arm64'
onnxruntime-gpu==1.16.1; sys_platform != 'darwin'
protobuf==4.23.2
tqdm==4.66.1
ftfy
regex
pyvirtualcam
```

Post the cmd output from installation, where it's "errored out on the Wheel module" here.
