### ISSUE TITLE
Broken thumbnails

### ISSUE THREAD

**Issue by gilraftiks** [C0untFloyd/roop-unleashed#342]
**Describe the bug**
No thumbnails showing in the WebUI. Is it just broken for me or everyone?

**To Reproduce**
Add a picture and it should show a thumbnail, but it shows a broken one instead.

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
Latest
**Screenshots**
![firefox_kcX8TXrjTS](https://github.com/C0untFloyd/roop-unleashed/assets/141192215/c8d3e7f9-4489-4127-856b-2e9d3cbffa48)

**Comment by Oil3** [comment]
Can you open your browser developer tools and tell us what error message u see? ("view" then developer tool, o
If you right click on the broken thumb and do "open image in new tab" (or similar), does the image load?
