### ISSUE TITLE
Error splitting the into NAL units, invalid NAL unit Size

### ISSUE THREAD

**Issue by meta4ric** [C0untFloyd/roop-unleashed#343]
**Describe the bug**
Error splitting the into NAL units, invalid NAL unit Size
![Screenshot 2023-11-16 182258](https://github.com/C0untFloyd/roop-unleashed/assets/37631252/796dd061-e91d-4856-b019-0a41b22ccd36)

**To Reproduce**
1. After Clicking the START Button

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
3.3.4
**Screenshots**
![Screenshot 2023-11-16 182258](https://github.com/C0untFloyd/roop-unleashed/assets/37631252/796dd061-e91d-4856-b019-0a41b22ccd36)

**Comment by lysxelapsed** [comment]
with every file? if yes, try reinstalling / replacing the  ffmpeg / ffprobe exe's being used. if not, try re-encoding the file.
