### ISSUE TITLE
Conda not installed

### ISSUE THREAD

**Issue by SwappyMcSwapperson** [C0untFloyd/roop-unleashed#346]
**Describe the bug**
I run the installer in cmd, it goes like i'd expect, once it finishes and tries to launch roop unleashed it says "Conda is not installed... Exiting" repeatedly. I'm attempting to run it on windows 11 and I've checked if conda is in the folder tree and it clearly took the time to download miniconda, and i'm not great at this stuff admittedly but i'm not bad at troubleshooting cmd stuff either, i've gotten deepface labs and faceswap to run fine in the past. However this conda issue has me boggled. I've reinstalled anaconda, miniconda, and double checked the paths and even tried several different paths to assign for conda. Nothing has worked. I have installed visual studio too. Nothing I do seems to get it to launch, in opening a instance of conda and trying to use it to run the installer a second time to run the program it still says conda is not installed. I've managed in using specifically an anaconda prompt and deactivating conda I've managed to get it to not return the error "conda is not installed" but instead of that it just stalls out on "Launching roop-unleashed" and then nothing opens, no gui, no window of visual studio, no browser window, notta, and it doesn't allow any more input in the command line because if i try to enter something new then it does give the not installed and exits. 

**To Reproduce**
1. unzip - extract to fresh folder
2. run the windows_run.bat
3. wait for downloads, all succeed even miniconda
4. cmd attempts to launch (or if not CMD, miniconda, or anaconda3) and then inevitable "conda is not installed exiting"

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?** most recent as of 11/18/2023 10pm eastern

**Screenshots**
There is no additional info given and i can get conda to run on it's own and successfully activate but the .bat file refuses to acknowledge it no matter what i've tried.

**possible suggestion**
try putting the file that causes the program to run seperate like a "run.bat" file instead of being part of the installer and maybe that could help determine if it's within the installing portion or the running portion that the check for conda is failing so bad? I've tried ensuring even that the conda.exe is in the same file as the windows_run.bat to see if it would alleviate path issues trying to find it as well as changing the paths in control panel. No luck.

Side note:
I did notice one of the files it installs is a _conda.exe file if the _ is causing the pathing to wonk out because it's looking for conda and not _conda maybe that's the issue???

Unsure as I'm not a programmer. Appreciate your work tho btw. TIA for the help.

**Comment by lysxelapsed** [comment]
Hard to say, why it's not recognizing conda. But it _could_ be related to the installer not having the proper rights to add something to your environment variables or similar. It's _not_ related to "underline thing" (but I've always thought it's weird, too)

First and foremost, watch the installer and make sure that it didn't throw any major errors, before doing anything else.

Besides that, here's how I would approach this:
1. Run the installer as administrator. Didn't help? Proceed with 2.
2. Locate / search for your _conda.exe and python.exe files, add the folder paths to "PATH" in your [environment variables](https://www.alphr.com/set-environment-variables-windows-11/) (scroll down to "Changing Environment Variables". Still the same? Have a look at 3.
3. If you're not bad at troubleshooting cmd stuff, you should be able to install it manually (I was never a fan of anaconda / miniconda tbh). You'll find simple instructions in my first post here: #210 | You only need the first part (basic installation), second part is for reverting to a specific commit. Substitute code for windows_run.bat (to run with one click after installation) is at the end of the post.

Alternatively, you can try to open the anaconda prompt manually after install, head to your roop-unleashed/scripts folder, activate the environment with either "activate" or "conda activate" (not sure anymore, haven't used the anaconda approach in a while now), head back to the roop-unleashed folder and run in with "run.py" or "python run.py" (again, not sure which one 😆)
