### ISSUE TITLE
Torch-only roop fork

### ISSUE THREAD

**Issue by Nikita-Sherstnev** [C0untFloyd/roop-unleashed#347]
Hi everyone! I created a fork of this project, with two main differences: removed onnx-runtime dependency, which did not support cuda 12, and removed some other dependencies by moving neural nets implementations to my project. Also I added tests, which will greatly facilitate addition of new features and not breaking old ones. Maybe this version will work if you have some troubles with Win 11. All requirements can be installed with pip:
https://github.com/Nikita-Sherstnev/roop-unchained/tree/torch

Also there is WIP version with kornia, which potentially speeds up swapping process by 2x as it avoids unnecessary loading memory from GPU to CPU and vise-versa. But it's buggy for now.
https://github.com/Nikita-Sherstnev/roop-unchained/tree/cuda_pipeline

**Comment by phineas-pta** [comment]
opencv should have cuda supported (although roop not using it), is kornia faster ?

**Comment by Nikita-Sherstnev** [comment]
@phineas-pta with CUDA indeed, kornia faster, have't checked with CPU. Didn't know that opencv have cuda support, seems like its not trivial to install and use. Also I am not sure that it supports torch tensor format, which means it would require double conversion anyway. Also kornia has user-friendly docs.

**Comment by phineas-pta** [comment]
in that case why not go further: replace `numpy` with `torch` so all tensors stay on gpu (not sure if it's worth)

**Comment by instant-high** [comment]
@Nikita-Sherstnev 
Hi, I've installed your torch only version but when trying to open any source image the following error occurs:

File "c:\Tutorial\roopTorch\roop\processors\frame\transform.py", line 67, in estimate_affine_matrix_3d23d
X_homo = np.hstack((X, np.ones([X.shape[0],1]))) #n x 4
AttributeError: 'NoneType' object has no attribute 'shape'

Opening target video seems to be working.

Can you give a little help please?

PS: kornia missing in requirements.txt

**Comment by instant-high** [comment]
@Nikita-Sherstnev thanks so far.
I'll try tomorrow

**Comment by instant-high** [comment]
@Nikita-Sherstnev
Oh, have not realized that. I will take a look.
I get another error in inswapper.py
model.state.dict(emap) .....????
and
process not found - maybe ffmpeg?

Regards

**Comment by instant-high** [comment]
@Nikita-Sherstnev 
sorry to bother you.

Re-downloaded inswapper_128.pt but error is still there

File "c:\Tutorial\roopTorch\roop\models\inswapper.py", line 17, in __init__
    self.emap = self.model.state_dict()['emap']
KeyError: 'emap'

ffmpeg solved, wrong system variable from previous installation I think.

**Comment by Nikita-Sherstnev** [comment]
@instant-high What version of torch are you using? I remember having similar issue on older torch versions. I use 2.1.1.

**Comment by instant-high** [comment]
@Nikita-Sherstnev 
It's working now after upgrading torch ... 

(pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117 did not work, installed torch 2.0.1)

As I mentioned before I installed manually on win11 as follows:

conda create -n cuda python==3.10
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
pip install -r requirements.txt (removed torch and torchvision before that)

That's all except for I also had to
pip install kornia
maybe it's not used but is importing it in some script..?
Or I have mixed up with your other version.

Thank you very much Sir

Regards Thomas

**Comment by instant-high** [comment]
At last a short inference time comparison between inswapper onnx running on CPU and the torch version running on GPU

torch version 0:28 min.
onnx version 1:10 min.

short clip of 75 frames, only swap no enhancement

**Comment by instant-high** [comment]
@Nikita-Sherstnev 
Looks like I mixed up something.... so I re-downloaded both

Correct inference time comparison:
original onnx version 1:10 min.
torch version 0:28 min.
cuda pipeline 0:07 min.

short clip of 75 frames, only swap no enhancement

**Comment by Oil3** [comment]
@Nikita-Sherstnev 3 weeks ago I told you 'when i try ur version I tell '".
Ok i did try but I didnt tell you because it took me a long time to make it run on mac, and then it was very slow so I deleted everything out of frustration.
Recently, I figured that it was because it was running on CPU only and thus I wasn't comparing the right thing, and being quite frustrated with onnxruntime, despite finally having ANE, and then GPU roar (meow is more accurate tho), I thought I should give torch (and tensorf) more attention.
So here I am trying again, tweaking code for mac.
You still on this project?

**Comment by Nikita-Sherstnev** [comment]
@Oil3 Not in the moment, but feel free to ask any questions. I might as well help with bugs.

**Comment by Oil3** [comment]
@Nikita-Sherstnev I bailed once more.
Do you happen to have a version that is not requiring Cuda in most places?
If not, i'll eventually get the motivtion to change everything, I had done it once.
The process is basically running the app, getting an error, about Cuda, fixing it, getting another error, . It's not a problem, I understand, but if you do hapen to have what I mentionned, that would make it smoother, if not, ill do it manually

**Comment by CoreyCorza** [comment]
@Nikita-Sherstnev What can I do to get the installer working for your roop unchained?

![image](https://github.com/C0untFloyd/roop-unleashed/assets/40785775/4ddd6292-15d2-4f0b-9203-9afca3b5911f)
