### ISSUE TITLE
Unable to start gui

### ISSUE THREAD

**Issue by reznofiat** [C0untFloyd/roop-unleashed#35]
After using the 1 click installer, this is what happens when I try to run the windows_run.bat file 
![rooperror](https://github.com/C0untFloyd/roop-unleashed/assets/136768848/6c4a8255-110b-485e-811b-33b0fa652748)

And nothing happens after that.

I'm very inexperienced with coding and this type of knowledge so I apologize if this issue is a very obvious or easy fix. 

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [O ] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [O ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Sanity Check**
- [O] I have the latest code from the github repository
- [O] I have followed the installation guide

**Comment by C0untFloyd** [comment]
It seems your install is corrupt/broken, try to update by using 'y'
