### ISSUE TITLE
Add restoreformer upscaler

### ISSUE THREAD

**Issue by dnnagy** [C0untFloyd/roop-unleashed#350]
A similar project, called [Swap-Mukham2](https://github.com/nyntany/Swap-Mukham2/tree/main) includes [Restorefomer](https://github.com/nyntany/Swap-Mukham2/blob/main/upscaler/restoreformer.py) for face upscaling. Can you please add this as a possible upscaler, it seems like restoreformer beats GFPGAN and Codeformer in quality.

**Comment by dnnagy** [comment]
@C0untFloyd Added Restoreformer upscaler, since I couldn't create a pull request, created a fork and added into that. [https://github.com/dnnagy/roop-unleashed](https://github.com/dnnagy/roop-unleashed)(https://github.com/dnnagy/roop-unleashed)

Unfortunately, Restoreformer has the same flickering issue as described in #331

**Comment by Oil3** [comment]
I think it's from somewhere here in ProcessMgr.py`

# Paste back adapted from here
    # https://github.com/fAIseh00d/refacer/blob/main/refacer.py
    # which is revised insightface paste back code

    def paste_upscale(self, fake_face, upsk_face, M, target_img, scale_factor, mask_offsets):
        M_scale = M * scale_factor
        IM = cv2.invertAffineTransform(M_scale)

        face_matte = np.full((target_img.shape[0],target_img.shape[1]), 255, dtype=np.uint8)
        ##Generate white square sized as a upsk_face
        img_matte = np.full((upsk_face.shape[0],upsk_face.shape[1]), 255, dtype=np.uint8)
        if mask_offsets[0] > 0:
            img_matte[:mask_offsets[0],:] = 0
        if mask_offsets[1] > 0:
            img_matte[-mask_offsets[1]:,:] = 0

        ##Transform white square back to target_img
        img_matte = cv2.warpAffine(img_matte, IM, (target_img.shape[1], target_img.shape[0]), flags=cv2.INTER_NEAREST, borderValue=0.0) 
        ##Blacken the edges of face_matte by 1 pixels (so the mask in not expanded on the image edges)
        img_matte[:1,:] = img_matte[-1:,:] = img_matte[:,:1] = img_matte[:,-1:] = 0

        #Detect the affine transformed white area
        mask_h_inds, mask_w_inds = np.where(img_matte==255) 
        #Calculate the size (and diagonal size) of transformed white area width and height boundaries
        mask_h = np.max(mask_h_inds) - np.min(mask_h_inds) 
        mask_w = np.max(mask_w_inds) - np.min(mask_w_inds)
        mask_size = int(np.sqrt(mask_h*mask_w))
        #Calculate the kernel size for eroding img_matte by kernel (insightface empirical guess for best size was max(mask_size//10,10))
        # k = max(mask_size//12, 8)
        k = max(mask_size//10, 10)
        kernel = np.ones((k,k),np.uint8)
        img_matte = cv2.erode(img_matte,kernel,iterations = 1)
        #Calculate the kernel size for blurring img_matte by blur_size (insightface empirical guess for best size was max(mask_size//20, 5))
        # k = max(mask_size//24, 4) 
        k = max(mask_size//20, 5) 
        kernel_size = (k, k)
        blur_size = tuple(2*i+1 for i in kernel_size)
        img_matte = cv2.GaussianBlur(img_matte, blur_size, 0)
        
        #Normalize images to float values and reshape
        img_matte = img_matte.astype(np.float32)/255
        face_matte = face_matte.astype(np.float32)/255
        img_matte = np.minimum(face_matte, img_matte)
        img_matte = np.reshape(img_matte, [img_matte.shape[0],img_matte.shape[1],1]) 
        ##Transform upcaled face back to target_img
        paste_face = cv2.warpAffine(upsk_face, IM, (target_img.shape[1], target_img.shape[0]), borderMode=cv2.BORDER_REPLICATE)
        if upsk_face is not fake_face:
            fake_face = cv2.warpAffine(fake_face, IM, (target_img.shape[1], target_img.shape[0]), borderMode=cv2.BORDER_REPLICATE)
            paste_face = cv2.addWeighted(paste_face, self.options.blend_ratio, fake_face, 1.0 - self.options.blend_ratio, 0)

        ##Re-assemble image
        paste_face = img_matte * paste_face
        paste_face = paste_face + (1-img_matte) * target_img.astype(np.float32)
        del img_matte
        del face_matte
        del upsk_face
        del fake_face
        return paste_face.astype(np.uint8)`

**Comment by Oil3** [comment]
I did some tests, I think it comes from the not-enhanced face. 
_Squares without blending  (blend ratio of 1) is nearly invisible_ had to increase contrasts to distinguish it
Tests with a white background, and blend ratios of: -1, 0, 0.65, 1 and 2. Black background same
![image](https://github.com/C0untFloyd/roop-unleashed/assets/22565084/db991ca4-f0f8-44d5-b782-fb1c4839dbee)

**Comment by Oil3** [comment]
w00t: Enhance_Codeformer.py at the very beginning, insert at line 18: name = None
In your enhance_reformer.py, i noticed it was also missing, have a try 

> class Enhance_CodeFormer():
    model_codeformer = None
    **_name = None_**
    devicename = None

**Comment by Nikita-Sherstnev** [comment]
@Oil3 I added this line, it did not help, I still have flickering on restoreformer. Tried on my torch fork.

<details>
  <summary>Example</summary>

![wonder-woman_23-05-37](https://github.com/C0untFloyd/roop-unleashed/assets/45091811/ebcb4908-5009-47fe-8081-af26719b0bf4)

</details>

**Comment by Oil3** [comment]
Remove the cache files inside the __pycache__ / folder,  if you didn't and try again pls

**Comment by Nikita-Sherstnev** [comment]
@Oil3 I removed the cache files, but the problem with restoreformer remains.

**Comment by Oil3** [comment]
@Nikita-Sherstnev 
Interesting. And with codeformer? 
Using low quntity of threads, right?
THe issue is present 100% of the time or just sometimes?
What happens if you put the blend ratio to 1 and to 0? With 1 isn't it mostly gone?
I'm gonna try restoreformer*
ps: on what device u running all this?

**Comment by Nikita-Sherstnev** [comment]
@Oil3 
I'm using GeForce GTX 1660 Ti. Only two threads, no issues with codeformer. I tried couple of gifs and they have the same problem with restoreformer. Blend ratio set to 0 gives non-enhanced face, and set to 1 makes the issue little bit more visible.

**Comment by Oil3** [comment]
@Nikita-Sherstnev so the blend ratio 0 gives u non enhanced face without issue, and ratio 1 gives  u more issue? 
Thats the opposit of what happened to me.
Sanity: you deleted the restore former cache file, not just the codeformer, right? and u added the line to the restoreformer file? Dont spurt my uestions, better safe than sorry: i have now 0 issues with codeformer which became the fastest enhancer for me now and I'm convinced it's 1 little line of code that messes it up. 
When I try torch version, i'll let you know. I'm myself interested in a coreml version lol

**Comment by Nikita-Sherstnev** [comment]
@Oil3 yes, sure, I added this line to restoreformer. Looks like I just have different problem.

**Comment by Oil3** [comment]
We'll find a way, the issue is the same, it must have the same cause. If you fixed it on codeformer (or didn't have it), then need to find where is the "difference".
I succeeded in making restore former work, after 2 hours of going crazy.: 
The error was  due to a "Module roop.processors.Enhance_Restoreformer does not exist" 
Eventually I checked faceswap_tab.py ... I had "RestoreFormer" written as "Restoreformer" and the biatch is case sensitive...
