### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Disorbs** [C0untFloyd/roop-unleashed#354]
**Describe the bug**
When I hit Start it get this error. (face preview works fine)

**To Reproduce**
1. Go to 'Face Swap'
2. Click on 'Enter Details'
3. Scroll down to 'Click start'

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
3.3.4

**Things I've tried to fix it**
1. fresh install
2. create venv and install requirements
3. start to create something but i get a error still same one.

**Screenshots**
![roop](https://github.com/C0untFloyd/roop-unleashed/assets/10566466/6310d72e-d19c-4b7b-a56b-259b115715dd)

**Error**
`Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Sorting videos/images
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'has_user_compute_stream': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Creating Eddie Brock Becomes Venom Scene - Spider-Man 3 2007 Movie CLIP HD__temp.mp4 with 25.0 FPS...
Extracting frames...
ffmpeg -hide_banner -hwaccel auto -y -loglevel error -i N:\AI\AI-DF\roop-unleashed\temp\2aa7c7f1d32a451eb511c1ca18656fab7ebe6900\Eddie Brock Becomes Venom Scene - Spider-Man 3 2007 Movie CLIP HD.mp4 -q:v 1 -pix_fmt rgb24 -vf trim=start_frame=0:end_frame=5410,fps=25.0 -vsync 0 N:\AI\AI-DF\roop-unleashed\temp\2aa7c7f1d32a451eb511c1ca18656fab7ebe6900\temp\Eddie Brock Becomes Venom Scene - Spider-Man 3 2007 Movie CLIP HD\%04d.png
[WinError 2] The system cannot find the file specified
Processing: |                                                                                 | 0/0 [00:00<?, ?frame/s]
Traceback (most recent call last):
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\gradio\blocks.py", line 1123, in call_function
    prediction = await utils.async_iteration(iterator)
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\gradio\utils.py", line 503, in async_iteration
    return await iterator.__anext__()
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\gradio\utils.py", line 496, in __anext__
    return await anyio.to_thread.run_sync(
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\gradio\utils.py", line 479, in run_sync_iterator_async
    return next(iterator)
  File "c:\users\maria\appdata\local\programs\python\python310\lib\site-packages\gradio\utils.py", line 629, in gen_wrapper
    yield from f(*args, **kwargs)
  File "N:\AI\AI-DF\roop-unleashed\ui\tabs\faceswap_tab.py", line 503, in start_swap
    batch_process(list_files_process, use_clip, clip_text, processing_method == "In-Memory processing", progress)
  File "N:\AI\AI-DF\roop-unleashed\roop\core.py", line 288, in batch_process
    extract_path = os.path.dirname(temp_frame_paths[0])
IndexError: list index out of range`

**Comment by lysxelapsed** [comment]
My guess would be: You're using In-Memory processing, while having the "Keep Frames" option checked.
Either use In-Memory processing _without_ the keep frames option, or (if keeping the frames is a must for whatever reason) "Extract frames to media" _with_ "Keep Frames" checked.

**Comment by Disorbs** [comment]
fixed its not using my ffmpeg from my path for some reason i added it to the root folder and its working now.

**Comment by Disorbs** [comment]
question now that its working is this using my gpu or cpu? it seems to take like 20+minutes on ones that would only take 1-3min using the old roop with cli.

`Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'has_user_compute_stream': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Sorting videos/images
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'has_user_compute_stream': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Creating 32k40fksm__temp.mp4 with 30.0 FPS...
Extracting frames...
ffmpeg -hide_banner -hwaccel auto -y -loglevel error -i N:\AI\AI-DF\roop-unleashed\temp\981a8e31c072dfdce6712b2472ae845d8157a7d8\32k40fksm.mp4 -q:v 1 -pix_fmt rgb24 -vf trim=start_frame=0:end_frame=254,fps=30.0 -vsync 0 N:\AI\AI-DF\roop-unleashed\temp\981a8e31c072dfdce6712b2472ae845d8157a7d8\temp\32k40fksm\%04d.png
Processing:   4%|▊                       | 9/254 [01:03<23:27,  5.75s/frame, memory_usage=02.74GB, execution_threads=3]`

**Comment by lysxelapsed** [comment]
it is using the cuda execution provider. the question is, how much of your gpu is being utilized. look at your task manager:
![Screenshot 2023-11-25 174610](https://github.com/C0untFloyd/roop-unleashed/assets/63816546/15927139-6f04-4b80-b49b-dded09adca8d)
quick question: why are you extracting the frames?

**Comment by Disorbs** [comment]
its utilizing 6.1gb/8gb and idk what should i be doing instead? also why does it always open temp folder and how come without it being checked i still have to hit continue to make the video and why does it remove all videos in the output?

**Comment by Oil3** [comment]
select "extract frame", deselect "keep frame" if its checked, save, wait a few seconds, reload the page, back to settings, select "in-memory", save, wait a few seconds, restart the server, try

**Comment by lysxelapsed** [comment]
> why does it remove all videos in the output

Because that's the default setting in the settings tab. You need to uncheck it.

> its utilizing 6.1gb/8gb

That's a good value. I recommend leaving ≈20% (24% in your case) of the available VRAM unused for roop-unleashed related spikes and other apps. But how's the gpu load itself?
![Screenshot 2023-11-25 174610](https://github.com/C0untFloyd/roop-unleashed/assets/63816546/5b963da2-7e69-46be-8c5f-65919ec8c962)

**Comment by lysxelapsed** [comment]
yeah whatever... you're welcome
