### ISSUE TITLE
Feature Suggestion - ability to use codeformer without faceswap

### ISSUE THREAD

**Issue by Legendaryl123** [C0untFloyd/roop-unleashed#355]
Is there a way we could be running codeformer/dmd/gfpgan to depixel faces after the face swap so that the processing load is lower?  It would be wonderful if we could process and output file and then reload that file into the GUI and just use the post-processing option to use codeformer, etc. to upscale the face after the fact (without performing a face swap, since it's already done.)  I currently do that inside "roop portable" but that gui requires me to save images to hard drive in order to use post-processing.  Your gui allows for in-memory processing which reduces ssd wear.

**Comment by Oil3** [comment]
Im on it, basically would be to detect a target face and run the codeformer on it rather than the swaped resulting face -i think.
We want to avoid running the enhancer on the whole pic

**Comment by C0untFloyd** [comment]
This was one of the features planned for the post-processing tab. Pretty easy to do but takes time nevertheless.
