### ISSUE TITLE
Incorrect File Permission Mode in mkdir_with_umask Function Leads to Permission Errors

### ISSUE THREAD

**Issue by julienwetzel** [C0untFloyd/roop-unleashed#356]
**Description**:
We encountered a `PermissionError` while extracting files from a ZIP archive using the `unzip` function in our Python application. The issue was traced back to the `mkdir_with_umask` function in the `roop/utilities.py` module, where the directory creation mode was incorrectly specified.

**Steps to Reproduce**:
1. Call the `mkdir_with_umask` function from `roop/utilities.py` to create a new directory.
2. Attempt to extract a ZIP file into this newly created directory using the `unzip` function in the same module.
3. Observe the `PermissionError` occurring during the extraction process.

**Expected Behavior**:
The directory should be created with the correct permissions, allowing files to be extracted from a ZIP archive without any permission issues.

**Actual Behavior**:
The `PermissionError` is thrown due to incorrect directory permissions, preventing the extraction of files from the ZIP archive.

**Root Cause**:
The `mkdir_with_umask` function incorrectly specifies the file mode as `mode=777` instead of `mode=0o777`. In Python, file modes should be specified in octal notation, and the lack of the `0o` prefix causes the mode to be interpreted as a decimal number, leading to incorrect permissions being set.

**Suggested Fix**:
Modify the file mode in the `mkdir_with_umask` function within `roop/utilities.py` from `mode=777` to `mode=0o777` to ensure the correct octal notation is used. This change will correctly set the intended directory permissions.

**Code Snippet for Correction**:
```python
def mkdir_with_umask(directory):
    oldmask = os.umask(000)
    os.makedirs(directory, mode=0o777, exist_ok=True)
    os.umask(oldmask)
```

**To Reproduce**
1. Go to 'Face Management Tabs'
2. Insert Photos in Input Files
3. Click on '.Create/Update Faceset file'
5. See error

```
  File "/home/wsl/dfk/roop-unleashed/ui/tabs/facemgr_tab.py", line 58, in on_faceset_changed
    util.unzip(filename, unzipfolder)
  File "/home/wsl/dfk/roop-unleashed/roop/utilities.py", line 263, in unzip
    zip_file.extractall(target_path)
  File "/usr/lib/python3.10/zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/usr/lib/python3.10/zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: '/home/wsl/dfk/roop-unleashed/temp/faceset/0.png'
```

**Details**
What OS are you using?
- [ ] Linux
- [X] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
[roop unleashed 3.3.4](https://github.com/C0untFloyd/roop-unleashed)

**Screenshots**

**Comment by infinitygorkem** [comment]
I produce this issue on Linux too. I get this error message at the top: "Errno 13: Permission denied" followed by the path of the temp folder.
I also confirm that changing 777 to 0o777 works.

**Comment by joshkerr** [comment]
Can confirm this fixed it for me too. I'm on a Mac.

**Comment by LatentLoser** [comment]
I wound up finding and fixing this in the course of https://github.com/C0untFloyd/roop-unleashed/pull/364
