### ISSUE TITLE
Roop-unleashed automatically opens in browser with no way to stop it

### ISSUE THREAD

**Issue by infinitygorkem** [C0untFloyd/roop-unleashed#358]
**Describe the bug**
Roop-unleashed opens in the browser automatically every time it's launched with ```python run.py```
I can see the appeal but please add an option in the settings page (or a commandline flag at the very least) to control this.

**To Reproduce**
1. Run ```python run.py```
2. Notice how it opens automatically

**Details**
What OS are you using?
- [X] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
Latest at time of writing, 3.3.4

**Comment by lysxelapsed** [comment]
Again, sorry if I misunderstand, but:

Isn't this how it's supposed to work? As far as I know, CLI arguments / CLI only aren't supported anymore. So what's the point of running "run.py" without having the web-gui opened at the same time?

**Comment by Oil3** [comment]
Edit /roop-unleashed/ui/main.py and delete the cache inside __pycache__
at line 70

>  ui.queue().launch(inbrowser=**False**

**Comment by infinitygorkem** [comment]
Thanks - I'll make that change locally. I'll close this issue but having this as a Gradio config option would be nice too. Thanks everyone.
