### ISSUE TITLE
Refreshed page keeps old video in "target files" list even though it's not shown

### ISSUE THREAD

**Issue by infinitygorkem** [C0untFloyd/roop-unleashed#359]
**Describe the bug**
When the page is refreshed, the existing set of faces _and_ the video list are empty, as expected. However, they are both still populated with the data that was there before the page was refreshed. If you upload a new image there that looks like the only image, you'll get to choose between the faces that were uploaded from before the page was refreshed. And more importantly, dragging a video onto the Target Files list works as normal, so does the preview, etc, but clicking Start first runs it with the video(s) in the target file list from before the page was refreshed, and THEN does the new video added after the page was refreshed. It looks like adding new videos or face images just appends to the existing list which isn't shown when the page is refreshed. 

**To Reproduce**
1. Upload a face picture and a video to the target list
2. Click start, wait for it to finish making the video (I don't even know if this step is necessary)
3. Refresh the page. It will look like brand new when you first launch it with ```python run.py```
4. Add a video to the target list and click Start. You'll notice it works on the video you uploaded first (ie before you refreshed) and then the 2nd video you uploaded (which is the one added after refreshing the page).

This is a problem because we're led to believe only the files in "target list" are processed - but after refreshing, it's still there in the backend but not visible on the Gradio UI. I think it should be updated when the page is refreshed, or the whole cache of faces and videos cleared when the page is refreshed. 

**Details**
What OS are you using?
- [X] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
Roop unleashed 3.3.4

**Screenshots**

**Comment by lysxelapsed** [comment]
I'm not sure if I'm getting this right, so: Sorry for the maybe dumb questions.

- Why would you want to refresh the page in the first place? What's the use-case?
- Can't you just, instead of refreshing the page, clear the source / target files with the X and add new ones? Or:
- Just close the tab / python and run it again? Takes not even 10 seconds

**Comment by Oil3** [comment]
@infinitygorkem 
> * Add any video
> * Click the X to clear the videos in the "Target list" (which I think also clears the video list in the backend)

It works, for me, for the videos, but not for the source faces, I have to do a clear cache. It's really annoying. If I restart roop, the face gets cleared, but the target pics, hidden, are still there somewhere -doing start after uploading a source would work.





@lysxelapsed 
> I'm not sure if I'm getting this right, so: Sorry for the maybe dumb questions.
> 
> * Why would you want to refresh the page in the first place? What's the use-case?
> * Can't you just, instead of refreshing the page, clear the source / target files with the X and add new ones? Or:
> * Just close the tab / python and run it again? Takes not even 10 seconds

Sometimes, the page bugs and freeze, Unleashed works good, but I need to reload.
I SSH into my stronger computer and I run bunch of tests, for exemple I(m tryin g to get the enhancers to work with coreML, I do a lot of reload, it's a pain in the ass I have to clear cache: I need to see the difference.

But the simplier reason is that it's not intended to work like that.

ps: just got the clip2seg to be MPS compliant with a _dirty_ trick

**Comment by C0untFloyd** [comment]
The reason for this is that I have no control over the frontend gui (Gradio). Most often I can only react to events happening and need to treat the GUI as a blackbox. If it was possible to clear those controls programmatically I would do it. Currently though it would only be possible by using JavaScript hacks with CSS and additional code, which I don't like 🤷‍♂️
