### ISSUE TITLE
cant get it to work

### ISSUE THREAD

**Issue by unnobody** [C0untFloyd/roop-unleashed#363]
File "C:\Users\young\Downloads\roop-unleashed-3.2.0\roop-unleashed-3.2.0\installer\installer_files\env\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 463, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=-1354976392 ; hostname=ANDREI ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=236 ; expr=cudaSetDevice(info_.device_id);

**To Reproduce**
i open web interface, add photo, add video and get this error

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [+ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [ +] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
3.2.0
**Screenshots**

**Comment by Oil3** [comment]
Go to the settings tabs, change your provider. Apply.
you need DirectML if i'm not mistaken

**Comment by unnobody** [comment]
> Go to the settings tabs, change your provider. Apply. you need DirectML if i'm not mistaken

Well, that's the problem...
I did install it as for the roop, but it just doesn't suggest it in the provider list.

**Comment by lysxelapsed** [comment]
directml is not properly installed then. aside from `pip uninstall onnxruntime onnxruntime-directml`, followed by `pip install onnxruntime-directml==1.15.1`, there are lots of threads regarding directml already. have a look at those - just search for `is:issue directml` in the issues section.

**Comment by unnobody** [comment]
> directml is not properly installed then. aside from `pip uninstall onnxruntime onnxruntime-directml`, followed by `pip install onnxruntime-directml==1.15.1`, there are lots of threads regarding directml already. have a look at those - just search for `is:issue directml` in the issues section.

Thx

**Comment by aiko929** [comment]
Where did you executed this commands? anywhere in the miniconda env?
