### ISSUE TITLE
Google Colab keep getting disconnected

### ISSUE THREAD

**Issue by suniljlandge** [C0untFloyd/roop-unleashed#365]
From last few days Google Colab keep getting disconnected and ask to buy credit(colab pro)... before that it works perfectly fine on free tier.
is there any way to bypass the colab pro or any alternative service  where roop-unleashed works fine on free tier...

**Comment by ziggyputtar** [comment]
you have to buy or just use paperspace

**Comment by ziggyputtar** [comment]
> is it possible use it on sagemaker studio?

i think it is possible in kaggle, but i am not good at coding and stuff, i dont know how to import a colab file in kaggle and make it work

**Comment by ajSh-dot** [comment]
Can Anyone  Guide on installation of Roop-Umleashed on  Paperspace , Sagemaker studio lab or Kaggle,   as Google colab free tier is getting constantly disconnected  on processing just 4-5 frame out of 300 frames,  Thanks in Advance though

**Comment by ziggyputtar** [comment]
> Can Anyone Guide on installation of Roop-Umleashed on Paperspace , Sagemaker studio lab or Kaggle, as Google colab free tier is getting constantly disconnected on processing just 4-5 frame out of 300 frames, Thanks in Advance though

i am using roop unleashed on paperspace for a month, it is only 8 usd per month,

there is no limit in generation or rendering like google colab,

we get GPUs like a4000, rtx5000, rtx 4000, p5000

in a4000(which is best) i get almost 10frames per second in generation....

it is super easy to use, just import the google colab notebook (ipynb) in paperspace then follow the same steps which you follow in google collab...............its no rocket science
![Screenshot (15)](https://github.com/C0untFloyd/roop-unleashed/assets/153287646/4ad42426-1475-4092-8fb3-94541eabfb36)
![Screenshot (16)](https://github.com/C0untFloyd/roop-unleashed/assets/153287646/a8a8fa44-43ce-49f1-9924-7df99d004c94)

**Comment by suniljlandge** [comment]
> > Can Anyone Guide on installation of Roop-Umleashed on Paperspace , Sagemaker studio lab or Kaggle, as Google colab free tier is getting constantly disconnected on processing just 4-5 frame out of 300 frames, Thanks in Advance though
> 
> i am using roop unleashed on paperspace for a month, it is only 8 usd per month,
> 
> there is no limit in generation or rendering like google colab,
> 
> we get GPUs like a4000, rtx5000, rtx 4000, p5000
> 
> in a4000(which is best) i get almost 10frames per second in generation....
> 
> it is super easy to use, just import the google colab notebook (ipynb) in paperspace then follow the same steps which you follow in google collab...............its no rocket science ![Screenshot (15)](https://private-user-images.githubusercontent.com/153287646/290918437-4ad42426-1475-4092-8fb3-94541eabfb36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MDM5NDcsIm5iZiI6MTcwMjgwMzY0NywicGF0aCI6Ii8xNTMyODc2NDYvMjkwOTE4NDM3LTRhZDQyNDI2LTE0NzUtNDA5Mi04ZmIzLTk0NTQxZWFiZmIzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxN1QwOTAwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iM2IzYmM3MjM5N2IyMTBkYmE5YmU3MzhjODhiYzY0YWI3ODMyNWJhOTYwNjFiZDA3ZjM5OGIzMGVmZTNlNzUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.e6hUjgDiP7eUylMnSwLnJWzQv893t4nwV4auUGMDe8c) ![Screenshot (16)](https://private-user-images.githubusercontent.com/153287646/290918443-a8a8fa44-43ce-49f1-9924-7df99d004c94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MDM5NDcsIm5iZiI6MTcwMjgwMzY0NywicGF0aCI6Ii8xNTMyODc2NDYvMjkwOTE4NDQzLWE4YThmYTQ0LTQzY2UtNDlmMS05OTI0LTdkZjk5ZDAwNGM5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxN1QwOTAwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODkxOGVjOGUwMGQ4ODMyYmM5MDA3NDBlYTE5OTkzZTU3MDRiODFiY2MzYmU4OTc0ZmEyYjdjZDI3ODI4Yjc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-o7oKnDnK60F1cxaXJ0abjMwxIGDmOfwFpJsDfMl5R4)

it says and wont generate public url
To create a public link, set `share=True` in `launch()`.

**Comment by 592429d** [comment]
I tried to run livecam on Google Colab (I have Colab pro) but it really slow (the output live cam is about 2 second per frame), then I found that the GPU not running, seem like the code some how not use the Colab's GPU. Can anyone know how to fix this please?
![image_2023-12-20_213710320](https://github.com/C0untFloyd/roop-unleashed/assets/81974770/cc60e681-3a2a-4068-81ef-fb5aead1e2f7)
**It ran, but extremely slow :(**
![image_2023-12-20_213731581](https://github.com/C0untFloyd/roop-unleashed/assets/81974770/c8f27072-faa7-4021-9f00-8c61099a3a1b)
**Google Colab even noticed me that I'm not using GPU and should change to standard runtime**

**Comment by phineas-pta** [comment]
#387

**Comment by mr-darksoul** [comment]
> > Can Anyone Guide on installation of Roop-Umleashed on Paperspace , Sagemaker studio lab or Kaggle, as Google colab free tier is getting constantly disconnected on processing just 4-5 frame out of 300 frames, Thanks in Advance though
> 
> i am using roop unleashed on paperspace for a month, it is only 8 usd per month,
> 
> there is no limit in generation or rendering like google colab,
> 
> we get GPUs like a4000, rtx5000, rtx 4000, p5000
> 
> in a4000(which is best) i get almost 10frames per second in generation....
> 
> it is super easy to use, just import the google colab notebook (ipynb) in paperspace then follow the same steps which you follow in google collab...............its no rocket science ![Screenshot (15)](https://private-user-images.githubusercontent.com/153287646/290918437-4ad42426-1475-4092-8fb3-94541eabfb36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MTcyOTUsIm5iZiI6MTcwNTYxNjk5NSwicGF0aCI6Ii8xNTMyODc2NDYvMjkwOTE4NDM3LTRhZDQyNDI2LTE0NzUtNDA5Mi04ZmIzLTk0NTQxZWFiZmIzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQyMjI5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2I3ZTJkOTJmYjM4MmRiZGVlOGMzNDljZDc1NDNmZjk3M2M5MWI0NzY4YjQ3YWQzM2QzZDU0YWU1Y2M0YThjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LsVkfaase4VAns1kf8ACQWZOnrYzORfmzG5CI1ssLw0) ![Screenshot (16)](https://private-user-images.githubusercontent.com/153287646/290918443-a8a8fa44-43ce-49f1-9924-7df99d004c94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MTcyOTUsIm5iZiI6MTcwNTYxNjk5NSwicGF0aCI6Ii8xNTMyODc2NDYvMjkwOTE4NDQzLWE4YThmYTQ0LTQzY2UtNDlmMS05OTI0LTdkZjk5ZDAwNGM5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQyMjI5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjQ0NDllNzcwMzcwNTI3N2U0ZjAyYjUxMmVlNmMwMzI4YWM2ZjhkOTk0NmY4MTQ1YWUxNTYyNTgzZDZmZDlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8yeLxlh9qGKkakFqSwRW2z6aTA92uCWfHAT5C2RPG9E)

Have you tired it on vast ai? I'm getting FFMPEG error

**Comment by Akibajack** [comment]
> > Can Anyone Guide on installation of Roop-Umleashed on Paperspace , Sagemaker studio lab or Kaggle, as Google colab free tier is getting constantly disconnected on processing just 4-5 frame out of 300 frames, Thanks in Advance though
> 
> i am using roop unleashed on paperspace for a month, it is only 8 usd per month,
> 
> there is no limit in generation or rendering like google colab,
> 
> we get GPUs like a4000, rtx5000, rtx 4000, p5000
> 
> in a4000(which is best) i get almost 10frames per second in generation....
> 
> it is super easy to use, just import the google colab notebook (ipynb) in paperspace then follow the same steps which you follow in google collab...............its no rocket science ![Screenshot (15)](https://private-user-images.githubusercontent.com/153287646/290918437-4ad42426-1475-4092-8fb3-94541eabfb36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5OTM0MzAsIm5iZiI6MTcwNjk5MzEzMCwicGF0aCI6Ii8xNTMyODc2NDYvMjkwOTE4NDM3LTRhZDQyNDI2LTE0NzUtNDA5Mi04ZmIzLTk0NTQxZWFiZmIzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QyMDQ1MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWE3ZGE5ODZhYTJkOGZkYTEyNTExOWZmMGQzN2ZkMDA3MmQyNzEwZjljZTM2M2E1YWJhYTgzZmE3Yzg5YzZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aV3gzMHf81fIn2sdAdekmpPDKEX_pKke-2hsBPI8RL4) ![Screenshot (16)](https://private-user-images.githubusercontent.com/153287646/290918443-a8a8fa44-43ce-49f1-9924-7df99d004c94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5OTM0MzAsIm5iZiI6MTcwNjk5MzEzMCwicGF0aCI6Ii8xNTMyODc2NDYvMjkwOTE4NDQzLWE4YThmYTQ0LTQzY2UtNDlmMS05OTI0LTdkZjk5ZDAwNGM5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QyMDQ1MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjhlNTIyMjljM2QzOGNmODllZmMyOWU2MTE5Yjk2ZjE3ZGU0MmEzMGU5YTI5ZDNmMmIwNzMzZTRjODRjZDRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8eTaZU5VrpoqZkanHjU4UHa3bTi6ltEAulHMuPIbR-o)



> > Can Anyone Guide on installation of Roop-Umleashed on Paperspace , Sagemaker studio lab or Kaggle, as Google colab free tier is getting constantly disconnected on processing just 4-5 frame out of 300 frames, Thanks in Advance though
> 
> i am using roop unleashed on paperspace for a month, it is only 8 usd per month,
> 
> there is no limit in generation or rendering like google colab,
> 
> we get GPUs like a4000, rtx5000, rtx 4000, p5000
> 
> in a4000(which is best) i get almost 10frames per second in generation....
> 
> it is super easy to use, just import the google colab notebook (ipynb) in paperspace then follow the same steps which you follow in google collab...............its no rocket science ![Screenshot (15)](https://private-user-images.githubusercontent.com/153287646/290918437-4ad42426-1475-4092-8fb3-94541eabfb36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5OTM0MzAsIm5iZiI6MTcwNjk5MzEzMCwicGF0aCI6Ii8xNTMyODc2NDYvMjkwOTE4NDM3LTRhZDQyNDI2LTE0NzUtNDA5Mi04ZmIzLTk0NTQxZWFiZmIzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QyMDQ1MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWE3ZGE5ODZhYTJkOGZkYTEyNTExOWZmMGQzN2ZkMDA3MmQyNzEwZjljZTM2M2E1YWJhYTgzZmE3Yzg5YzZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aV3gzMHf81fIn2sdAdekmpPDKEX_pKke-2hsBPI8RL4) ![Screenshot (16)](https://private-user-images.githubusercontent.com/153287646/290918443-a8a8fa44-43ce-49f1-9924-7df99d004c94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5OTM0MzAsIm5iZiI6MTcwNjk5MzEzMCwicGF0aCI6Ii8xNTMyODc2NDYvMjkwOTE4NDQzLWE4YThmYTQ0LTQzY2UtNDlmMS05OTI0LTdkZjk5ZDAwNGM5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QyMDQ1MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjhlNTIyMjljM2QzOGNmODllZmMyOWU2MTE5Yjk2ZjE3ZGU0MmEzMGU5YTI5ZDNmMmIwNzMzZTRjODRjZDRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8eTaZU5VrpoqZkanHjU4UHa3bTi6ltEAulHMuPIbR-o)

hi...i was wondering about what you said, before i put any money on it does it have a good if not fast rendering speed? and i also ask if tou could point me to a tutorial or screeshot to how i could get roop in paperspace...because kaggle and colab got greedy and have sabotaged their own good product..thanks in advance
