### ISSUE TITLE
No audio in video

### ISSUE THREAD

**Issue by Arkham862** [C0untFloyd/roop-unleashed#366]
Created my first video, I used a short video for a test run before moving on to a larger video and was really excited that it turned so good, but my only issue was there was no audio in the finished video.  I would like to figure this out before I move on to a larger video. Any useful advice would be greatly appreciated. I will admit I am running a shit computer, and it takes a long time to process the videos, but I have no problem dealing with the long waits and if I have to, I can always extract the audio from the original video and use one of my video converters to add the audio to the new video which would take even longer,  but I would really prefer not having to resort to that option.

**Comment by RFedz007989** [comment]
I installed the new version even I am not having audio for the final swapped result.

Thank You
