### ISSUE TITLE
encountering continuous disconnections on Google Colab,    seeking advice on how to address this issue or installation of Roop-Unleashed on different platforms 

### ISSUE THREAD

**Issue by ajSh-dot** [C0untFloyd/roop-unleashed#369]
We ar encountering continuous disconnections on Google Colab, and I'm seeking advice on how to address this issue. Additionally, if anyone has successfully installed Roop-Unleashed on Amazon SageMaker Studio Lab, Kaggle, or Paperspace, I would be grateful for any insights or step-by-step instructions you can provide.

facing challenges with the installation of Roop-Unleashed on different platforms and would greatly appreciate your expertise and guidance 

Thank you in advance for your support.

**Comment by ziggyputtar** [comment]
i am using roop unleashed on paperspace (a good alternative of Google Colab) for a month, it is only 8 usd per month,

there is no limit in generation or rendering like google colab,

we get GPUs like a4000, rtx5000, rtx 4000, p5000

in a4000(which is best) i get almost 10frames per second in generation....

it is super easy to use, just import the google colab notebook (ipynb) in paperspace then follow the same steps which you

**Comment by ragnar569** [comment]
pls somebody help this problem is there for weeks

**Comment by ajSh-dot** [comment]
> pls somebody help this problem is there for weeks

After continues Disconnting , its working but at speed of 1Fps process rate

**Comment by ajSh-dot** [comment]
> i am using roop unleashed on paperspace (a good alternative of Google Colab) for a month, it is only 8 usd per month,
> 
> there is no limit in generation or rendering like google colab,
> 
> we get GPUs like a4000, rtx5000, rtx 4000, p5000
> 
> in a4000(which is best) i get almost 10frames per second in generation....
> 
> it is super easy to use, just import the google colab notebook (ipynb) in paperspace then follow the same steps which you

Thank you for your valuable input, paperspace Gradient  payment gateway is not working , Had to use Amazon sagemaker studio lab, if any help would be appreciated

**Comment by alejandro010493** [comment]
please help on using roop unleashed on sagemaker

**Comment by 592429d** [comment]
> > pls somebody help this problem is there for weeks
> 
> After continues Disconnting , its working but at speed of 1Fps process rate

Same with me. I found that the GPU of Colab is not running and I don't know why or how to fix it. I even can't signup for Paperspace because they not accept phone verify in my country.
