### ISSUE TITLE
Low quality faces in Batch mode

### ISSUE THREAD

**Issue by etruscanmuffin909** [C0untFloyd/roop-unleashed#37]
**Describe the bug**
In Batch processing, the results come out with fuzzy or blurry faces every time. The face enhancer settings do not affect this. The rest of it works beautifully - thank you for this!

**To Reproduce**
1. Run with default settings
2. Batch process with or without face enhancer seems to be happening in command line
3. The faces all come out blurry/fuzzy. Single-file mode with same faces and settings works perfectly.

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by eniora** [comment]
I can confirm this. Even though face enhancer takes its time processing the frames yet it has no effect on the output images.

**Comment by GilfalasOrcbane** [comment]
Can confirm too.

In fact I believe, the enhancer tries to enhance the source images instead of the target images.
If you check the "modified" time/date of the images you will notice it.

**Comment by TheBigSmokey** [comment]
Can confirm having the same issue

**Comment by Skuuurt** [comment]
Same for me

**Comment by Skuuurt** [comment]
Regarding that matter, it would be cool to have some sort of quality slider inside the gui. Furthermore, some quality options for video do exist but I realy don't know if they are applied when it comes to pics. At least the quality of the faces seems to be always the same for pics, no matter what the input resolution of the face is. I tried to modify quality in the bat, but honestly don't know if I did it well, hence the fact that a slider would be a well apreciated feature.

**Comment by eniora** [comment]
@Skuuurt I think what you want is a slider for the face enhancer strength? if so @C0untFloyd said will be implemented in a future update. https://github.com/C0untFloyd/roop-unleashed/issues/42

**Comment by etruscanmuffin909** [comment]
I appreciate all the hard work and realize this project is going in a new direction, but is it at all possible for this one feature to work? Could someone explain how to fix it maybe? Batch mode is the only extra feature I really need. Thank you.

**Comment by lyn444** [comment]
hihi @C0untFloyd why this is marked as completed? which branch can we pull to use the latest version?

**Comment by C0untFloyd** [comment]
#66
