### ISSUE TITLE
Running the windows_run.bat file on Win11 has an error. Help me fix the error

### ISSUE THREAD

**Issue by Lucax699** [C0untFloyd/roop-unleashed#380]
**Describe the bug**
I followed the instructions for running the windows_run file in the patch: C:\Users\Lucas\Desktop\roop-unleashed-main\roop-unleashed-main\installer . After running, I get this error:
.....
      copying insightface\thirdparty\face3d\mesh\cython\setup.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
      running build_ext
      building 'insightface.thirdparty.face3d.mesh.cython.mesh_core_cython' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for insightface
Failed to build insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects
Launching App
Traceback (most recent call last):
  File "C:\Users\Lucas\Desktop\roop-unleashed-main\roop-unleashed-main\installer\roop-unleashed\run.py", line 3, in <module>
    from roop import core
  File "C:\Users\Lucas\Desktop\roop-unleashed-main\roop-unleashed-main\installer\roop-unleashed\roop\core.py", line 14, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Done!
Press any key to continue . . .

**To Reproduce**
1. Run file windows_run.bat
2. Run it for a while and get the error as shown in the picture

**Details**
What OS are you using?
- [x] Windows 

Are you using a GPU?
- [x] NVIDIA
- [x] Intel

**Which version of roop unleashed are you using?**

**Screenshots**
![image](https://github.com/C0untFloyd/roop-unleashed/assets/112509430/216f8236-0cc0-4d3f-9b60-7e015def13b1)

**Comment by C0untFloyd** [comment]
You're missing the [Visual Studio Installation](https://github.com/C0untFloyd/roop-unleashed/wiki/Installation#installation)
