### ISSUE TITLE
Error in execution: Invalid Output Name:1288 when choosing GFPGAN

### ISSUE THREAD

**Issue by dondonliao** [C0untFloyd/roop-unleashed#382]
**Describe the bug**

Dear CountFloyd,
Roop Unleashed is simply fantastic ! I've using it well on my computer; Yet while I put it on cloud to leverage Nvidia CPU hoping to run faster, when i choose post-processing GFPGAN, it shows error " Error in execution: Invalid Output Name:1288 ". Could you tell anything I am missing?

Appreciate in Advance!!!

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ X ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ X ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
3.3.4

**Screenshots**
![image](https://github.com/C0untFloyd/roop-unleashed/assets/46164344/2a135c55-e1cf-4338-827b-002904e89d2e)

![image](https://github.com/C0untFloyd/roop-unleashed/assets/46164344/ffe6b5c5-1e5b-426b-97f0-6b5f1f8fe13e)
![image](https://github.com/C0untFloyd/roop-unleashed/assets/46164344/36a35f4f-e1d3-4148-b6d7-e0f2937bf9d6)

**Comment by Oil3** [comment]
Do you have access to terminal/onsole to show more details? 
A blind idea: redownload the gfpgan model.

And as a side question, how is this service? Seetalabs? I checked Azure and Amazon but not for me

**Comment by C0untFloyd** [comment]
Sounds like a corrupted model, like Oil3 suggested.
