### ISSUE TITLE
[Errno 2] No such file or directory: 'models/CLIP/rd64-uni-refined.pth

### ISSUE THREAD

**Issue by Dofase** [C0untFloyd/roop-unleashed#386]
**Describe the bug**
[Errno 2] No such file or directory: 'models/CLIP/rd64-uni-refined.pth

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ x ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ x ] Mac

**Which version of roop unleashed are you using? 3.3.4

**Screenshots**
![Capture d’écran 2023-12-18 à 16 52 26](https://github.com/C0untFloyd/roop-unleashed/assets/153669343/68a6ad4e-729f-4f0d-9609-ebc4fbd468eb)

Hello, I don't understand why I have this error. Do you have an idea ? I tried this solution:

https://github.com/C0untFloyd/roop-unleashed/issues/362

But nothing works.
I'm on a mac M1 silicon

Thanks

**Comment by lysxelapsed** [comment]
You're almost there 😉 The solution in #362 will work for you too, you just have to adjust the path to your system. The `/Users/user/roop-unleashed/`-part of `/Users/user/roop-unleashed/models/CLIP/rd64-uni-refined.pth'` I got from his cmd output. You have to adjust the path to wherever you got your roop-unleashed installed. In his case, that was `/Users/user`
