### ISSUE TITLE
Automatically switches to CPU on Google Colab even though the GPU has not exceeded the limit

### ISSUE THREAD

**Issue by huyitus** [C0untFloyd/roop-unleashed#387]
**Describe the bug**
I use roop-unleashed on Google Colab, it automatically switches to CPU on Google Colab even though the GPU has not exceeded the limit.

**To Reproduce**
1. Pull from Github
2. Install some dependencies
3. Run

**2023-12-21 03:41:58.970384683 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1193 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcufft.so.10: cannot open shared object file: No such file or directory**

**Comment by 592429d** [comment]
Same with me, the code run fine but I noticed that the GPU was not running, even just a little.

**Comment by phineas-pta** [comment]
recently colab switch to cuda 12, but current onnxruntime (backend of inswapper) version 1.16.x still require cuda 11.8

solutions:
- force downgrade cuda on colab
- build onnxruntime for cuda 12 on colab
- *easier solution but only temporary*: https://github.com/googlecolab/colabtools/issues/4214#issuecomment-1859155789
