### ISSUE TITLE
Output fps of livecam is super low, even not running face swap.

### ISSUE THREAD

**Issue by 592429d** [C0untFloyd/roop-unleashed#388]
**Describe the bug**
The output livecam is just 1-2 fps, even without face swapping (just run the code and see the output live cam without uploading any image for face swap). I uploaded an image and ran with 1 thread then got the result even slower (just approx 1fps). Then I increase 1 thread per time until got to more than 20 threads but got same result.
I use NVIDA and cmd said I was running on cuda. My GPU utilization is just about 30% and 1.9 Gb in Vram (with 1 thread). Even with 20 threads there's no big different. I think it's because the fps of output livecam is low by default, which lead to low utilization of GPU even when increase the number of threads

**Comment by maxmelichov** [comment]
Hey, were you able to fix this issue?

**Comment by 592429d** [comment]
> Hey, were you able to fix this issue?

No I still don't know how to deal with it

**Comment by jorvilla84** [comment]
Does anyone knows what file (.py) has the 'fake camera output'? I am having the issue (posted on another thread) with same testing and same results.

**Comment by C0untFloyd** [comment]
Are you talking about the output in the browser (the live cam tab) or the obs output?
The tab output can't be sped up as long as I'm abusing an image control to display the final frame. Gradio (the UI Framework) is missing some sort of fast control for user streaming. However the OBS virtual camera doesn't have these limitations and can be tweaked to your needs in virtualcam.py
`pref_width = 1280
    pref_height = 720
    pref_fps_in = 30`
