### ISSUE TITLE
Faceswapping Tab Functions

### ISSUE THREAD

**Issue by u3214vf590dc** [C0untFloyd/roop-unleashed#390]
Can someone explain how to use "Add from local files" under target section of the faceswapping tab? Is there a way to detect all the faces in the faceswapping tab?

**Comment by C0untFloyd** [comment]
This was more or less added for running on Colab Servers. Specifying a folder path here, fills the target files with all videos/images from that folder. This means you can prepare a server folder before running roop and don't need to upload them through the GUI over the internet (which is much slower).
> Is there a way to detect all the faces in the faceswapping tab?
I don't get your question. Please have a look at the [Wiki](https://github.com/C0untFloyd/roop-unleashed/wiki/Face-Swap-Tab)

**Comment by u3214vf590dc** [comment]
Thank you. To clarify the second question: is it possible to add functionality by which the code scans the target video for all “swappable” faces? This will be helpful for files with many faces. Also, sometimes the application interprets the same face as two separate faces. This results in the second face not getting replaced. Sent from my iPhoneOn Dec 28, 2023, at 5:23 AM, C0untFloyd ***@***.***> wrote:﻿
This was more or less added for running on Colab Servers. Specifying a folder path here, fills the target files with all videos/images from that folder. This means you can prepare a server folder before running roop and don't need to upload them through the GUI over the internet (which is much slower).

Is there a way to detect all the faces in the faceswapping tab?
I don't get your question. Please have a look at the Wiki

**Comment by C0untFloyd** [comment]
> is it possible to add functionality by which the code scans the target video for all “swappable” faces?

Certainly is this possible, just impractical. If the code would scan a 90 minute whole movie this might take a very long time. Instead you should skip to the frames with the faces you're interested in and select them for usage.

> Also, sometimes the application interprets the same face as two separate faces.

This is adjusted by using the face similarity slider. Use a higher value like e.g. 0.85 and the face won't be seen as different.
