### ISSUE TITLE
How to change in windows_run.bat for Auto-Launch another Browser?

### ISSUE THREAD

**Issue by lost-in-emotions** [C0untFloyd/roop-unleashed#392]
How to change in windows_run.bat for Auto-Launch another Browser?
Or maybe atleast completely deactivate the Auto-Launch.

Thx4Hlp

**Comment by C0untFloyd** [comment]
https://github.com/C0untFloyd/roop-unleashed/blob/3ec817630d432fba2bfa4f59703df1db69e81463/ui/main.py#L70

Change inbrowser=True to inbrowser=False

**Comment by lost-in-emotions** [comment]
ah nice. yes this is it.

can i here also change the auto launch with f.e. my second browser "chrome"?
