### ISSUE TITLE
create video bug

### ISSUE THREAD

**Issue by kongqi404** [C0untFloyd/roop-unleashed#394]
**Describe the bug**
when processed face swap and then use ffmpeg command to create video, My os haven't libx264 and other encoder, so i can't get the output video.
perhaps we need to modify it by use a optional execute parameter 
**To Reproduce**
1. just no optional encoder

**Details**
What OS are you using?
- [✔] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [✔] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
the latest version
**Screenshots**

**Comment by C0untFloyd** [comment]
I don't get the question and obviously noone else so far. Encoding of videos is done by ffmpeg as the Wiki @ https://github.com/C0untFloyd/roop-unleashed/wiki/Installation clearly states -> "For Video face-swapping you also need to have ffmpeg properly installed (having it in your PATH Env)."
