### ISSUE TITLE
Installed on Widows10. Works only with Force CPU. Doesnt work on GPU or NVIDIA . Freezes after 1 or 2 farames.Error says unable to allocate required memory

### ISSUE THREAD

**Issue by rajnish1959** [C0untFloyd/roop-unleashed#395]
**Describe the bug**

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**

**Screenshots**

**Comment by rajnish1959** [comment]
Installed on Widows10. Works only with Force CPU. Doesnt work on GPU or NVIDIA . Freezes after 1 or 2 farames.Error says unable to allocate required memory

**Comment by C0untFloyd** [comment]
You followed the instructions [here](https://github.com/C0untFloyd/roop-unleashed/wiki/Installation)?
And successfully installed CUDA + Visual Studio? What GPU and how much memory?

**Comment by lysxelapsed** [comment]
I think this refers to system memory, happened to me a few times. Roop-unleashed allocates at least 14GB RAM (probably less with cpu only) during swapping process.
