### ISSUE TITLE
When Tenssort is selcted the app uses the cpu instead of the Nvidia gpu

### ISSUE THREAD

**Issue by Doctordefector** [C0untFloyd/roop-unleashed#398]
![image](https://github.com/C0untFloyd/roop-unleashed/assets/51265033/266d90be-73c1-4df7-9057-187a59c30144)
All drivers updated,Hardware accelerated GPU scheduling is on but the app uses my cpu instead of the 3060 for some reason

**Comment by C0untFloyd** [comment]
#300
