### ISSUE TITLE
Request to upgrade masking function

### ISSUE THREAD

**Issue by aiise117** [C0untFloyd/roop-unleashed#399]
Can you add more comprehensive parts to the mask, such as increasing transparency options and specifying individual masks for facial features

**Comment by C0untFloyd** [comment]
There is an ongoing discussion here -> https://github.com/C0untFloyd/roop-unleashed/discussions/27

**Comment by aiise117** [comment]
Thank you for your continuous hard work in modifying and optimizing the code! Only then can we experience more user-friendly products. Here's a small suggestion for you: can facial masks add more options in left and right directions, as well as different transparency options! I hope you can notice. Wishing you a happy life and all the best
