### ISSUE TITLE
Roop not using gcolab GPUs

### ISSUE THREAD

**Issue by cubargh** [C0untFloyd/roop-unleashed#400]
**Describe the bug**
I have collab premium. Copied the notebook, ran it in a v100 hardware. No GPU utilization. Tried it in a100, same result

Help?

got this error on console
`[E:onnxruntime:Default, provider_bridge_ort.cc:1480 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1193 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcufft.so.10: cannot open shared object file: No such file or director`

**Comment by backtr4ck** [comment]
@C0untFloyd got any idea why is this happening?

**Comment by marat2509** [comment]
Google Colab has updated the Cuda version to version 12. ONNXRuntime does not support this version yet, but this feature will appear soon 
See https://github.com/microsoft/onnxruntime/issues/18850

**Comment by backtr4ck** [comment]
For a temporary fix, go to the command palette (ctrl+shift+P) and select "Use fallback runtime version"

**Comment by C0untFloyd** [comment]
I was having problems on my local pc as well, suddenly not recognizing cuda but instead having "Azure" among the execution providers. I went back to installing onnxruntime-gpu v1.16.2 which seemed to have solved it. Weird...

**Comment by thany22** [comment]
> For a temporary fix, go to the command palette (ctrl+shift+P) and select "Use fallback runtime version"

The previous runtime version isn't available anymore. Any solutions)

**Comment by marat2509** [comment]
> > For a temporary fix, go to the command palette (ctrl+shift+P) and select "Use fallback runtime version"
> 
> The previous runtime version isn't available anymore. Any solutions)

Install latest official onnxruntime-gpu

**Comment by Marv761125** [comment]
> > > For a temporary fix, go to the command palette (ctrl+shift+P) and select "Use fallback runtime version"
> > 
> > 
> > The previous runtime version isn't available anymore. Any solutions)
> 
> Install latest official onnxruntime-gpu

Hi. Could you tell me how to do this or is there a link you used? Thx.

**Comment by marat2509** [comment]
> how to do this
```shell
pip install --upgrade onnxruntime-gpu
```

**Comment by htmlcodepreview** [comment]
> > how to do this
> 
> ```shell
> pip install --upgrade onnxruntime-gpu
> ```

Tried this and several versions like 16.2 17 and 17.1, with no success.

**Comment by marat2509** [comment]
Setup (after cloning):
```python
import os
!pip install pyyaml -r requirements.txt

if os.path.isfile("/usr/bin/nvidia-smi") or os.path.isfile("/opt/bin/nvidia-smi"):
    !pip uninstall -y onnxruntime onnxruntime-gpu
    !pip install onnxruntime-gpu

```

Run:
```python
import yaml
import os

roop_config = {
    'clear_output': True,
    'live_cam_start_active': False,
    'max_threads': 32,
    'output_image_format': 'png',
    'output_video_codec': 'libx264',
    'output_video_format': 'mp4',
    'video_quality': 14,
    'frame_buffer_size': 6,
    'selected_theme': 'Default',
    'server_name': '',
    'server_port': 0,
    'server_share': True
}

if os.path.isfile("/usr/bin/nvidia-smi") or os.path.isfile("/opt/bin/nvidia-smi"):
    roop_config["provider"] = "cuda"
    print("I: Using CUDA")
else:
    roop_config["provider"] = "cpu"

with open("./config.yaml", "w") as config_file:
    config_file.write(yaml.dump(roop_config))

!python run.py
```

**Comment by zachysaur** [comment]
wht about on kaggle?

**Comment by michidaeron** [comment]
> > how to do this
> 
> ```shell
> pip install --upgrade onnxruntime-gpu
> ```

Is there no way to avoid the message about colab limitation and cause it to be disconnected?
Using fallback runtime version it worked before but not now :C

**Comment by marat2509** [comment]
@michidaeron @htmlcodepreview @Marv761125 - me updated and tested new setup code. Please test

**Comment by htmlcodepreview** [comment]
it works for me now
