### ISSUE TITLE
Slow Processing on Colab Pro

### ISSUE THREAD

**Issue by issuestissue** [C0untFloyd/roop-unleashed#403]
Hello! Great work, I've read some other issues but struggling to find the right balance to set for Google Colab un on V100-High RAM.
Using Codeformers:
at 8 threads it uses 12.77GB of mem but processes at around 3 seconds PER  frame, NOT FPS

at 2 threads it uses 5.5GB mem and a whopping 20s per every frame.

i feel like my settings are wrong somewhere as I think everyone else is getting more frames 

Anyone that uses the Colab version, have any optimizations that they've found ?

Thanks in advanced

**Comment by backtr4ck** [comment]
GPUs are not being used. Still waiting for some feedback from @C0untFloyd on #400

**Comment by backtr4ck** [comment]
For a temporary fix, go to the command palette (ctrl+shift+P) and select "Use fallback runtime version"
