### ISSUE TITLE
FFMPEG a real pain 

### ISSUE THREAD

**Issue by mr-darksoul** [C0untFloyd/roop-unleashed#404]
What OS are you using?
- [x] Linux

Are you using a GPU?
- [x] NVIDIA

Traceback (most recent call last):
  File "/roop-unleashed/roop/ffmpeg_writer.py", line 153, in write_frame
    self.proc.stdin.write(img_array.tobytes())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/roop-unleashed/roop/ProcessMgr.py", line 184, in write_frames_thread
    self.videowriter.write_frame(frame)
  File "/roop-unleashed/roop/ffmpeg_writer.py", line 197, in write_frame
    raise IOError(error)
OSError: [Errno 32] Broken pipe

roop unleashed error: FFMPEG encountered the following error while writing file /roop-unleashed/output/swapped 7__temp.mp4:

 b"Unrecognized option 'crf'.\nError splitting the argument list: Option not found\n"

**Comment by mr-darksoul** [comment]
ffmpeg version 4.3 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 7.3.0 (crosstool-NG 1.23.0.449-a04d0)
configuration: --prefix=/opt/conda/conda-bld/ffmpeg_1597178665428/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh --cc=/opt/conda/conda-bld/ffmpeg_1597178665428/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc --disable-doc --disable-openssl --enable-avresample --enable-gnutls --enable-hardcoded-tables --enable-libfreetype --enable-libopenh264 --enable-pic --enable-pthreads --enable-shared --disable-static --enable-version3 --enable-zlib --enable-libmp3lame
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100

**Comment by C0untFloyd** [comment]
Updating your ffmpeg to a newer version (I'm running v6.0) should solve your problems...

**Comment by mr-darksoul** [comment]
Well, it turned out to be Ubuntu. I had to switch from v20 to v22.
