### ISSUE TITLE
Previous output file continuously overwritten

### ISSUE THREAD

**Issue by CoreyCorza** [C0untFloyd/roop-unleashed#405]
**Describe the bug**
Not really a bug but kind of is, but also more of a basic stock standard feature/enhancement.
-There is only ever 1 output file in the output folder because it just keeps overwriting the previous output file. 
-Renaming the previous output file has no effect and it still gets overwritten. 
-The only way to salvage an output file is to completely remove it from the output folder before the next process overwrites it.

**To Reproduce**
Pretty self explanatory really

Are you using a GPU?
- [ ] No. CPU FTW
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?** 
Whatever the latest is, as of the time of posting this

**Screenshots**
Exhibit A: Only one output file despite processing several videos
![image](https://github.com/C0untFloyd/roop-unleashed/assets/40785775/e11b90c2-094c-451c-a6bc-9c00012e76e5)

**Comment by C0untFloyd** [comment]
It's a setting:
![grafik](https://github.com/C0untFloyd/roop-unleashed/assets/131583554/8378e1f2-eaf8-477e-9a01-b5c7e1aea0c0)

**Comment by CoreyCorza** [comment]
Confirmed that my eyes are painted on
