### ISSUE TITLE
Noticeable face masking 

### ISSUE THREAD

**Issue by CoreyCorza** [C0untFloyd/roop-unleashed#407]
**Describe the bug**
Maybe a feature request more than a bug. 
But I'm not sure exactly what the feature request/solution is or should be.

Been noticing here and there a pretty noticeable mask line at the bottom of faces around the jaw line, in some cases creating double jawlines. 
It would be nice to improve it. 

![ApplicationFrameHost_chubc4tJFy01](https://github.com/C0untFloyd/roop-unleashed/assets/40785775/9bd0573c-011c-4fb0-a35a-15a353d176a6)

I don't really know what the solution is though, whether that be something like having access to an mask edge blur control maybe? I'm not sure.

A side note: Pretty amazing how good roop unleashed is now. Great work!

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
The latest.

**Comment by whitebabyblackmarket** [comment]
I noticed this as well. I'd like to add a similar noticeable output issue with the eyes. Some of the output images have a melted eye effect happening. Some do and some don't, not sure what makes the difference. 
![angelaeye](https://github.com/C0untFloyd/roop-unleashed/assets/116154299/1fde129a-d84c-4fc2-bf2f-c9d0c4eab72b)

![eye](https://github.com/C0untFloyd/roop-unleashed/assets/116154299/38fcf17f-7468-4a72-b7d2-39af1918bd66)

**Comment by C0untFloyd** [comment]
Yes, there is currently no one-fits-all solution to masking. It's even more visible if you have some kind of repeating pattern or moire effect in the background. Best I can currently do is giving users more control over the blur amounts and padding/masking. This however clutters the UI and might turn off newbies.
The "melted" eye effect is different I think and is probably caused by bad landmark detection or weird angle interpretation by the swapper model. Again, there is not much one can currently do 🤷‍♂️

**Comment by CoreyCorza** [comment]
``This however clutters the UI and might turn off newbies``
Maybe to counteract this, there could be an "advanced masking" option under the settings tab? And only when enabled it will show the extra controls.
Some more control over the blur amount and padding would definitely help I think, I hope

**Comment by Oil3** [comment]
> This however clutters the UI and might turn off newbies. 

I couldn't resist: if they aren't turned off by Python, I think we be fine 🙈

It would be amazing if you could add like "advanced settings", which would unlock the controls you mentionned.

As for noticeable "marks", I figured playing with the  "face similarity treshold" could help ("tightening" it -lowering), as well as using "selected face" rather than "first found", and  adding the face again when it's at an angle.
*

**Comment by C0untFloyd** [comment]
> I couldn't resist: if they aren't turned off by Python, I think we be fine 🙈

I also couldn't [resist](https://www.youtube.com/watch?v=A8MO7fkZc5o&t=86s) 😄 

Ok, ok I'm adding the options to the already existing advanced section...

**Comment by CoreyCorza** [comment]
[Noice](https://www.youtube.com/watch?v=26lZvxwWzY0)

**Comment by KalliasX** [comment]
Back in closed 2.7.X threads, so not sure it's relevant anymore, you spoke about frame buffer settings. Where is this set? and the 35+ with 16 threads (3090), is this still relevant in today's version? And if so, where do you the change frame buffer value? Thx in advance and sorry if I should have posted this somewhere else. Cheers.

**Comment by C0untFloyd** [comment]
> Back in closed 2.7.X threads, so not sure it's relevant anymore, you spoke about frame buffer settings. Where is this set? and the 35+ with 16 threads (3090), is this still relevant in today's version? And if so, where do you the change frame buffer value? Thx in advance and sorry if I should have posted this somewhere else. Cheers.

No, not relevant anymore. Meanwhile it's almost the other way around, you have to be quite cautious with the number of threads to prevent running out of VRAM.

**Comment by KalliasX** [comment]
That explains a few things... over 6-7 on a 3090 and I get issues it goes to shared vram and perf tanks badly (with 4k source file)Thanks 🙏 Sent from my iPhoneOn 26 Jan 2024, at 21:22, C0untFloyd ***@***.***> wrote:﻿

Back in closed 2.7.X threads, so not sure it's relevant anymore, you spoke about frame buffer settings. Where is this set? and the 35+ with 16 threads (3090), is this still relevant in today's version? And if so, where do you the change frame buffer value? Thx in advance and sorry if I should have posted this somewhere else. Cheers.

No, not relevant anymore. Meanwhile it's almost the other way around, you have to be quite cautious with the number of threads to prevent running out of VRAM.

**Comment by C0untFloyd** [comment]
Manual masking incoming! Small teaser for the upcoming version:

![grafik](https://github.com/C0untFloyd/roop-unleashed/assets/131583554/3c76eaa6-bd8b-4ec8-9806-ad1a160c5223)

![grafik](https://github.com/C0untFloyd/roop-unleashed/assets/131583554/f12b26b3-5735-4eca-8405-ad31d3c59c64)

![grafik](https://github.com/C0untFloyd/roop-unleashed/assets/131583554/53580c05-06d9-4432-b39d-86db9120157b)

It's almost finished but I also upgraded to the latest gradio framework which also contains the latest, newest bugs so I'm waiting on the gradio guys to fix their issues.

**Comment by CoreyCorza** [comment]
@C0untFloyd Looks good! 
Will it include something for blurring the mask edge?
And out of curiosity, when drawing on 1 frame it propagates the mask to the rest of the frames?

**Comment by C0untFloyd** [comment]
Yes to both. Somoothing is done on the edges, currently the same amount as for text masking. Yes, the mask is propagated but it probably makes not much sense for most videos.
