### ISSUE TITLE
Not utilizing GPUs

### ISSUE THREAD

**Issue by mr-darksoul** [C0untFloyd/roop-unleashed#408]
**Describe the bug**
Not utilizing GPU Nvidia RTX4090 (cloud) hosted on Vast ai

**Details**
What OS are you using?
- [x] Linux

Are you using a GPU?
- [x] NVIDIA

nvidia-smi

Fri Jan 19 19:58:57 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.29.02              Driver Version: 545.29.02    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        On  | 00000000:07:00.0  On |                  Off |
|  0%   51C    P8              21W / 490W |    194MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+
**Which version of roop unleashed are you using?**
Latest and Greatest

**Comment by mr-darksoul** [comment]
this pops up after I hit start button:

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
2024-01-19 20:33:24.173581287 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1193 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcufft.so.10: cannot open shared object file: No such file or directory

**Comment by C0untFloyd** [comment]
You should try a CUDA version smaller than 12 (I'm using 11.8) and be sure to set the provider to cuda in the settings tab. Perhaps your issue is also related to #400
