### ISSUE TITLE
a toggle for face enhancement

### ISSUE THREAD

**Issue by patientx** [C0untFloyd/roop-unleashed#41]
It is not always needed and takes extra time , can we get a toggle on gui so we can disable it and save time when needed ?

**Comment by mammuthus** [comment]
Huh? You can choose "None" here and it will work without any face enhancement:
![image](https://github.com/C0untFloyd/roop-unleashed/assets/1700286/fed5eb92-2cd7-4a73-b961-62e5af3ee0bd)

**Comment by C0untFloyd** [comment]
> and it takes shorter time than it does swapping , so that's actually doing nothing in that time ? Because nothing is selected ?

Yes
