### ISSUE TITLE
Detecting `cuda` but not using it.

### ISSUE THREAD

**Issue by tikendraw** [C0untFloyd/roop-unleashed#412]
**Describe the bug**
Roop is detecting the GPU, but not using it.

**Details**
What OS are you using?
- [x] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
jan 20, 2024 git pull

**Screenshots**
![Screenshot from 2024-01-20 19-40-16](https://github.com/C0untFloyd/roop-unleashed/assets/68785366/a471538d-534f-4602-a7ea-7bdb96e907ae)

**Comment by C0untFloyd** [comment]
Your CUDA version is not suuported currently, please see #400

**Comment by tikendraw** [comment]
> Your CUDA version is not suuported currently, please see #400

Will converting this ONNX model to latest model work? 
```python
import onnx
from onnx import version_converter

model_path = Path("models")
dest_path = Path('converted_models')

for model_ in model_path.iterdir():
	if str(model_).endswith('onnx'):
		dest_path_model = dest_path/model_.name
		print(dest_path_model)

		model = onnx.load(model_)
		converted_model = version_converter.convert_version(model, 11)
		onnx.save(converted_model, dest_path_model)
```

**Comment by C0untFloyd** [comment]
I doubt it. The problem isn't the model but the runtime which isn't up to date.

**Comment by tikendraw** [comment]
> I doubt it. The problem isn't the model but the runtime which isn't up to date.

[Somedev's roop](https://github.com/s0md3v/roop) is working on this same gpu. how?
