### ISSUE TITLE
pip3 install onnxruntime-silicon==1.16.0 on M1?

### ISSUE THREAD

**Issue by giulas** [C0untFloyd/roop-unleashed#414]
**Describe the bug**
It doesn't install (surely...it even says silicon...it's not for m1 Macs).
Do you guys have an idea of how to make it work? Not that doesn't involve installing cocoa anyway.

**To Reproduce**
:pip3 install onnxruntime-silicon==1.16.0
ERROR: Could not find a version that satisfies the requirement onnxruntime-silicon==1.16.0 (from versions: 1.14.1, 1.15.0)
ERROR: No matching distribution found for onnxruntime-silicon==1.16.0

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ x] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [x ] Mac

**Comment by Oil3** [comment]
@giulas I  just checked and see these versions: (from versions: 1.14.1, 1.15.0, 1.16.0, 1.16.3)
i see from your log that you seem restricted to 1.15.0. This could be a Python version mismatch, or OsX, or the usual python stuff. I love this language but nothing ever works on the first time and it's always about jungling versions like people can't be bothered to adapt to new versions.
Enough for the rant, I checked pip versions and the 1.15 and the later are available for pyrhon 3.8, 3.9, 3.10, 3.11, so I dont know.
Please tell us versions of: osX, python, pip, please

Also you can download from @cansik https://github.com/cansik/onnxruntime-silicon/releases the package according to your pyrhon;: 311 being pyrhon 3.11, 310 python enzovoort
Once you download, you can't change the name, you do:
pip3 install path-to-the-file
Right click then alt, then "copy pathname", or drag and drop onto your terminal window after "pip3 install "
Let me know. And get 1.16.3
