### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by M3KB7N** [C0untFloyd/roop-unleashed#418]
**Describe the bug**

**To Reproduce**
1. Go to '~cd roop-unleashed/
2. run  "python3 run.py "
3. See error : Segmentation fault (core dumped)

**Details**
What OS are you using?
- [ X] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
v3.5.0

**Screenshots**
If applicable, add screensh
![Screenshot from 2024-01-23 22-56-07](https://github.com/C0untFloyd/roop-unleashed/assets/157558982/ec75cb1a-5fc0-4285-ac9c-90b4c1783133)
ots to help explain your problem.

**Comment by C0untFloyd** [comment]
Looks like either your OS is gone haywire or your hardware (GPU VRAM?) is faulty. Unrelated to roop but you're seeing the effect of filling your RAM with models.
