### ISSUE TITLE
i want to implement face swap with a specific face in the video without using the ui, how can do this by python run.py , like i dont want to use UI, i just to implement face swap with that specific person present at specific frame at postion 1

### ISSUE THREAD

**Issue by Shekharmeena28** [C0untFloyd/roop-unleashed#420]
**Describe the bug**

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**

**Screenshots**

**Comment by C0untFloyd** [comment]
Here take your 🎁 for having the biggest title topic of them all.
But why no UI? You can do batch processing using this, the GUI works on a colab or on hugging face...the only reason I can think of is hiding your fakes. If you still insist on using commandline args, use the old archived tkinter version:
https://github.com/C0untFloyd/roop-unleashed/tree/tkinter
