### ISSUE TITLE
This script relies on Miniconda which can not be silently installed under a path with spaces.

### ISSUE THREAD

**Issue by IamMidoZ** [C0untFloyd/roop-unleashed#424]
**Describing the bug**
When I click on "windows_run" I get this message:
"_This script relies on Miniconda which can not be silently installed under a path with spaces._"

**Details**
1. I am using **Windows 11**
2. I am using **NVIDIA**

I am using the latest version of Roop-Unleashed.

**NOTE:**
Yes, I tried to rename the path to be a path with no spaces at all and it still didn't work. I also reinstalled MiniConda but nothing was fixed.

**Comment by sumit-coder** [comment]
#### I was also getting the same issue, i just copy the C directory path like this in image and it worked, have a try may be it will work 

![Screenshot 2024-02-01 005323-2](https://github.com/C0untFloyd/roop-unleashed/assets/55745378/ddecdfcb-89cd-4197-bf33-553cdf7eeb19)
