### ISSUE TITLE
As previously reported - no faces to select in target faces window

### ISSUE THREAD

**Issue by mashoutsider** [C0untFloyd/roop-unleashed#426]
**Describe the bug**

**To Reproduce**
1. Add image (jpg) to target window.
2. Expect faces detected and option to select target face
3. If I instead set same image as source (rather than target), then I get expected behavior - face detected and able to select as source  

**Details**
- Linux, Nvidia GPU (provider = cuda)
- Have also set provider = cpu and restarted roop - same issue
- No multiple environments / instances of python running

**Which version of roop unleashed are you using?**
- Roop version 3.5.0
- Git clone repository
- Created conda env with python 3.10.6
- pip install requirements

**Comment by C0untFloyd** [comment]
To select target faces you have to click the 'Use face from this frame' Button.
https://github.com/C0untFloyd/roop-unleashed/wiki/Face-Management-Tab
