### ISSUE TITLE
Need help understanding what I'm doing wrong - No Facial Recognition

### ISSUE THREAD

**Issue by Wheart99** [C0untFloyd/roop-unleashed#431]
**Describe the bug**
Attempted to get this running today and have been working all day; I've installed CUDA, Visual Studio, C++, Git, FFmpeg, Python, PyTorch, pip, updated and patched things bit by bit, but no matter what I attempt to do, faces are not recognized, targetable, and do not show up in input or target. Nothing I seem to do fixes this issue. 

Image is to demonstrate what I'm seeing, visually. Unfortunately, this leads Roop to not see which faces to swap, and therefore does not... well, swap. I only see my "target" in the preview on the right, but it doesn't recognize any faces.

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X ] Windows 11
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?** 3.5.0

**Screenshots**
![roop error](https://github.com/C0untFloyd/roop-unleashed/assets/159370585/2cfcfd9b-439f-46ba-b851-632f62198aa7)

**Comment by Wheart99** [comment]
Also, switching from CUDA to CPU and forcing CPU for facial recognition does not seem to help or fix anything. Sorry for commenting immediately, I just thought it was prevalent.

**Comment by lysxelapsed** [comment]
for faces that are too close or missing a small part: try adding a border around it, enhances the chances of recognition.
