### ISSUE TITLE
Root Unleashed on Kaggle

### ISSUE THREAD

**Issue by John95674** [C0untFloyd/roop-unleashed#434]
**Describe the bug**
I have installed and run roop Gradio version on Kaggle and i runs up to a point.
I am unable to upload source or target files, they just hang.

**To Reproduce**
Run kaggle notebook and attempt to upload files/

**Details**
What OS are you using?
- [ ] Windows 

Are you using a GPU?
- [ ] No.

**Which version of roop unleashed are you using?**
[roop unleashed 3.5.0

**Screenshots**

**Comment by C0untFloyd** [comment]
I'm not using kaggle but found this video and notebook for it:
https://www.youtube.com/watch?v=R518EAqarX8
