### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

### ISSUE THREAD

**Issue by LaineDevWork** [C0untFloyd/roop-unleashed#435]
**Describe the bug**
After using the windows_run.bat, it says "Launching App", then this error shows up : urllib.error.HTTPError: HTTP Error 500: Internal Server Error

**Details**
What OS are you using?
- [x] Windows 

Are you using a GPU?
- [ ] NVIDIA

**Which version of roop unleashed are you using?**
lastest

**Screenshots**
![image](https://github.com/C0untFloyd/roop-unleashed/assets/159627130/c1ea0f88-ac9b-4449-a959-8df5310d0672)

**Comment by pathtanan** [comment]
how fix
