### ISSUE TITLE
Better masking using BiSeNet

### ISSUE THREAD

**Issue by Maxinger15** [C0untFloyd/roop-unleashed#436]
Hi,
I am using the bisenet masker in the deepfakes/faceswap software and it works really well with obstacles in the face like hair or hands.
Is there a way to implement this masker in roop?

Here is the repo where faceswap refers to in the code: [FaceParsing](https://github.com/zllrunning/face-parsing.PyTorch?tab=readme-ov-file)

Greetings

**Comment by C0untFloyd** [comment]
Some of the other roop derivates use this already and of course it's possible. But how are you using it for example when hands occlude the nose? And is it fast enough?

**Comment by sparking-meteor** [comment]
Would be nice at least having an alternative because the current masking engine is too bad
