### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by Angletonian** [C0untFloyd/roop-unleashed#439]
Launching App
Traceback (most recent call last):
  File "F:\ROOP\installer\roop-unleashed\run.py", line 3, in <module>
    from roop import core
  File "F:\ROOP\installer\roop-unleashed\roop\core.py", line 22, in <module>
    import roop.utilities as util
  File "F:\ROOP\installer\roop-unleashed\roop\utilities.py", line 202
    return 'mps'
TabError: inconsistent use of tabs and spaces in indentation

**Comment by AgitoRivers** [comment]
I can confirm this bug. Happened right after the update

**Comment by FranTesla** [comment]
a commit using tabs instead of spaces (as the rest of the file) in utilities.py was made
as workaround you can edit/change the tabs for spaces and the program will work again

**Comment by Deda2007** [comment]
How can I edit the tabs for spaces ?

**Comment by Deda2007** [comment]
> a commit using tabs instead of spaces (as the rest of the file) in utilities.py was made as workaround you can edit/change the tabs for spaces and the program will work again

I chaneged the tabs for spaces but it didn't work

**Comment by 14422** [comment]
Got mine fixed.

1. Copy everything from *\installer\roop-unleashed\roop\utilities.py into [https://www.browserling.com/tools/spaces-to-tabs](url)
2. "Space in one tab?" -> 4
3. Convert 
4. Paste everything back

**Comment by UltraCannstatt** [comment]
> Got mine fixed.
> 
>     1. Copy everything from *\installer\roop-unleashed\roop\utilities.py into https://www.browserling.com/tools/spaces-to-tabs
> 
>     2. "Space in one tab?" -> 4
> 
>     3. Convert
> 
>     4. Paste everything back

Worked perfectly well! Thanks mate! :)

**Comment by C0untFloyd** [comment]
Fixed now, thanks for the quick notice. Yes, I committed a small change via web browser instead of my usual ide and python is very pedantic about this.
