### ISSUE TITLE
Do not work with CPU in APP

### ISSUE THREAD

**Issue by gu021** [C0untFloyd/roop-unleashed#441]
**Describe the bug**
Do not work with CPU in APP.

**To Reproduce**
1. Go to 'roop unleashed' local web page.
2. click 'Settings'.
3. select CPU as Provider.
4. click 'Restart Server'
5. select 'Face Swap'
6. upload source and target files.
7. Click on 'Start'
8. Scroll down to 'Anaconda prompt window'
9. See following error:

To create a public link, set `share=True` in `launch()`.
Sorting videos/images
EP Error D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=-1161344600 ; hostname=GULAPTOP ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=236 ; expr=cudaSetDevice(info_.device_id);

 when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
Traceback (most recent call last):
  File "C:\Download\roopCode\installer\installer_files\env\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Download\roopCode\installer\installer_files\env\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 463, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=-1161344600 ; hostname=GULAPTOP ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=236 ; expr=cudaSetDevice(info_.device_id);

**Question**
There is no such folder in D drive at all: 'D:\a\_work\1\s\onnxruntime'.

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 10
- [ ] Mac

Are you using a GPU?
- [x] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
[roop unleashed 3.5.1] (https://github.com/C0untFloyd/roop-unleashed)

**Screenshots**
![2024-02-14 15_14_01-](https://github.com/C0untFloyd/roop-unleashed/assets/59003911/250a7118-0506-4107-8baa-9908730a1d32)

**Comment by tff2011** [comment]
Same problem here.

**Comment by C0untFloyd** [comment]
You need to save your settings before restarting (apply) and it seems you need to update your nvidia drivers to a more recent version.

**Comment by KRapil** [comment]
same problem i am facing

**Comment by KRapil** [comment]
RuntimeError: D:\a_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=-1161344600 ; hostname=GULAPTOP ; file=D:\a_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=236 ; expr=cudaSetDevice(info.device_id);
while roop-unleashed run on computer and click to start button

**Comment by C0untFloyd** [comment]
Either your nvidia drivers aren't up to date or your laptop gpu is too weak.

**Comment by KRapil** [comment]
I am using i7 12th gen

**Comment by KRapil** [comment]
i have nvidia geforce gt 730 GPU

**Comment by C0untFloyd** [comment]
It won't work with that GPU (2 Gb VRAM, you're very brave to even try 🤣 ). Switch to CPU in the settings, face swapping will then take forever however.

**Comment by KRapil** [comment]
🤣 🤣 ru
