### ISSUE TITLE
miniconda hook not found

### ISSUE THREAD

**Issue by Squityjoe420** [C0untFloyd/roop-unleashed#446]
**Describe the bug**

**To Reproduce**
1. Go to 'installer'
2. Click on 'windows_run'

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ x

] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**

**Screenshots**
![image_2024-02-17_234117329](https://github.com/C0untFloyd/roop-unleashed/assets/160374891/3ec77806-cc36-45c2-bc02-eab3c4f32082)

**Comment by C0untFloyd** [comment]
Did you install into a path with spaces or lack the user rights for a folder? For testing you could try as simple a path as possible...

**Comment by Dcode1999** [comment]
"I, too, am encountering the same issue."

**Comment by C0untFloyd** [comment]
My question is also still valid. Did you unpack/install into a very long path? Try keeping it simple.

**Comment by Dcode1999** [comment]
I still encounter issues with the following system specifications: Windows 11, 16 GB of RAM, and RTX 2060 GPU. I have attached a screenshot for you to review.
![Screenshot 2024-09-27 151203](https://github.com/user-attachments/assets/1566292d-f4cc-4928-898d-46f26988a0f9)

**Comment by C0untFloyd** [comment]
I found [this](https://community.anaconda.cloud/t/from-conda-cli-import-main-modulenotfounderror-no-module-named-conda/62149)
I suggest doing as proposed here, trying to delete the existing files and installing again. It is likely some files were corrupted during your first download.

**Comment by Dcode1999** [comment]
@rem activate installer env
    call "%CONDA_ROOT_PREFIX%\condabin\conda.bat" activate "%INSTALL_ENV_DIR%" || ( echo. && echo ERROR: Miniconda hook not found. && goto end )



I was reviewing the .bat file, and I came across a particular line that's generating the mentioned error.
