### ISSUE TITLE
Switch to chain-img-processor plugins

### ISSUE THREAD

**Issue by janvarev** [C0untFloyd/roop-unleashed#45]
There are a lib here: https://github.com/janvarev/chain-img-processor that allow write and share img processing plugins in standart way with customizable options for each.

It's already used in https://github.com/RichardErkhov/Richard-roop fork - with plugins for codeformer, gfpgan, etc.

It also has effective way to process video in-memory, without stages "split-to-images", "assemble-back"

Imho it'll be cool to swap processing to use this lib.

**Comment by C0untFloyd** [comment]
Yes nice lib you got there 😏 
I'm currently in the process of porting to another UI Framework and have a lot of bug fixing/cleanup to do. After that there will hopefully be time to redo the workflow and chaining in a modular way is very much needed, yes.
