### ISSUE TITLE
Unsupported device type: mkl

### ISSUE THREAD

**Issue by deponija** [C0untFloyd/roop-unleashed#451]
When trying to use openvino execution provider I get the following exception:
>   File "/home/wsl/roop/venv/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 32, in get_ort_device_type
    raise Exception("Unsupported device type: " + device_type)
Exception: Unsupported device type: mkl

CPU execution provider works without any problems.

I have followed the installation instructions from the wiki and it was completed 100% without any reported issues.

**Details**
What OS are you using?
- [x] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [x] Intel
- [ ] Mac

roop unleashed v3.5.0
Ubuntu 22.04 on Intel Core i5 1350P (with integrated Iris Xe GPU)

Thanks in advance!

**Comment by C0untFloyd** [comment]
Please update to the latest source, in the previous wrong torch devices were used.

**Comment by deponija** [comment]
Thank you very much for the response.
You probably meant to update to the latest version of the main branch.

I've just realized that I've mistakenly mentioned that the issue is encountered on version 3.5.0. It is actually on version 3.5.1 (installed it fresh couple of days ago).

**Comment by C0untFloyd** [comment]
Oh ok I see. You are probably missing the OpenVino Installation itself from here:
https://docs.openvino.ai/2023.3/openvino_docs_install_guides_overview.html

This is missing in the installation wiki, I need to add this.
There is also an old issue about OpenVino here #108 
Hope this helps...

**Comment by chris9-0** [comment]
I'm facing the same problem, but the strange thing is that yesterday everything worked fine. Today I restarted Roop and get this unknown device mkl error. Any help will be appreciated.

**Comment by GrannyWolve** [comment]
I already installed openvino, it still not working.
![mkl](https://github.com/C0untFloyd/roop-unleashed/assets/108083701/277e44ee-010f-4a18-8ed0-3ec17acad226)
![openvino](https://github.com/C0untFloyd/roop-unleashed/assets/108083701/8b2fe8d6-c6aa-47c2-a2fa-e33a08928833)
