### ISSUE TITLE
Video compression too high?

### ISSUE THREAD

**Issue by lost-in-emotions** [C0untFloyd/roop-unleashed#454]
Hi, 
i have a .mp4 video of a 3min music clip that is about **120MB**.
if I use FaceSwap the final rendered video is only **50MB** ?! 

The slider with the compression (standard 14) does not seem to work. 
No matter whether I do 4 or 40, the file size remains exactly the same.

I use h264 codec because libx264 compresses the video to **15MB** o.O

Where can I set it to stay at about the same quality or is this an issue?

thx4help

**Comment by lysxelapsed** [comment]
#463
