### ISSUE TITLE
Radeon RX470 XFX 4GB compatibility

### ISSUE THREAD

**Issue by brunoaduarte** [C0untFloyd/roop-unleashed#455]
Hi, is it possible to run roop-unleashed with my Radeon RX470 XFX 4GB ?

If i set it to Cuda it throws an error message.

![image](https://github.com/C0untFloyd/roop-unleashed/assets/5354345/557c0c38-aade-4dd0-9ebd-5d3ada0b1fe0)

**Comment by lysxelapsed** [comment]
In short: No, your graphics card isn't suited or these kinds of tasks. You can forget using an enhancer with 4GB VRAM. Maybe, just maybe, it will work without an enhancer. Also cuda is for Nvidia graphics cards, you need to use DirectML for AMD cards -> See Wiki -> Installation. If you want to try getting it to work with your hardware, here's a whole thread about it -> #428, but in my opinion it's not worth it. I'd recommend an Nvidia card with 10GB+ VRAM for roop-unleashed.
