### ISSUE TITLE
D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=1167449144 ; hostname=LAPTOP-GURTBS7E ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=236 ; expr=cudaSetDevice(info_.device_id);

### ISSUE THREAD

**Issue by Yug36** [C0untFloyd/roop-unleashed#457]
D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=1167449144 ; hostname=LAPTOP-GURTBS7E ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=236 ; expr=cudaSetDevice(info_.device_id);

**To Reproduce**
i open web interface, add photo, add another target image then start and have this error

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [+] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [+] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
3.5.1

**Screenshots**
![image](https://github.com/C0untFloyd/roop-unleashed/assets/160840417/42a050b2-9ee3-4cb7-a481-e76357e57aed

**Comment by lysxelapsed** [comment]
Cuda provider is for Nvidia cards. You need to install and select openvino provider for intel cards. See Wiki -> Installation.

**Comment by Kerremict** [comment]
Do you know the provider for AMD?

**Comment by C0untFloyd** [comment]
If you're not even trying to read the installation wiki 🤷‍♂️

**Comment by jackripperrr1** [comment]
Hello. I already downloaded [cuda_11.8.0] version and it still not working. Can anyone help me?
