### ISSUE TITLE
FileNotFoundError: 'roop-unleashed'

### ISSUE THREAD

**Issue by Amirbtz** [C0untFloyd/roop-unleashed#458]
Cloning into 'roop-unleashed'...
remote: Enumerating objects: 2585, done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 1601 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "D:\roop-unleashed-main\installer\installer.py", line 74, in <module>
    install_dependencies()
  File "D:\roop-unleashed-main\installer\installer.py", line 37, in install_dependencies
    update_dependencies()
  File "D:\roop-unleashed-main\installer\installer.py", line 43, in update_dependencies
    os.chdir(MY_PATH)
**FileNotFoundError: [WinError 2] The system cannot find the file specified: 'roop-unleashed'**

Done!
Press any key to continue . . .

**Comment by krabouilleur** [comment]
Same issue today, yesterday all worked (I've update, maybe the problem)

**Comment by SkylerLB** [comment]
install git from https://git-scm.com/download/win
Check everything in the installer.
Open git bash in the installer folder
type
 git clone https://github.com/C0untFloyd/roop-unleashed.git --depth 1

**Comment by mccalltristan** [comment]
same

**Comment by etruscanmuffin909** [comment]
Also having this issue on videos only

**Comment by Susi99** [comment]
> install git from https://git-scm.com/download/win Check everything in the installer Open git bash in the installer folder type git clone https://github.com/C0untFloyd/roop-unleashed.git --depth 1

worked for me ty
