### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by esdras616** [C0untFloyd/roop-unleashed#465]
When I start this error appears:

error
D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=-2011338632 ; hostname=DESKTOP-F9GHF2T ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=236 ; expr=cudaSetDevice(info_.device_id); 

I am using cuda 11.8.

**Comment by lysxelapsed** [comment]
hard to tell with the lack of information. everything installed according to wiki? system specs? graphics card?
on the toop of my head I'd say re-install cuda and don't update the graphics card driver, use the one that comes with it.
