### ISSUE TITLE
selected face 

### ISSUE THREAD

**Issue by zachysaur** [C0untFloyd/roop-unleashed#468]
when i use selected face option it just freeze

**Comment by lysxelapsed** [comment]
the questions when opening a new issue are there for a reason, just saying...
- when you SELECT the option or when you START with selected face?
- what freezes? your browser? the terminal window?
- is there an error message in the terminal window? post it.
- what are your system specs? what graphics card?

**Comment by zachysaur** [comment]
no within gradio  like it dont load or anything no matter you  try to stop process but when its first found face it work fine

**Comment by C0untFloyd** [comment]
Looking at your other non-issue #467 I assume you installed the latest gradio instead of the one from the requirements -> v3.44.2
The newest gradio version has code-breaking stuff in it and won't work with the current version of roop unleashed.

**Comment by zachysaur** [comment]
i rolled back to older version still same issue

**Comment by zachysaur** [comment]
even using this on google collab giving same issue

**Comment by lysxelapsed** [comment]
the only times it every froze (as in doesn't handle new inputs anymore) was when... 
- trying to do a new action before the last one is finished. clicking on use face from this frame and immediately load a source face, before loading the model and recognizing the target face is finished face for example
- switching too often between multiple loaded videos (to find a suitable frame for target face)

but again, hard to tell without terminal output or anything....

**Comment by lysxelapsed** [comment]
just saw the comment on the latest commit, it could be related to that - I'm not updating to a new commit for at least a few days, learned my lesson 😆):
https://github.com/C0untFloyd/roop-unleashed/commit/3f30269cef4b5f0001e9ba183d91907c61be3fca

The I'm on 3.5.0 from 8. Jan., works fine for me. You can try reverting to that with "git reset --hard edff845" after activating the environment.
