### ISSUE TITLE
Face Enhancer runs even when None is selected

### ISSUE THREAD

**Issue by Siraj-HM** [C0untFloyd/roop-unleashed#47]
**Describe the bug**
In the face enhancement option, when "None" is selected, the enhancement process still runs even though nothing is selected.

**To Reproduce**
1. Select the source image and target video
2. Click on None in face enhancement
3. Do a test run
4. We can check the cmd prompt windows for the process to start once face swapping is complete.

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you trying to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**
https://imgur.com/a/2LkZgdX

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by Orchoidizer** [comment]
I have noticed this as well. It's confusing. What actually IS happening as this runs?

**Comment by lysxelapsed** [comment]
Working method until solved: Select one of the enhancers, then go back to none.

**Comment by Martyprod** [comment]
on my side, it's running the face enhancer part, but doesn't apply it. so it's time lost. i'll try the "working method", thanks.

**Comment by Bonifes07** [comment]
Removing this "--frame-processor face_swapper face_enhancer " from the COMMANDLINE_ARGS did the job for me.

**Comment by eniora** [comment]
I came here to report this, if you however after running roop just select None manually or select any other enhancer and then select None then the enhancer doesn't run as it's supposed to. And yes when the enhancer is running automatically after running roop while it's on None it only takes the time to enhance (in the console) but then the output video won't be enhanced.

@Bonifes07 that doesn't work on unleashed 2.0.3, tried already.

**Comment by eniora** [comment]
@gokhanmeteerturk this worked thanks.
