### ISSUE TITLE
Faceswap only using first face

### ISSUE THREAD

**Issue by ali-m-github** [C0untFloyd/roop-unleashed#470]
**Describe the bug**
When I upload like 5 photos(faces) under the source tab the faceswap option only uses the first face for the swap and does not change when I click on the other faces. Program was working fine 2 days ago so not sure what is the problem.

**Details**
What OS are you using?

-Win 10 Pro

Are you using a GPU?
-RTX 3090

**Which version of roop unleashed are you using?**
3.5.1

**Comment by C0untFloyd** [comment]
Bug will be fixed this weekend.

**Comment by ali-m-github** [comment]
> Bug will be fixed this weekend.

Thank you :) Appreciate your efforts!
