### ISSUE TITLE
selected face

### ISSUE THREAD

**Issue by zachysaur** [C0untFloyd/roop-unleashed#472]
selected face not fixed yet

**Comment by Didier-Eloy** [comment]
Hello

I loaded the update this morning and it works.

**Comment by zachysaur** [comment]
no its not fixed yet now you can use ctrl+c on anaconda to start over but ui stil feeze no matter you move anything like similarity bar everything stay same

**Comment by C0untFloyd** [comment]
Can you explain the problem? While face swapping, you can't do anything with the UI.

**Comment by zachysaur** [comment]
![2024-03-03_06h30_40](https://github.com/C0untFloyd/roop-unleashed/assets/124980322/5f8e4a22-cee6-4682-a76a-669df8d02374)
![2024-03-03_06h31_11](https://github.com/C0untFloyd/roop-unleashed/assets/124980322/3d5c9112-4a69-4d1d-bb36-a347f274c0d1)

**Comment by zachysaur** [comment]
![2024-03-03_06h30_15](https://github.com/C0untFloyd/roop-unleashed/assets/124980322/d2297ff1-4378-4f56-9a46-a0dfe224c5dd)

**Comment by zachysaur** [comment]
everything just stuck here

**Comment by lysxelapsed** [comment]
can you post your cmd window output?

**Comment by C0untFloyd** [comment]
The upper half with the versions would be helpful too. It doesn't freeze when using the other modes like 'First found'?

**Comment by zachysaur** [comment]
no it work fine only when i use selected face

**Comment by C0untFloyd** [comment]
> can you post your cmd window output?
> The upper half with the versions would be helpful too.

**Comment by zachysaur** [comment]
i just give up since selected face didnt worked
