### ISSUE TITLE
After replacing the face in version 3.5.2, there are boxes around it,

### ISSUE THREAD

**Issue by zhangjinyan888** [C0untFloyd/roop-unleashed#473]
After replacing the face in version 3.5.2, there are boxes around it, and it is obvious that version 3.5.0 is normal

**Comment by C0untFloyd** [comment]
With or without face enhancer? Nothing's changed since 3.5.0.

**Comment by zachysaur** [comment]
where is 3.5.2

**Comment by C0untFloyd** [comment]
You guys crack me up 😆
