### ISSUE TITLE
Multiple Faces

### ISSUE THREAD

**Issue by ali-m-github** [C0untFloyd/roop-unleashed#474]
Hello,
I am having an issue swapping multiple faces in the target image.
Steps I do:

I choose "selected face"
I upload few pics to the source
Upload a target image that contains two faces(2 females)
Click on "use face from this frame"
I select the face on the right and click "use selected face"
I choose a face from source then click on swap frames and the face on left gets swapped instead of one on the right.
I am not sure if I am doing something wrong so any help would be appreciated!

**Comment by C0untFloyd** [comment]
If you specify the faces to be swapped the mode in the combobox should be set to "Selected face". Take a look into the wiki https://github.com/C0untFloyd/roop-unleashed/wiki/Face-Swap-Tab#face-swapping-parameters-enhancement-options-and-masking

**Comment by ali-m-github** [comment]
I already did that as I mentioned in my post but it still won't change the second face, only the first.

**Comment by lysxelapsed** [comment]
Your sequence seems a bit odd to me. Try it this way:
1. Load a target picture / video. If video, find a suitable frame for face detection.
2. Click "Use face from this frame", wait for detection, select the right face, click "Use selected face" and "Done"
3. Upload 1 source face. I never upload more than 1 source face, if there's only 1 face to swap. To change to source face, use "clear all" and upload another. Comparison works better anyway with the saving the previews (upper right corner of the preview window)
4. (optional) Choose your settings like similarity threshold, enhancer. 
5. Click "Face swap frames"
If you're following this order, you shouldn't have to select "Selected face" at all. It will do that automatically at point 2 or 3.

**Comment by ali-m-github** [comment]
> The sequence seems a bit odd to me. Yeah, it's like that in the wiki. Try it this way anyway, never fails me:
> 
> 1. Load a target picture / video. If video, find a suitable frame for face detection.
> 2. Click "Use face from this frame", wait for detection, select the right face, click "Use selected face" and "Done"
> 3. Upload 1 source face. I never upload more than 1 source face, if there's only 1 face to swap. To change to source face, use "clear all" and upload another. Comparison works better anyway with saving the previews (upper right corner of the preview window)
> 4. (optional) Choose your settings like similarity threshold, enhancer.
> 5. Click "Face swap frames"
>    If you're following this order, you shouldn't have to select "Selected face" at all. It will do that automatically at point 2 or 3.

Thanks for your suggestion! Unfortunately it did not work. It still swaps the opposite face and if I pick the other face it still changes the first one.

**Comment by C0untFloyd** [comment]
>  if I pick the other face it still changes the first one.

What do you exactly mean by "picking"? If you deleted the previously selected face, chose the other one and have the swapping mode on selected face, there is absolutely no chance it will swap the other one. There has to be some small user error but I can't put my finger on it so far.

**Comment by ali-m-github** [comment]
> > if I pick the other face it still changes the first one.
> 
> What do you exactly mean by "picking"? If you deleted the previously selected face, chose the other one and have the swapping mode on selected face, there is absolutely no chance it will swap the other one. Are you perhaps thinking you can select the target face in the target gallery? This is not the case! Let's say you have 2 faces (S1,S2) you want to put on 2 target faces (T1,T2). Then the order how they were picked specifies the swapping order, meaning S1 will be swapped onto T1, S2 onto T2 etc. If you have 1 face S1 but picked 2 target faces T1,T2 then always the first (T1) will be used. Is this your problem?

Changed "Select face selection for swapping" to "selected"
Added 2 source faces
Added a target photo with 2 faces
Clicked on use face from this frame
It gives me 2 faces
The first selected face is selected by default, I click use selected face then done
The selected face shows up in the target face box
I click on the first source face
click swap frames
It swaps the face
Then I Click on use face from this frame again
Pick the second face > use selected face > done
I select the face in the target box , select the second source face, refresh then the first target face gets replaced with the second source face instead of T2 being replaced with S2.

**Comment by deepraj31** [comment]
![Screenshot_13-4-2024_201445_127 0 0 1](https://github.com/C0untFloyd/roop-unleashed/assets/71033285/244ca9ae-95a6-4234-991f-97952d78587a)

Can anyone tell me why its not swapping the selected target face

> > > if I pick the other face it still changes the first one.
> > 
> > 
> > What do you exactly mean by "picking"? If you deleted the previously selected face, chose the other one and have the swapping mode on selected face, there is absolutely no chance it will swap the other one. Are you perhaps thinking you can select the target face in the target gallery? This is not the case! Let's say you have 2 faces (S1,S2) you want to put on 2 target faces (T1,T2). Then the order how they were picked specifies the swapping order, meaning S1 will be swapped onto T1, S2 onto T2 etc. If you have 1 face S1 but picked 2 target faces T1,T2 then always the first (T1) will be used. Is this your problem?
> 
> Changed "Select face selection for swapping" to "selected" Added 2 source faces Added a target photo with 2 faces Clicked on use face from this frame It gives me 2 faces The first selected face is selected by default, I click use selected face then done The selected face shows up in the target face box I click on the first source face click swap frames It swaps the face Then I Click on use face from this frame again Pick the second face > use selected face > done I select the face in the target box , select the second source face, refresh then the first target face gets replaced with the second source face instead of T2 being replaced with S2.

**Comment by deepraj31** [comment]
![Screenshot_13-4-2024_201445_127 0 0 1](https://github.com/C0untFloyd/roop-unleashed/assets/71033285/57a3db92-b31f-4bc0-908a-b5c73ff6cb2d)
Can someone tell me why the face I selected for swapping isn't swapping, and instead another face is swapping?

**Comment by lysxelapsed** [comment]
Because of your face similarity threshold. 0 means the face has to be the exact same to get swapped, 1 means that even a totally different face gets swapped. The frame gets analyzed from left to right. The person you want to swap is on the right. But because the threshold is set to 1, it swaps the first (left) face. The default max face similarity threshold value is ok for most cases.
