### ISSUE TITLE
A few Restoreformer ++ issues 

### ISSUE THREAD

**Issue by ozmix** [C0untFloyd/roop-unleashed#475]
**Describe the bug**

Using Restoreformer ++ causes box artifacting and it is being misplaced/aligned the face of either images or videos. FYI the faces set used was the same images used they should all be aligned and match up.

Restoreformer++ is definitely one of the best post-processing models, it would be a shame to see it go to waste.

Furthermore, in some cases when rendering is completed it begins to render the same again. I do not know the steps as to why it happened twice. 

Another issue is it sometimes stops at 98%|██████████████████████▌| 45/46 and then completes the rendering as done with the no video complete.

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
**_- [✓] Windows_** 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
**_- [✓] NVIDIA_**
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of Roop Unleashed are you using?**
3.5.3

**Screenshots**

https://github.com/C0untFloyd/roop-unleashed/assets/88434082/23013ac4-439e-46f9-9fa2-9126ccd73b87

https://github.com/C0untFloyd/roop-unleashed/assets/88434082/f9bcf7d0-348d-4a9d-8e52-90306fba5e6d

![5_19-47-00](https://github.com/C0untFloyd/roop-unleashed/assets/88434082/3b217979-7f97-472e-b7ae-8f40bf94bf48)
![0_19-47-00](https://github.com/C0untFloyd/roop-unleashed/assets/88434082/c7154625-546a-42af-a99f-f6d973481119)
![1_19-47-00](https://github.com/C0untFloyd/roop-unleashed/assets/88434082/0c4d04b1-5529-4875-82e3-e033f4442306)
![2_19-47-00](https://github.com/C0untFloyd/roop-unleashed/assets/88434082/1ee67423-ec6c-4da0-82ad-07eda27a5855)
![3_19-47-00](https://github.com/C0untFloyd/roop-unleashed/assets/88434082/77c6cbb5-56f7-4f6a-b377-637477c00096)
![4_19-47-00](https://github.com/C0untFloyd/roop-unleashed/assets/88434082/84f5edcf-175c-4fe2-a04a-36cf2c47793c)

**Comment by C0untFloyd** [comment]
It might be that restoreformer doesn't like faces at angles. Looking into it.

**Comment by ozmix** [comment]
Hi there @C0untFloyd  here is the 2 second clip 

https://github.com/C0untFloyd/roop-unleashed/assets/88434082/863cbca8-759e-413f-91ba-1b4ad2d36a41

**Comment by C0untFloyd** [comment]
Thanks, as I assumed it's the angle while turning the head and it's no restoreformer issue but a general one. Take a look at e.g. frame 21. If you turned on face swapping, even without any enhancer this looks just plain wrong. The face swapping model can't cope well enough with faces where only half of the face is visible. The wrong dimensions are then just a lot more noticeable when using a face enhancer (and it doesn't matter which one). You can work around this (at least when it's such a quick and short motion) by using the 'Skip frame' action but generally I'm afraid for such edge cases you would still need pre-trained models like the ones Deepface Lab uses.

**Comment by lysxelapsed** [comment]
Sure it's the insightface model? I'm still on 3.5.0 (so can't test with ++) and it doesn't produce that heavy misalignment, at least not with no enhancer and restoreformer.
no enhancer:
https://github.com/C0untFloyd/roop-unleashed/assets/63816546/47230261-3370-4f00-afc4-50407a72eee8
restoreformer:
https://github.com/C0untFloyd/roop-unleashed/assets/63816546/86ca2fb9-aa53-44b2-8b9f-8398a6e12230

**Comment by C0untFloyd** [comment]
It won't happen when you're using selected faces with the similarity measure (at least not with the default of 0.65). Why? Because at those weird angles the face distance is too high and roop won't consider them as same person and won't do a swap.
