### ISSUE TITLE
ffmpeg cannot be downloaded and the installer aborts

### ISSUE THREAD

**Issue by Secretalim** [C0untFloyd/roop-unleashed#480]
*Info*: 
OS: Windows
roop-unleashed Version: 3.50

*Bug*:
ffmpeg cannot be downloaded and the installer aborts

*Screenshots*
(https://github.com/C0untFloyd/roop-unleashed/assets/112650850/ed42c449-458d-477c-a730-6e30d29b483c)

**Comment by C0untFloyd** [comment]
Either try again at a later time when the internet problems (you or github) disappeared or download/install it by yourself. The installer checks for presence of ffmpeg in the windows path and wouldn't download it again.
