### ISSUE TITLE
Colab?

### ISSUE THREAD

**Issue by Orchoidizer** [C0untFloyd/roop-unleashed#49]
I notice that the main roop repo has a colab implementation at:
https://colab.research.google.com/drive/1NG9AoH3QDtC7h97z1Yodmn_CiiGh8Y1T#scrollTo=nCKli1C-_EaO
Can this be used in some way to enable one for this fork.

**Comment by C0untFloyd** [comment]
Yes it's easy to create a Colab based on the original, however I currently lack the time to do it 🤷‍♂️
