### ISSUE TITLE
Getting File "/opt/conda/lib/python3.10/urllib/request.py", line 643, in http_error_default     raise HTTPError(req.full_url, code, msg, hdrs, fp) urllib.error.HTTPError: HTTP Error 404: Not Found error on Kaggle

### ISSUE THREAD

**Issue by sharmariya101998** [C0untFloyd/roop-unleashed#490]
While running roop-unleashed on kaggle, I am getting the below error

 File "/kaggle/working/roop-unleashed/roop/core.py", line 123, in pre_check
    util.conditional_download(download_directory_path, ['https://github.com/facefusion/facefusion-assets/releases/download/models/GPEN-BFR-512.onnx'])

File "/opt/conda/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

<img width="555" alt="image" src="https://github.com/C0untFloyd/roop-unleashed/assets/162943928/c1a2f19b-8748-4e12-be58-9efb64c7edfa">

**Comment by ai-tester731** [comment]
I am getting the same error when doing fresh installation.
![Screenshot](https://github.com/C0untFloyd/roop-unleashed/assets/152654707/f01de426-bb03-4789-b42e-1290e1b7ec15)

**Comment by C0untFloyd** [comment]
Fixed with https://github.com/C0untFloyd/roop-unleashed/commit/87943ad5413545db620921228bbcf73a6f9dab62
