### ISSUE TITLE
how??

### ISSUE THREAD

**Issue by zachysaur** [C0untFloyd/roop-unleashed#491]
**Describe the bug**

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**

**Screenshots**

**Comment by zachysaur** [comment]
how to set dark mode ?

**Comment by ai-tester731** [comment]
Run the software, go to Settings tab, select Theme, click Apply Settings, restart.

**Comment by alast0r** [comment]
That's the dark theme if you don't like it do your own :)

**Comment by femkegit** [comment]
Running on Windows 11.
But I tried all themes applied the settings and restarted the server.
But I do not get a dark mode (got for example write characters and steampunk underground) but no black 
Try to find theme_schema.json but couldn't find it.
A suggestion would be so nice for my eyes.
Thanks

**Comment by C0untFloyd** [comment]
The UI automatically chooses between light/dark mode by using your browser setting. Some themes don't support dark mode however.

**Comment by lysxelapsed** [comment]
I was also gonna suggest a different (dark) browser theme. Alternatively, there are "Dark Mode" extensions for almost every browser, which you can enable and disable with a single click. I always use them for bright sites at night.
