### ISSUE TITLE
Same face gets swapped on both target faces

### ISSUE THREAD

**Issue by lysxelapsed** [C0untFloyd/roop-unleashed#495]
This is somewhat strange, since nothing has changed in that process (I think at least):

I don't do a lot of multiple-face-swapping, it's usually just one. But doing two always worked for me. Sometimes it would swap to the wrong target face (analyzing from left to right, similarity threshold and all that, I know), but it never swapped the same face to both targets, as I've encountered with 3.5.3 and now 3.5.5. So I did a test with the same settings, same source and target files that worked fine in previous versions. Now it looks like this in a lot of frames:
![snapshot](https://github.com/C0untFloyd/roop-unleashed/assets/63816546/f41374dc-bc17-4f48-b461-ca2b185cb917)

Any idea what could cause this?

**Comment by C0untFloyd** [comment]
2 things might cause this:

- VR Mode
if this is enabled, roop won't stop after finding the first similar face but continue until it finds another within similarity distance.

- the input face selection index
if there is only 1 target face but multiple faces in the gallery of input faces then you can select which one to paste onto the target. Perhaps there is a bug and the index isn't reset back

If you want me to guess I would say it's likely a bug with the vr mode. Is it possible to upload that exact original frame above or another frame where this is always happening? Thanks!

**Comment by lysxelapsed** [comment]
I have my eyes on these two things too, could by either one of them.
VR Mode was not checked. Still haven't tried it out, shame on me 😶‍🌫️ Is it possible, that VR Mode is activated by default in the background? No idea how to check for that 🤷‍♂️ 

It should be reproducible with any 2-person swap. Did another quick test with a short cut from The 100:

https://github.com/C0untFloyd/roop-unleashed/assets/63816546/e42344be-6e0a-465b-b29e-6d7cbec16351

![The 100 Test mp4_snapshot_00 07 799](https://github.com/C0untFloyd/roop-unleashed/assets/63816546/7b31134a-49cc-48aa-a14d-252c7882a73b)
![The 100 Test mkv_snapshot_00 07 799](https://github.com/C0untFloyd/roop-unleashed/assets/63816546/053c65f7-6cf1-4855-a68d-c897234a58cd)

**Comment by C0untFloyd** [comment]
Too bad you uploaded the already swapped movie. You used an enhancer, which one was it? And did you by any chance try without a face enhancer?

**Comment by lysxelapsed** [comment]
Yeah forgot to mention: Used Codeformer at either standard blend ratio or 0.9 out of habit 😆 But I didn't touch the similarity threshold, that I'm sure of 😉 
And no, didn't try without enhancer, since I didn't think (and still don't 😋) that it's an enhancer issue.

Here's the "original" (had to tone it down a bit because of githubs 10mb-limit):

https://github.com/C0untFloyd/roop-unleashed/assets/63816546/fd4afa29-2100-4980-8f33-5363fd656cc9

**Comment by C0untFloyd** [comment]
I'm sorry, it just works at my place. Tried with both girls faces, with Codeformer and without and also with 2 and 3 threads. I did always use a fairly frontal face angle, could it be that? Wouldn't explain why it worked previously though. I don't know...perhaps try if 4 or 1 threads make a difference? There are 2 things very obvious in your wrongly pasted faces, they aren't even the correct angle for that face keypoints and they aren't smoothed into that area like the correct one (I assume you wanted to swap the girl on the right in your clip). This is very weird.

**Comment by lysxelapsed** [comment]
Ahh again I didn't make myself clear enough:
This only happens, when both targets are to swap, Input1 to Target1 and Input2 to Target2. From what I see in your screenshot, you're only swappping one at a time.

**Comment by C0untFloyd** [comment]
Ah alright I was hoping you could spot a difference in my screenshot. Ok I'll give it a go with 2x2 faces. There was a change recently with the input face index, let's see if that's the culprit.

**Comment by lysxelapsed** [comment]
You tipped me in the right direction, thank you!
It was the thread count. Read your second reply again and then it hit me: Codeformer gave me a distorted-square-result at 4 threads when benchmarking, that was one too many.
Reduced the thread count from 3 to 2, and here we go: Just 2 minor flickers at the beginning because of the distance.

https://github.com/C0untFloyd/roop-unleashed/assets/63816546/237cb2e5-ddc9-4e0c-9b83-bca55febddb1

Thanks again for helping me troubleshoot 😃
