### ISSUE TITLE
windows_bat.run error

### ISSUE THREAD

**Issue by spurci** [C0untFloyd/roop-unleashed#496]
**Describe the bug**
I'm opening the windows_run.bat and when it ask me to press "y" or "n", i tried both of them and always is the same result:

raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

What should i do in this situation?

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- ✓ Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- ✓ AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
The last one

**Screenshots**

**Comment by lysxelapsed** [comment]
Does nobody do a quick search or look at closed issues before opening a new one? geez....
#487 #492 #493 aaaaand - the answer to your question - -> #486

**Comment by C0untFloyd** [comment]
Man...I can hardly keep up with closing them all 😄
