### ISSUE TITLE
Connection errored out

### ISSUE THREAD

**Issue by spurci** [C0untFloyd/roop-unleashed#498]
**Describe the bug**

When I trying to start the process of face swapping this error appears: Connection errored out.

*To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ .] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [. ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
Last one

**Screenshots**
The error is just a window in top right of the screen saying: Connection errored out.

**Comment by C0untFloyd** [comment]
Could it be that your closing the commandline window after the Tab opens in the browser? If so, don't!
