### ISSUE TITLE
No Audio in Video

### ISSUE THREAD

**Issue by RFedz007989** [C0untFloyd/roop-unleashed#502]
Hello,

I installed the new version even I am not having audio for the final swapped result.

Thank You

**Comment by lysxelapsed** [comment]
Is skip audio maybe checked?
![Screenshot 2024-03-13 102943](https://github.com/C0untFloyd/roop-unleashed/assets/63816546/61a06222-e6c6-4b6e-a32f-06f5dcbe5b58)

**Comment by RFedz007989** [comment]
I have unchecked here.

**Comment by C0untFloyd** [comment]
Exotic audio codec, GIF Anim instead of video, muted audio? Didn't have that issue in almost 1 year. I very much doubt this is roop related.

**Comment by RFedz007989** [comment]
OK, as I thought must have been something wrong with installation, so I uninstalled & installed twice, but still it's the same Video with no audio. Will this be fixed,

**Comment by C0untFloyd** [comment]
Can't be fixed when you're the only one where it's happening and you dont show any output. Perhaps upload a short clip of it here if it's SFW. Other than that I wouldn't know how to help you.

**Comment by RFedz007989** [comment]
OK, as you said this issue is happening with nobody else then I feel I need to fix this myself.

**Comment by lysxelapsed** [comment]
I once swapped a target video three times, before I realized, that the target video itself had no audio 😆
What's the audio codec of the target file? You could try a re-encode with aac or mp3 audio and then try again.
