### ISSUE TITLE
Any way to restore gender detection?

### ISSUE THREAD

**Issue by Cohejh** [C0untFloyd/roop-unleashed#503]
Is there anyway to restore the gender detection module/settings?

**Comment by C0untFloyd** [comment]
You were too late for the public vote https://github.com/C0untFloyd/roop-unleashed/discussions/482
😏 
Personally it never worked good enough for me but I think I can revive it by dynamically loading the models when the gender option is chosen. I just need some time the upcoming weekend (won't promise though).

**Comment by Cohejh** [comment]
Ah, ok. I was surprised when I updated, and the option was missing.

**Comment by Cynicalmender34** [comment]
Yes, the gender detection option is a must have. 
Was very easy to swap without an hassle.

With the current update. It just swaps the male face too. 

Hoping for it to be included in the next update

**Comment by C0untFloyd** [comment]
You guys know that you can still swap all female faces in your art productions, don't you? Don't you?!?

**Comment by Cynicalmender34** [comment]
> You guys know that you can still swap all female faces in your art productions, don't you? Don't you?!?

Honestly, no.👀

Is it some option in roop itself, ?

**Comment by C0untFloyd** [comment]
I knew it 🤦‍♂️ 
Just use the selected faces option described in the wiki:
https://github.com/C0untFloyd/roop-unleashed/wiki/Face-Swap-Tab
You can select as many target faces as you want. You can also click on every image in your batch of images, select use face from this frame etc.
I agree this is tedious if you're swapping many different faces or group photos.

**Comment by lysxelapsed** [comment]
> You can also click on every image in your batch of images, select use face from this frame etc. I agree this is tedious if you're swapping many different faces or group photos.

I think that's the real issue they're having here. If the model recognizes correctly - I'm still surprised that it does for so many - you can put as many target files in as you want, and let roop-unleashed do the work. Instead of, lets say 10 target files, for which you have to find a suitable frame for face recognition for every face. That's (of course) a lot more time consuming.

**Comment by C0untFloyd** [comment]
It's back, closing issue.

**Comment by Cohejh** [comment]
Thank you very much!
