### ISSUE TITLE
CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by fdefake** [C0untFloyd/roop-unleashed#506]
**Describe the bug**
I get the error "CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device" when I try to analize a face using GPU, so I changed to CPU. It analized the face correctly, but when I got to the swaping phase it gave me the error though I was using CPU. 

**To Reproduce**
1. Install from Windows Installer bat.
2. Run the program.
3. Analize a face, either by using CPU or GPU. 
4. Start the swaping process, if it hasn't give you the error yet. 

**Details**
- [x] Windows 

Are you using a GPU?
- [x] NVIDIA

**Which version of roop unleashed are you using?**
3.5.5

**Comment by fdefake** [comment]
Also, my GPU is NVIDIA GeForce MX130 with a 551.76 driver version. Please help!

**Comment by zhangjinyan888** [comment]
Change to a new graphics card, your graphics card doesn't support it

**Comment by C0untFloyd** [comment]
Did you do 'Apply settings' and restart the whole app after switching to CPU?
Everything else:
https://github.com/C0untFloyd/roop-unleashed/discussions/489
