### ISSUE TITLE
gpu not in use while face swap 

### ISSUE THREAD

**Issue by ShashwatDubey99** [C0untFloyd/roop-unleashed#507]
![image](https://github.com/C0untFloyd/roop-unleashed/assets/90603919/01ad89e1-cae8-4848-b26e-19bbb9a1980f)
![image](https://github.com/C0untFloyd/roop-unleashed/assets/90603919/880e5f3b-5722-4901-bd9f-62bd65f6eed7)

**Comment by C0untFloyd** [comment]
This looks like a homebrew colab version which misses some stuff (did you create it?). Try the official one:
https://colab.research.google.com/github/C0untFloyd/roop-unleashed/blob/main/roop-unleashed.ipynb

**Comment by ShashwatDubey99** [comment]
> This looks like a homebrew colab version which misses some stuff (did you create it?). Try the official one: https://colab.research.google.com/github/C0untFloyd/roop-unleashed/blob/main/roop-unleashed.ipynb

It fixed the problem was with the onnxruntime-gpu version  I forgot to close the issue
