### ISSUE TITLE
[FEATURE REQUEST] Add CLI support.

### ISSUE THREAD

**Issue by tikendraw** [C0untFloyd/roop-unleashed#513]
Add cli support for faceswap tab. adding the whole application in cli would be difficult, but basic swapping and enhancing can be option.

**Comment by C0untFloyd** [comment]
I removed CLI Support for a reason . If you want to have remote control you can do so by sending requests to the Gradio API.
As a last resort, use the old TKInter Branch which still has CLI Support.
