### ISSUE TITLE
CPU ulitization  V 3.6.0

### ISSUE THREAD

**Issue by fablox1** [C0untFloyd/roop-unleashed#514]
After update to v3.6.0 Roop is basically killing my CPU, almost all time is utilization on 100%
For example when I add input face (source files), it take long time to recognize.
When I add video sample (target files) file with size about 20mb and 435 frames , scrolling in frames is very slow and CPU utilization is again on 100% for long time and preview of image is very slow .

Version v3.5.5 was working very smooth and without above mentioned issues .

**Details**
What OS are you using?
- [ ] Windows 10

Are you using a GPU?
- [ ] NVIDIA 4070 TI SUPER 16
- [ ] Intel I7 11700KF

**Which version of roop unleashed are you using?  - v3.6.0

**Comment by C0untFloyd** [comment]
Change your execution provider to 'cuda' in the settings.

**Comment by C0untFloyd** [comment]
Yes very much possible, there are tons of issues with gradio > 3.44 but I would like to use it for the new controls. Thanks for investigating.
