### ISSUE TITLE
processed file window inactive

### ISSUE THREAD

**Issue by Kingkladzemcr** [C0untFloyd/roop-unleashed#515]
**Describe the bug**
processed file window inactive on colab/gradio interface. Processing can viewed on python cell on colab but progress not visible on gradio interface until action complete
![Screenshot 2024-03-19 09 21 08](https://github.com/C0untFloyd/roop-unleashed/assets/161225567/5950263f-35e8-4979-986d-fd5aab82930f)

**Comment by C0untFloyd** [comment]
Yes I know. Seems to be one of the bugs in the new gradio version, it's only flashing the color although my code for displaying progress is still active.

**Comment by KRapil** [comment]
same with me
