### ISSUE TITLE
Preview image div missing proper styles

### ISSUE THREAD

**Issue by HomAfromPTZ** [C0untFloyd/roop-unleashed#517]
The div with the ".image-container" class missing "height: 100%" property which causes preview image to be cropped (and "object-fit: contain" not take effect)

<img width="1547" alt="Screenshot_1" src="https://github.com/C0untFloyd/roop-unleashed/assets/9579310/89132fed-62ef-4969-8834-6fbd59c9ce89">

With the proper styling:
<img width="1523" alt="Screenshot_2" src="https://github.com/C0untFloyd/roop-unleashed/assets/9579310/59a019f1-def2-4f65-90da-87102e755f4c">

**Comment by C0untFloyd** [comment]
Thank you, I've created an issue @ gradio https://github.com/gradio-app/gradio/issues/7748

**Comment by C0untFloyd** [comment]
I worked around this issue with additional css https://github.com/C0untFloyd/roop-unleashed/commit/39fed869d43ddc08b054d848368380a6ad53b339
