### ISSUE TITLE
High CPU Usage on New Update

### ISSUE THREAD

**Issue by ali-m-github** [C0untFloyd/roop-unleashed#521]
Hello,
I have just updated to the latest version v3.6.0 and I am experiencing high CPU usage even when idle. Issue only happens on Chrome. Edge seems to be working fine.
It is also laggy on Chrome but very smooth on Edge.

**Comment by insanemafia** [comment]
yes, its laggy on brave also, but edge is smooth

**Comment by C0untFloyd** [comment]
This was previously reported in #514 
It's most probably an issue with the browser framework I'm using. I don't see anything unusual using Firefox...about to report it in the gradio repository.
