### ISSUE TITLE
BUG- NEW UPDATE: advanced settings and manual mask

### ISSUE THREAD

**Issue by insanemafia** [C0untFloyd/roop-unleashed#522]
1.  offset face bottom and offset face right are not working 
2. manual mask is also not working in new update ( maybe i can't make it work )

**Comment by insanemafia** [comment]
NORMAL
![Screenshot 2024-03-20 021718](https://github.com/C0untFloyd/roop-unleashed/assets/137728224/53e397cd-0f01-4b56-ae15-523cfc1ba8dd)

OUTPUT
![portrait-beautiful-face-young-woman-with-long-brown-hair-scaled_02-16-31](https://github.com/C0untFloyd/roop-unleashed/assets/137728224/d4f19d36-dbf5-437f-b117-14da4391e360)

TOP (working)
![Screenshot 2024-03-20 021912](https://github.com/C0untFloyd/roop-unleashed/assets/137728224/d530664a-d5a4-439e-a7eb-137c3e901332)

OUTPUT
![portrait-beautiful-face-young-woman-with-long-brown-hair-scaled_02-23-53](https://github.com/C0untFloyd/roop-unleashed/assets/137728224/8849a5b5-2dea-41e5-bd61-214323f9ebdb)

BOTTOM (not working)
![Screenshot 2024-03-20 021945](https://github.com/C0untFloyd/roop-unleashed/assets/137728224/e3a9e057-e7b7-4f16-8247-cdb83857904b)

OUTPUT
![portrait-beautiful-face-young-woman-with-long-brown-hair-scaled_02-22-02](https://github.com/C0untFloyd/roop-unleashed/assets/137728224/e6f1e981-a651-4c26-b891-e0e494ed73e3)

LEFT (working)
![Screenshot 2024-03-20 022549](https://github.com/C0untFloyd/roop-unleashed/assets/137728224/7273aa56-30a1-4695-92a6-43de0eee0824)

OUTPUT 
![portrait-beautiful-face-young-woman-with-long-brown-hair-scaled_02-19-50](https://github.com/C0untFloyd/roop-unleashed/assets/137728224/c99a3e32-3c70-45ee-a3c7-639494b2e02e)

RIGHT (not working)
![Screenshot 2024-03-20 022724](https://github.com/C0untFloyd/roop-unleashed/assets/137728224/45be588d-3358-40a4-84f5-ec49c947bfc5)

OUTPUT
![portrait-beautiful-face-young-woman-with-long-brown-hair-scaled_02-27-28](https://github.com/C0untFloyd/roop-unleashed/assets/137728224/afd1d6e7-342f-4f8a-b483-49b75682c655)

**Comment by C0untFloyd** [comment]
I'll take a look into the offset issue. For a quick manual masking example please see here:
https://github.com/C0untFloyd/roop-unleashed/discussions/512#discussioncomment-8839184

**Comment by C0untFloyd** [comment]
Should be fixed https://github.com/C0untFloyd/roop-unleashed/commit/39fed869d43ddc08b054d848368380a6ad53b339
