### ISSUE TITLE
I'm using a Rx7900xt from AMD i can't use Cuda and when i switch to cpu it still try to use Cuda

### ISSUE THREAD

**Issue by Kerremict** [C0untFloyd/roop-unleashed#524]
Error
D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=670512248 ; hostname=GAMINGPC ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=236 ; expr=cudaSetDevice(info_.device_id);

**Comment by C0untFloyd** [comment]
https://github.com/C0untFloyd/roop-unleashed/wiki/Installation
