### ISSUE TITLE
Live Cam not working on Colab

### ISSUE THREAD

**Issue by axelblaze88** [C0untFloyd/roop-unleashed#526]
![roop-unleashed](https://github.com/C0untFloyd/roop-unleashed/assets/56967210/d24326f8-09e9-4cd4-b701-645c81fe2620)

I always receive this error:
Starting capture
Cannot open camera

I have tried everything, with both the integrated camera of my computer and with OBS. The browser never asks me if I want to allow camera permissions. Even if I provide them manually, it does not work. I have tried with several different browsers too...

**Comment by C0untFloyd** [comment]
Let me think about this...
1. you're running the app in a colab
2. colab is a cloud service by google, computing stuff for you spread on different servers all over the world
3. you're connected by your browser to this colab
4. the webcam and obs run on your local pc

Is this correct so far? Do you see your error?
You would have to send your webcam to google and have them install obs for you to use. The webcam control I was using some versions ago streamed your local webcam to the server but this also blocked usage of the cam and was really, really slow. The OBS thing would never have worked in a colab, not even back then. You need to run this on the pc where the webcam is connected.

**Comment by kat3ri** [comment]
> Let me think about this...
> 
> 1. you're running the app in a colab
> 2. colab is a cloud service by google, computing stuff for you spread on different servers all over the world
> 3. you're connected by your browser to this colab
> 4. the webcam and obs run on your local pc
> 
> Is this correct so far? Do you see your error? You would have to send your webcam to google and have them install obs for you to use. The webcam control I was using some versions ago streamed your local webcam to the server but this also blocked usage of the cam and was really, really slow. The OBS thing would never have worked in a colab, not even back then. You need to run this on the pc where the webcam is connected.

So this isn't strictly true, I was able to modify the code to recognize my webcam via the browser in Gradio. However, I'm still getting the "Cannot Open Camera" error that the OP reported :)

![Image](https://github.com/user-attachments/assets/901b4a5c-f167-48ef-aabf-7c536f29558b)
![Image](https://github.com/user-attachments/assets/c74a0dc2-247a-4ad1-ba44-c0cebe57c487)
