### ISSUE TITLE
How to perform version upgrade

### ISSUE THREAD

**Issue by aiise117** [C0untFloyd/roop-unleashed#529]
I have installed 3.5.5. How should I run the automatic upgrade program?

**Comment by lysxelapsed** [comment]
[This](https://github.com/C0untFloyd/roop-unleashed/releases/download/3.6.3/roop-unleashed_win3.6.3_installer.zip) (unpack and run the "windows_run.bat" installer) will install the newest version, no need to update. You can just delete the folders from older installations.
The other two (source code) are for manual installation.

**Comment by aiise117** [comment]
<img width="867" alt="微信图片_20240321222734" src="https://github.com/C0untFloyd/roop-unleashed/assets/114309081/121ba9d6-b708-46cf-ba8b-507b5614860a">
I manually installed it in a virtual environment and encountered this PIP error. What should I do?

**Comment by lysxelapsed** [comment]
Never saw this error message to be honest. But others have: https://stackoverflow.com/questions/72297487/pip-install-error-cannot-set-home-and-prefix-together. You can try the solutions there or using the installer.

**Comment by thenewgold** [comment]
how can I downgrade from the latest version???
