### ISSUE TITLE
Sometimes fails to load target video

### ISSUE THREAD

**Issue by Orchoidizer** [C0untFloyd/roop-unleashed#53]
Not always but occasionally fails to import the target video.
Any suggestions what might be going wrong?

**Comment by kalabina** [comment]
Maybe is from video format. Convert to mp4 and try again.

**Comment by Orchoidizer** [comment]
Always .mp4 always same properties and yet some import some dont. Makes no sense.
Also, regular roop version doesn't have this problem

**Comment by xlgn** [comment]
Oddly enough when I feed it a roop-unleashed generated video file, it fails to import. Even when there's another face in the clip which hasn't been altered by roop previously.
