### ISSUE TITLE
Downgrade version

### ISSUE THREAD

**Issue by thenewgold** [C0untFloyd/roop-unleashed#530]
Hey, I installed the new version of roop 3.6.3...
But i'm facing issues with the output quality, I want to downgrade because it was working perfectly fine is there any way to do so? 
I reinstalled the 3.6.0 version but it updates it automatically.

Would appreciate any help 🙏

**Comment by insanemafia** [comment]
give some examples of the issues you are facing

**Comment by thenewgold** [comment]
> give some examples of the issues you are facing

So I have a weird use case where I use them on bad quality videos and It always worked perfectly with the face enhancement engine on "None", but on this new version the mask is really buggy it flickers a lot and you can see the outlines of the mask.

**Comment by lysxelapsed** [comment]
> So I have a weird use case where I use them on bad quality videos and It always worked perfectly with the face enhancement engine on "None", but on this new version the mask is really buggy it flickers a lot and you can see the outlines of the mask.

This _could_ be related to the thread count. Experienced this with 4 Threads (Codeformer, RTX3060 12GB), with 3 threads everything was fine. On a "2-targets-swap", I had to reduce to 2 threads to avoid flickering issues. Try lowering the thread count by one.
Doesn't the installer ask you first, if you want to update when installing an older version?

**Comment by Sevensleeper81** [comment]
![k](https://github.com/C0untFloyd/roop-unleashed/assets/89541210/a3f38087-2b21-44eb-8fd9-53a836a2537f)
Ha can I remove this frame? Thanks

**Comment by thenewgold** [comment]
> ![k](https://private-user-images.githubusercontent.com/89541210/315614883-a3f38087-2b21-44eb-8fd9-53a836a2537f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNTMwMzUsIm5iZiI6MTcxMTA1MjczNSwicGF0aCI6Ii84OTU0MTIxMC8zMTU2MTQ4ODMtYTNmMzgwODctMmIyMS00NGViLThmZDktNTNhODM2YTI1MzdmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDIwMjUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjNWI4MDJmYjBiMjg1MGE5Zjg0NzAwYjY3MzI2ZGM1NjhkN2I1NzIzZDUwZjc4ZGYyZWI3MjNkNzY5OWNhOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UuHsbZ3kscKStx-Ed22y1C9Q2zbVtKSJVbzULLtpDLI) Ha can I remove this frame? Thanks Last update 3.6.3

Yeah thats exactly what im experiencing too... And cutting the mask doesn't work good either...

**Comment by thenewgold** [comment]
> > So I have a weird use case where I use them on bad quality videos and It always worked perfectly with the face enhancement engine on "None", but on this new version the mask is really buggy it flickers a lot and you can see the outlines of the mask.
> 
> This _could_ be related to the thread count. Experienced this with 4 Threads (Codeformer, RTX3060 12GB), with 3 threads everything was fine. On a "2-targets-swap", I had to reduce to 2 threads to avoid flickering issues. Try lowering the thread count by one. Doesn't the installer ask you first, if you want to update when installing an older version?

Already tried lowering the threads sadly nothing worked... Found a old version ( 2.0.3 ) which I found in some old threads here... UI is worse than on the 3.6.0 but it works better

**Comment by Sevensleeper81** [comment]
If you lunch the bat file 3.6.0....press"n" you don't want update .....Is it update automatic?

**Comment by thenewgold** [comment]
> If you lunch the bat file 3.6.0....press"n" you don't want update .....Is it update automatic?

No I updated with "y", but then I got the bugs... Tried to deleted and install it again, but its on the latest version automatically

**Comment by Sevensleeper81** [comment]
3.6.0 version : https://github.com/C0untFloyd/roop-unleashed/releases/tag/3.6.0

**Comment by Sevensleeper81** [comment]
I will do the same! Delet and instal 3.6.0.....Wait the bug fix 3.6.4 :)

**Comment by insanemafia** [comment]
> I will do the same! Delet and install 3.6.0.....Wait the bug fix 3.6.4 :)

i tried it but it automatically updates to the latest version

**Comment by Sevensleeper81** [comment]
Fu....k

**Comment by C0untFloyd** [comment]
> > I will do the same! Delet and install 3.6.0.....Wait the bug fix 3.6.4 :)
> 
> i tried it but it automatically updates to the latest version

How so? You're seriously confused.

**Comment by thenewgold** [comment]
> > > I will do the same! Delet and install 3.6.0.....Wait the bug fix 3.6.4 :)
> > 
> > 
> > i tried it but it automatically updates to the latest version
> 
> How so? You're seriously confused.

Im also confused 😂 I download the [roop-unleashed_win3.6.0_installer.zip] run the "windows_run.bat" and it is automatically the 3.6.3 version

**Comment by C0untFloyd** [comment]
I'm sorry, I stand corrected! I'm confused too...this bug must have been in the installer for quite some time.

For a quick hotfix edit installer.py to have the install_dependencies method look like this:

```
def install_dependencies():
    global MY_PATH

    # Install Git and clone repo
    run_cmd("conda install -y -k git")
    run_cmd("git clone https://github.com/C0untFloyd/roop-unleashed.git")
    os.chdir(MY_PATH)
    run_cmd("git checkout 8e73d8ffcf9009ca68f33d8984206544e5dc3b8f")
    # Installs/Updates dependencies from all requirements.txt
    run_cmd("python -m pip install -r requirements.txt")
```

This will take you back to v3.5.5. I will re-upload the corrected installer files later this day.

**Comment by lysxelapsed** [comment]
Did a whole batch with 3.6.3 and I can confirm heavily increased visible frames. Doing the 100 video later so you'll have direct comparison @C0untFloyd

**Comment by C0untFloyd** [comment]
Thanks, no need to. I had a quick look into the paste method and indeed the whole eroding/blurring is missing. While I'm at it I should expose the blur amount in the UI too.

**Comment by C0untFloyd** [comment]
https://github.com/C0untFloyd/roop-unleashed/releases/tag/3.6.5
