### ISSUE TITLE
bug/downgrade in face offset

### ISSUE THREAD

**Issue by insanemafia** [C0untFloyd/roop-unleashed#531]
in previous version , when offset bottom on
![old](https://github.com/C0untFloyd/roop-unleashed/assets/137728224/f3a6ef88-246e-4031-8835-356469ef618c)

the offset is hardly visible in the small circles
![old 2](https://github.com/C0untFloyd/roop-unleashed/assets/137728224/e50b0e33-83dc-48f0-a2a0-1f1b1f873e76)

in the current version, when same offset bottom is on

![new](https://github.com/C0untFloyd/roop-unleashed/assets/137728224/3f5c9682-9156-412f-816b-2f416546024b)

the offset is clearly visible in the big elipses
![new 2](https://github.com/C0untFloyd/roop-unleashed/assets/137728224/5506e4f8-71be-400b-9fac-9457958c9f6f)

how do i revert back to previous version?

**Comment by thenewgold** [comment]
same issue here

**Comment by insanemafia** [comment]
i think this problem has occurred in the past (box issue)

**Comment by Sevensleeper81** [comment]
I think few day and we get update.....
Don't worry

**Comment by C0untFloyd** [comment]
> I think few day and we get update..... Don't worry

How on earth did you know?

https://github.com/C0untFloyd/roop-unleashed/releases/tag/3.6.5
