### ISSUE TITLE
 "process files" field - the  percentage treadmill is gone

### ISSUE THREAD

**Issue by GCown** [C0untFloyd/roop-unleashed#535]
In the "process files" field, a percentage treadmill was  visible in the previous version, now only the box lights up

- [ ] Windows 
- [ ] NVIDIA
roop unleashed 3.6.3
python: 3.10.13 • torch: 2.1.2+cu118 • gradio: 4.21.0 

![2024-03-22 07_35_31-roop unleashed 3 6 3 – Mozilla Firefox](https://github.com/C0untFloyd/roop-unleashed/assets/146350956/535bbf4a-b540-457a-87b5-bd541c823ce3)

**Comment by C0untFloyd** [comment]
#515
