### ISSUE TITLE
Darker color boxes around the bounds of people's faces when swapped

### ISSUE THREAD

**Issue by smashepotato** [C0untFloyd/roop-unleashed#536]
I updated from Jan 8th version to the latest version.

Big mistake on my part apparently. There are dark-colored boxes surrounding faces on every swap, no matter the model used.

Now I can't revert, because when replacing the files with an old commit ZIP, it comes up with an error "module gradio has no attribute Box"

.. not sure how to proceed. Very sad though, all the other faceswap desktop apps suck and are slow as balls compared to Roop Unleashed, basically unusable even with a 4070ti. Hope this issue gets fixed. 

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
latest 3.6.3

**Comment by C0untFloyd** [comment]
#531
