### ISSUE TITLE
Duplicate/Identical frames from source video are missed out when using "In Memory Processing" - but are preserved when doing "Extract Frames to media"

### ISSUE THREAD

**Issue by infinitygorkem** [C0untFloyd/roop-unleashed#537]
**Describe the bug**
A different number of frames generated and compiled into a video between the "In Memory Processing" and "Extract Frames to media" options.

In Memory Processing: Duplicate/identical frames that are preserved in the input video are removed from the final video.
Extract Frames to Media: Every single frame from the source is copied and swapped across even if there are duplicates.

This causes issues where editing the video (e.g to overlay it onto the source video using an alpha mask) does not work because there are some frames missing from the output video.

**Details**
What OS are you using?
- [X] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
3.6.5

I have installed ffmpeg 5.1.2 in the conda environment so I doubt this is an ffmpeg issue. But even in this case I don't know how to check what ffmpeg version roop-unleashed is using, in case this is an ffmpeg issue. Though opening a python shell in the conda environment and running "python -version" using a subprocess the same way as is done in Roop-unleashed, I see it is in fact using 5.1.2

**Comment by C0untFloyd** [comment]
Interesting. Well, In-Memory Processing uses OpenCV to extract frame after frame, the file based method uses ffmpeg. I'm no expert on video processing but I guess that ffmpeg is using the keypoints to interpolate between frames and OpenCV only extracts whatever it gets. I'm actually unsure how to cope with this. Couldn't you just use extract frames for both of the movie versions?

**Comment by infinitygorkem** [comment]
That is my workaround at the moment, as I don't need to do alpha-masking very often at all, so when I do, I'll use extract frames. I wondered if it was a simple change but alas I see now that they are two different mechanisms. I'm happy to close this issue but I will leave it open for you to close it, in case you want to leave it open to come back to...
