### ISSUE TITLE
Nothing works whenever I click.

### ISSUE THREAD

**Issue by wrldslife** [C0untFloyd/roop-unleashed#539]
**Describe the bug**
So, I installed roop unleashed with the one click installer, everything worked fine. However, as soon as the web page starts no features work at all. I will provide a video down below.

**To Reproduce**
1. Open windows_run.bat
2. Wait for everything to finalize.
3. Change some web features like disable auto load site & share.
4. Site loads then nothing works.

**Details**
What OS are you using?
- [x] Windows 10

Are you using a GPU?
- [x] NVIDIA Rtx 3080 CUDA

**Which version of roop unleashed are you using?**
Latest version

**Screenshots**
https://streamable.com/u7fs8o
![image](https://github.com/C0untFloyd/roop-unleashed/assets/69610079/eb98d420-6e67-4cbe-9697-fd2e2569d7ff)

**Comment by wrldslife** [comment]
![image](https://github.com/C0untFloyd/roop-unleashed/assets/69610079/f19b7d06-b848-45a8-b027-e147a90b0a85)
Repaired python and pip installed gradio now it says this.

**Comment by C0untFloyd** [comment]
Why did you turn on public share? And why did you start it twice? The video looks good to me don't know what your problem is exactly 🤷‍♂️

**Comment by wrldslife** [comment]
> Why did you turn on public share? And why did you start it twice? The video looks good to me don't know what your problem is exactly 🤷‍♂️

I turned on public share to show that local url & public url does not work for any of the features. My issue is that NONE of the buttons work. It might be a little hard to tell, but in the video, I'm trying to click on the buttons on both the local & public url which does not do anything.

**Comment by C0untFloyd** [comment]
Ok, did you turn on private mode or use any extensions which might interfere? Is your firewall blocking port 7860? Did you try other browsers? Never heard of that issue.

**Comment by wrldslife** [comment]
> Ok, did you turn on private mode or use any extensions which might interfere? Is your firewall blocking port 7860? Did you try other browsers? Never heard of that issue.

Thanks so much for the suggestions, it seems FireFox was the issue. I switched to google and everything works.

**Comment by C0untFloyd** [comment]
Weird, I'm using Firefox all the time. Must be some extension/add-on of yours.
