### ISSUE TITLE
Running really slow on colab

### ISSUE THREAD

**Issue by Kingkladzemcr** [C0untFloyd/roop-unleashed#540]
pulling below 3 frames per second on colab using T4. GPU ram below 9GB and  system on 5GB. Is this due to the previous Cuda issue and can processing speed be improved on colab?

**Comment by sparking-meteor** [comment]
Before executing a cell look for an option named "console" or "developer console" when it opens search 'use fallback' and click the first option then save, then execute the cells 
Note that you must do this every time you want to use it

**Comment by Kingkladzemcr** [comment]
sorry can't find that option on cells. What sort of frames per sec processing should I be seeing using T4 on colab?

**Comment by mhoangvslev** [comment]
I noted that not having the right cuda-toolkit version significantly slow down the the processing rate

**Comment by Kingkladzemcr** [comment]
> Before executing a cell look for an option named "console" or "developer console" (in Google colab , not browser console) when it opens search 'use fallback' and click the first option then save, then execute the cells Note that you must do this every time you want to use it

error saying "The fallback runtime version is unavailable at this time"

**Comment by Kingkladzemcr** [comment]
I think it is a problem that Google are creating. I have Colab pro subscription and running on T4. Lucky to max out of 4fps probably average 2fps. I've run similar today on paperspace using various rtx5000, p5000 & rtx 4000 combinations and getting anywhere between 7fps & 12fps. Google is throttling the hell out of it even on paid subscription.
Won't be using that again
