### ISSUE TITLE
OPENSSL_Applink Error

### ISSUE THREAD

**Issue by neoldev** [C0untFloyd/roop-unleashed#541]
**no OPENSSL_Applink error**
When i run the windows_run.bat file it creates the conda environment but then get a line of error code
`Retrieving notices: ...working... OPENSSL_Uplink(00007FFF423F9C88,08): no OPENSSL_Applink`

**To Reproduce**
1. Go to 'C:\Desktop\roop-unleashed-main\installer'
2. Click on 'windows_run.bat'
3. See error

**Details**
I am on a windows 10 pc that runs on a AMD 5 5600X and a NVIDIA GTX 1660 SUPER. And I have tried to reinstall roop-unleashed v3.6.5 two times now and still getting the same error.

![image](https://github.com/C0untFloyd/roop-unleashed/assets/95879772/e27ba229-d768-4212-92f3-a9500dbabf8c)

**Comment by C0untFloyd** [comment]
Did you follow https://github.com/C0untFloyd/roop-unleashed/wiki/Installation#installation and install Visual Studio? If yes...this is weird. I could google reports about this dating back from 2013. Perhaps try installing OpenSSL -> https://slproweb.com/products/Win32OpenSSL.html

**Comment by neoldev** [comment]
I have followed the installations and install both the c++ packages in visual studio. I too searched on it but didn't really get an solution going to try installing OpenSSL.

**Comment by C0untFloyd** [comment]
I'm sorry I don't know where this error originates. My only advice is installing the necessary stuff yourself. This would be git, then git clone the repo into a folder of your choice and python or a anaconda environment which comes with python. After that you need to install the requirements with pip install -r requirements.txt and then run it with python run.py. Good luck!
