### ISSUE TITLE
No masking

### ISSUE THREAD

**Issue by testujemai** [C0untFloyd/roop-unleashed#544]
There is no masking choice
![ewf](https://github.com/C0untFloyd/roop-unleashed/assets/164744062/dab17eb2-75b9-45c2-ba0a-829e977b7d08)
In previous version there was no problem. Is a bug on my site?

**Comment by lysxelapsed** [comment]
"Advanced Masking", below Input faces.

**Comment by C0untFloyd** [comment]
Yes, masking was grouped together and layout changed (for the better I hope).
