### ISSUE TITLE
Processing to video failed!

### ISSUE THREAD

**Issue by mccalltristan** [C0untFloyd/roop-unleashed#55]
**Describe the bug**
When trying to generate a video, with no options on, or any face enhancement engines enabled, the process immediately fails and reports "Processing to video failed!"

**To Reproduce**
1. Go to Roop GUI
2. Input image and video
3. Click Start
4. [ROOP.CORE] Creating temp resources...
[ROOP.CORE] Extracting frames...
[ROOP.CORE] ROOP.FACE-SWAPPER in progress...
Processing: |                                                                                 | 0/0 [00:00<?, ?frame/s]
[ROOP.CORE] Creating video with 30.0 fps...
[ROOP.CORE] Restoring audio might cause issues as fps are not kept...
[ROOP.CORE] Processing to video failed!

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [√ ] Windows 
- [ ] Mac

Are you try to use a GPU?
- [√ ] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [√ ] I have the latest code from the github repository
- [ √] I have followed the installation guide

**Comment by eniora** [comment]
Do you have ffmpeg properly installed? does it happen with all videos?
Anyway you could try with **--video-encoder libx265** or **--video-encoder libvpx-vp9** command line arguments and see if that helps.

**Comment by pwntUA** [comment]
I am also facing the same issue, when using any SFW video it is working fine but NSFW ones will give the error. Have already tired --video-encoder libx265 or --video-encoder libvpx-vp9 command line arguments but it doesn't solve the issue.

**Comment by C0untFloyd** [comment]
Closed all old issues because of new rewritten version.
