### ISSUE TITLE
Ngrok url bug (without ok-free.app)

### ISSUE THREAD

**Issue by testujemai** [C0untFloyd/roop-unleashed#550]
I'm using kaggle for roop unleashed. Everything worked perfectly, but last patch I had problem with kaggle. It is working but I can't see preview. If I open preview on new tab, the image is not opened. I noticed that url is wrong (see the screenshots). If I add ok-free.app to the url, everything works. Do you have solution for this so I don't need to open every time on new tab and write (ngr)ok-free.app? Thank you.

![111](https://github.com/C0untFloyd/roop-unleashed/assets/164744062/b2594463-a5ba-4e68-944e-323f90867a68)
![222](https://github.com/C0untFloyd/roop-unleashed/assets/164744062/c12770c4-00a0-4fbc-8786-b8d5e7ddb942)
![555](https://github.com/C0untFloyd/roop-unleashed/assets/164744062/f2105aa6-ad65-489b-bda3-99cbc11c8c73)
![333](https://github.com/C0untFloyd/roop-unleashed/assets/164744062/2de29a2f-71b6-48e3-b67f-09ef12223ec6)
![444](https://github.com/C0untFloyd/roop-unleashed/assets/164744062/62f99409-6da9-4081-b6db-615d1bd09596)

**Comment by sparking-meteor** [comment]
Yeah I also noticed this behaviour, fortunately I made a fork of the version before the things messed up, of course it has less features but it's usable

**Comment by C0untFloyd** [comment]
Upgrading to gradio 1.24.0 might have fixed the issue, see also #564

**Comment by zachysaur** [comment]
did selected face worked for you?

**Comment by sparking-meteor** [comment]
It works now, but there are some inconvenients i found:
1- After starting the processing it doesn't show up in the Ngrok page, you can only keep a track of the progress bar from Kaggle's console, and output files must be manually downloaded (they don't show up as result in Ngrok page like it used to do)
2- Manual masking doesn't seem to be working for some reason, yes i can paint the parts i want to mask but the end result is the same as if i was not using a mask at all... maybe I'm doing something wrong but i don't think so

**Comment by zachysaur** [comment]
no sadly selected face not working even if you choose other face it still swap first found face

**Comment by zachysaur** [comment]
![Uploading 2024-04-02_06h43_25.png…]()

**Comment by sparking-meteor** [comment]
Bump
