### ISSUE TITLE
Face swap to image works but not video.

### ISSUE THREAD

**Issue by Kaeez** [C0untFloyd/roop-unleashed#551]
**Describe the bug**
Face swapping to an image works but when I try the same with a video file, it just outputs the original video in the end without swapping the face. 

**Details**
What OS are you using?
- Windows

Are you using a GPU?
- NVIDIA

**Which version of roop unleashed are you using?**
-  3.6.5

**Comment by C0untFloyd** [comment]
Take a deep breath and try to remember what you did wrong. Did you install ffmpeg in first place? How about taking a look into the terminal output to see what's wrong? What about pasting the output here? So many questions, so little time.

**Comment by Kaeez** [comment]
It outputs the video file, shows no errors on the terminal, but the outputted video doesn’t have the face swapped. I had my threads cranked up all the way, I set it to the default and it seems to be working. Am I not supposed to tweak with the threads?

**Comment by Kaeez** [comment]
I’m running a GTX 1650 w/ 4 gigs. The processing time on default threads for a 1080p 20 sec video is like half an hour. Anything I can do to further streamline this other than playing with the threads which doesn’t seem to help in this case?

**Comment by lysxelapsed** [comment]
> Am I not supposed to tweak with the threads?

No. At least not upwards with a 4GB card. Use 1 thread with that card, maybe 2 (check your VRAM usage) with no enhancer. More on that in the [FAQ](https://github.com/C0untFloyd/roop-unleashed/wiki/FAQ), general usage is explained in the [Wiki ](https://github.com/C0untFloyd/roop-unleashed/wiki)too.

**Comment by anj2208** [comment]
> I’m running a GTX 1650 w/ 4 gigs. The processing time on default threads for a 1080p 20 sec video is like half an hour. Anything I can do to further streamline this other than playing with the threads which doesn’t seem to help in this case?

use only 1 or max w threads. use gpu z to check your card activity if its running full load with max vram usage and yet u r getting 10sec/frame. u need to lower your thread use. use of enhancer and mask does affect the card usage. i have 1 machine running 1660s, the best it can do is 4fps with enhancer no mask and 2 threads.
