### ISSUE TITLE
Install error.

### ISSUE THREAD

**Issue by donleo78** [C0untFloyd/roop-unleashed#553]
**Describe the bug**
Im getting this error during fresh instalation process.
-
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.57.1 requires numpy<1.25,>=1.21, but you have numpy 1.26.2 which is incompatible.
tensorflow-intel 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.26.2 which is incompatible.
-
It happens only when fresh install it, on PC. 
It works but slow, and after a little use it sends this message:
-
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "H:\roop-unleashed\roop-unleashed\installer\installer_files\env\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "H:\roop-unleashed\roop-unleashed\installer\installer_files\env\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto
-

Anyway, amazing work. Thanks!

**Comment by C0untFloyd** [comment]
https://github.com/C0untFloyd/roop-unleashed/discussions/525#discussioncomment-8865344

**Comment by donleo78** [comment]
Awesome, i see some changes when i run it today, it installed something, but i still get this error:
-
Downloading numpy-1.24.3-cp310-cp310-win_amd64.whl (14.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.8/14.8 MB 14.9 MB/s eta 0:00:00
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.2
    Uninstalling numpy-1.26.2:
      Successfully uninstalled numpy-1.26.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-intel 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.24.3 which is incompatible.
Successfully installed numpy-1.24.3
Launching App
-
Do i have to open a new thread? i just want to help you fix the errors, but i dont want to bother you.
Thanks!

**Comment by C0untFloyd** [comment]
No, I think this can be treated more or less like a warning. I don't think tensorflow-intel is used by me anywhere. And the app should be working, shouldn't it?

**Comment by lysxelapsed** [comment]
Numpy issues lead to pytorch issues in my experience. Not exactly sure to what extend pytorch is used in roop-unleashed nowadays though.
@C0untFloyd I'm guessing the installer overwrites a changed requirements.txt when running the installer a second time? Is there a way around that? Trying to help unexperienced users, which are using the installer, is a b****. This (and countless other cases) would be so easy to solve otherwise: adjust numpy in requirements.txt to 1.24, run the installer again.

**Comment by C0untFloyd** [comment]
> I'm guessing the installer overwrites a changed requirements.txt when running the installer a second time? 

No, the installer is hardcoded to that release (commit hash). The requirements won't be changed.

> adjust numpy in requirements.txt to 1.24, run the installer again.

That's what I already did in the latest commit: https://github.com/C0untFloyd/roop-unleashed/commit/9907f1f5b01d5927fbb9b084f7aa40a75bab7ab0

**Comment by lysxelapsed** [comment]
> > I'm guessing the installer overwrites a changed requirements.txt when running the installer a second time?
> 
> No, the installer is hardcoded to that release (commit hash). The requirements won't be changed.

Well then:
@donleo78 Open the requirements.txt file in your roop-unleashed folder, adjust the numpy version to 1.24, save the file and run the installer again.
> 
> > adjust numpy in requirements.txt to 1.24, run the installer again.
> 
> That's what I already did in the latest commit: [9907f1f](https://github.com/C0untFloyd/roop-unleashed/commit/9907f1f5b01d5927fbb9b084f7aa40a75bab7ab0)


Commit is 1.24.3, it's asking for 1.22 - 1.24 (and not a byte higher, python is so insufferable 🤣)

**Comment by C0untFloyd** [comment]
Don't want to argue and you're most helpful but in his case this wasn't a breaking error anyway:
```
Successfully installed numpy-1.24.3
Launching App
````
I still have it running with numpy 1.26 something
I need to find out which of the 3rd party things imports tensorflow-intel (it's not used anywhere by me).

**Comment by lysxelapsed** [comment]
OMG reading is hard on my part🤦‍♂️ I always read Successfully **UN**installed numpy-1.24.3. Result of just glancing through it. Sorry for wasting everyone's time 🙈
