### ISSUE TITLE
about roop run in centos server and ffmpeg some  question

### ISSUE THREAD

**Issue by Xander-x** [C0untFloyd/roop-unleashed#557]
**Describe the bug**
1.the log display ffmpeg is not installed.my server haven install it into the path 'usr/local/ffmpeg',and i writed executable='usr/local/ffmpeg/bin/ffmpeg' in ffmpy3.py.How can i do?

![WX20240328-050344@2x](https://github.com/C0untFloyd/roop-unleashed/assets/18110338/cedbb753-8fad-43c7-b955-befb92b32db5)

2.My project is deployed on a remote server, using domain names for external network mapping, but it doesn't seem to work, while the public link is functioning properly

![WX20240328-050416@2x](https://github.com/C0untFloyd/roop-unleashed/assets/18110338/411a64b9-41ee-4fb1-b3f4-e28aea229a62)

![WX20240328-050542@2x](https://github.com/C0untFloyd/roop-unleashed/assets/18110338/536a4635-cc9c-4d44-9c5b-41af3d4dc993)
![WX20240328-050604@2x](https://github.com/C0untFloyd/roop-unleashed/assets/18110338/cdf039ec-ce00-4b98-b49a-2f369d5a02b6)

how can i do?

**Details**
What OS are you using?
- [x] Linux

Are you using a GPU?
- [x] No. CPU FTW

**Which version of roop unleashed are you using?**
3.6.5

**Screenshots**

**Comment by Xander-x** [comment]
emmm,q1 is OK
i should change the path in roop/core.py line 130 like this
if not shutil.which('/usr/local/ffmpeg/bin/ffmpeg'):
       update_status('ffmpeg is not installed.')

so q2 who can help me?

**Comment by C0untFloyd** [comment]
For Q1 just add your installed ffmpeg to the centos path environment. If you're in the terminal and type ffmpeg it needs to be found. Trying to hardcode the path is a very, very bad idea and unlikely to work.
Q2: I don't even get the question 🤷‍♂️
