### ISSUE TITLE
input image loading failure 

### ISSUE THREAD

**Issue by Roosh12** [C0untFloyd/roop-unleashed#559]
**Describe the bug**
the  app is refusing to accept any image 
**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac
windows
Are you using a GPU?
- [x] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [x] Intel
- [ ] Mac
cpu
**Which version of roop unleashed are you using?**
3.6.0
**Screenshots**
![Annotation 2024-03-29 144627](https://github.com/C0untFloyd/roop-unleashed/assets/165393882/f09dd245-e219-4b5b-8720-adfe3d6ed1df)
![Annotation 2024-03-29 144628](https://github.com/C0untFloyd/roop-unleashed/assets/165393882/3afa798b-3800-4dab-bc1c-7080a8d824f3)

**Comment by Roosh12** [comment]
please help

**Comment by C0untFloyd** [comment]
There is no target face in your screenshot?!?
https://github.com/C0untFloyd/roop-unleashed/wiki/Face-Swap-Tab might help.

**Comment by Roosh12** [comment]
> can you post the output of your cmd window?



> can you post the output of your cmd window?

![Annotation 2024-03-30 104135](https://github.com/C0untFloyd/roop-unleashed/assets/165393882/b7d7d6a4-8d79-4d98-8f77-67bf3f96e8d2)

**Comment by Roosh12** [comment]
> There is no target file or face in your screenshot?!? https://github.com/C0untFloyd/roop-unleashed/wiki/Face-Swap-Tab might already help.

because the program refuses to accept any image and keeping gives me an error all the time like the screen shot

**Comment by Roosh12** [comment]
![Annotation 2024-03-30 104135](https://github.com/C0untFloyd/roop-unleashed/assets/165393882/c15d0753-b959-45b3-a6e0-d3b0e937327c)

this the last of my cmd gave me when i tried to upload photo after updating some drivers

**Comment by lysxelapsed** [comment]
I'm confused, maybe I'm missing something again. But just tested: Source face gets recognized without loading a target face first.

In your first cmd, I noticed you're using a strange filename. Don't use any special or "foreign" (asian, middle eastern etc.) characters, stick to simple file names.
As for the ConnectionResetError: I get these from time to time when changing the source face, and sometimes I have to clear and load it a second time. But otherwise it has no impact on the processing in my experience.
Your second cmd is ok, that's how it's supposed to look like.

Make sure the whole face is visible, otherwise it will have problems recognizing. See my comment in #558. If there are multiple faces in your picture, you need to scroll down and select one.

**Comment by Roosh12** [comment]
i did everything you advised even at the comment of #558 but still facing the same problem : output face gets recognized but input face always gets interrupted during loading it and refuses to be loaded into the program to be recognized to be replaced with the target face output .

![image](https://github.com/C0untFloyd/roop-unleashed/assets/165393882/00f26a04-019e-4852-a55c-79f5d8698fad)

**Comment by Roosh12** [comment]
can you help me setting a date with you to inter my lap top by the anydesk app and fix me this problem please @lysxelapsed  , i trust you can fix it

**Comment by Roosh12** [comment]
@lysxelapsed 
thanks dear , your help and support is much appreciated , i tried to change the image name and the program accepted it and the target video is processing now but do you know why it is very slow 2% in 30 min. ! , and do you know if the processing interrupted by any reason , can it be resumed by any way ? and what does it mean when cmd mention set det size 640,640 ?
![Annotation 2024-03-31 174156](https://github.com/C0untFloyd/roop-unleashed/assets/165393882/64a962a3-5d98-42fc-8acf-53b34fd24da4)
![Annotation 2024-03-31 174156](https://github.com/C0untFloyd/roop-unleashed/assets/165393882/de57ea37-d2af-4c36-9a7c-09f05a56f4cc)

**Comment by lysxelapsed** [comment]
Like I said, it's gonna be slow with cpu.
Det-size is the default detection window size of 640x640, nothing you need to worry about.
You should be able to pause processing with left-click into the cmd window and resume later with a right-click.

**Comment by spudnick1UK** [comment]
I have added one image and worked but now i cant add any others
cleaned out the temp files removed all of the working image but nothing shows
it shows that the image has been inserted but nothing in the procced image box

**Comment by omarnabil004** [comment]
Hi everyone,
this issue has only one solution that's you must resize source image to 563x700.

**Comment by bishoseven** [comment]
Hello did any one got a solution for this ? my cmd shows no errors but my WEBui doesn't detect any input faces from source files
![Screenshot 2024-05-19 024309](https://github.com/C0untFloyd/roop-unleashed/assets/109801044/6090bf1b-8fc6-45d8-b4ac-fc27cd299a47)
![Screenshot 2024-05-19 024454](https://github.com/C0untFloyd/roop-unleashed/assets/109801044/3acb9f62-20a1-42fa-9783-6f4ea77a216e)

**Comment by shannu-dotcom** [comment]
> Like I said, it's gonna be slow with cpu. Det-size is the default detection window size of 640x640, nothing you need to worry about. You should be able to pause processing with left-click into the cmd window and resume later with a right-click.

@lysxelapsed please can you help i got same issue
