### ISSUE TITLE
Batch processing using the UI: (file name already exists)

### ISSUE THREAD

**Issue by Oedipus7** [C0untFloyd/roop-unleashed#56]
**Describe the bug**
Everything works fine for single videos.
When the batch process starts after the first video is created with the name "temp.mp4" and when the second video finishes processing it says that the name already exist and it stops.
am I doing something wrong or it is not supposed to work with the UI?
**To Reproduce**
After selecting the face and leaving the video box empty. I selected batch processing source and target folders. then the issue occurs.

**Details**
What OS are you using?
- [x ] Windows 10
Are you try to use a GPU?
- [x ] NVIDIA

**Comment by C0untFloyd** [comment]
#36
