### ISSUE TITLE
UI without function in Firefox

### ISSUE THREAD

**Issue by kreativezgit** [C0untFloyd/roop-unleashed#563]
**Describe the bug**

UI without function in Firefox. whereever you click nothing happens. Chromium ungoogled doest works too.
Microsoft Edge works.
It worked the versions before.

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
3.6.5

**Screenshots**

Uncaught (in promise) Error: Unable to auto-detect a suitable renderer.
    autoDetectRenderer autoDetectRenderer.mjs:7
    _Application2 Application.mjs:9
    create_pixi_app pixi.ts:82
    3 ImageEditor.svelte:261
    run svelte.js:41
    mount_component svelte.js:3149
    flush svelte.js:2108
[autoDetectRenderer.mjs:7:6](http://127.0.0.1:7860/node_modules/.pnpm/@pixi+core@7.3.2/node_modules/@pixi/core/lib/autoDetectRenderer.mjs)
![Screenshot 2024-03-30 111109](https://github.com/C0untFloyd/roop-unleashed/assets/100515877/3388d26c-fab9-4366-83f4-89d6f047ed41)

**Comment by C0untFloyd** [comment]
#564
