### ISSUE TITLE
browser UI > Advanced Masking > up/down buttons unexepectedly fold the Advanced Masking section

### ISSUE THREAD

**Issue by Laylog** [C0untFloyd/roop-unleashed#566]
**Describe the bug**
Happens since commit c2931cf and newer gradio install (terminal output => ''Successfully installed gradio-4.24.0 gradio-client-0.14.0'')
Clicking any button within Advanced Masking folds this section instantly.

**To Reproduce**
1. Unfold Advanced Masking
2. Offset Face Top > Click on UP or DOWN button
3. Advanced Masking folds unexpectedly

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
3.6.6

Browser : Firefox 124.0.1

**Comment by C0untFloyd** [comment]
Yes, another new gradio bug so it seems. I mentioned this here https://github.com/gradio-app/gradio/issues/7895

**Comment by Laylog** [comment]
Fixed with Gradio 4.26.0. Thanks.
