### ISSUE TITLE
fix selected face 

### ISSUE THREAD

**Issue by zachysaur** [C0untFloyd/roop-unleashed#567]
i think you should stick with some older version when selected face was working lol

**Comment by Didier-Eloy** [comment]
Hello 
I've just downloaded the latest version and nothing works?

"Input Face.   9 Files loaded: 4 displayed

"Use face from this frame" : No face detected?

Best regard
![Bug ](https://github.com/C0untFloyd/roop-unleashed/assets/93537096/dae8ecf9-d7ed-4c01-a45d-60f270ce50a1)

**Comment by C0untFloyd** [comment]
#568
