### ISSUE TITLE
Bug version du 30 mars 2024

### ISSUE THREAD

**Issue by Didier-Eloy** [C0untFloyd/roop-unleashed#568]
Hello 
I've just downloaded the latest version and nothing works?

"Input Face.   9 Files loaded: 4 displayed

"Use face from this frame" : No face detected?

Best regard

![Bug ](https://github.com/C0untFloyd/roop-unleashed/assets/93537096/eb04898c-7051-4aaa-aa77-bccfb1cb7c60)

**Comment by Bootwilliam1** [comment]
me too

**Comment by C0untFloyd** [comment]
Try a target picture where the face is clearly visible (the hat confuses the AI). And also your source images seem to be bad although 4 faces from 9 input files is not exactly "nothing". For advanced deepfakes you might want to use something like https://github.com/iperov/DeepFaceLab

**Comment by C0untFloyd** [comment]
Nothing's changed in face detection for months. But if you think it did, you can always go back to older versions and install them again. Just be sure to not update.

**Comment by holycause** [comment]
I am having the exact same issue.
Everything worked fine until the 30th

**Comment by Didier-Eloy** [comment]
Hello,

 I installed version 3.5.5 and everything is back to normal. Everything works.
I uninstalled and reinstalled version 3.6.6 and I'm having the same problems as in my previous email?
I used the same files for the 2 versions 

![version 355](https://github.com/C0untFloyd/roop-unleashed/assets/93537096/204728c1-b99c-4795-bd53-927dc2ac8413)


Thank you for all your work on this excellent application, which far surpasses all the others I've tested.

**Comment by Didier-Eloy** [comment]
Good evening

No, I haven't changed the code,
I use Google translate which automatically translates the page into French or any other language as soon as I open the application.

**Comment by Didier-Eloy** [comment]
Chinese langage !!!

![Page en chinois    ](https://github.com/C0untFloyd/roop-unleashed/assets/93537096/866559b4-5560-4776-936e-e1e410fb6f68)

**Comment by C0untFloyd** [comment]
Hahaha ok, I keep forgetting stuff about my own app 😄 
Please update to 3.6.7 and tell me if images work again for you.

**Comment by Didier-Eloy** [comment]
Good evening

The new version works perfectly 
Test on several images and a video .

The source files load correctly.

Thanks for everything.

Didier ( France : Dijon )
