### ISSUE TITLE
UI Not Worky Worky on Collab 

### ISSUE THREAD

**Issue by Bootwilliam1** [C0untFloyd/roop-unleashed#569]
**Describe the bug**
Not able to upload Facesets, Images, Videos... Pretty much everything is unuseable. 

**To Reproduce**
Open Roop Unleashed on Google Colab and try to use it. 

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ x] Windows 
- [ ] Mac

Are you using a GPU?
The Colab CPU T4 High Ram 

**Which version of roop unleashed are you using?**
3.6.6. 

**Screenshots**
Cant really add screenshots. 

Sorry about previous posts, i'm new to all this

**Comment by C0untFloyd** [comment]
I tried as you suggested and everything worked as it should:
![grafik](https://github.com/C0untFloyd/roop-unleashed/assets/131583554/fa01d4db-44c7-4937-9979-3798b07a512b)
![grafik](https://github.com/C0untFloyd/roop-unleashed/assets/131583554/48a672f2-b4b4-4792-8318-7c210adabdf9)
![grafik](https://github.com/C0untFloyd/roop-unleashed/assets/131583554/65e1ca66-3288-4140-9442-0bd5304f8921)

I didn't faceswap a video but image faceswapping worked as ever:
![grafik](https://github.com/C0untFloyd/roop-unleashed/assets/131583554/69181416-7c67-40a1-88f1-96f9deb631ce)

Honestly, I don't know what is as you also don't show any output from the colab. Perhaps some other guy is able to help you but I'm out of ideas.

**Comment by Bootwilliam1** [comment]
Alright let me check again and see what the issue is

**Comment by Bootwilliam1** [comment]
What output can i show you, everything looks normal. 
It will only allow me to upload one image but honestly it is not working on colab. I am not the only person to have this issue as well.

**Comment by dremix97** [comment]
> What output can i show you, everything looks normal. It will only allow me to upload one image but honestly it is not working on colab. I am not the only person to have this issue as well.

Hi, is it working for you now? Still doesn't work for me for some reason.

**Comment by zachysaur** [comment]
rather then first found try selected sometimes why you ignoring this huge error

**Comment by C0untFloyd** [comment]
> rather then first found try selected sometimes why you ignoring this huge error
Here you go:
![Colab](https://github.com/C0untFloyd/roop-unleashed/assets/131583554/356724bb-4c15-4254-85d2-cabad95bf555)

You're obviously the only one with that problem and you didn't want us to help in the issue you created https://github.com/C0untFloyd/roop-unleashed/issues/472
I'm giving up on you, perhaps others can help you 🤷‍♂️

**Comment by C0untFloyd** [comment]
Buuut this issue (slow on colab) is totally different from what zachysaur writes (face selection not working). It's also very different from your first entry above (not able to upload Facesets, Images, Videos). 
Can we agree that this issue - if it even exists - is colab specific? If yes, would you be very surprised that there's no single line of code especially for colabs in this app? There is LOTS of code for CUDA machines which coincidentally also include google colabs. But if you take a look into the benchmark thread https://github.com/C0untFloyd/roop-unleashed/discussions/461 processing speed even increased in the latter versions! Can we then further agree that logically there can't be a bug inside the roop unleashed app? Reading between the lines, my best guess is you're not complaining about the length of the swapping process but the time it takes to upload media? If that's the case there are only these solutions:
1. your browser doesn't play well with the newest gradio versions. There are many people who reported problems with e.g. chrome. Try a different one.
2. your upload speed is slow. It's a client/server application and images/videos are uploaded from you to the colab server.
3. you're using an outdated colab. Mine was updated a few weeks ago and includes installation of an older, more compatible CUDA version.  Be sure to restart the colab when asked!
4. Last and least, google is throttling your account or this app for misuse.

As you can see above I tried myself briefly above and had no unusual slow processing or anything, using Firefox.

**Comment by zachysaur** [comment]
there no error at all everything work fine just selected face dont work

**Comment by C0untFloyd** [comment]
> there no error at all everything work fine just selected face dont work

Could it be this? https://github.com/C0untFloyd/roop-unleashed/discussions/565#discussioncomment-9019373

**Comment by zachysaur** [comment]
i dont know about this one earlier i tried swap-mukham it got same feature of selected face was having same problem i needed to change gr. in code then it worked fine

**Comment by zachysaur** [comment]
he not willing to fix selected face you choose different face it end up swap face of first found face
