### ISSUE TITLE
Square box around the face :  bug of enhancer

### ISSUE THREAD

**Issue by SamPse** [C0untFloyd/roop-unleashed#57]
**Describe the bug**

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [x] I have the latest code from the github repository
- [ ] I have followed the installation guide

How using face parsing mask as final mask to hide those box seams?
![output - frame at 0m0s](https://github.com/C0untFloyd/roop-unleashed/assets/48360190/0d09f557-9c30-4dae-a1e7-52a73cbcfddd)

**Comment by C0untFloyd** [comment]
I'm sorry I don't really understand. I'm not doing any face parsing, are you perhaps using a different fork? The current insightface model has a resolution of 128x128, there's nothing you can do about it except enhance/upscale after swapping.
![angry-man-smoked-brain](https://github.com/C0untFloyd/roop-unleashed/assets/131583554/bf55d2a6-d13f-4d58-80c5-91b4944d0b92)

**Comment by SamPse** [comment]
I’m getting a square box around the face. Any way to fix it?

**Comment by C0untFloyd** [comment]
This is weird. Of course the face swapping uses a bounding box but it's very close to the face and your example is way bigger. Does this also happen when using CPU? Did you try with the original roop?

**Comment by SamPse** [comment]
> This is weird. Of course the face swapping uses a bounding box but it's very close to the face and your example is way bigger. Does this also happen when using CPU? Did you try with the original roop?

Thank you for your answer, yes I also have the same result with roop and with the GFPGAN option activated to improve the result. Roop knows this bug well. They just updated some of the code responsible for this box. https://github.com/s0md3v/roop/issues/750

**Comment by C0untFloyd** [comment]
Thanks for the hint, never noticed this previously.

**Comment by SamPse** [comment]
> Thanks for the hint, never noticed this previously.

The enhancer does not enhance backgrounds! The approach will be write your own frame processor and use super resolution models like https://github.com/pytorch/tutorials/blob/main/advanced_source/super_resolution_with_onnxruntime.py

**Comment by phineas-pta** [comment]
this is because original roop wanted to limit enhancer to a box instead of whole frame

there's nothing like this in roop unleashed so this bug shouldnt exist

**Comment by danigarciaoca** [comment]
Hi, I'm facing this same issue, when swapping faces: a weird box bigger than the face (and that include part of the background) is visible. It is more noticeable in videos. Let me show and example image:

*Original*
![portrait_1](https://github.com/C0untFloyd/roop-unleashed/assets/27818263/2cfd4d69-f064-4eae-9542-cf3dddb6903d)

*Swapped (whithout post-processing)*
![image (35)](https://github.com/C0untFloyd/roop-unleashed/assets/27818263/3cff3ba4-237c-4de9-a7bb-915dba2e5357)

There is like this kind of bigger face bounding box in the swapped one. It is more visible when comparing the hair in the original upper part vs swapped one:
![image (35) (1)](https://github.com/C0untFloyd/roop-unleashed/assets/27818263/77180f34-3107-48ea-9a81-ccb7aac91029)

Any idea about what can it be? I'm running it on Ubuntu 20.04, Python 3.9 and CUDA 11.8

Thanks in advance!

**Comment by C0untFloyd** [comment]
Yes, I know about this and it's still the same reason, the 128x128 limited resolution of the insightface swapping model. This is very visible in faces with lots of fine details like your example. That's why the enhancers exist, they do upscaling to hopefully get rid of this. Try experimenting with the blend amount to refine it.
