### ISSUE TITLE
Not a bug report. Improvment idea

### ISSUE THREAD

**Issue by Kittyskj** [C0untFloyd/roop-unleashed#570]
I would like to propose an idea that could potentially enhance the accuracy of time estimation for face processing in your application.

Currently, the application does not accurately estimate the processing time for videos. I have observed that when the application processes frames containing faces, the frame rate drops to approximately 1-4 frames per second. However, when processing frames without faces, the frame rate is around 10-14 frames per second.

Based on this observation, I suggest the following approach: The application could track the number of frames with and without faces, calculate the average frame rate for each frame type, and then estimate the overall processing time by taking into account these two different frame rates and the number of frames of each type.

By implementing this method, the time estimation would be more accurate as it would account for the performance differences when processing frames with and without faces.

I hope you find this suggestion valuable, and I look forward to seeing it implemented in future versions of your application.

Thank you for your excellent product and for considering user feedback.

**Comment by lysxelapsed** [comment]
> The application could track the number of frames with and without faces, calculate the average frame rate for each frame type, and then estimate the overall processing time by taking into account these two different frame rates and the number of frames of each type.

This alone would take minutes for a single video. The "skipping frames fps" (frames without faces) is around 120fps in my case. A 30 minute video at 30 frames per second amounts to 54'000 frames to analyze. So it would take 7.5 minutes to analyze alone, if the video had no faces at all in it. Assuming more than half of the video has at least one face in it, it goes way beyond 10 minutes before even a single face is swapped. Not worth it just to have a better processing time estimate in my opinion.
Correct me if my math or logic is off, but I only see the downside here: Added processing time. Also, with time, you get good at guessing the approximate processing time with a quick glance through the target video, which takes a few seconds instead of minutes.

**Comment by Kittyskj** [comment]
> > The application could track the number of frames with and without faces, calculate the average frame rate for each frame type, and then estimate the overall processing time by taking into account these two different frame rates and the number of frames of each type.
> 
> This alone would take minutes for a single video. The "skipping frames fps" (frames without faces) is around 120fps in my case. A 30 minute video at 30 frames per second amounts to 54'000 frames to analyze. So it would take 7.5 minutes to analyze alone, if the video had no faces at all in it. Assuming more than half of the video has at least one face in it, it goes way beyond 10 minutes before even a single face is swapped. Not worth it just to have a better processing time estimate in my opinion. Correct me if my math or logic is off, but I only see the downside here: Added processing time. Also, with time, you get good at guessing the approximate processing time with a quick glance through the target video, which takes a few seconds instead of minutes.

Thank you for the detailed response and explanation. I understand your perspective better now.

You make a fair point that implementing the suggested approach would add significant processing time, especially for longer videos with a high frame rate. The overhead of analyzing each frame to determine if it contains a face, calculating separate average frame rates, and then estimating the total time based on that may not be worthwhile, given that an experienced user can roughly gauge the processing time with a quick preview.

Your math seems sound - breaking down a 30-minute 30fps video into 54,000 frames and having to analyze each one would indeed take substantial time, likely multiple minutes, even before any face swapping is done. For shorter clips it may be more feasible, but for longer videos the tradeoff of added processing time outweighs the benefit of a more accurate time estimate.

I appreciate you taking the time to clarify the drawbacks and provide that perspective. Given the additional processing overhead required, pursuing this approach may not be optimal for improving the user experience in the application. Your feedback helps identify when an optimization idea may create more problems than it solves. Thank you for the insightful response.

**Comment by Kittyskj** [comment]
Instead of analyzing every single frame, the application could take a statistical sampling of frames at regular intervals (e.g., every 10 seconds) and determine if those sampled frames contain faces or not. This would give a representative snapshot of the ratio of face/non-face frames without having to process the entire video.

Using this sample data, the application could then calculate an estimated overall frame rate by weighing the typical face and non-face frame rates against their approximate proportions in the video.

For example, if the samples showed 60% of frames had faces, and 40% didn't, the estimated frame rate could be calculated as:

(0.6 * typical_face_framerate) + (0.4 * typical_non_face_framerate)

This weighted average frame rate could then be used to estimate the total processing time for the full video length.

The sampling interval could be made configurable, allowing users to trade off estimation accuracy versus sampling overhead. More frequent sampling would give a more accurate estimate but require more processing.

This approach eliminates the need to analyze every single frame, while still accounting for the difference in frame rates when faces are present. It leverages statistical sampling to get a reasonable approximation of the frame rate dynamics without the high overhead of a full frame-by-frame analysis.

Please let me know if this sampling-based estimation method seems more viable or if you have any other suggestions to improve the time estimation while minimizing added processing time.

**Comment by lysxelapsed** [comment]
Yes I had some second thoughts on this too after posting. My response is mostly aimed at how _I_ use roop-unleashed, which is mostly on longer videos - I even swapped a full 2h movie with multiple faces 🤣
The other thought I had was the same as yours: Does it really need to analyze every frame? And the answer is clearly no, as you already exlpained 😉 
And as long as it's optional by checkbox or similar, there's no real downside. How hard this would be to implement however, as this is probably a python _and_ a ffmpeg thing: No idea 😆
