### ISSUE TITLE
0.0byte output file after processing

### ISSUE THREAD

**Issue by dave4712xx** [C0untFloyd/roop-unleashed#571]
got the third time an empty 0.0byte output file after normal processing,maybe format .wmv causes this ?

Windows11
13900k
3090 FE
64gb RAM

"Sorting videos/images
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'has_user_compute_stream': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
C:\roop-unleashed-main\installer\roop-unleashed\roop\ProcessMgr.py:118: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self.options.imagemask is not None and "layers" in self.options.imagemask and len(self.options.imagemask["layers"]) > 0:
Creating BVB1909.mp4 with 29.97002997002997 FPS...
['ffmpeg', '-hide_banner', '-hwaccel', 'auto', '-y', '-loglevel', 'error', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '1920x1080', '-pix_fmt', 'bgr24', '-r', '29.97002997002997', '-an', '-i', '-', '-vcodec', 'libx264', '-crf', '14', '-vf', 'colorspace=bt709:iall=bt601-6-625:fast=1', '-pix_fmt', 'yuv420p', 'C:\\roop-unleashed-main\\installer\\roop-unleashed\\output\\BVB1909.mp4']
Processing: 100%|██████████████▉| 49899/49906 [1:26:46<00:00,  9.58frames/s, memory_usage=01.40GB, execution_threads=2]
Running ffmpeg
Running ffmpeg failed! Commandline:
ffmpeg -hide_banner -hwaccel auto -y -loglevel error -i C:\roop-unleashed-main\installer\roop-unleashed\output\BVB1909__temp.mp4 -ss 0.00 -to 1665.16 -i C:\roop-unleashed-main\temp\181fca8f3b1dfaddab85244c2ba240e559966bd1\BVB1909.wmv -c copy -map 0:v:0 -map 1:a:0? -shortest C:\roop-unleashed-main\installer\roop-unleashed\output\BVB1909.mp4

Processing BVB1909.mp4 took 5208.473825931549 secs
Finished"

**Comment by lysxelapsed** [comment]
Since the swapping process went fine, I think the issue is the audio track of your wmv file. I would recommend to re-encode the wmv file to mp4 with either aac or mp3 audio and try again.
