### ISSUE TITLE
installation error , roop unleashed not found

### ISSUE THREAD

**Issue by Andrewvich** [C0untFloyd/roop-unleashed#577]
**hi** , i ran the installation several times and each time it is 
giving me a punch of errors

error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 585 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
Traceback (most recent call last):
  File "C:\Users\MAC-SHOP\Downloads\Programs\roop-unleashed-main\installer\installer.py", line 78, in <module>
    install_dependencies()
  File "C:\Users\MAC-SHOP\Downloads\Programs\roop-unleashed-main\installer\installer.py", line 37, in install_dependencies
    os.chdir(MY_PATH)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'roop-unleashed'

please tell me how to fix these
thank you so much

**Comment by C0untFloyd** [comment]
At its base this is a network issue with your machine  It could be either one of these problems:
* Github down
* Bad WiFi Connection
* Firewall/Port problems
* ISP block

First, I would try to connect to the internet through other means. Either try connecting by creating a cellphone hotspot or use a VPN. Perhaps this already fixes your problems. If not I'm afraid you need to try the manual downloading/install as described in the  
 [wiki](https://github.com/C0untFloyd/roop-unleashed/wiki/Installation)

**Comment by Andrewvich** [comment]
thank you for the help
VPN solved the problem
but now i can only swap faces in photos
as it says no ffmpeg is installed
if you can help id be grateful

**Comment by C0untFloyd** [comment]
Weird, it should have been installed by the installer too. Anyway, I think this is a good article explaining how to install it:
https://www.wikihow.com/Install-FFmpeg-on-Windows

(most important is the last part, adding it to your path)
