### ISSUE TITLE
URLopen error retrieval incomplete

### ISSUE THREAD

**Issue by epsteinandme** [C0untFloyd/roop-unleashed#583]
I keep getting 
 "urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 548681076 out of 554253681 bytes>" as an error. What should I do to fix this?
<img width="861" alt="image" src="https://github.com/C0untFloyd/roop-unleashed/assets/152642594/4e8a1bca-1c15-4b40-82cb-1db908d2a6bf">
<img width="861" alt="Screenshot 2024-04-04 161349" src="https://github.com/C0untFloyd/roop-unleashed/assets/152642594/8256ddb4-b77b-44dd-9664-139be33e9dc8">

**Comment by C0untFloyd** [comment]
Yeah and the older version already downloaded all the necessary models back when your network was still working. Please see
https://github.com/C0untFloyd/roop-unleashed/discussions/486#discussioncomment-8749137

And @epsteinandme it might be a good idea to install this into a shorter path somewhere to prevent future problems...

**Comment by eddiepot** [comment]
> Yeah and the older version already downloaded all the necessary models back when your network was still working. Please see [#486 (reply in thread)](https://github.com/C0untFloyd/roop-unleashed/discussions/486#discussioncomment-8749137)
> 
> And @epsteinandme it might be a good idea to install this into a shorter path somewhere to prevent future problems...

Thanks for the quick reply! I will give it a try. Love roop!
