### ISSUE TITLE
I get this error while using roop unleashed

### ISSUE THREAD

**Issue by famestreammodelling** [C0untFloyd/roop-unleashed#586]
Hello I have watched this video:
https://www.youtube.com/watch?v=vgZ83Oxnjh8
and did everything he said.
This is my hardware:
Device name	DESKTOP-F5CC2RU
Processor	Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz   3.41 GHz
Installed RAM	16.0 GB (15.9 GB usable)
Device ID	464418FF-8E76-4CA8-BA23-39E1CB33E462
Product ID	00330-54142-09116-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

I do not have an nvidia card (I have an Intel(R) HD graphics 530) so I am trying to run roop with CPU but I keep seeing this error:

D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=-1231511160 ; hostname=DESKTOP-F5CC2RU ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=236 ; expr=cudaSetDevice(info_.device_id);

Please advice how to fix this.
Thanks

**Comment by lysxelapsed** [comment]
You can open up `config.yaml` (in your roop-unleashed folder) with an editor, adjust `provider: cuda` to `provider: cpu` and try again.
That being said, you'll probably have other troubles with only 16GB RAM, at least with some of the enhancers.

**Comment by winston6767** [comment]
Hi
I experience exactly the same error. Changed config.yaml as advised above but error remains.
Any help would be greatly appreciated...

**Comment by winston6767** [comment]
Had to reinstall roop, now it's working.
