### ISSUE TITLE
roop urllib.error.URLError

### ISSUE THREAD

**Issue by eddiepot** [C0untFloyd/roop-unleashed#587]
Trying to install roop on Windows 11,
Nvidia 4080 super, 
latest roop.

It seems to install all componets okay, but when it's about to launch the app I get this error:

"urllib.error.URLError: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>

Done!
Press any key to continue . . ."
This is a local install and I'm confused with the error say closed by remote host

I am currently running roop on windows 10 on Firefox  on another pc no problem.

Thanks for any help
love roop!

**Comment by lysxelapsed** [comment]
When running for the first time, roop-unleashed downloads the various models, it seems to be a probleme there. You can try to download them manually and place them in your models folder. Links are here -> #486

**Comment by simpleness23** [comment]
> When running for the first time, roop-unleashed downloads the various models, it seems to be a probleme there. You can try to download them manually and place them in your models folder. Links are here -> #486

I'm receiving the same error and I manually placed the models in the correct folder and I'm still receiving the same error code.

**Comment by eddiepot** [comment]
> When running for the first time, roop-unleashed downloads the various models, it seems to be a probleme there. You can try to download them manually and place them in your models folder. Links are here -> #486

I will give this a try when I get home from work. Thanks for the help. I will let you know.

**Comment by simpleness23** [comment]
> > When running for the first time, roop-unleashed downloads the various models, it seems to be a probleme there. You can try to download them manually and place them in your models folder. Links are here -> #486
> 
> I will give this a try when I get home from work. Thanks for the help. I will let you know.

Did it resolve the issue for you?

**Comment by lysxelapsed** [comment]
If you google the error, you'll find countless possible causes unfortunately. Could also be ressource- or browser-related. Try a restart and / or setting a different browser as default.

**Comment by eddiepot** [comment]
Thanks for all the help! I will keep trying and let you know. Have to wait until I getr off work

**Comment by eddiepot** [comment]
I was able to fix this issue by changing the DNS settings in Windows 11 to 8.8.8.8 8.8.4.4!

**Comment by lysxelapsed** [comment]
Interesting. Thanks for the update, this could possibly come in handy for future connection-related issues 👍
