### ISSUE TITLE
FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by IzriGit** [C0untFloyd/roop-unleashed#588]
FFmpeg is already installed.
Skipping FFmpeg installation as it is already available.
Downloading insightface package from https://github.com/C0untFloyd/roop-unleashed/releases/download/3.6.6/insightface-0.7.3-cp310-cp310-win_amd64.whl to C:\Users\izrid\Downloads\roop-unleashed-main\installer\installer_files\insightface-0.7.3-cp310-cp310-win_amd64.whl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  821k  100  821k    0     0   728k      0  0:00:01  0:00:01 --:--:-- 1783k
Installing insightface package
Processing c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\insightface-0.7.3-cp310-cp310-win_amd64.whl
Requirement already satisfied: numpy in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from insightface==0.7.3) (1.24.3)
Requirement already satisfied: onnx in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from insightface==0.7.3) (1.15.0)
Requirement already satisfied: tqdm in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from insightface==0.7.3) (4.66.2)
Requirement already satisfied: requests in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from insightface==0.7.3) (2.31.0)
Requirement already satisfied: matplotlib in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from insightface==0.7.3) (3.8.4)
Requirement already satisfied: Pillow in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from insightface==0.7.3) (10.3.0)
Requirement already satisfied: scipy in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from insightface==0.7.3) (1.13.0)
Requirement already satisfied: scikit-learn in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from insightface==0.7.3) (1.4.1.post1)
Requirement already satisfied: scikit-image in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from insightface==0.7.3) (0.22.0)
Requirement already satisfied: easydict in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from insightface==0.7.3) (1.13)
Requirement already satisfied: cython in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from insightface==0.7.3) (3.0.10)
Requirement already satisfied: albumentations in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from insightface==0.7.3) (1.3.1)
Requirement already satisfied: prettytable in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from insightface==0.7.3) (3.10.0)
Requirement already satisfied: PyYAML in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from albumentations->insightface==0.7.3) (6.0.1)
Requirement already satisfied: qudida>=0.0.4 in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from albumentations->insightface==0.7.3) (0.0.4)
Requirement already satisfied: opencv-python-headless>=4.1.1 in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from albumentations->insightface==0.7.3) (4.9.0.80)
Requirement already satisfied: networkx>=2.8 in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from scikit-image->insightface==0.7.3) (3.3)
Requirement already satisfied: imageio>=2.27 in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from scikit-image->insightface==0.7.3) (2.34.0)
Requirement already satisfied: tifffile>=2022.8.12 in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from scikit-image->insightface==0.7.3) (2024.2.12)
Requirement already satisfied: packaging>=21 in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from scikit-image->insightface==0.7.3) (24.0)
Requirement already satisfied: lazy_loader>=0.3 in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from scikit-image->insightface==0.7.3) (0.4)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from matplotlib->insightface==0.7.3) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from matplotlib->insightface==0.7.3) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from matplotlib->insightface==0.7.3) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from matplotlib->insightface==0.7.3) (1.4.5)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from matplotlib->insightface==0.7.3) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from matplotlib->insightface==0.7.3) (2.9.0.post0)
Requirement already satisfied: protobuf>=3.20.2 in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from onnx->insightface==0.7.3) (5.26.1)
Requirement already satisfied: wcwidth in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from prettytable->insightface==0.7.3) (0.2.13)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from requests->insightface==0.7.3) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from requests->insightface==0.7.3) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from requests->insightface==0.7.3) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from requests->insightface==0.7.3) (2024.2.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from scikit-learn->insightface==0.7.3) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from scikit-learn->insightface==0.7.3) (3.4.0)
Requirement already satisfied: colorama in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from tqdm->insightface==0.7.3) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from python-dateutil>=2.7->matplotlib->insightface==0.7.3) (1.16.0)
Requirement already satisfied: typing-extensions in c:\users\izrid\downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from qudida>=0.0.4->albumentations->insightface==0.7.3) (4.11.0)
insightface is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
Launching roop unleashed
Check for Updates? [y/n]n
Launching App
ffmpeg is not installed.
Using provider ['CUDAExecutionProvider'] - Device:cuda
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'has_user_compute_stream': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\izrid\Downloads\roop-unleashed-main\installer\roop-unleashed\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'has_user_compute_stream': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\izrid\Downloads\roop-unleashed-main\installer\roop-unleashed\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'has_user_compute_stream': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\izrid\Downloads\roop-unleashed-main\installer\roop-unleashed\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'has_user_compute_stream': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\izrid\Downloads\roop-unleashed-main\installer\roop-unleashed\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'has_user_compute_stream': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\izrid\Downloads\roop-unleashed-main\installer\roop-unleashed\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Sorting videos/images
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'has_user_compute_stream': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Creating Luka Modric Free Clip _ 4k Ultra Hd _ Real Madrid Scenes__temp.mp4 with 30.0 FPS...
['ffmpeg', '-hide_banner', '-hwaccel', 'auto', '-y', '-loglevel', 'error', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '1280x720', '-pix_fmt', 'bgr24', '-r', '30.0', '-an', '-i', '-', '-vcodec', 'libx264', '-crf', '14', '-vf', 'colorspace=bt709:iall=bt601-6-625:fast=1', '-pix_fmt', 'yuv420p', 'C:\\Users\\izrid\\Downloads\\roop-unleashed-main\\installer\\roop-unleashed\\output\\Luka Modric Free Clip _ 4k Ultra Hd _ Real Madrid Scenes__temp.mp4']
Traceback (most recent call last):
  File "C:\Users\izrid\Downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages\gradio\queueing.py", line 561, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\izrid\Downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages\gradio\route_utils.py", line 260, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\izrid\Downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1689, in process_api
    result = await self.call_function(
  File "C:\Users\izrid\Downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1267, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\izrid\Downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages\gradio\utils.py", line 574, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\izrid\Downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages\gradio\utils.py", line 567, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\izrid\Downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\izrid\Downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "C:\Users\izrid\Downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\Users\izrid\Downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages\gradio\utils.py", line 550, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\izrid\Downloads\roop-unleashed-main\installer\installer_files\env\lib\site-packages\gradio\utils.py", line 733, in gen_wrapper
    response = next(iterator)
  File "C:\Users\izrid\Downloads\roop-unleashed-main\installer\roop-unleashed\ui\tabs\faceswap_tab.py", line 575, in start_swap
    batch_process(list_files_process, use_clip, clip_text, processing_method == "In-Memory processing", imagemask, progress, SELECTED_INPUT_FACE_INDEX)
  File "C:\Users\izrid\Downloads\roop-unleashed-main\installer\roop-unleashed\roop\core.py", line 309, in batch_process
    process_mgr.run_batch_inmem(v.filename, v.finalname, v.startframe, v.endframe, fps,roop.globals.execution_threads, skip_audio)
  File "C:\Users\izrid\Downloads\roop-unleashed-main\installer\roop-unleashed\roop\ProcessMgr.py", line 235, in run_batch_inmem
    self.videowriter =  FFMPEG_VideoWriter(target_video, (width, height), fps, codec=roop.globals.video_encoder, crf=roop.globals.video_quality, audiofile=None)
  File "C:\Users\izrid\Downloads\roop-unleashed-main\installer\roop-unleashed\roop\ffmpeg_writer.py", line 146, in __init__
    self.proc = sp.Popen(cmd, **popen_params)
  File "C:\Users\izrid\Downloads\roop-unleashed-main\installer\installer_files\env\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\izrid\Downloads\roop-unleashed-main\installer\installer_files\env\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

I tried to install ffmpeg myself because there is a warning in gradio "ffmpeg is not installed, video processing isn't possible" I put the ffmpeg in the right path Downloads\roop-unleashed-main\installer\installer_files. And I also tried other paths. I looked all the issues having the same problem but it still don't work. any solution pls ?

**Comment by lysxelapsed** [comment]
Probably ffmpeg folder not added under `Path` in [environment variables](https://phoenixnap.com/kb/ffmpeg-windows) (step 3)?

**Comment by Dcode1999** [comment]
Update roop it might solve the error that you are getting.

**Comment by AnderVicario** [comment]
i solved the problem, in my case i had to change "ffmpeg----" folder's name in installer/installer_file to fmpeg
![solution](https://github.com/C0untFloyd/roop-unleashed/assets/102811194/4eda0b6e-5392-4d78-ac45-d6d1d5aa539c)

**Comment by Grecoton** [comment]
In my case it doesn't even install ffmpeg in the folder directly, it skips it
