### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by X3TSF** [C0untFloyd/roop-unleashed#589]
FFmpeg is already installed.
Skipping FFmpeg installation as it is already available.
Downloading insightface package from https://github.com/C0untFloyd/roop-unleashed/releases/download/3.6.6/insightface-0.7.3-cp310-cp310-win_amd64.whl to D:\roop-unleashed-main\installer\installer_files\insightface-0.7.3-cp310-cp310-win_amd64.whl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  821k  100  821k    0     0   353k      0  0:00:02  0:00:02 --:--:--  770k
Installing insightface package
Processing d:\roop-unleashed-main\installer\installer_files\insightface-0.7.3-cp310-cp310-win_amd64.whl
Requirement already satisfied: numpy in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from insightface==0.7.3) (1.26.2)
Requirement already satisfied: onnx in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from insightface==0.7.3) (1.15.0)
Requirement already satisfied: tqdm in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from insightface==0.7.3) (4.66.2)
Requirement already satisfied: requests in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from insightface==0.7.3) (2.31.0)
Requirement already satisfied: matplotlib in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from insightface==0.7.3) (3.8.4)
Requirement already satisfied: Pillow in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from insightface==0.7.3) (10.3.0)
Requirement already satisfied: scipy in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from insightface==0.7.3) (1.13.0)
Requirement already satisfied: scikit-learn in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from insightface==0.7.3) (1.4.1.post1)
Requirement already satisfied: scikit-image in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from insightface==0.7.3) (0.22.0)
Requirement already satisfied: easydict in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from insightface==0.7.3) (1.13)
Requirement already satisfied: cython in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from insightface==0.7.3) (3.0.10)
Requirement already satisfied: albumentations in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from insightface==0.7.3) (1.4.3)
Requirement already satisfied: prettytable in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from insightface==0.7.3) (3.10.0)
Requirement already satisfied: PyYAML in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from albumentations->insightface==0.7.3) (6.0.1)
Requirement already satisfied: typing-extensions>=4.9.0 in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from albumentations->insightface==0.7.3) (4.11.0)
Requirement already satisfied: opencv-python-headless>=4.9.0 in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from albumentations->insightface==0.7.3) (4.9.0.80)
Requirement already satisfied: networkx>=2.8 in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from scikit-image->insightface==0.7.3) (3.3)
Requirement already satisfied: imageio>=2.27 in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from scikit-image->insightface==0.7.3) (2.34.0)
Requirement already satisfied: tifffile>=2022.8.12 in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from scikit-image->insightface==0.7.3) (2024.2.12)
Requirement already satisfied: packaging>=21 in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from scikit-image->insightface==0.7.3) (24.0)
Requirement already satisfied: lazy_loader>=0.3 in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from scikit-image->insightface==0.7.3) (0.4)
Requirement already satisfied: joblib>=1.2.0 in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from scikit-learn->insightface==0.7.3) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from scikit-learn->insightface==0.7.3) (3.4.0)
Requirement already satisfied: contourpy>=1.0.1 in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from matplotlib->insightface==0.7.3) (1.2.1)
Requirement already satisfied: cycler>=0.10 in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from matplotlib->insightface==0.7.3) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from matplotlib->insightface==0.7.3) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from matplotlib->insightface==0.7.3) (1.4.5)
Requirement already satisfied: pyparsing>=2.3.1 in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from matplotlib->insightface==0.7.3) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from matplotlib->insightface==0.7.3) (2.9.0.post0)
Requirement already satisfied: protobuf>=3.20.2 in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from onnx->insightface==0.7.3) (5.26.1)
Requirement already satisfied: wcwidth in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from prettytable->insightface==0.7.3) (0.2.13)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from requests->insightface==0.7.3) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from requests->insightface==0.7.3) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from requests->insightface==0.7.3) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from requests->insightface==0.7.3) (2024.2.2)
Requirement already satisfied: colorama in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from tqdm->insightface==0.7.3) (0.4.6)
Requirement already satisfied: six>=1.5 in d:\roop-unleashed-main\installer\installer_files\env\lib\site-packages (from python-dateutil>=2.7->matplotlib->insightface==0.7.3) (1.16.0)
insightface is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
Launching roop unleashed
Check for Updates? [y/n]y
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Launching App
python: can't open file 'D:\\roop-unleashed-main\\installer\\roop-unleashed\\run.py': [Errno 2] No such file or directory

Done!
Press any key to continue . . .

**Comment by Dcode1999** [comment]
Try updating roop it will solve your issue.

**Comment by amen92** [comment]
> Try updating roop it will solve your issue. It has solved my issue.

I tried that didn't work.

**Comment by lysxelapsed** [comment]
This was with 3.6.6, right? Try a clean install with the [latest version](https://github.com/C0untFloyd/roop-unleashed/releases/tag/3.6.7). For some reason it doesn't get recognized as github repository, therefore you can't update within the app.
