### ISSUE TITLE
Many Image referece for one target video.

### ISSUE THREAD

**Issue by tikendraw** [C0untFloyd/roop-unleashed#59]
Instead of using one image for the entire video and wrapping it, take many source images for one target video to match the facial structure better.

**Comment by phineas-pta** [comment]
impossible with currently used model (insightface inswapper)

**Comment by tikendraw** [comment]
Understandable. 👍

**Comment by phineas-pta** [comment]
this altermative to inswapper may be what u want https://github.com/eric-ai-lab/photoswap

**Comment by C0untFloyd** [comment]
Nice find but this looks more like a Diffusion Lora paired with Control.NET. Also it seems you need to train a checkpoint. This is too much for a quick deepfake I think.
