### ISSUE TITLE
It says that ffmpg is not downloaded 

### ISSUE THREAD

**Issue by Avoid13** [C0untFloyd/roop-unleashed#590]
when i go into the installer files ffmpg is there. I already Deletet roop and wonloaded it again but it says that ffmgp cant be found. Please help me.
FilenotFounderror

**Comment by Dcode1999** [comment]
I also have the same issue, but it just disappeared after updating Roop to its new version 3.6.7. So try updating roop. it might solve your problem.

**Comment by amen92** [comment]
I have the same problem, updating and reinstalling didn't work. I also tried copying ffmpg files to the .bat file location, that too didn't work either.

**Comment by lysxelapsed** [comment]
Try adding the folder containing ffmpeg manually to `Path` in [environment variables](https://phoenixnap.com/kb/ffmpeg-windows) (step 3)

**Comment by amen92** [comment]
> Try adding the folder containing ffmpeg manually to `Path` in [environment variables](https://phoenixnap.com/kb/ffmpeg-windows) (step 3)

C:\roop-unleashed-main\installer\installer_files\ffmpeg-2023-06-21-git-1bcb8a7338-essentials_build\bin

This folder? If not which one? It has ffprobe.exe, ffplay.exe and ffmpeg.exe in that folder.

**Comment by lysxelapsed** [comment]
Yes, that one 👍

**Comment by amen92** [comment]
> Yes, that one 👍

Sorry for the late reply it worked for me.

**Comment by spudnick1UK** [comment]
the FFMPEG does get downloaded but the folder has to many non characters
so you just have to change the folder name to 
 ffmpeg
it is loacted in the roop unleashed /installer/installer files/ FFMPEG Bla bla bla
just rename that folder to ffmpeg

**Comment by spudnick1UK** [comment]
I have fixed the issue.
