### ISSUE TITLE
CUDA provider not Selectable

### ISSUE THREAD

**Issue by MrDreadfall** [C0untFloyd/roop-unleashed#596]
Hi Everyone,

For some reason, when I opened the Browser UI under setting, CPU is pre-selected as Provider. There are no other Options. I am have already installed CUDA toolkit and cudnn like the Instruction, it has no effect at all. 
<img width="391" alt="NoCUDA" src="https://github.com/C0untFloyd/roop-unleashed/assets/166607443/7b0d5022-4bde-4845-a19d-07e4c0b61585">

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Comment by lysxelapsed** [comment]
There still seems to be something missing or not supported. What's your graphics card?

**Comment by MrDreadfall** [comment]
I'm using a RTX 4070.

**Comment by kingmike67** [comment]
Any chance you are using the NVidia Studio drivers? I ran into the same issue with my 3060 with Studio Drivers. I switched to Game Ready and its working

**Comment by MrDreadfall** [comment]
Thanks for the answer! I did like you said to reinstall and switch to Game Ready Drivers. Sadly it did not fix the problem -_-

**Comment by MrDreadfall** [comment]
I have discovered something that could be relevant to the subject. Can someone make a sense out of this, sorry I am really a noob!

![Bild_2024-04-10_214519929](https://github.com/C0untFloyd/roop-unleashed/assets/166607443/a298ecac-5263-4e6a-add1-05bf8fe0114e)

**Comment by lysxelapsed** [comment]
You can try the following:
Go to your `roop-unleashed\Lib\site-packages\gradio\components` folder. If there's a `pycache` folder in it, delete it. Open up dropdown.py with an editor, change `allow_custom_value: bool = False` to `allow_custom_value: bool = True` at line 38, save the file and try again.

This has worked for a different user with that error message, but no guarantees.

**Comment by MrDreadfall** [comment]
Sadly, it didn't work. CPU is still the only dropdown option. The only difference is, I can now write in the text box, which does little because Roop still uses the CPU despite me writing "cuda" in the box.

**Comment by lysxelapsed** [comment]
Any errors when running the installer? If so, post it here. Besides that, only the usual tipps are left: Reboot your system, re-install everything needed, use the newest installer (or try the manual install explained in the wiki), have a look at the wiki, especially installation and FAQ.

**Comment by Herold-Lambda** [comment]
This should not be happening, have you installed Cudnn and the Cuda Toolkit? 
(ref: https://developer.nvidia.com/cuda-11-8-0-download-archive)
(ref: https://developer.nvidia.com/rdp/cudnn-archive)
Also, if you already updated your Nvidia drivers, have you installed it properly by doing it manually?

The step by step explanation would be:

1. Install Conda, or mini Conda
2. Git clone the repo in your desired directory 
3. Open Conda and head to the directory
4. Create a Conda Environment with this code "Assuming "myenv" is not already an existing environment use this line:
`conda create --name myenv python=3.9`
Then in the directory (path/roop-unleashed) run: `pip install -r requirements.txt`
And then after installing everything you should be able to run it by using: 
`python run.py`

Usually cu118 torch-2.1.2 is not being installed properly installed by the windows installer, hope this helps.

**Comment by MrDreadfall** [comment]
Thank you very much ! I managed to follow every step and IT WORKS! The problem was the Window installer file all along.

**Comment by Benjamim-EP** [comment]
> Isso não deveria estar acontecendo, você instalou o Cudnn e o Cuda Toolkit? (ref: https://developer.nvidia.com/cuda-11-8-0-download-archive ) (ref: https://developer.nvidia.com/rdp/cudnn-archive ) Além disso, se você já atualizou seus drivers da Nvidia, você os instalou corretamente manualmente?
> 
> A explicação passo a passo seria:
> 
> 1. Instale Conda ou mini Conda
> 2. Git clone o repositório no diretório desejado
> 3. Abra o Conda e vá para o diretório
> 4. Crie um ambiente Conda com este código "Supondo que "myenv" ainda não seja um ambiente existente, use esta linha: 
>    `conda create --name myenv python=3.9`
>    Em seguida, no diretório (path/roop-unleashed) execute: `pip install -r requirements.txt`
>    E depois de instalar tudo, você poderá executá-lo usando:
>    `python run.py`
> 
> Normalmente cu118 torch-2.1.2 não está sendo instalado corretamente pelo instalador do Windows, espero que isso ajude.

God, very thanks friend
