### ISSUE TITLE
Failed downloading ffmpeg

### ISSUE THREAD

**Issue by laxordm** [C0untFloyd/roop-unleashed#598]
Hello, i have always an error when i will start it with ffmpeg when i start windows_run.bat the error

Downloading ffmpeg from https://github.com/GyanD/codexffmpeg/releases/download/2023-06-21-git-1bcb8a7338/ffmpeg-2023-06-21-git-1bcb8a7338-essentials_build.zip to C:\Users\jonas\Desktop\roop-unleashed-main\installer\installer_files
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                          Dload  Upload   Total   Spent    Left  Speed                                             0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0                                          100 82.2M  100 82.2M    0     0  8541k      0  0:00:09  0:00:09 --:--:-- 8494k                                          The system can not find the stated file.
WARNING: The saved data will be truncated to 1024 characters.

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?** the newest

![Bild_2024-04-11_145059552](https://github.com/C0untFloyd/roop-unleashed/assets/166720155/6deb9c44-daa4-4221-a4f8-2a757620b250)

(SCREENSHOT IS IN GERMANY I PASTE IT IN ENGLISH ON TOP)

**Comment by lysxelapsed** [comment]
Phew that's a long filename in addition to your folder structure. Try installing in a shorter path, C:\roop-unleashed for example.
If you're still having trouble, you can install [ffmpeg](https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z) and add it to `Path` in your [environment variables](https://phoenixnap.com/kb/ffmpeg-windows) (step3) yourself, then run the windows_run.bat again.

**Comment by spudnick1UK** [comment]
simple Fix
Look in roop folder 
go to the installer folder /installer files and you will see a FFMPEG  folder that has a longer Name
just rename to ffmpeg
you should be OK
