### ISSUE TITLE
DIST_THRESHOLD set at the current 0.65 doesn't swap all frames

### ISSUE THREAD

**Issue by eniora** [C0untFloyd/roop-unleashed#60]
**Describe the bug**
The current DIST_THRESHOLD in **face_swapper.py** using unleashed 2.0.3 doesn't swap all frames especially if the face orientation is changing. I found that the old 0.85 value works best.
This is just a suggestion to make the default value 0.85 or 0.8 instead of 0.65 which will make the swapping much better and more effective.

**To Reproduce**
Just try on any video with some face orientations.

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by C0untFloyd** [comment]
This can be adjusted in the upcoming version

**Comment by eniora** [comment]
Thank you! btw I saw that the new upcoming roop 2.0.0 version will be using gradio UI (saw a sneak peek in their discord), hopefully you can make a good fork out of it as usual. :)

**Comment by C0untFloyd** [comment]
Perhaps they should rather fork from me soon:

![grafik](https://github.com/C0untFloyd/roop-unleashed/assets/131583554/6b7033b7-520c-4ed4-ac8d-78c8e7b36083)

😛

**Comment by eniora** [comment]
OMG this is so sexy!!!!!! :D
I like the "Use face from this frame" and the ability to change similarity threshold and blend ratio. Very clever!

TBH I tried the Swap-Mukham fork a week or so ago which is built on gradio but it doesn't have the ability to choose the target face in a video and no ability to change the enhancement strength, it also doesn't have browse button for video, you have to insert the path manually, and form what I have tested unleashed is much faster at processing with same quality. I am very much looking forward to unleashed 2.2.0
Cheers!

**Comment by eniora** [comment]
Would we be able to choose the face from the frame? like if the frame has multiple faces like in the current 2.0.3 version.

**Comment by C0untFloyd** [comment]
Yes if there's only 1 it will be used straight away, if there is more than 1 a selection pops up. And it's not limited to 7 faces max like previously.

**Comment by eniora** [comment]
That's very nice
