### ISSUE TITLE
Getting errors when trying to launch

### ISSUE THREAD

**Issue by Oedipus7** [C0untFloyd/roop-unleashed#600]
**Describe the bug**
it has been a while since I used this, when I run my usual run.py the program no longer works. I did a reinstall same issue. (extra info: recently upgraded gpu)

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [1] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [1 ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
v3.6.7

**Screenshots**
I get this then the cmd closes
![image](https://github.com/C0untFloyd/roop-unleashed/assets/117510990/55deee44-f615-447c-8312-c30441a65acc)
is there some process that didn't terminate before or temp info messing everything?

**Comment by lysxelapsed** [comment]
This is a manual install, right? Seems like the gradio version isn't up to date. Did you update the requirements with `pip install -r requirements.txt`?
