### ISSUE TITLE
Web UI so slow

### ISSUE THREAD

**Issue by Johannpcs** [C0untFloyd/roop-unleashed#601]
What OS are you using?
- [x] Windows 
Are you using a GPU?
- [x] NVIDIA

Before the update, I could upload a face, or a video and there was no lag. Now even uploading a face freezes the web UI. When uploading a video it literally freezes the Web UI for at least 1 minute. You were able to use the slider to look at frames of the video in seconds. Now it freezes for 30 seconds before even going to the frame (no face swap just the frame slider).

Is there a fix? Since all of these updates seem like a downgrade.

**Comment by C0untFloyd** [comment]
Sure. #564
