### ISSUE TITLE
Manual masking - User error or it's not working?

### ISSUE THREAD

**Issue by Rooper-ai** [C0untFloyd/roop-unleashed#604]
**Describe the bug**

Perhaps I am not understand how manual masking should work or the steps to get it to work, but had no luck so far. I have read the 3.6.0 release note comments here: (https://github.com/C0untFloyd/roop-unleashed/discussions/512) but its not helping

**To Reproduce**

1.Add input face (woman's face)
2.Add target face (man's face)
3. 'Use face from this frame' for target face
4. Go to Advanced Masking dropdown
5. hit Toggle manual masking button
6. Select Draw button in manual mask image
7. Draw mask over man's left eye and eyebrow
8. Hit Start button

At this point I would expect to see the Final image with a man's left eye (masked) and a woman's right eye (not masked)

But I'm getting two female eyes with no masking (???)

**Details**
What OS are you using?
- [ Yes] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [Yes ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**

3.6.7

**Screenshots**

**Comment by C0untFloyd** [comment]
You are right, I tested myself and it's not working. It IS working if you're using it with face swap frames enabled in the preview image. I remember thinking that since this is images only, nobody would need this in the batch processing. Anyway, I will integrate this into real processing too.

**Comment by iemtejas** [comment]
Manual masking is not working on single images

**Comment by C0untFloyd** [comment]
> It IS working if you're using it with face swap frames enabled in the preview image.

**Comment by Rooper-ai** [comment]
These steps work:

1. Add input face (woman's face)
2. Add target face (man's face)
3. 'Use face from this frame' for target face
4. Go to Advanced Masking dropdown
5. hit Toggle manual masking button
6. Select Draw button in manual mask image
7. Draw mask over man's left eye and eyebrow
8. Hit Face swap frames tick box (below Preview Image) [BTW looks greyed out on my browser]

..processed manual masked image then appears in the Preview Image area (works)

However this isn't the workflow I would have expected. I would expect to hit the Start button and see the processed manual mask image in the Final image area (doesn't work)

For example does post-processing work in preview, UI would suggest not, even if it does.

Also thanks for all your efforts on this fork. It's appreciated

**Comment by iemtejas** [comment]
> > It IS working if you're using it with face swap frames enabled in the preview image.

It's not working for me. I've tried these steps, but it's still not just changing the masked area, but the whole face. Unfortunately, it's not working for me. Could you please add a button to it, similar to text masking? This way, we can select and mask the area we want to swap, and it'll only swap the masked area. This method would be the best, similar to XEG masking

**Comment by C0untFloyd** [comment]
> Could you please add a button to it, similar to text masking? This way, we can select and mask the area we want to swap, and it'll only swap the masked area. This method would be the best, similar to XEG masking

But it is exactly like that?!? Click on toggle manual masking, draw the mask onto the areas YOU WANT TO KEEP, hit refresh and be surprised.

**Comment by iemtejas** [comment]
What's your Instagram username?

**Comment by C0untFloyd** [comment]
> For example does post-processing work in preview, UI would suggest not, even if it does.

Preview does EVERYTHING the regular processing does, except for the batch processing. I often don't even click on start but save the image right away from the preview area. Btw. to see the preview image in all its glory you can also do a right click and "Open in new Tab".

**Comment by Sam929228** [comment]
Hello i am new to this awsome software can u guys teel me how i can extract or delete unwanted frames from my videos please reply soon using roop unleashed v4 and i have rtx3070 ti 8gb laptop gpu how any threads should in keep it at far faster rendering

**Comment by C0untFloyd** [comment]
> Hello i am new to this awsome software can u guys teel me how i can extract or delete unwanted frames from my videos please reply soon using roop unleashed v4 and i have rtx3070 ti 8gb laptop gpu how any threads should in keep it at far faster rendering

https://github.com/C0untFloyd/roop-unleashed/wiki/Face-Swap-Tab
https://github.com/C0untFloyd/roop-unleashed/wiki/FAQ#why-is-my-graphics-card-gpu-not--hardly-being-utilized
