### ISSUE TITLE
I cant seem to find Text masking area. Was it removed?

### ISSUE THREAD

**Issue by ThePetePandaPablo** [C0untFloyd/roop-unleashed#608]
**Describe the bug**
I used to have a section called text masking. It allowed you to redraw frames if hands or arms where in the way. I'm not sure if it's just been moved or removed? Which update was it last in?

**To Reproduce**
1. Download latest version
2. The text masking not there 

**Details**
What OS are you using?
- Windows 11 

Are you using a GPU?
- [ rtx 3090] NVIDIA

**Which version of roop unleashed are you using? New

**Screenshots**
![Screenshot_20240413_092946_Opera](https://github.com/C0untFloyd/roop-unleashed/assets/98638520/4f5fecec-1e2f-4275-b873-49da35818093)

**Comment by sparking-meteor** [comment]
Iirc it's now been moved to the top right corner, click manual masking then text-masking option should appear, not sure though (i would check but making roop work on kaggle is a pain the )

**Comment by C0untFloyd** [comment]
You know, there is a search at the top and you don't need to ask twice.
#544

**Comment by ThePetePandaPablo** [comment]
Bingo found it thanks <3
