### ISSUE TITLE
swapping wrong face

### ISSUE THREAD

**Issue by deepraj31** [C0untFloyd/roop-unleashed#609]
**Swapping wrong face**
Can someone tell me why the face I selected for swapping isn't swapping, and instead another face is swapping?

**Details**
- OS using:
Windows 

- GPU:
NVIDIA

**Version: roop unleashed 3.6.7**

**Screenshots**
![Screenshot_13-4-2024_201445_127 0 0 1](https://github.com/C0untFloyd/roop-unleashed/assets/71033285/a72d4aca-2dc5-4951-9bc6-a187c0ac7241)

**Comment by lysxelapsed** [comment]
https://github.com/C0untFloyd/roop-unleashed/issues/474#issuecomment-2053707126
