### ISSUE TITLE
Not able to swap face it gets stuck on processing and the times goes on and on hitting start nothing happens the video and photos remains the same the do not change I tried reinstalling many times but nothing chabged

### ISSUE THREAD

**Issue by 2005animesh** [C0untFloyd/roop-unleashed#610]
**Describe the bug**

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [x] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**

**Screenshots**

**Comment by C0untFloyd** [comment]
You're not using any GPU. Trying to run this on CPU only works, but takes ages. Have a look into the terminal output to see what it's doing and at what speed.
#461
