### ISSUE TITLE
Reinstall Slowed Down App and Stopped Webcam

### ISSUE THREAD

**Issue by gjnave** [C0untFloyd/roop-unleashed#616]
Hey guys,
i had this actually running really well and had to (long story) start from scratch. 
However, this time I have the following problems which are boggling:
1) if i choose a video and use the "use face from frame" and select a single face, it no longer will do anything when I click "start". However, if I go back to one face in a frame, and select it, it works

2) The webcam option used to run fast but now, even without a mask face, the camera lags massively.. like 10 seconds per frame or greater.

Thanks for any ideas

**Comment by C0untFloyd** [comment]
1. What does "no longer will do anything" mean? Start button not working, no video processing...
2. Yes, that's a problem with the latest gradio version. I'd suggest installing one of the free virtual cams like OBS which doesn't have any of these limitations

**Comment by gjnave** [comment]
> 1. What does "no longer will do anything" mean? Start button not working, no video processing...
The "Submit" /"Start" button disappears to a sliver and the server does nothing. Just sits there.
If i redo the settings and re-select the "Use face from frame" but this time find a frame with only one person in it... then click the sliver of a button, it will work. So "nothing" means, literally nothing.

> 2. Yes, that's a problem with the latest gradio version. I'd suggest installing one of the free virtual cams like OBS which doesn't have any of these limitations
What do you mean "limitations"? 

Thank you for your work btw.. totally awesome

**Comment by C0untFloyd** [comment]
1. The start button disappears into a "sliver" ?!? Is there any error output? Can you perhaps make a screenshot?
2. I'm talking about the limitations of [gradio](https://www.gradio.app/) the UI framework I'm using. For the webcam display I'm abusing an image control which isn't really meant to as a streaming target. The older gradio versions could at least keep a steady display of ~ 10fps but the newer ones don't even display an image (at least not for me). So just install https://obsproject.com which is free and roop unleashed will stream your fake camera at its full speed to the virtual camera.

**Comment by gjnave** [comment]
![image](https://github.com/C0untFloyd/roop-unleashed/assets/59668562/fa2d944e-77e7-420a-bad2-0a513cae15c9)
![image](https://github.com/C0untFloyd/roop-unleashed/assets/59668562/af8b788a-1894-46cb-a8f8-bdd7b1a32317)

In the terminal, the det shown is from selecting the image. So when I clicked the START button, it just slivers.. nothing else. However the server will still respond if I do something else.

**Comment by C0untFloyd** [comment]
Does it work when you click on 'Done'? The face gallery is meant for temporarily choosing input faces. After selecting your desired face(s) it should be closed.

**Comment by gjnave** [comment]
> Does it work when you click on 'Done'? The face gallery is meant for temporarily choosing input faces. After selecting your desired face(s) it should be closed.

Appreciate you getting back to this. So the virtual camera worked as you said. Got that working with the OB suite. And you're correct about the issue with the slivering... I didn't see the button to the right. Now there's a box line there and it looks like odd place to put it because you have the left side of the app d the right side. But that's just nitpicking over little things. Appreciate it

**Comment by frosty3907** [comment]
> > Does it work when you click on 'Done'? The face gallery is meant for temporarily choosing input faces. After selecting your desired face(s) it should be closed.
> 
> Appreciate you getting back to this. So the virtual camera worked as you said. Got that working with the OB suite. And you're correct about the issue with the slivering... I didn't see the button to the right. Now there's a box line there and it looks like odd place to put it because you have the left side of the app d the right side. But that's just nitpicking over little things. Appreciate it

Sorry could you explain the steps for using the virtual cam with OBS? I'm just getting black output.

**Comment by C0untFloyd** [comment]
Do you still need help? It looks like you solved your issues reading the other reply.

**Comment by frosty3907** [comment]
yes all sorted thanks!
