### ISSUE TITLE
Info No faces detected!

### ISSUE THREAD

**Issue by MateuszKudelko** [C0untFloyd/roop-unleashed#618]
**Describe the bug**

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X] Windows 
- [ ] Mac

Are you using a GPU?
- [X] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

I have a problem with the app when I add a photo I get a message that the face was not detected.
In the console I get this message: 
when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
EP Error D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=833275960 ; hostname=ACER ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=236 ; expr=cudaSetDevice(info_.device_id);
"

**Which version of roop unleashed are you using?**
[roop unleashed 3.6.7](https://github.com/C0untFloyd/roop-unleashed)
**Screenshots**
![SC](https://github.com/C0untFloyd/roop-unleashed/assets/81158042/7c6dd8fd-a399-4278-b203-b713a4e4ee90)

**Comment by C0untFloyd** [comment]
You checked that you're using your CPU but the error message says you are trying to use an older NVIDIA GPU:
> CUDA driver version is insufficient for CUDA runtime version ; GPU=833275960 ; hostname=ACER ; file=D:

Either change your provider setting (Tab Settings) to cpu or try updating your GPU with newer drivers.
