### ISSUE TITLE
Unable to use GPU as provider for swap

### ISSUE THREAD

**Issue by khanajan** [C0untFloyd/roop-unleashed#619]
**Describe the bug**
I am able to work the software while i set the provider to " CPU " and tick " Force CPU face analyzer ", but of course the conversion takes up time.
I encounter issues when i set provider to "GPU", i start encountering issues as follows,
1. Source file shows the file name but i am unable to see the image in the INPUT FACE - image of software+backend attached
2. The preview image does not mask the face even after ticking FACE SWAP FRAMES 
3. When i START processing it works but end product is the same video without any swap.

find model: C:\roop-unleashed-main\installer\roop-unleashed\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
2024-04-21 11:20:08.1587507 [E:onnxruntime:, sequential_executor.cc:514 onnxruntime::ExecuteKernel] Non-zero status code returned while running Resize node. Name:'Resize_124' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device

Currently i am using precision 5520, 32 RAM, contains quadro M1200

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ++++ ] Windows 10 Pro 22H2
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ +++++ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?** 3.6.7

**Screenshots**
![Image not uploading](https://github.com/C0untFloyd/roop-unleashed/assets/167640741/c7c48cab-2cef-4a85-880f-1d6d839aa201)
![image not upload backend](https://github.com/C0untFloyd/roop-unleashed/assets/167640741/68fdec39-3fa6-402c-96d8-800b2fc80a12)
![CUDA](https://github.com/C0untFloyd/roop-unleashed/assets/167640741/c45d29bc-c182-4ef9-9926-2bf1794d6e06)

**Comment by C0untFloyd** [comment]
Your Quadro M1200 doesn't provide the functionality CUDA needs to use here. It's just not up to the task. You could try using directml as a provider but I don't think it will run much faster than using cpu.
