### ISSUE TITLE
Multi-face images

### ISSUE THREAD

**Issue by Didier-Eloy** [C0untFloyd/roop-unleashed#620]
Hello 
I think there's a little problem with the multi-faces.
For the first face (here Woman) . it's OK .
![multiface 1](https://github.com/C0untFloyd/roop-unleashed/assets/93537096/435f7be6-2e70-4973-9dbd-72d8f5822b0e)

For the 2nd face ( here man ) The 2 faces are replaced by the first 2 photos of the input face .

![multiface 2](https://github.com/C0untFloyd/roop-unleashed/assets/93537096/460d08ea-e8f6-436b-a88d-74f8f1d70296)

![multiface 3](https://github.com/C0untFloyd/roop-unleashed/assets/93537096/54f91836-9f83-4730-ad1c-c1954fd6a263)

Then, everything remains stuck in this state .
***********************************************************************************************************
A few suggestions to make it easier to use .

1 . When reloading a New "target file" after a multi-face .
The target face window is cleaned up . ok
The "Detected faces" window should also be cleaned. (Equivalent to "Done" . ) and set "Specify face selection for swapping" to "First found".
*******************************************************
2 . Would it be possible to set . The :
"Face swap frames" enabled when the software is opened ?
As well as: "Select post-processing" by default. ( The one you think is the best !! ) 
******************************************************
3 . I can't see any effect on the image with the . "Max Face Similarity Threshold" and "Original/Enhanced image blend ratio" ?
Maybe I'm not using them ?
****************************************************
Thanks for sharing your work if you need me to test something don't hesitate .

**Comment by C0untFloyd** [comment]
First, please take a look into the [wiki](https://github.com/C0untFloyd/roop-unleashed/wiki/Face-Swap-Tab)

> For the 2nd face ( here man ) The 2 faces are replaced by the first 2 photos of the input face

This is correct. You can only switch around faces when there is only 1 target faces. More target faces and they will be swapped in the order of your input faces. It's a 1 to 1 relationship.

> Then, everything remains stuck in this state

I don't know what you mean with this.

Your suggestions:

1. You mean clearing the input faces? What if you want to continue using them? Resetting the face selection is a good idea.
2. IMHO it would be smarter to give users the ability to save their personal UI setting. I for example almost never use post-processing and having face swap enabled while scrolling through a big video is also not my favourite setting. I'd rather implement a user setting later but for this the UI needs to be almost finished, which it isn't yet.
3. In the wiki there is an explanation what these values do.

**Comment by Didier-Eloy** [comment]
Hello, thank you for your feedback 

Sorry I couldn't reply sooner, I was traveling.

I didn't know about the wiki, but it gave me some clarification.

I use an automatic translator to reach you. It can sometimes distort my words.

Version 3.9.0 works very well.
The new “Number of swapping steps” setting is very effective; above a value of 4, distortions are noticeable. 
Suggestion 1: For an even more precise setting, can we increment the step by one decimal?

Suggestion 2: For the multi-faces, we could use the method described in algorithm number one in the attachment. If it's not very clear, I can provide some clarification.

Suggestion 3: I've found that if you put several faces in the “Target face”, you can select each face one by one by clicking on the photo of the face. You can then match a “target face” to an “input face” and process the change. Face
Combined with suggestion: 2 we could have a very intuitive multi-face method. See Algorithm 2 in attachment


Best Regard

----- Mail original -----
De: "C0untFloyd" ***@***.***>
À: "C0untFloyd/roop-unleashed" ***@***.***>
Cc: "Didier-Eloy" ***@***.***>, "Author" ***@***.***>
Envoyé: Dimanche 21 Avril 2024 11:59:30
Objet: Re: [C0untFloyd/roop-unleashed] Multi-face images (Issue #620)





First, please take a look into the wiki 



For the 2nd face ( here man ) The 2 faces are replaced by the first 2 photos of the input face 

This is correct. You can only switch around faces when there is only 1 target faces. More target faces and they will be swapped in the order of your input faces. It's a 1 to 1 relationship. 



Then, everything remains stuck in this state 

I don't know what you mean with this. 

Your suggestions: 

    1. You mean clearing the input faces? What if you want to continue using them? Resetting the face selection is a good idea. 
    2. IMHO it would be smarter to give users the ability to save their personal UI setting. I for example almost never use post-processing and having face swap enabled while scrolling through a big video is also not my favourite setting. I'd rather implement a user setting later but for this the UI needs to be almost finished, which it isn't yet. 
    3. In the wiki there is an explanation what these values do.

**Comment by Didier-Eloy** [comment]
Hello, 

Did you receive my e-mail of April 30? 

I don't see that it's been read.

Best regard

----- Mail original -----
De: "C0untFloyd" ***@***.***>
À: "C0untFloyd/roop-unleashed" ***@***.***>
Cc: "Didier-Eloy" ***@***.***>, "Author" ***@***.***>
Envoyé: Dimanche 21 Avril 2024 11:59:30
Objet: Re: [C0untFloyd/roop-unleashed] Multi-face images (Issue #620)





First, please take a look into the wiki 



For the 2nd face ( here man ) The 2 faces are replaced by the first 2 photos of the input face 

This is correct. You can only switch around faces when there is only 1 target faces. More target faces and they will be swapped in the order of your input faces. It's a 1 to 1 relationship. 



Then, everything remains stuck in this state 

I don't know what you mean with this. 

Your suggestions: 

    1. You mean clearing the input faces? What if you want to continue using them? Resetting the face selection is a good idea. 
    2. IMHO it would be smarter to give users the ability to save their personal UI setting. I for example almost never use post-processing and having face swap enabled while scrolling through a big video is also not my favourite setting. I'd rather implement a user setting later but for this the UI needs to be almost finished, which it isn't yet. 
    3. In the wiki there is an explanation what these values do.

**Comment by JashS286** [comment]
Hello, I have been trying to verify a website, when it gets to selfie part and I upload the rooped video, it says multiple faces detected. What could be the problem?

**Comment by C0untFloyd** [comment]
?

**Comment by JashS286** [comment]
I’m not able to pass KYC (persona) with a rooped video I made with roop-unleashed. When I get to selfie part it keep saying ‘move closer’ then says ‘multiple faces detected’.

**Comment by C0untFloyd** [comment]
You want us to help you with fraud?!? Unbelievable...
