### ISSUE TITLE
Unable to launch into Web UI

### ISSUE THREAD

**Issue by Arndtagonist** [C0untFloyd/roop-unleashed#622]
**Describe the bug**
I'm unable to launch roop unleashed. The web UI doesn't open. I've reinstalled roop without success.

**To Reproduce**
1. start windows_run
2. choose if you want to check for updates (it makes no difference for me)
3. After a while this message comes up:
![grafik](https://github.com/C0untFloyd/roop-unleashed/assets/167778684/c564adb9-f9f8-4e04-a65a-a1abc45657b1)

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**

I was using the current version 3.6.7 and installed this version again.

**Screenshots**

Thanks in advance for your help and your great project!

**Comment by nitatemic** [comment]
Huggingface was down, it should work now
