### ISSUE TITLE
AMD - DML DIDN'T SHOW UP

### ISSUE THREAD

**Issue by IZUR0** [C0untFloyd/roop-unleashed#625]
**Describe the bug**
I've been trying to get my amd card to work for 3 hours now, but unfortunately, even though I've followed all the "issues", it still doesn't work. dml still isn't there, there's just "tensort", "cuda" and "cpu". 

-I've reinstalled roop
-installed hip amd emulators to convert to cuda
-I installed and reinstalled the requirements
-same for torch and onnxruntime-directml==1.15.1
-scraped the internet

-but I can't edit the python files and I don't know which path to put in "anaconda".

well... I hope someone can help me, thanks in advance (translator)

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [x] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
3.9

**Comment by C0untFloyd** [comment]
> there's just "tensort", "cuda" and "cpu".

It sounds like you didn't activate the conda environment, meaning everything you've installed is out of reach for roop unleashed. The windows installer creates and activates an environment automatically. Easiest would probably be running windows_run.bat from commandline and hitting Ctrl-C when it opens the browser page. That way the environment is activated and you can uninstall/install everything inside it ( inside the commandline window).

> Been trying the same and also need help, why does no one make a fork that has DML insted of cuda.

Probably because it's not worth the effort yet and as you're experiencing, very tricky. DML using AMD doesn't reach the speed of NVIDIA cards with CUDA, most machine learning and AI is very NVIDIA fixated at the moment.

**Comment by Saelll96** [comment]
> It sounds like you didn't activate the conda environment, meaning everything you've installed is out of reach for roop unleashed. The windows installer creates and activates an environment automatically. Easiest would probably be running windows_run.bat from commandline and hitting Ctrl-C when it opens the browser page. That way the environment is activated and you can uninstall/install everything inside it ( inside the commandline window).

"Insightface package installation failed
Terminate batch job (Y/N)?"

It doesnt matter what option i chose both close the command prompt and do nothing.

**Comment by IZUR0** [comment]
> > there's just "tensort", "cuda" and "cpu".
> 
> It sounds like you didn't activate the conda environment, meaning everything you've installed is out of reach for roop unleashed. The windows installer creates and activates an environment automatically. Easiest would probably be running windows_run.bat from commandline and hitting Ctrl-C when it opens the browser page. That way the environment is activated and you can uninstall/install everything inside it ( inside the commandline window).
> 
> > Been trying the same and also need help, why does no one make a fork that has DML insted of cuda.
> 
> Probably because it's not worth the effort yet and as you're experiencing, very tricky. DML using AMD doesn't reach the speed of NVIDIA cards with CUDA, most machine learning and AI is very NVIDIA fixated at the moment.

then
in order :
- I open miniconda
- put in the roop directory
- write "conda activate
- uninstall and reinstall torch and torchvision
- I uninstall and reinstall onnxruntime dml but it can't find a version, and when I try to install it, it tells me that:
![image_2024-04-23_143415650](https://github.com/C0untFloyd/roop-unleashed/assets/167806745/e5703d81-c2d6-422c-85e8-2c39d59194fd)

**Comment by C0untFloyd** [comment]
1. open commandline and navigate to roop folder
2. start windows_run.bat by typing it into the console
3. Once browser opens, hammer on ctrl-c until roop quits and you're back in the commandline window but with the correct env activated
4. type 'pip install onnxruntime-directml'
5. Profit

**Comment by IZUR0** [comment]
> 1. open commandline and navigate to roop folder
> 2. start windows_run.bat by typing it into the console
> 3. Once browser opens, hammer on ctrl-c until roop quits and you're back in the commandline window but with the correct env activated
> 4. type 'pip install onnxruntime-directml'
> 5. Profit

THANK YOU A LOT MAN, I WISH YOU HAPPINESS IN YOUR LIFE
I'm not very talented so thank you for reaching out to me already that it's you who made this wonderful application, thank you for the time you devote to not talented people like me

just a little thing, is it normal that my gpu spikes at 100% instead of staying at 100% like my cpu did when I had the "cpu" parameter
![image_2024-04-23_161321453](https://github.com/C0untFloyd/roop-unleashed/assets/167806745/59c1d7f4-b2f7-4c7a-b42e-1d633c90ea1b)

thanks again bro

**Comment by C0untFloyd** [comment]
You're welcome and yes the spikes are normal because sometimes saving and other CPU processing interrupts the GPU. How fast is it compared to previously? It would be interesting to compare your results with others in the [benchmark thread](https://github.com/C0untFloyd/roop-unleashed/discussions/461)

**Comment by IZUR0** [comment]
> You're welcome and yes the spikes are normal because sometimes saving and other CPU processing interrupts the GPU. How fast is it compared to previously? It would be interesting to compare your results with others in the [benchmark thread](https://github.com/C0untFloyd/roop-unleashed/discussions/461)

I don't know how to see the performance of the 4 threads especially since I am limited to only 1
but I tested the benchamrk video, I reached 50 seconds without touching any parameters
and as for the difference in performance between the cpu and the gpu, it is HUGE :)
before a 1 minute 17 scd video took me almost 2 hours
now it only took 7 minutes, it's a real treat :)

**Comment by C0untFloyd** [comment]
Ah ok, yes I forgot you're limited to 1 thread only. Thanks for trying and nice that it's working for you 👍
