### ISSUE TITLE
face restoration seems slow / fails on batch image folder

### ISSUE THREAD

**Issue by jmp909** [C0untFloyd/roop-unleashed#63]
**Describe the bug**
1) face restoration seems slow 7-10 seconds on eg a 1024x640 image (face is under 256x256px)
using A111's/Vladmandic's Automatic it's about 1.3s (after an initial warmup / model load). 
even with warmup on roop-unleashed with the first image for instance, subsequent images in the batch are still around 7-10 seconds.

is it possible Codeformer restorationon A1111 is targeting just the face and compositing whereas yours is loading the whole image? (not sure what the difference is here)

2) when processing a folder of images using batch mode, the face restoration does not seem to be applied (that is it seems to run but the restored image is not saved out)

**To Reproduce**
1. Load a source image 
2. Click on 'Batch process folder'
3. Select target folder and output
4. Start

**Details**
What OS are you using? Windows, RTX 3080 FE

Are you try to use a GPU?
NVIDIA - using `--execution-provider cuda`

**Comment by C0untFloyd** [comment]
1. Are you talking about the SD Extension? It doesn't have in-built CodeFormer functionality?!?
2. Yes, this is a known bug.
