### ISSUE TITLE
windows_run doesn't launch the program

### ISSUE THREAD

**Issue by kokopuffs15** [C0untFloyd/roop-unleashed#635]
I've downloaded the newest version, 3.9.0 and I am trying to launch the program with the 1 click windows installer

The first time I launched it, it downloaded everything and then the window closed.

Now when I try and launch it, it doesn't launch. I've added a gif of what happens.

I've tried restarting my computer, re downloading roop unleashed, running as administrator, to no avail.
![2024-04-25 17-04-35](https://github.com/C0untFloyd/roop-unleashed/assets/75354567/5d20299a-734a-4558-8fba-5fea35043a50)

Any help is appreciated.

**Comment by kokopuffs15** [comment]
This is what it looks like when I run the installer from a freshly unzipped download.

![2024-04-25 17-17-23 - Trim](https://github.com/C0untFloyd/roop-unleashed/assets/75354567/37b95ba8-9000-4a63-b9a2-006a3d5b6336)

I think it may not be installing everything on first launch

**Comment by C0untFloyd** [comment]
Instead of clicking on the .bat file try opening a commandline first, navigate to the installed roop folder and launch from there by typing windows_run.bat
That way the window doesn't close and you could copy/paste the output here.

**Comment by kokopuffs15** [comment]
Fixed the issue.

I had FFmpeg installed elsewhere on my computer which I believe was stopping it from being installed into the "roop-unleashed-main > installer >installer_files" folder.

I put ffmpeg in that folder and then checked roop unleashed which was working perfectly fine on my laptop, and it turns out my path in my Environment Variables on my Laptop had roop unleashed set properly. I think FFmpeg being installed elsewhere was preventing this from happening automatically on my PC.

To do this, search "Variables" in the windows search bar and "Edit the system environment variables" will come up, click that, then in the Advanced tab of System Properties click on "Environment variables..."

There are User variables and System variables. Choose either one, not sure if it matters.

Under "variable" click path and then click edit, then click new.

Your path should look something like this

C:\roop-unleashed-main\installer\installer_files\ffmpeg\bin

Then click "Move up" until its at the top. Press ok and you should be good to go.

Hope this helps, and thanks Floyd for the tip on opening the commandline first. I didn't know how to do that, I'm totally new to all this coding stuff, lol.

**Comment by z-komm** [comment]
Change the windows_run.bat (set PATH before echo)
to
REM No CLI arguments supported anymore
set COMMANDLINE_ARGS=

cd /D "%~dp0"
set PATH=%PATH%;%SystemRoot%\system32

echo "%CD%"| findstr /C:" " >nul && echo This script relies on Miniconda which can not be silently installed under a path with spaces. && goto end
