### ISSUE TITLE
Javascript Error On Roop Unleashed 3.9.0 on Preview and the Start Button

### ISSUE THREAD

**Issue by testygit01** [C0untFloyd/roop-unleashed#636]
**Describe the bug**
The roop unleashed page loads just fine. I can upload the source files and the target file. But the preview doesn't work and nothing happens when I click the start button. If I open javascript console, I get the following error when I click on refresh button on the preview section or the start button to start the face swapping process. I am using kaggle and ngrok. 

**To Reproduce**
1. Go to the roop unleashed app. Upload the source file and the target file.
2. Click on the 'Refresh' button on the preview image section or the 'Start' button to start the face swapping process. Nothing happens. No preview is loading either. 
3. Open javascript console and click the 'Start' button or the 'Refresh' button again and you will see the following error on the javascript console. 
4. 
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'options')
    at _e (index.js:365:12)
    at nt (index.js:489:11)
    at vS.b (InteractiveImageEditor.svelte:70:6)
    at async cC.Z (Index.svelte:82:14)
    at async Promise.all (/index 14)
    at async Co (Blocks.svelte:227:16)

I am using kaggle notebook and ngrok. I am using GPU T4 X 2 and a Mac computer.  

**Which version of roop unleashed are you using?**

I am using roop 3.9.0

**Screenshots**
![Screen Shot 2024-04-25 at 11 09 22 PM](https://github.com/C0untFloyd/roop-unleashed/assets/85206865/e8c6064a-3c2b-418e-8279-4b27c2037ac4)

**Comment by testygit01** [comment]
It worked fine until about 12 hours ago. Having this issue on both chrome and edge.

**Comment by testygit01** [comment]
![Screen Shot 2024-04-25 at 11 42 40 PM](https://github.com/C0untFloyd/roop-unleashed/assets/85206865/a07b9296-ba06-481f-b5b3-cb87c8dbbda5)

**Comment by C0untFloyd** [comment]
It's a gradio issue, perhaps only affecting Macs. Their forum is currently exploding with browser issues like https://github.com/gradio-app/gradio/issues/8129
https://github.com/gradio-app/gradio/issues/8134 and probably some more.
Try reverting to an older version for example 'pip install gradio==4.24.0'. You could also try the newest one 4.28.0 by just typing 'pip install gradio'. Let us know if it's working.

**Comment by testygit01** [comment]
It's working with gradio 4.26 now. Thanks a lot for your reply.
