### ISSUE TITLE
I tried ti run the CMD % python3 ~/roop-unleashed-main/run.py and got this error.

### ISSUE THREAD

**Issue by jbm0674** [C0untFloyd/roop-unleashed#639]
I downloaded on my Mac M2 chip and got this error; AttributeError: module 'gradio' has no attribute 'ImageEditor'. Is there a way to fix this?

juliu@MacBook-Air ~ % python3 ~/roop-unleashed-main/run.py
Downloading https://huggingface.co/countfloyd/deepfake/resolve/main/inswapper_128.onnx: 529MB [00:09, 58.0MB/s]
Downloading https://huggingface.co/countfloyd/deepfake/resolve/main/GFPGANv1.4.onnx: 325MB [00:05, 64.3MB/s]
Downloading https://github.com/csxmli2016/DMDNet/releases/download/v1/DMDNet.pth: 576MB [00:08, 70.4MB/s]
Downloading https://huggingface.co/countfloyd/deepfake/resolve/main/GPEN-BFR-512.onnx: 271MB [00:05, 52.9MB/s]
Downloading https://huggingface.co/countfloyd/deepfake/resolve/main/restoreformer_plus_plus.onnx: 281MB [00:05, 51.6MB/s]
Downloading https://huggingface.co/countfloyd/deepfake/resolve/main/xseg.onnx: 67.1MB [00:01, 42.0MB/s]
Downloading https://huggingface.co/countfloyd/deepfake/resolve/main/rd64-uni-refined.pth: 4.52MB [00:00, 5.42MB/s]
Downloading https://huggingface.co/countfloyd/deepfake/resolve/main/CodeFormerv0.1.onnx: 359MB [00:05, 65.9MB/s]
Using provider [] - Device:cpu
Traceback (most recent call last):
  File "/Users/juliu/roop-unleashed-main/run.py", line 6, in <module>
    core.run()
  File "/Users/juliu/roop-unleashed-main/roop/core.py", line 352, in run
    main.run()
  File "/Users/juliu/roop-unleashed-main/ui/main.py", line 63, in run
    faceswap_tab()
  File "/Users/juliu/roop-unleashed-main/ui/tabs/faceswap_tab.py", line 77, in faceswap_tab
    maskimage = gr.ImageEditor(label="Manual mask Image", sources=["clipboard"], transforms="", type="numpy",
                ^^^^^^^^^^^^^^
AttributeError: module 'gradio' has no attribute 'ImageEditor'

**Comment by lysxelapsed** [comment]
Did you install the requirements with `pip install -r requirements.txt`?
If you already did, try `pip uninstall gradio`, followed by `pip install gradio==4.26.0` and run it again.

**Comment by jbm0674** [comment]
I had installed the requirements.  I did uninstall Gradio and installed the updated and I got the same error message.

**Comment by lysxelapsed** [comment]
Any (version dependency) errors when installing the requirements? Hmm, gradio is making a lot of trouble lately... maybe try another version (`gradio==4.24.0` or just `gradio`, which installs the newest version)?

**Comment by jbm0674** [comment]
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement onnxruntime-silicon==1.13.1 (from versions: 1.14.1, 1.15.0, 1.16.0, 1.16.3)
ERROR: No matching distribution found for onnxruntime-silicon==1.13.1

**Comment by jbm0674** [comment]
The error messages you're encountering are due to version incompatibilities between the Python packages you're trying to install and the version of Python you have installed.

Breaking Down the Errors:
Python Version Incompatibility: The first part of your error indicates that the Python version you have installed is not compatible with the versions of numpy you are attempting to install. numpy versions from 1.21.2 to 1.21.6 require a Python version between 3.7 and 3.10. Since you are using Python 3.11.6, these versions of numpy will not work.
onnxruntime-silicon Version Not Found: The second part of the error is telling you that the specific version of onnxruntime-silicon (1.13.1) you are trying to install does not exist in the repository. Available versions start from 1.14.1 and above.
Solutions:
For the Python Version Issue:

You could downgrade your Python to a version compatible with the required packages, such as Python 3.10.
Alternatively, you could try installing the latest versions of the packages that are compatible with Python 3.11.6, if specific versions are not a strict requirement for Roop-Unleashed to function properly.
For the onnxruntime-silicon Issue:

Update your requirements.txt file to use an available version of onnxruntime-silicon such as 1.14.1, 1.15.0, or 1.16.0, which are compatible with newer Python versions and are available in the repository.
Updating Your requirements.txt:
Open your requirements.txt and replace the lines for the conflicting packages with the correct versions. For example:
Copy code
numpy
onnxruntime-silicon==1.16.0
Then try reinstalling the dependencies:
javascript
Copy code
pip3 install -r ~/roop-unleashed-main/requirements.txt
These changes should help resolve the version compatibility issues. If specific versions of the libraries are crucial for the application, you might need to consult the application's documentation or support channels to verify compatibility or obtain guidance on the required setup.


Updating the "requirements.txt file worked.  I knew that ChatGPT subscription would start to pay off one day.
