### ISSUE TITLE
Trying to make it work on archlinux .... but I have a lot of missing libraries.

### ISSUE THREAD

**Issue by saronno76** [C0untFloyd/roop-unleashed#641]
**Describe the bug**
I clone the repo, create a python virtual environment venv, activate it, launche pip install -r requirements.txt ...
requirements seems to install fine (no error).
Try to use roop with CPU and it works fine.
Try to use with GPU (rtx 3060 12gb), onnxruntime doesn't find a lot of libraries (libcurand.so.10, etc ).

**To Reproduce**
Error when you try to load your input image ... program switch to CPU Execution Provider because of onnxruntime error
[ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcurand.so.10: cannot open shared object file: No such file or directory

**Details**
What OS are you using?
- [* ] Linux (arch)

Are you using a GPU?
- [ ] No. CPU FTW
- [* ] NVIDIA (rtx 3060)
- [ ] AMD
- [ ] Intel
- [ ] Mac

I use regularly stable diffusion in another python virtual environment ... no problem with cuda.
Probably something 

**Which version of roop unleashed are you using?**
Latest

This is "ldd *.so" output from onnxruntime/capi directory (venv of course)

`(venv) [saronno@kanon capi]$ ldd *.so 
libonnxruntime_providers_cuda.so:
	linux-vdso.so.1 (0x00007ffe699f1000)
	libcublasLt.so.11 => not found
	libcublas.so.11 => not found
	libcudnn.so.8 => not found
	libcurand.so.10 => not found
	libcufft.so.10 => not found
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007e56db55e000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007e56db559000)
	libcudart.so.11.0 => not found
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007e56c1400000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007e56c1714000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007e56db534000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007e56c121e000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007e56db5ae000)
libonnxruntime_providers_shared.so:
	linux-vdso.so.1 (0x00007ffe84ddc000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x000078d1d5400000)
	libm.so.6 => /usr/lib/libm.so.6 (0x000078d1d5314000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x000078d1d56f6000)
	libc.so.6 => /usr/lib/libc.so.6 (0x000078d1d5132000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x000078d1d5769000)
libonnxruntime_providers_tensorrt.so:
	linux-vdso.so.1 (0x00007ffdfddb6000)
	libcudnn.so.8 => not found
	libcublas.so.11 => not found
	libdl.so.2 => /usr/lib/libdl.so.2 (0x0000754b14ad2000)
	libnvinfer.so.8 => not found
	libnvinfer_plugin.so.8 => not found
	libnvonnxparser.so.8 => not found
	libcudart.so.11.0 => not found
	libz.so.1 => /usr/lib/libz.so.1 (0x0000754b14ab6000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x0000754b14ab1000)
	librt.so.1 => /usr/lib/librt.so.1 (0x0000754b14aac000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x0000754b14800000)
	libm.so.6 => /usr/lib/libm.so.6 (0x0000754b14714000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x0000754b14a85000)
	libc.so.6 => /usr/lib/libc.so.6 (0x0000754b14532000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x0000754b14be5000)
onnxruntime_pybind11_state.cpython-311-x86_64-linux-gnu.so:
ldd: warning: you do not have execution permission for `./onnxruntime_pybind11_state.cpython-311-x86_64-linux-gnu.so'
	linux-vdso.so.1 (0x00007fffc785d000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007b1c86399000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007b1c86394000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007b1c8637a000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007b1c86375000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007b1c84e00000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007b1c86287000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007b1c86262000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007b1c84c1e000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007b1c863e7000)
`

PS: I don't think installing cuda as archlinux package is a great idea, the latest package has more recent library ... so, if possibile, I want to work on this venv.

**Comment by lysxelapsed** [comment]
I'm no linux expert by any means. But my guess is that those missing libraries belong to [cudnn](https://developer.nvidia.com/cudnn-downloads?target_os=Linux), not cuda.

**Comment by saronno76** [comment]
maybe you are correct but, in arch linux, they are under cuda package

https://archlinux.org/packages/extra/x86_64/cuda/files/

not 

https://archlinux.org/packages/extra/x86_64/cudnn/files/

**Comment by C0untFloyd** [comment]
Did you take a look [here](https://docs.nvidia.com/deeplearning/cudnn/latest/installation/linux.html) ?

Especially the bit at the end:
[Python Wheels - Linux Installation](https://docs.nvidia.com/deeplearning/cudnn/latest/installation/linux.html#python-wheels-linux-installation)

NVIDIA provides Python Wheels for installing cuDNN through pip, primarily for the use of cuDNN with Python. With this installation method, the cuDNN installation environment is managed via pip. Additional care must be taken to set up your host environment to use cuDNN outside the pip environment.

**Comment by saronno76** [comment]
Thanks ... I will give it a try tomorrow and report back

**Comment by saronno76** [comment]
Nope ... but probably I found a solution

nvidia_cufft_cu11
nvidia_curand_cu11

are distribuited standalone

so, if you pip install both ..... no problem so far. But I will update.

**Comment by saronno76** [comment]
I solved the problem, but not with cudnn, but installing:

![Screenshot_2024-04-27_09-32-05](https://github.com/C0untFloyd/roop-unleashed/assets/168217033/26a3f9af-7c5a-4203-ae92-1033f58aa09d)

Then I manually add their "lib" directory to LD_LIBRARY_PATH in the activation script (I also mod the deactivate part to put the env variable back to his original value when you exit fron the venv.

**Comment by C0untFloyd** [comment]
Whatever is working for you, I'm glad you solved it.
