### ISSUE TITLE
Cannot get DirectML

### ISSUE THREAD

**Issue by TritonTrance** [C0untFloyd/roop-unleashed#642]
**Describe the bug**
Tried everything including windows_run.bat, ctrl-c and pip install onnxruntime-directml

Always shows CPUExecutionProvider in cmd launch window

Please help! It's so slow on my cpu and my 7800xt will no doubt be an improvement. 

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [X ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
3.9.0

**Comment by TritonTrance** [comment]
Python 3.10.14
Torch 2.1.2+cu118
Gradio 4.26.0

**Comment by lysxelapsed** [comment]
Try changin `Max. Number of Threads` to 1 in the settings tab, apply settings, close everything and restart.

**Comment by TritonTrance** [comment]
Tried changing the threads to 1. Dml isn't in the drop down box in the launcher. I've tried all the solutions in the threads and have been at it for 2 days.

**Comment by TritonTrance** [comment]
Panic over. I put the required lines in the batch file and it worked.
Getting around 550% increased performance! Magic!

**Comment by aveeeteeeeee2** [comment]
> Panic over. I put the required lines in the batch file and it worked. Getting around 550% increased performance! Magic!

what were the lines?
