### ISSUE TITLE
Cannot get Apple M2 Max's GPU to kick in

### ISSUE THREAD

**Issue by farsadf** [C0untFloyd/roop-unleashed#645]
**Describe the bug**
Not sure what I'm doing wrong; however, no matter what I do I won't get the GPU to get utilized. I've enabled CoreML, Max. Number of Threads = 32, GFPGAN (and tried with DMDNet with suggested changes in [this](https://github.com/C0untFloyd/roop-unleashed/issues/423#issuecomment-1980210188) response).

My configuration is:
- MacBook Pro 16" 2023
- M2 Max
- 32 GB RAM
- Python 3.10.13

The rate is quite low like 1 to 3s / frames, and it mostly hangs up, not going forward for 3-5s, then recalculates to 1-2s / frames.

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [x] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [x] Mac

**Which version of roop unleashed are you using?**
3.9.0

**Screenshots**
<img width="953" alt="Screenshot 2024-04-27 at 04 45 45" src="https://github.com/C0untFloyd/roop-unleashed/assets/5587389/8d07f87c-570e-443f-81b4-a48e293265c2">

**Comment by lysxelapsed** [comment]
32 Threads?? Try 1 or 2.
32 you can try with an Nvidia A100 with 80GB VRAM or something.

**Comment by Gabbelgu** [comment]
Describe the bug
Same problem, I won't get the GPU to get utilized. I've enabled CoreML, Max. Number of Threads = 18, GFPGAN.

Same problem with Max. Number of Threads = 3, GFPGAN.

My configuration is:

MacBook Pro 16" 2023
M3 Max
128 GB RAM
Python 3.11
The rate is quite low like 1 to 2s / frames, and it mostly hangs up, not going forward for 3-5s, then recalculates to 1-2s / frames.

Details

What OS are you using?

Mac

Are you using a GPU?

Mac

Which version of roop unleashed are you using?

4.3.1

**Comment by stevenvlee0606** [comment]
Im having the same issue too, M1 Max here. Anyone found a fix yet?
