### ISSUE TITLE
When the Face masking engine selects Clip2Seg, clicking show Mask Preview will result in an error message

### ISSUE THREAD

**Issue by zhangjinyan888** [C0untFloyd/roop-unleashed#646]
When the Face masking engine selects Clip2Seg, clicking show Mask Preview will result in an error message

  File "E:\unleashed3.9.0\ui\tabs\faceswap_tab.py", line 543, in on_preview_mask
    current_frame = live_swap(current_frame, options)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\unleashed3.9.0\roop\core.py", line 193, in live_swap
    process_mgr.initialize(roop.globals.INPUT_FACESETS, roop.globals.TARGET_FACES, options)
  File "E:\unleashed3.9.0\roop\ProcessMgr.py", line 109, in initialize
    classname = self.plugins[pn]
                ~~~~~~~~~~~~^^^^
KeyError: 'Clip2Seg'

**Comment by ammarzammam** [comment]
Yes whatever mask I choose this happens suddenly today this happened I wish if there is a solution for this

**Comment by ammarzammam** [comment]
Yes whatever mask I choose this happens suddenly today this happened I wish if there is a solution for this

**Comment by Michael2Miller** [comment]
Yes whatever mask I choose this happens suddenly today this happened I wish if there wil be a solution for this soon

**Comment by lysxelapsed** [comment]
#632 
Should be fixed in newest commit.
