### ISSUE TITLE
Cuda Eroor and ffmpeg error.

### ISSUE THREAD

**Issue by AshleyRomano** [C0untFloyd/roop-unleashed#648]
**Describe the bug**

**To Reproduce**

**Details**
What OS are you using?

- [] Windows 

Are you using a GPU?
- [ ] No. CPU FTW

- [ ] Intel
mostly i try using cpu.

**Which version of roop unleashed are you using?**
3.9.0
**Screenshots**
<img width="364" alt="image" src="https://github.com/C0untFloyd/roop-unleashed/assets/168258448/c4dde7a9-98d4-45fc-8b1d-e9577b4922ee">

**Comment by C0untFloyd** [comment]
Did you install manually? I'm asking because ffmpeg is missing too, you won't be able to process videos.
For the error you're showing you only need to change the provider to cpu in the settings, apply settings and restart everything.

**Comment by AshleyRomano** [comment]
i got it now, and it is working, thank you :)
