### ISSUE TITLE
Unable to Save after clicking START

### ISSUE THREAD

**Issue by DashPz** [C0untFloyd/roop-unleashed#65]
**Describe the bug**
After adding input & target, Not able to save the output because there's no option of saving format after clicking on Start.
Preview shows normally though.

**To Reproduce**
1. Go to 'roop unleashed 2.0.3'
2. Add 'input image with face' & 'target image/video'
3. Then click 'start'
4. There's no 'Save as type' format showing & it won't save. 
5. On the cmd, it shows "FileNotFoundError: [WinError2] The system cannot find the file specified: 'directory'

Please help🙏

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows ✓
- [ ] Mac

Are you trying to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**
If applicable, add screenshots to help explain your problem
![Picsart_23-07-28_15-12-08-604](https://github.com/C0untFloyd/roop-unleashed/assets/140276179/6c2f137c-c55c-4baa-88fb-520b4e0ae428)
.

**Sanity Check**
- [ ] I have the latest code from the github repository
- [ ] I have followed the installation guide

**Comment by C0untFloyd** [comment]
Filetype is selected by the extension .mp4 you don't need to specify it. Just pick a destination folder and click save.
