### ISSUE TITLE
What is the reason for the following error when running run.py after manually installing Win10?

### ISSUE THREAD

**Issue by jian27com** [C0untFloyd/roop-unleashed#650]
C:\AI\roop-unleashed>.\python310\python.exe run.py
Traceback (most recent call last):
  File "C:\AI\roop-unleashed\run.py", line 3, in <module>
    from roop import core
ModuleNotFoundError: No module named 'roop'

**Comment by C0untFloyd** [comment]
> .\python310\python.exe run.py

Probably this. It looks like you installed python into some subfolder of roop and didn't add it to the Path Env. Why don't you just use the automatic installer?

**Comment by jian27com** [comment]
Thank you for your reply. I have already taken care of it. I feel that it is not personalized and leaves too many useless files without the need for automatic installation of the program
