### ISSUE TITLE
Request : color control for face

### ISSUE THREAD

**Issue by Michael2Miller** [C0untFloyd/roop-unleashed#652]
If you add color control to control the color temperature of the generated swapped face this would be great

**Comment by C0untFloyd** [comment]
I'm unsure what this means exactly. The technology used here is nothing like e.g. controlnet for stable diffusion. It's not generating something out of noise like those models do but was instead trained on many images of persons faces. And the model itself is treated as a blackbox, you feed it the original aligned face and some face to swap to and it delivers. It also seems to adapt to different light conditions and you can even swap people of color to white people and vice versa without noticing. So again, I'm not sure what you would achieve with an extra color control. This would be an extra post-processing step like the enhancers but I'm positive that there are probably better tools out there to do this.

**Comment by Michael2Miller** [comment]
I'm so frame colorizer enhancer.. in face fusion but to be honest I prefer roop unleashed because in unleashed results are much more realistic and believable more than face fusion but when I saw frame colorizer there I had to wish that if you can add it to roop unleashed it would be a good addition

**Comment by C0untFloyd** [comment]
Ah ok, you're talking about colorizing b/w images and videos? That's easy and is about to be released together with other full frame features in the next version.
