### ISSUE TITLE
How to update roop 3.6.7 to 3.9.0 when using AMD gpu

### ISSUE THREAD

**Issue by KillerBean1206** [C0untFloyd/roop-unleashed#658]
So, I've been able to use roop unleashed version 3.6.7 with my amd gpu by running the following command "python run.py --execution-provider dml" in the command prompt of the roop-unleashed-main folder. However, when I try to run the windows_run.bat file, it does show that its using the latest 3.9.0 update but there's no option to use dml as provider. Any ideas what I could try do to be able use the latest roop unleashed 3.9.0 but with my amd gpu?

**Comment by lysxelapsed** [comment]
CLI arguments aren't suported for a while now and they weren't supported in 3.6.7 either.
The general solution is [this](https://github.com/C0untFloyd/roop-unleashed/issues/625#issuecomment-2072361976).
Aside from that: Some of individual solutions in the issues section [here](https://github.com/C0untFloyd/roop-unleashed/issues?q=dml).
