### ISSUE TITLE
RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION

### ISSUE THREAD

**Issue by newgtcli** [C0untFloyd/roop-unleashed#659]
Running picture swap and got error alert as follow:

RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ;

OS Win10 CPU 3.4GHz with 16G RAM, with Nvidia GTC 760 on Intel syetem

Roop unleased 3.6.6

Do I need to upgrade to 32G RAM? and higher tier GPU?

Thanks for help!!

**Comment by newgtcli** [comment]
Also, running the app which start download something everytime:
FFmpeg is already installed.
Skipping FFmpeg installation as it is already available.
Downloading insightface package from https://github.com/C0untFloyd/roop-unleashed/releases/download/3.6.6/insightface-0.7.3-cp310-cp310-win_amd64.whl to C:\roop-unleashed-main\installer\installer_files\insightface-0.7.3-cp310-cp310-win_amd64.whl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  5  821k    5 49152    0     0   2495      0  0:05:37  0:00:19  0:05:18     0

Once upload face picture and target picture, the app running very very slow, seems like it upload picture to some server instead of running locally on my PC. 

Does it seems right? or I need to reinstall all?

**Comment by C0untFloyd** [comment]
> Do I need to upgrade to 32G RAM? and higher tier GPU?

If you want to use the GPU for faster processing, yes certainly. To get rid of the error above you need to switch provider to cpu in the settings page.

> Once upload face picture and target picture, the app running very very slow, seems like it upload picture to some server instead of running locally on my PC.

The thing is, you're running a server locally on your PC 😄 
It's a client/server architecture, you can even host this for other people to use. So yes, you really are uploading everything and it takes longer than just copying something on your harddisk.
