### ISSUE TITLE
Missing feature

### ISSUE THREAD

**Issue by joaquingrech** [C0untFloyd/roop-unleashed#662]
Hi

This is not a bug, one thing I miss from FaceFusion in Roop Unleashed is that possibility to automatically detect a face based on size. For when there are a group picture, the main character usually is the larger face, so in FaceFusion I could usually select from the dropdown "Larger to smaller", to pick the largest one.

In Roop Unleashed we don't have that option and it should be an easy addition. We only have male/female/first...

Could this be added, please?

**Comment by C0untFloyd** [comment]
No, because this won't work when your main character turns its head. The face area will became smaller than the others and the wrong face will be swapped leading to questions here. What's so hard to select 1 face out of 4? It takes some seconds at most.
