### ISSUE TITLE
"Mask" Section is not showing

### ISSUE THREAD

**Issue by krabouilleur** [C0untFloyd/roop-unleashed#664]
**Describe the bug**
I've updated the program. But now, there is no the "mask" section (to write text and mask...)

**Details**
What OS are you using?
-  Windows 11

Are you using a GPU?
- [ ] No. CPU FTW

**Which version of roop unleashed are you using?
3.9.0

**Screenshots**
![image](https://github.com/C0untFloyd/roop-unleashed/assets/53522372/6da5d142-f195-43ab-b92e-c7128fddbe8f)

**Comment by Kingkladzemcr** [comment]
It's within the drop down of advanced masking just above remove selected on the top right of your screenshot
