### ISSUE TITLE
Please allow for standard API

### ISSUE THREAD

**Issue by joaquingrech** [C0untFloyd/roop-unleashed#666]
Feature Request: I love Gradio as much as the next guy, but it limited our usage to either Python or Javascript.
Many of us are in environments where we call APIs from different languages (c#, java, PHP...) and there are no Gradio clients for them.

I believe there is a setting in Gradio that will also spin up a FastAPI API, which accepts standard restful API. This will be perfect, the same way than Automatic1111 is doing and will allow everyone to use the API without the Gradio client limitation.

Thank you

**Comment by C0untFloyd** [comment]
Any volunteers for a PR?
