### ISSUE TITLE
Request: Allow for CLI parameters

### ISSUE THREAD

**Issue by joaquingrech** [C0untFloyd/roop-unleashed#667]
One thing I like about FaceFusion is that you can call the program with parameters and do everything.

It would be great we can call it from the command prompt with something like: run -source file.jpg -target target.jpg -output whatever.jpg -model "whatever" -xmoreparams "etc"

and get the result without doing anything else.

**Comment by C0untFloyd** [comment]
I'm sorry but that's another no. The more options, the more it becomes a bug ridden nightmare.
It's still possible with the older non-web version https://github.com/C0untFloyd/roop-unleashed/tree/tkinter
