### ISSUE TITLE
better way to launch beside windows_run? (needing internet connection)

### ISSUE THREAD

**Issue by Oedipus7** [C0untFloyd/roop-unleashed#668]
**Describe the bug**

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [1 ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ 1] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
3.67
**Screenshots**

python run.py doesn't work, but windows_run works fines but it will need internet connection to check for some things then run the program, is there a way to make windows_run not neet internet connection...?

this is what happens when using pythong run.py
![image](https://github.com/C0untFloyd/roop-unleashed/assets/117510990/0ad986eb-5eac-447a-b91f-e5809bba3d79)
and this with windows_run (works but needs internet connection)
![image](https://github.com/C0untFloyd/roop-unleashed/assets/117510990/6d889431-9bff-4c60-aae6-ed559a91de03)

**Comment by lysxelapsed** [comment]
You need to activate the environment before running `python run.py`. Navigate to your `roop-unleashed/scripts` folder and activate it with either `activate` or `conda activate` (not sure), then navigate back to the main folder an run it.

**Comment by Oedipus7** [comment]
> You need to activate the environment before running `python run.py`. Navigate to your `roop-unleashed/scripts` folder and activate it with either `activate` or `conda activate` (not sure), then navigate back to the main folder an run it.

didn't find that scripts folder in that directory but i found two other scripts folders
roop-unleashed\installer\installer_files\env\Scripts
roop2\roop-unleashed\installer\installer_files\conda\Scripts
 `activate` or `conda activate` (not sure),  both didn't work. welp, for now imma run it with windows run but it would be nice in the future to include a straightforward bat file that doesn't need to check for updates/require internet connection at the start.

**Comment by jonk999** [comment]
Do you have a venv folder in the root of where it was installed?
If so, you run from a command prompt in the root (eg: f:\roop-unleashed): venv\scripts\activate
Once done, you then run: python run.py
![image](https://github.com/C0untFloyd/roop-unleashed/assets/27007377/e2e28320-cca5-4af4-9675-8a78ce3b0bc2)

Else you could create your own bat file where it's installed - which is what I do.
```
call venv\Scripts\activate.bat
python run.py 
pause
```
This is assuming a Python virtual env was created. Conda is slightly different in the command to run.

**Comment by C0untFloyd** [comment]
Overwrite your current windows_run.bat with the one of the latest version (installer folder). It should be fixed.

**Comment by Oedipus7** [comment]
> Overwrite your current windows_run.bat with the one of the latest version (installer folder). It should be fixed.

Great, Thanks < 3

**Comment by wonderall-coder** [comment]
[roop-unleashed]  it work without the internet ? and I think someone must be seeing the files we saved, right? i'm so new I just wanted to ask, thanks ^^

**Comment by C0untFloyd** [comment]
You only need internet once to download all the models. So yes, it can be used offline.
