### ISSUE TITLE
Not doing proper face swap if the he target face have moving hand 

### ISSUE THREAD

**Issue by jaikargupta** [C0untFloyd/roop-unleashed#669]
Not doing proper face swap if the he target face have moving hand 
Please find the attached video.

https://github.com/C0untFloyd/roop-unleashed/assets/41422385/a5d0b648-5935-4f4a-b0df-5b32e49c4e03

**Comment by lysxelapsed** [comment]
This should work with clip2seg:
- Open up `Advanced Masking` (below the input face)
- Select `Clip2Seg` as `Face masking engine`
- Enter `hand` in the field below

But in my experience, the result won't be perfect even with masking.

**Comment by jaikargupta** [comment]
> This should work with clip2seg:
> 
> * Open up `Advanced Masking` (below the input face)
> * Select `Clip2Seg` as `Face masking engine`
> * Enter `hand` in the field below
> 
> But in my experience, the result won't be perfect even with masking.

Yes, I tried but the result is same :(

**Comment by C0untFloyd** [comment]
Do you have still the original untouched clip? I think xseg should work well with this but the real problem is if the hand covers a lot of the face there will be NO face detected and therefore no face swapping/masking will happen.

**Comment by jaikargupta** [comment]
> Do you still have the original untouched clip? Perhaps upload this here so I can give it a go. I think xseg should work well with this but the real problem is if the hand covers a lot of the face there will be NO face detected and therefore no face swapping/masking will happen.

Yes, I still have and here it is

https://github.com/C0untFloyd/roop-unleashed/assets/41422385/0c230b1d-26f0-478e-908e-f7cfe5ab0757

**Comment by C0untFloyd** [comment]
Non cherry picked quick run using DFL XSeg und GPEN:
https://github.com/C0untFloyd/roop-unleashed/assets/131583554/9d97399f-31c9-4c69-bad8-fd33582dbe04

I think this is better than your try, it doesn't have any half transparent eyes on the hands or stuff like that, so the masking is working very well. However this is still far from perfect as the face detection has problems to get the face orientation with just 1 eye. This is as good as it gets without training I'm afraid.
My Settings:
![settings](https://github.com/C0untFloyd/roop-unleashed/assets/131583554/fb6db92f-230c-4218-9929-604813870e87)
