### ISSUE TITLE
Save Extracted Frames to a New Folder Before Swap Process Overwrites ?

### ISSUE THREAD

**Issue by chalkncheese** [C0untFloyd/roop-unleashed#67]
Is it possible to create a feature to save the extracted frames to a new folder before the swap process overwrites the files in the Temp folder? This would be useful for further post-production options in applications such as After Effects.

**Comment by phineas-pta** [comment]
frame extraction can be easily done with `ffmeg`

future release may skip this step & process in-memory

**Comment by C0untFloyd** [comment]
Both is already possible in the gradio branch.
