### ISSUE TITLE
Keeping face details

### ISSUE THREAD

**Issue by krabouilleur** [C0untFloyd/roop-unleashed#670]
**Describe the bug**
Is there a way to keep details face from faceset ? (I have a faceset file from 200 photos) but on the result, the face don't keep the spots, freckles, rides (the result removes all facial imperfections and smoothes the face)

**Comment by C0untFloyd** [comment]
No and 200 photos are about 190 too much. What people mostly don't get, facesets are used to average landmark positions like eye positions relative to nose etc. they don't have much influence on the texture of the resulting face. I don't think you'll notice a difference when using a faceset of 5 images with different angles to your 200 photos.
