### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by CassySpencer** [C0untFloyd/roop-unleashed#674]
I'm totally in you to get hard and I'm wondering how do I update on my Mac? 
Do I type the following commands?

```
% CD /Users/cassy/roop-unleashed-main
% pip3 update roop-unleashed
```

I would appreciate your assistance.

**Comment by lysxelapsed** [comment]
Navigate to your roop-unleashed folder, activate the environment and update with `git pull`, after that update the requirements with `pip3 install -r requirements.txt`.
