### ISSUE TITLE
Macos Camera

### ISSUE THREAD

**Issue by kir3d** [C0untFloyd/roop-unleashed#676]
1.  in virtualcam.py at 22 line need replace CAP_DSHOW `cap = cv2.VideoCapture(cam_num, cv2.CAP_AVFOUNDATION)`
2. in livecam_tab.py need greater then 1 at line 24 for `camera_num = gr.Slider(0, **1**, ..`. because faceam or phone cam may be higher
3. in doc add about permission in terminal:
List devices:
`ffmpeg -f avfoundation -list_devices true -i ""`
Save frame and request permission:
`ffmpeg -ss 0.5 -f avfoundation -i "0" -t 1 capture.jpg`
may be replace "0" to number from list for FaceTime HD Camera

**Comment by kir3d** [comment]
4. in doc Installation for mac need add last pip3:
`pip3 install virtualcam`

**Comment by C0untFloyd** [comment]
I don't have a Mac to test this but I added some code like you said.
The Wiki and also the installation page is free for all and wasn't written by me. Feel free to add stuff you think is missing:
![grafik](https://github.com/C0untFloyd/roop-unleashed/assets/131583554/d80fae74-3cff-41e7-b990-b42291563aae)

(Edit button on the right)
