### ISSUE TITLE
Input faces

### ISSUE THREAD

**Issue by brunodenis18** [C0untFloyd/roop-unleashed#678]
**Describe the bug**
When I upload the photo (good photo) to make the deep fake, it doesn't upload and takes a few seconds.
Does anyone help me or does the same thing happen to them?
**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [x] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
3.6.7
**Screenshots**
![Captura de pantalla 2024-05-11 040126](https://github.com/C0untFloyd/roop-unleashed/assets/169518874/21cda46d-2a47-4440-b3eb-211d529c683e)

**Comment by lysxelapsed** [comment]
That's how it looks when no face got detected. Is the whole face visible? The face recognition model doesn't like (sometimes even slightly) incomplete faces. You can try my [workaround suggestion](https://github.com/C0untFloyd/roop-unleashed/discussions/558#discussioncomment-8939225) though.

**Comment by brunodenis18** [comment]
hi,download the photo you recommended and even that one doesn't work for me
![317700922-1940b950-50c7-4bb6-b18e-cfee2aaa8c27 (1)](https://github.com/C0untFloyd/roop-unleashed/assets/169518874/66b9b8b0-3366-4324-b218-11531b96a2ed)

**Comment by C0untFloyd** [comment]
Can you post your console output here? I'm betting there's somthing very basic going wrong, like a corrupted model or something like that.

**Comment by brunodenis18** [comment]
sorry, what should I send you? 
I'm new to these things

**Comment by giba21** [comment]
no me lee la cara de entrada, he intentado con muchas imágenes y nada aún.
![Captura de pantalla 2024-05-25 103357](https://github.com/C0untFloyd/roop-unleashed/assets/170817044/76028c3e-cd66-48a1-b175-cdabd9b39bbe)
