### ISSUE TITLE
Tweak the similarity to the source or destination

### ISSUE THREAD

**Issue by alikashanii** [C0untFloyd/roop-unleashed#679]
Is there any way to increase the similarity to the source? For example, if the source has a tattoo on its face, can we keep that? It seems this model tends to maintain the destination face.

What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ .] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [. ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

v3.9.0

**Comment by C0untFloyd** [comment]
There's nothing we can do about the inner workings of the swapping model. It probably was trained on frontal celebrity images and doesn't know what to do with freckles or tattoos.
