### ISSUE TITLE
Enable usage of GPU

### ISSUE THREAD

**Issue by P1zzaPrime** [C0untFloyd/roop-unleashed#68]
In **simple terms*, how do you add a command line argument to the windows_run.bat exactly?

**Comment by phineas-pta** [comment]
should be enable by default

**Comment by Showstoppah** [comment]
right click on windows_run.bat, click edit, 3rd line down, after set COMMANDLINE_ARGS=  add --execution-provider cuda --frame-processor face_swapper face_enhancer --video-encoder libvpx-vp9
