### ISSUE TITLE
Request: Resize target video resolution

### ISSUE THREAD

**Issue by huyitus** [C0untFloyd/roop-unleashed#680]
Roop unleashed is great because it can trim target video by frame number. Why don't you add the feature for resizing the target video resolution?

**Comment by C0untFloyd** [comment]
Because that is something any decent video editing software does better. Or are you talking about upscaling? This is something I'm actively working on and should be available to you in some hours in the next version.

**Comment by C0untFloyd** [comment]
New version with upscaling is out...
