### ISSUE TITLE
Problems with gradio

### ISSUE THREAD

**Issue by Michael2Miller** [C0untFloyd/roop-unleashed#687]
![IMG_20240513_192344_628](https://github.com/C0untFloyd/roop-unleashed/assets/168263994/56719226-ac16-4b49-bb05-c131506283f3)
![IMG_20240513_192341_869](https://github.com/C0untFloyd/roop-unleashed/assets/168263994/731d61e7-f217-4c6d-861f-c841427ab6ed)
I tried a lot but I couldn't fix this problem always when I run the program after installing requirements I always face this problem as you can see in pictures it only happened after the update I don't know what the solution for this problem

**Comment by Michael2Miller** [comment]
The problem is that every time I run it the connection shut down... I don't know how to fix it I tried ngrok and zrok but I don't think that the problem is from them

**Comment by Michael2Miller** [comment]
I uninstalled gradio then installed 4.29.0 again " !pip uninstall -y gradio && pip install gradio==4.29.0 "  now everything is working very well

**Comment by grimbord** [comment]
> Megoldva: eltávolítottam a gradio-t, majd újra telepítettem a 4.29.0-t " !pip uninstall -y gradio && pip install gradio==4.29.0 " most minden nagyon jól működik

Hi! I try this, but dont work
![Kijelölés Applio 2024  05  14  8_57_43](https://github.com/C0untFloyd/roop-unleashed/assets/165640386/a1815001-a987-4436-9e08-c6a2d0e0d9ec)
