### ISSUE TITLE
Cuda error

### ISSUE THREAD

**Issue by felipe4001** [C0untFloyd/roop-unleashed#689]
**Describe the bug**
When I upload a photo it doesn't upload and I get this error

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [ x] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
4.0.0
**Screenshots**
![Captura de pantalla 2024-05-13 221312](https://github.com/C0untFloyd/roop-unleashed/assets/169734360/28d7626e-e2d6-4856-bcab-288dbb79377d)

**Comment by turkiet** [comment]
Same for me, [https://github.com/C0untFloyd/roop-unleashed/issues/688](url)

**Comment by lysxelapsed** [comment]
Answered in #688

**Comment by verqqa** [comment]
maybe your gup has low v-ram
