### ISSUE TITLE
missing ftfy module (and regex)

### ISSUE THREAD

**Issue by nlienard** [C0untFloyd/roop-unleashed#69]
using gradio branch, fresh install, fresh venv, got this error

```
ModuleNotFoundError: No module named 'ftfy'
```

adding it to requirements.txt fixed the issue

After starting back and trying again, got new issue with regex

```
ModuleNotFoundError: No module named 'regex'
```

adding it to requirements.txt fixed the issue

**Comment by C0untFloyd** [comment]
Thanks for the info, yes this is needed by clip2seg.
