### ISSUE TITLE
Preview Window Issues in 4.0.0

### ISSUE THREAD

**Issue by swilks84** [C0untFloyd/roop-unleashed#693]
**Describe the bug**
Since 4.0.0 attempting to open the image from the Preview Window in a new tab leads to garbage output/webp file.

**To Reproduce**
Steps to reproduce the behaviour:
1. Load image into Target Files, wait for image to appear in Preview Window
2. Attempt to 'Open Image in New Tab' (Firefox)
3. Newly opened tab doesn't show image, instead shows broken unicode symbols
4 Right clicking Preview Window image and Save Image As (Firefox) attempts to save image file as webp file instead of user choice (jpg, png)

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?** 4.0.0

**Comment by swilks84** [comment]
Note, tried another browser, and opening the Preview Window image in a new Chrome tab displays the image correctly, but it's still in the (undesirable) webp format. As a user who often saves images directly from the Preview Window, this is a problem. Thank you for your development!

**Comment by C0untFloyd** [comment]
I'm actually in the same boat as you. In previous version I also rarely used start but mostly just saved images from the preview. Unfortunately I don't have control over the formats gradio (the web ui) uses and they decided at one point to use webp to save bandwidth. I think it is this issue: https://github.com/gradio-app/gradio/issues/2418
I could go back to earlier versions but would loose then a lot of the new neat features. Can't have everything I guess 🤷‍♂️
