### ISSUE TITLE
DML has disappeared in v4.0.0

### ISSUE THREAD

**Issue by TinoTano** [C0untFloyd/roop-unleashed#694]
**Describe the bug**
Today I've updated to 4.0.0 and dml option has disappeared. I have directml 1.15.1 installed in installer_files\env\Lib\site-packages and I start the program from windows_run.bat.
It was working perfectly in 3.9.0 version and I haven't changed anything.

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [x] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
4.0.0

**Comment by lysxelapsed** [comment]
Have you tried re-installing with `pip uninstall onnxruntime onnxruntime-directml pip install onnxruntime-directml==1.15.1`?
Also this post might help: [688](https://github.com/C0untFloyd/roop-unleashed/issues/688#issuecomment-2109962389)

**Comment by TinoTano** [comment]
I reinstalled and did the steps in the post you linked and still not working.
I've downloaded the 3.9.0 version and installed directml and is working.

**Comment by lysxelapsed** [comment]
Maybe removing old folders from the environment variables or moving the new ones higher up? But that's all I got, sorry.

**Comment by IZUR0** [comment]
https://github.com/C0untFloyd/roop-unleashed/issues/625

**Comment by kmhar1688** [comment]
pip uninstall onnxruntime onnxruntime-gpu
pip uninstall onnxruntime onnxruntime-directml 
pip install onnxruntime-directml==1.15.1

Go to your roop folder or create a bath file and run in DML mode using the command below

python run.py --execution-provider dml
 
 It worked for me and I hope it worked for you too.
 
 
![image](https://github.com/C0untFloyd/roop-unleashed/assets/87787032/2d2f9ffd-ac98-4527-b32a-a91e9d689e25)
