### ISSUE TITLE
how to get the best swap resemblance 

### ISSUE THREAD

**Issue by maic2209** [C0untFloyd/roop-unleashed#696]
**Describe the bug**

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [windows 11 pro ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ 8gb RTX 2070] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?* 3.9.0*

**Screenshots* 
![Screenshot 2024-05-14 233112](https://github.com/C0untFloyd/roop-unleashed/assets/118336775/67301184-a074-4261-a58a-f8abd55f0290)
![Screenshot 2024-05-14 233112](https://github.com/C0untFloyd/roop-unleashed/assets/118336775/f0346442-a655-4f4f-99dd-106d80f8f2fd)
*

**Comment by maic2209** [comment]
> Depends on the input and target face. There's no golden "fits all" setting. I mostly set swapping steps to 2, but not with all input faces / combinations. You can do an easy direct comparison by saving the preview frames and chose the settings which match your expecations best.

thank you, sorry i have a glitch, when i choose select face the start button becomes slim and doesn't allow me to run the program, look at it in the screenshot below, the slim orange line was the start button
![Screenshot 2024-05-16 001056](https://github.com/C0untFloyd/roop-unleashed/assets/118336775/427a2011-59c6-4a3b-910b-164e80c76560)

**Comment by lysxelapsed** [comment]
Yeah that looks strange. Maybe try with another browser?

**Comment by maic2209** [comment]
Which browser are you using?
