### ISSUE TITLE
AMD GPU Vega 64

### ISSUE THREAD

**Issue by SoulCZ** [C0untFloyd/roop-unleashed#70]
Hi, I would like to ask someone who has experience with this so I don't have to bother the project creator :).. Could someone here advise me how to connect Vega 64 ( AMD ) ? I've tried the tutorials but I still can't get to it ... Is there any video tutorial ? Or a well described tutorial ? Thank you in advance for the answer ( used translator )

**Comment by C0untFloyd** [comment]
I wouldn't know anyway, I don't own a AMD GPU 🤷

**Comment by SoulCZ** [comment]
Anyway, thank you for being active :) it's rare to see someone actually responding

**Comment by SoulCZ** [comment]
Hi, thanks for the reply .. I'm currently using windows :)

**Comment by phineas-pta** [comment]
then replace `onnxruntime-gpu` with `onnxruntime-directml`

add to lauch command: `--execution-provider dml --execution-threads 1`

**Comment by zzek300** [comment]
Hi I similarly was trying to use an amd card on windows (6700xt) but came across an issue as seen below

![image](https://github.com/C0untFloyd/roop-unleashed/assets/142314109/551bf11e-b610-4fbf-8fb0-63a5123c6431)

I'm like 99.99% sure I've installed onnxruntime-directml and used the right launch functions so I'm not sure we're to go (I'm inexperienced with python)

**Comment by phineas-pta** [comment]
it's not onnxruntime fault

it's because default torch (in requirements) uses cuda backend

1st remove it
```
pip unistall torch torchvision
```

then reinstall
```
pip install torch torchvision
```

keep in mind that torch will use cpu so gfpgan / codeformer is very slow

**Comment by zzek300** [comment]
That doesn't seem to have changed the error messages as far as I can tell, also a distribution error warning appears during the torchvision installation (I don't know what it means)

![image](https://github.com/C0untFloyd/roop-unleashed/assets/142314109/608d46fd-0572-414b-b3fd-013ff04d3bcd)

**Comment by phineas-pta** [comment]
something off with your installation im afraid 🤔

my advice is remove anything python and start again

this time edit requirements: remove 1st line and anything `+cu118`

**Comment by lysxelapsed** [comment]
when re-installing a component like onnxruntime-gpu or torchvision, I recommend adding the --force-reinstall argument. if you don't, chances are that it will install the very same thing as before from the cache. so with phineas-pta's suggestion, that would be:
- pip unistall torch torchvision
- pip install torch torchvision --force-reinstall

I still don't understand, why it works that way with python. In my opinion, it should ask at least, if you want to use the one from the cache or download and install anew.

**Comment by lysxelapsed** [comment]
> That doesn't seem to have changed the error messages as far as I can tell, also a distribution error warning appears during the torchvision installation (I don't know what it means)
> 
> ![image](https://user-images.githubusercontent.com/142314109/260704535-608d46fd-0572-414b-b3fd-013ff04d3bcd.png)

did you install python from the windows store? if so, try uninstalling that one and install a release from python.org. just a guess, but I read recommendations not to install python from the windows store more than once now.

**Comment by Sidharthiam** [comment]
> then replace onnxruntime-gpu with onnxruntime-directml
> 
> add to lauch command: `--execution-provider dml --execution-threads 1`

Hi, sorry for being a noob, im also having this issue, where should i replace "onnxruntime-gpu with onnxruntime-directml"?

**Comment by brucecolino** [comment]
hi guys, little noob here wants to use directml for AMD gpu instead of cpu cause it's too low.
can somebody explain wich file to modify, how and what should try to make it work in order? thank you so much

**Comment by phineas-pta** [comment]
@brucecolino for ease of mind, use cpu, support for amd gpu in AI is not easy for beginner

**Comment by idronbes** [comment]
i am looking for a solution too, in the original roop, i could use the command --execution-provider dml but with roop-unleashed we cannot use this command ; it writes "No CLI args supported - use Settings Tab instead".  But in the settings tab, there is cuda, tensorrt and cpu.   I guess we can add directml but i dont know where to change the code to make it work as original roop (with dml command).  Does anybody knows which file to edit to remove cuda and add directml ? thank you

**Comment by idronbes** [comment]
i found the solution.  you need to do this in command prompt ; type the commands : pip uninstall onnxruntime and pip install onnxruntime-directml==1.15.1 

then you will have to edit this file (at the begining, with the option "Flase" , the dml option was there but was not loading)
C:\Users\YOURUSERNAME\AppData\Local\Programs\Python\Python39\Lib\site-packages\gradio\components\dropdown.py

allow_custom_value: bool = False 
to 
allow_custom_value: bool = True

After that you should be able to run roop-unleashed and set the provider in the settings tab to dml.  

it just worked for me.

**Comment by riccorohl** [comment]
> i found the solution. you need to do this in command prompt ; type the commands : pip uninstall onnxruntime and pip install onnxruntime-directml==1.15.1
> 
> then you will have to edit this file (at the begining, with the option "Flase" , the dml option was there but was not loading) C:\Users\YOURUSERNAME\AppData\Local\Programs\Python\Python39\Lib\site-packages\gradio\components\dropdown.py
> 
> allow_custom_value: bool = False to allow_custom_value: bool = True
> 
> After that you should be able to run roop-unleashed and set the provider in the settings tab to dml.
> 
> it just worked for me.

dml didn't, showed up after following this

**Comment by riccorohl** [comment]
> then replace `onnxruntime-gpu` with `onnxruntime-directml`
> 
> add to lauch command: `--execution-provider dml --execution-threads 1`

Replace it where?

**Comment by idronbes** [comment]
on original roop when you launch it by entering in the command ;  
"python run.py --execution-provider dml --execution-threads 1"
but i think on unleashed you cannot add options to the command

**Comment by KillerBean1206** [comment]
> i found the solution. you need to do this in command prompt ; type the commands : pip uninstall onnxruntime and pip install onnxruntime-directml==1.15.1
> 
> then you will have to edit this file (at the begining, with the option "Flase" , the dml option was there but was not loading) C:\Users\YOURUSERNAME\AppData\Local\Programs\Python\Python39\Lib\site-packages\gradio\components\dropdown.py
> 
> allow_custom_value: bool = False to allow_custom_value: bool = True
> 
> After that you should be able to run roop-unleashed and set the provider in the settings tab to dml.
> 
> it just worked for me.

By "Flase" do you mean false? I change False to True but the dml option is not appearing

**Comment by idronbes** [comment]
oops yes lol.  since i updated the app last week, i can't get the dml option back in the list.  maybe try to enable the args on the command 

python run.py --execution-provider dml --execution-threads 1 

 original roop accepted these CLI args but not unleashed version, maybe it can be changed but idk where

**Comment by idronbes** [comment]
i think i got it.  you need to uninstall torch and reinstall as said above

--------------------
[phineas-pta](https://github.com/phineas-pta) commented [on Aug 15, 2023](https://github.com/C0untFloyd/roop-unleashed/issues/70#issuecomment-1678816922)
it's not onnxruntime fault

it's because default torch (in requirements) uses cuda backend

1st remove it

pip uninstall torch torchvision
then reinstall

pip install torch torchvision
keep in mind that torch will use cpu so gfpgan / codeformer is very slow

-------------------
cu118 means for cuda so i think the problem comes from there.

Successfully uninstalled torch-2.1.2+cu118

Successfully installed torch-2.2.2 torchvision-0.17.2

Now i have dml option in the list, and cpu option.

**Comment by KillerBean1206** [comment]
actually i got it to work thanks very much

**Comment by riccorohl** [comment]
How do I tell it to specifically install torch-2.2.2 torchvision-0.17.2 ?

**Comment by idronbes** [comment]
Did you update roop? Maybe try clone and reinstall with "windows_run.bat" from zero, then refollow the steps.  At end i ran the command 
Pip install -r requirements.txt  (in roop directory)
Maybe there is something missing to get the 2
2.2
