### ISSUE TITLE
Roop unleashed 4.0.0 uses too much RAM, is this normal?

### ISSUE THREAD

**Issue by amen92** [C0untFloyd/roop-unleashed#705]
**Describe the bug**

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**

**Screenshots**

I didn't have this problem in 3.6.7 version. I lowered the threads to one but still, having this problem.

**Comment by oldbutter** [comment]
![2024-05-19_15-56](https://github.com/C0untFloyd/roop-unleashed/assets/62179438/d53d2379-88f0-487c-a17f-020e0c049028)

in idle
