### ISSUE TITLE
.webp Images in Preview Window for Gradio Versions>4.26

### ISSUE THREAD

**Issue by JayJackRussel** [C0untFloyd/roop-unleashed#717]
**Describe the bug**
Images saved from the preview window are in .webp format instead of .png. This issue occurs in Gradio versions newer than 4.26.

The problem does not occur in Gradio version 4.26. Can you downgrade to version 4.26?

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
4.0.0

**Comment by C0untFloyd** [comment]
The gradio devs decided to use webp format to save bandwidth. Going back to 4.26 would work but re-introduce the old bugs from gradio in that version (bugged upload progress, errors in maskeditor). It would be a tradeoff between old bugs and new bugfixes/features. Perhaps they add an option later, to set the preferred save format. I don't know, I think this should be left to the user, you can always do a pip uninstall gradio and pip install gradio==4.26
