### ISSUE TITLE
Roop Unleashed stopped working after update

### ISSUE THREAD

**Issue by naveen80023** [C0untFloyd/roop-unleashed#727]
Hey guys, so I've been using roop unleashed for the last 3 months

Even though I don't have the best laptop, it worked fine. It just took time.

But yesterday, I decided to update it (the software asks if you'd like to update roop before you open and use it)

And after the update, it's gone completely sh*t. I mean, literally nothing works.

I upload my face swap image and the video to add the face to, and the process NEVER STARTS.

I used to get this % bar in the "Processed File" box with the number of frames processed, now it just goes blank.

Anyone face this? How to solve this issue?

PS: I use GPEN as post processing

**Comment by Michael2Miller** [comment]
everything is working very well all bugs have been fixed with 4.0.0 yes i faced issues with the previous version with the preview while using clip2seg
But right now Roop unleashed it's working without problems with no bugs

**Comment by andreaaraya01** [comment]
It's pausing for me too, I do not know if its the OS, but now I have to hit enter to the console and it continues processing. How can I uninstall and reinstall all?, deleting the folder and executing the windows_run.bat?
