### ISSUE TITLE
Enhancement suggestion:

### ISSUE THREAD

**Issue by Michael2Miller** [C0untFloyd/roop-unleashed#728]
Please if you can add 
-frame enhancement: with options for enhancement models
- options to choose which face detection model to use
-options to choose the version of gpen 512-1024 face enhancer options 
- Lipsync options
-
This would be great.❤️

**Comment by C0untFloyd** [comment]
I don't want this to be a cheap copy of face fusion and I'm not interested in lip syncing as such. Of course I could implement e.g. yolo for face detection but for what gain? The face swapper itself can't cope very well with weird angles, so even if more faces at funky angles are detected, the results would still be weird.
