### ISSUE TITLE
onnxruntime-silicon v1.17.1 does not exist, but is set in requirements.txt

### ISSUE THREAD

**Issue by cannuri** [C0untFloyd/roop-unleashed#729]
The `requirements.txt` file requires `onnxruntime-silicon` version 1.17.1, but the latest release's version is 1.16.3

That leads to the following error when running `pip3 install -r requirements.txt`:

```
ERROR: Could not find a version that satisfies the requirement onnxruntime-silicon==1.17.1 (from versions: 1.11.1, 1.13.1, 1.14.1, 1.15.0, 1.16.0, 1.16.3)
ERROR: No matching distribution found for onnxruntime-silicon==1.17.1
```

**Comment by C0untFloyd** [comment]
Thanks, will fix ASAP.

**Comment by C0untFloyd** [comment]
https://github.com/C0untFloyd/roop-unleashed/commit/e2e61047798fd78f5380b114aa32659df3ce8701
