### ISSUE TITLE
Missing torch, I am new to linux but I ran the Python run.py and It leads me to no module named torch

### ISSUE THREAD

**Issue by senorYME** [C0untFloyd/roop-unleashed#733]
**Describe the bug**

**To Reproduce**
1. Go to '...' konsole Python run.py
4. See errorFile "/home/user/Downloads/roop-unleashed-4.0.0/run.py", line 3, in <module>
from roop import core
File "/home/user/Downloads/roop-unleashed-4.0.0/roop/core.py", line 14, in <module>
import torch
ModuleNotFoundError: No module named 'torch'

need help figuring this out 

**Details**
What OS are you using?
- [ x] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?** latest 4.0.0

**Screenshots**

**Comment by slainte-frm-rod** [comment]
having this same issue

**Comment by senorYME** [comment]
> having this same issue

If you are on Linux you need to install python3.11 then run in terminal from the folder directory pyrhon 3.11 requirements.txt then it will install torch my only issue now is trying to install cuda 11.8 which is non existent on arch Linux

**Comment by slainte-frm-rod** [comment]
thanks bro, i was using automatic1111 and it updated me to Python 3.12. I tried uninstalling and installing 3.11 again. Now i'm installing each package in their correct version. Hopefully it starts working again

**Comment by slainte-frm-rod** [comment]
solved
