### ISSUE TITLE
Images saved as WEBP , but i want as png

### ISSUE THREAD

**Issue by isurajboss** [C0untFloyd/roop-unleashed#737]
Hey, after the recent update, when I tried to swap the faces of images and clicked on the download button of result, it saved in as WEBP format, not as a png or jpeg. but in Settings, Image Output Format is set as png. tried changing it, but no luck. Check out the screenshot below.

![image](https://github.com/C0untFloyd/roop-unleashed/assets/136398107/6bcbcf0d-e21b-4293-b0d6-0a810ed81b85)

OS - Windows 11
GPU - Nvidia RTX 3060 12gb
Roop Version - roop unleashed 4.0.0

**Comment by C0untFloyd** [comment]
Is searching for existing issues out of fashion nowadays?
#693 #717 #736
