### ISSUE TITLE
Batch processing names each file temp.mp4 and then crashes.

### ISSUE THREAD

**Issue by gilraftiks** [C0untFloyd/roop-unleashed#74]
**Describe the bug**
Batch processing crashes when getting to file number two cause it tries to name it temp.mp4, which it already has named the first file.

**To Reproduce**
Run batch processing with multiple files.

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you trying to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by raptureoh9** [comment]
I have the same issue. I saw a few other posts for this same issue were closed saying it was fixed in the "Gradio" branch, but I've tried the last 3 builds from that branch as well and they all have the same problem too.
