### ISSUE TITLE
Saving image as webp instead of png

### ISSUE THREAD

**Issue by Darienxccs4** [C0untFloyd/roop-unleashed#741]
**Describe the bug**
Since the last updated the images are saved as webp even when i put to be saved as png

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X] Windows 
- [ ] Mac

Are you using a GPU?
- [X] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
using the 4.0 Roop

**Comment by C0untFloyd** [comment]
#737
