### ISSUE TITLE
Request: regarding the res could it be upgraded from 128 to 512?

### ISSUE THREAD

**Issue by Oedipus7** [C0untFloyd/roop-unleashed#749]
Sorry if this is not the right place to write the request,

I have seen this on reddit regarding a higher resolution rope:

https://www.reddit.com/r/StableDiffusion/comments/1d21s4t/rope_pearl_released_which_includes_128_256_and/

I am not sure if this is using totally different engine under the hood for the swapping or it is an upgraded version with higher res or what. I was wondering about having this in the webui version or is it incompatible?

**Comment by C0untFloyd** [comment]
No it's perfectly fine with me to ask for features, however I don't have much time lately and aren't doing this fulltime for donations like the other guys.
In the thread you've linked the author (Hillobar) explains the technique https://www.reddit.com/r/StableDiffusion/comments/1d21s4t/rope_pearl_released_which_includes_128_256_and/l5y4ha3/

It's a smart way of subsampling the 128x128 input image and upscaling it by feeding it several times to the inswapper model. Sort of upscaling it but without adding details not present in the original image. Really nice and could be applied to any low-resolution faceswapper. It's not hard to integrate this but I don't know when.

**Comment by ShrekLovesAll** [comment]
> It's a smart way of subsampling the 128x128 input image and upscaling it by feeding it several times to the inswapper model. Sort of upscaling it but without adding details not present in the original image. Really nice and could be applied to any low-resolution faceswapper. It's not hard to integrate this but I don't know when.

It's kinda funny how the entirety of pic faceswapping is basically held up on insightface and we're all just trying to find workarounds to get the same level of quality they get out of 512. Wonder if someone else will eventually ever make something OS to compete.

**Comment by C0untFloyd** [comment]
Haha yes indeed.
