### ISSUE TITLE
Frame processor face_enhancer not found

### ISSUE THREAD

**Issue by Freddy22119** [C0untFloyd/roop-unleashed#75]
**Describe the bug**
Currently running into this when doing run.py

Loading roop.processors.frame.face_swapper
Loading roop.processors.frame.face_enhancer
Frame processor face_enhancer not found.

**To Reproduce**
Use the run.py

**Details**
What OS are you using?
Windows 

Are you trying to use a GPU?
NVIDIA

**Sanity Check**
- [x ] I have the latest code from the github repository
- [x ] I have followed the installation guide

**Comment by katherineex** [comment]
just read on reddit 
" I had the same issue as you, and I've came up with a halfway solution. You won't be able to use upscalers or gfpgan but you can use the regular application nonetheless.

Open up "roop-unleased/roop/core.py"

Go to line 64 and delete "face_enhancer" in "roop.globals.frame_processors = ['face_swapper', 'face_enhancer'] "

Save and it should be up and running now."

**Comment by xddhxll** [comment]
Frame processor face_swapper could not be loaded

**Comment by zhd36** [comment]
The issue with Frame processor face_enhancer not found is indeed related to another project.  https://github.com/XPixelGroup/BasicSR/pull/650
I changed line 8 in basicsr/data/degradations.py and it works
