### ISSUE TITLE
Roop Unleashed Pc Crash

### ISSUE THREAD

**Issue by hvkeye01** [C0untFloyd/roop-unleashed#756]
**Describe the bug**
So I was using Roop perfectly yesterday, now I just wanted to do some photos and it crashed my whole Pc and shut it down, I didnt change anything in the meantime I just always updated it before I started it.
My Pc has quite ok specs so I doubt its because of that
So if I do more than 1 Picture as target file or a video even if its 1 second long, it crashes my whole Pc after I press the start button

If anyone has a solution for that Im happy to get help, Im not good with code so please try to me as detailed as possible haha, THANK YOU IN ADVANCE!

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x ] Windows 
- [ ] Mac

Are you using a GPU?
- [x ] No. CPU FTW
- [ ] NVIDIA
- [ x] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**

**Screenshots**

**Comment by kmhar1688** [comment]
You can solve this by reducing your GPU Frequency using the AMD Software.

![image](https://github.com/C0untFloyd/roop-unleashed/assets/87787032/f42298a1-e766-4d1d-9ef7-03e84cf9bf70)
