### ISSUE TITLE
Image output file format

### ISSUE THREAD

**Issue by Didier-Eloy** [C0untFloyd/roop-unleashed#757]
The image is always saved in WEBP format, even though the PNG format is enabled in the “Settings” tab.

**Comment by isurajboss** [comment]
download image from Processed file box, on left side,, just click on size with down arrow, and you will get png file

**Comment by Didier-Eloy** [comment]
Thank you for your feedback 

I used to save the image from the "Image preview" window.  

In previous versions, the image was saved as a PNG file in this window
