### ISSUE TITLE
Problem - ONNRunTimeError

### ISSUE THREAD

**Issue by Asotekkk** [C0untFloyd/roop-unleashed#758]
How to fix this problem?
![aaaaaaaa](https://github.com/C0untFloyd/roop-unleashed/assets/172528392/21062137-f6d4-407e-8226-4fd5835a69f5)

**Comment by Asotekkk** [comment]
?

**Comment by ssuvamm** [comment]
[E:onnxruntime:Default, provider_bridge_ort.cc:1548 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1209 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcufft.so.10: cannot open shared object file: No such file or directory


I have this error

**Comment by Asotekkk** [comment]
Here I think it is necessary to tinker by yourself because no one will answer as I will have a solution I will say since I published this post I have not messed with anything but it still did not work, I will test it today
