### ISSUE TITLE
issue - it says ffmpeg is not installed

### ISSUE THREAD

**Issue by dookiefart100023** [C0untFloyd/roop-unleashed#760]
Everything is installed correctly however when I click start to run roop, it says that:
![image](https://github.com/C0untFloyd/roop-unleashed/assets/76995217/649585d6-eff2-4c21-b68b-189a9fa28f68)
ffmpeg is not installed but I see it in my folder in installed files.
What should I do?
Update:
When I reran the batch file, it said this:
![image](https://github.com/C0untFloyd/roop-unleashed/assets/76995217/a1f7e97f-0a0e-4c30-80c7-4e4c509f4fa1)
I restarted roop many times however it keeps redownloading ffmpeg and then saying it is not installed when I tried starting a swap

**Comment by astridxox** [comment]
In the directory "\roop-unleashed-main\installer\installer_files" - I just renamed the folder "ffmpeg-2023-06-21-git-1bcb8a7338-essentials_build" to "ffmpeg" and that should fix it (that whole folder is extracted from the ffmpeg.zip)

I found this while searching for the same issue and it worked for me.

**Comment by dookiefart100023** [comment]
Thanks its now fixed. I renamed to ffmpeg and I added it to \C: with this tutorial:
https://www.wikihow.com/Install-FFmpeg-on-Windows
Thanks for the tip!
