### ISSUE TITLE
pix_fmt input

### ISSUE THREAD

**Issue by giuseppe30** [C0untFloyd/roop-unleashed#762]
**Describe the bug**
to improve quality in ffmpeg_writer.py under cmd = [ I want change -pix_fmt bgr24 to bgr32 or 48. But it causes color shift output.
Anything other than bgr24 causes issues.

**To Reproduce**
color shift output

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [X ] AMD
- [ ] Intel
- [ ] Mac

roop version roop-unleashed_win3.9.0

![IMG_2194](https://github.com/C0untFloyd/roop-unleashed/assets/81449172/309a9cc4-562c-46a3-80b5-a3119c439313)

**Comment by C0untFloyd** [comment]
The calculations inside roop are in 24bit. Writing those images as 32bit wouldn't make any difference in quality.
