### ISSUE TITLE
face don't show

### ISSUE THREAD

**Issue by masdaMehdi** [C0untFloyd/roop-unleashed#763]
**Describe the bug**
the face does not show after i upload the source image 

**Details**
What OS are you using?
- [] Windows 10
Are you using a GPU?
- [ ] NVIDIA
- [ ] Intel

**Which version of roop unleashed are you using?**
- [ ] roop unleashed 4.0.0

**Screenshots**
![1](https://github.com/C0untFloyd/roop-unleashed/assets/38921390/847df3b1-c9e6-4781-9f1f-c1ea48857aeb)
![2](https://github.com/C0untFloyd/roop-unleashed/assets/38921390/b89c7b92-c530-4c6a-bc4e-1bfdc8fcb608)

**Comment by sellessuhteset** [comment]
i hava same issue

**Comment by masdaMehdi** [comment]
for me i format my laptop windows 10, than i download  roop-unleashed (version 4.0.0) and install it ,than when he finish insatalation i go to installer folder 'you will see a ziped file named something like 'figma' and the extracted folder for this but named diffrent somthing like 'figma vertion 4554 2023' , so i rename this folder the same name in the zipped folder , than i run the program and everything is ok

**Comment by sellessuhteset** [comment]
still not work :(

**Comment by masdaMehdi** [comment]
send me a screenshot of the terminal
