### ISSUE TITLE
Math Error

### ISSUE THREAD

**Issue by giuseppe30** [C0untFloyd/roop-unleashed#764]
**Describe the bug**
Import target video causes randomly Math Error message

**To Reproduce**
1. Go to 'Import'
2. Click on 'Import Target'
3. after upload video
4. Message: math error

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [X ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

roop unleashed v. 3.9 and v. 4

**Comment by C0untFloyd** [comment]
Can't reproduce. Corrupt video?
