### ISSUE TITLE
new version 4.0.0 livecam fram is super low, 4080 0.1fram/1s ,don't know why, 3.6.5 have 15fram/s

### ISSUE THREAD

**Issue by Kafka97** [C0untFloyd/roop-unleashed#767]
**Describe the bug**

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**

**Screenshots**

**Comment by C0untFloyd** [comment]
Using OBS or without?
If without, this is sadly a problem with the UI framework I can't do anything about it.
