### ISSUE TITLE
Cuda

### ISSUE THREAD

**Issue by bigm1312** [C0untFloyd/roop-unleashed#768]
![Képernyőkép 2024-06-24 123451](https://github.com/C0untFloyd/roop-unleashed/assets/173681646/2a43942c-999f-4102-8c53-f54aec133bd2)

Anyone has tis problem when trying to faceswap with cuda?

**Comment by BurnyBurns** [comment]
Yes - I am having the same issue. Are you using a CUDA compatible GPU? I currently have an NVIDIA 2070 Super.

**Comment by YetAnotherSiteThatNeedsMyInfo** [comment]
I have this issue. Chat GPT told me to install older cuda drivers. Didn't help.

**Comment by C0untFloyd** [comment]
You also need to install the NVIDIA Cuda Drivers if you want to use your GPU:

CUDA (Nvidia) Install CUDA Toolkit 11.8 and cuDNN for Cuda 11.x
https://developer.nvidia.com/cuda-11-8-0-download-archive
https://developer.nvidia.com/rdp/cudnn-archive

https://github.com/C0untFloyd/roop-unleashed/wiki/Installation
