### ISSUE TITLE
modify server

### ISSUE THREAD

**Issue by bobgus39** [C0untFloyd/roop-unleashed#772]
**Describe the bug**
I want to change de server where is deployed

**To Reproduce**
1. Go to 'settings.py'
2. Click on '  self.server_name = self.default_get(data, 'server_name', "[here do I have to change it?]")'

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [X ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**

**Screenshots**

**Comment by bobgus39** [comment]
to change it, we have to go to http_server.py:

# By default, the local server will try to open on localhost, port 7860.
# If that is not available, then it will try 7861, 7862, ... 7959.
INITIAL_PORT_VALUE = int(os.getenv("GRADIO_SERVER_PORT", "7860"))
TRY_NUM_PORTS = int(os.getenv("GRADIO_NUM_PORTS", "100"))
LOCALHOST_NAME = os.getenv("GRADIO_SERVER_NAME", "127.0.0.1")

**Comment by C0untFloyd** [comment]
This can all be changed in the settings tab without having to modify a file.
