### ISSUE TITLE
Video and photo processing speed

### ISSUE THREAD

**Issue by imp1508** [C0untFloyd/roop-unleashed#774]
**To Reproduce**

**Details**
What OS are you using?
- [x] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

![IMAGE 2024-06-27 22:21:54](https://github.com/C0untFloyd/roop-unleashed/assets/100021063/1dfaa75a-0d88-4883-883a-2c4b5a8a07f4)
![IMAGE 2024-06-27 22:21:58](https://github.com/C0untFloyd/roop-unleashed/assets/100021063/1d83f3e3-3c67-48f7-9bf9-1fc86c8dd692)

My question is, why is the video processed at a speed of 14 frames per second, and the photo, which is essentially one frame, is processed in 4 seconds? Is this behavior normal and if so, what is the reason for it?

**Comment by C0untFloyd** [comment]
Because at the start of batch processing the necessary AI models are loaded into memory and this adds to the first entry. Btw. you know you can have multiple files processed at once?
