### ISSUE TITLE
Output format issue: default 'png' setting generates 'webp' images

### ISSUE THREAD

**Issue by mammuthus** [C0untFloyd/roop-unleashed#775]
**Describe the bug**
The default settings haven't been changed, and the output format on the Settings page is set to the default 'png'. 
However, the generation still gives me a webp image. 
Even when I try to re-set it to 'png', nothing changes after applying the settings, and the issue persists even after a server restart.

**To Reproduce**
1. Install the roop
2. Load face resources
3. Run face swap
4. See the result in webp instead of png

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
Latest released: [roop unleashed 4.0.0](https://github.com/C0untFloyd/roop-unleashed) python: 3.10.14 • torch: 2.1.2+cu118 • gradio: 4.32.1

**Screenshots**
![image](https://github.com/C0untFloyd/roop-unleashed/assets/1700286/1dd9c43c-922e-45a5-8d90-47b2caee449d)
![image](https://github.com/C0untFloyd/roop-unleashed/assets/1700286/dcfd0a8a-63b8-414d-89c8-e37212db17b1)

**Comment by C0untFloyd** [comment]
#737
