### ISSUE TITLE
'Use OS temp folder' is ignored

### ISSUE THREAD

**Issue by mammuthus** [C0untFloyd/roop-unleashed#779]
**Describe the bug**
The 'Use OS temp folder' parameter is totally ignored. There is no difference whether I choose 'Use OS temp folder' - it still uses the `\roop-unleashed\temp`

**To Reproduce**
1. Load resources for face swap
2. Set the 'Use OS temp folder' check-box to 'off' (this is default setting)
4. Make a generation 
5. Check a `\roop-unleashed\temp` - there should be new temporary files
6. Set the 'Use OS temp folder' check-box to 'on'
7. Make a generation 
8. Check the `\roop-unleashed\temp` folder - there shouldn't be new temporary files, but they are present.
9. Check the `OS temp folder` - there should be new temporary files, but they are not present.

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
Latest released: [roop unleashed 4.0.0](https://github.com/C0untFloyd/roop-unleashed) python: 3.10.14 • torch: 2.1.2+cu118 • gradio: 4.32.1

**Screenshots**

All generations after 12:33 were made with 'Use OS temp folder' set to on. 
However, roop continues to use its own temp directory instead of the OS temp folder.

![image](https://github.com/C0untFloyd/roop-unleashed/assets/1700286/08de49e3-7054-4081-9e2f-0da9001a3389)

**Comment by C0untFloyd** [comment]
You need to restart the app for most settings to be applied.
