### ISSUE TITLE
CLI is broken

### ISSUE THREAD

**Issue by Shoaibr** [C0untFloyd/roop-unleashed#78]
**Describe the bug**
Running from the CLI doesn't work at all, although in GUI everything works fine.

**To Reproduce**
After installation, just activate the environment and run the following command:

For Image swap :
`python3 run.py -s s.png -t t.png -o o.png --execution-provider cuda --video-encoder libvpx-vp9`

For Video swap :
`python3 run.py -s s.png -t t.mp4 -o o.mp4 --execution-provider cuda --video-encoder libvpx-vp9`

Also have tried changing parameters `COMMANDLINE_ARGS` in windows_run.bat and running that .bat file, but still the same result.

For Image or Video swap, both have different errors

**Details**
What OS are you using?
- [X] Linux
- [X] Windows 

Are you trying to use a GPU?
- [X] NVIDIA Tesla A100 x8
- [X] NVIDIA Tesla V100 x4
- [X] NVIDIA Tesla T4 x2
- [X] NVIDIA Geforce RTX 3070 x1

**Screenshots**

For IMAGE swap :
![image](https://github.com/C0untFloyd/roop-unleashed/assets/15673034/89b177b6-d969-420d-a630-1778e0aaddef)

For VIDEO swap :
![image](https://github.com/C0untFloyd/roop-unleashed/assets/15673034/7b6127c9-2b99-4ebe-b38f-b1a552ce89ad)

**Sanity Check**
- [X] I have the latest code from the github repository
- [X] I have followed the installation guide

**Edited**
- [X] Uploaded the correct screenshot of the error.
- [X] Updated the correct run parameters which I used and other details.

**Comment by phineas-pta** [comment]
u have to input your video & image, the command is just an example of files

**Comment by Shoaibr** [comment]
> u have to input your video & image, the command is just an example of files

These are the actual command I used and the files with the same name were present where run.py is located.

I have tried running from CLI & also by changing the `COMMANDLINE_ARGS` parameter and running the .BAT file.

Are you able to run on CLI successfully without using GUI?

**Comment by phineas-pta** [comment]
maybe try other video & image located elsewhere

**Comment by Shoaibr** [comment]
> maybe try other video & image located elsewhere

I tried all possibilities, renaming, changing the video or picture, etc., the point is if there was any problem with the video or picture file then it shouldn't have worked in GUI.

Are you able to run in CLI successfully?

**Comment by phineas-pta** [comment]
> Are you able to run in CLI successfully?

no im not even able to run roop unleashed with gui nor cli eventhough i have a working roop (original)

have same error as #75 but still trying to find the root cause instead of workaround

**Comment by jkendric** [comment]
I have the same issue mentioned hear.  Gui works great, but trying to use headless gives
"AttributeError: 'NoneType' object has no attribute 'shape'"

**Comment by Shoaibr** [comment]
If CLI starts working, so it would be easy to make a Colab on Google as we can't use GUI on Colab!

**Comment by ash368** [comment]
> If CLI starts working, so it would be easy to make a Colab on Google as we can't use GUI on Colab!


use gradio branch

**Comment by marat2509** [comment]
> use gradio branch

Gradio branch don't changing faces on image.
