### ISSUE TITLE
Face Masking Feature Disappeared Entirely

### ISSUE THREAD

**Issue by babursss** [C0untFloyd/roop-unleashed#788]
This happened a while ago, not sure after which update. But the face masking dialog box disappeared from my interface entirely (see screenshot)
<img width="559" alt="roop" src="https://github.com/C0untFloyd/roop-unleashed/assets/174831915/de4a5907-a9a7-4493-8180-5e61a8cf3ba9">.
When I launch using "windows_run.bat", the first two lines read like this:
FFmpeg is already installed.
Skipping FFmpeg installation as it is already available.

I presume this is the root of the problem. I tried uninstalling ffmpeg and letting roop install it automatically, to no avail.
Could anybody help with this issue?

Win 11 64 Bit
NVIDIA GPU
roop version 4.0.0

Thanks.

**Comment by etruscanmuffin909** [comment]
Click "Advanced Masking"

**Comment by babursss** [comment]
> Click "Advanced Masking"

Man... It was that simple, thank you!
