### ISSUE TITLE
output video is in  libvpx-vp9

### ISSUE THREAD

**Issue by SrGrafoasspee** [C0untFloyd/roop-unleashed#8]
I installed the software using the installer and the video encodes in compressed libvpx-vp9 format instead of default libx264 as https://github.com/s0md3v/roop/wiki/3.-Advanced-Options says

How do I make it encode outputs in libx264 by default?

Thank you

**Comment by C0untFloyd** [comment]
Edit this line in windows_run.bat:
`set COMMANDLINE_ARGS=--execution-provider cuda --frame-processor face_swapper face_enhancer --video-encoder libvpx-vp9`
and remove the  --video-encoder libvpx-vp part.
