### ISSUE TITLE
 the output array type must be explicitly specified in function 'cv::arithm_op'

### ISSUE THREAD

**Issue by zhangjinyan888** [C0untFloyd/roop-unleashed#801]
**Describe the bug**

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**

**Screenshots**

Processing:   0%|                                                                             | 0/1 [00:14<?, ?frame/s]
Traceback (most recent call last):
  File "E:\roop-unleashed4.1\python311\Lib\site-packages\gradio\queueing.py", line 575, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\roop-unleashed4.1\python311\Lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\roop-unleashed4.1\python311\Lib\site-packages\gradio\blocks.py", line 1897, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\roop-unleashed4.1\python311\Lib\site-packages\gradio\blocks.py", line 1495, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\roop-unleashed4.1\python311\Lib\site-packages\gradio\utils.py", line 661, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\roop-unleashed4.1\python311\Lib\site-packages\gradio\utils.py", line 654, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\roop-unleashed4.1\python311\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\roop-unleashed4.1\python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "E:\roop-unleashed4.1\python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\roop-unleashed4.1\python311\Lib\site-packages\gradio\utils.py", line 637, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "E:\roop-unleashed4.1\python311\Lib\site-packages\gradio\utils.py", line 799, in gen_wrapper
    response = next(iterator)
               ^^^^^^^^^^^^^^
  File "E:\roop-unleashed4.1\ui\tabs\faceswap_tab.py", line 626, in start_swap
    batch_process_regular(list_files_process, mask_engine, clip_text, processing_method == "In-Memory processing", imagemask, num_swap_steps, progress, SELECTED_INPUT_FACE_INDEX)
  File "E:\roop-unleashed4.1\roop\core.py", line 221, in batch_process_regular
    batch_process(files, use_new_method)
  File "E:\roop-unleashed4.1\roop\core.py", line 279, in batch_process
    process_mgr.run_batch(origimages, fakeimages, roop.globals.execution_threads)
  File "E:\roop-unleashed4.1\roop\ProcessMgr.py", line 171, in run_batch
    future.result()
  File "E:\roop-unleashed4.1\python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "E:\roop-unleashed4.1\python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "E:\roop-unleashed4.1\python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\roop-unleashed4.1\roop\ProcessMgr.py", line 187, in process_frames
    resimg = self.process_frame(temp_frame)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\roop-unleashed4.1\roop\ProcessMgr.py", line 327, in process_frame
    num_swapped, temp_frame = self.swap_faces(frame, temp_frame)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\roop-unleashed4.1\roop\ProcessMgr.py", line 373, in swap_faces
    temp_frame = self.process_face(self.options.selected_index, face, temp_frame)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\roop-unleashed4.1\roop\ProcessMgr.py", line 582, in process_face
    result = self.paste_upscale(fake_frame, enhanced_frame, target_face.matrix, frame, scale_factor, mask_offsets)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\roop-unleashed4.1\roop\ProcessMgr.py", line 655, in paste_upscale
    paste_face = cv2.addWeighted(paste_face, self.options.blend_ratio, fake_face, 1.0 - self.options.blend_ratio, 0)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\arithm.cpp:674: error: (-5:Bad argument) When the input arrays in add/subtract/multiply/divide functions have different types, the output array type must be explicitly specified in function 'cv::arithm_op'

**Comment by batheinherchest** [comment]
yep, having this exact issue

**Comment by CKVNZ** [comment]
getting this error after the update as well.

**Comment by kumarvivek1752** [comment]
exactly same issue i have 
```
  File "D:\program\roop-unleashed\installer\roop-unleashed\roop\ProcessMgr.py", line 655, in paste_upscale
    paste_face = cv2.addWeighted(paste_face, self.options.blend_ratio, fake_face, 1.0 - self.options.blend_ratio, 0)
cv2.error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\arithm.cpp:674: error: (-5:Bad argument) When the input arrays in add/subtract/multiply/divide functions have different types, the output array type must be explicitly specified in function 'cv::arithm_op'

```

**Comment by testygit01** [comment]
Getting the same error after the update today

**Comment by oklmland** [comment]
same error after the update today

**Comment by DarienXcom** [comment]
i am getting that error since update , does anyone found any fix?

**Comment by zeki0485** [comment]
Find the following lines:
if upsk_face is not fake_face:
    fake_face = cv2.warpAffine(fake_face, IM, (target_img.shape[1], target_img.shape[0]), borderMode=cv2.BORDER_REPLICATE)
    paste_face = cv2.addWeighted(paste_face, self.options.blend_ratio, fake_face, 1.0 - self.options.blend_ratio, 0)

and replace it with:
if upsk_face is not fake_face:
    fake_face = cv2.warpAffine(fake_face, IM, (target_img.shape[1], target_img.shape[0]), borderMode=cv2.BORDER_REPLICATE)
    # Ensure both arrays have the same data type
    paste_face = paste_face.astype(np.float32)
    fake_face = fake_face.astype(np.float32)
    paste_face = cv2.addWeighted(paste_face, self.options.blend_ratio, fake_face, 1.0 - self.options.blend_ratio, 0)

**Comment by kumarvivek1752** [comment]
@zeki0485 i replaced but its not working
my changes:
```python
        img_matte = np.reshape(img_matte, [img_matte.shape[0],img_matte.shape[1],1]) 
        paste_face = cv2.warpAffine(upsk_face, IM, (target_img.shape[1], target_img.shape[0]), borderMode=cv2.BORDER_REPLICATE)
        # if upsk_face is not fake_face:
        #     fake_face = cv2.warpAffine(fake_face, IM, (target_img.shape[1], target_img.shape[0]), borderMode=cv2.BORDER_REPLICATE)
        #     paste_face = cv2.addWeighted(paste_face, self.options.blend_ratio, fake_face, 1.0 - self.options.blend_ratio, 0)
        if upsk_face is not fake_face:
            fake_face = cv2.warpAffine(fake_face, IM, (target_img.shape[1], target_img.shape[0]), borderMode=cv2.BORDER_REPLICATE)
            # Ensure both arrays have the same data type
            paste_face = paste_face.astype(np.float32)
            fake_face = fake_face.astype(np.float32)
            paste_face = cv2.addWeighted(paste_face, self.options.blend_ratio, fake_face, 1.0 - self.options.blend_ratio, 0)
            
```

**Comment by zeki0485** [comment]
@kumarvivek1752

Unfortunately I can't debug it because I'm at work.
Try this:

AFTER:
paste_face = paste_face.astype(np.float32)
fake_face = fake_face.astype(np.float32)

add this:
if paste_face.shape[-1] != 3:
        paste_face = cv2.cvtColor(paste_face, cv2.COLOR_GRAY2BGR)
if fake_face.shape[-1] != 3:
        fake_face = cv2.cvtColor(fake_face, cv2.COLOR_GRAY2BGR)

**Comment by kumarvivek1752** [comment]
@zeki0485 i added but still same error

my current code :
```python

        img_matte = np.reshape(img_matte, [img_matte.shape[0],img_matte.shape[1],1]) 
        paste_face = cv2.warpAffine(upsk_face, IM, (target_img.shape[1], target_img.shape[0]), borderMode=cv2.BORDER_REPLICATE)
        # if upsk_face is not fake_face:
        #     fake_face = cv2.warpAffine(fake_face, IM, (target_img.shape[1], target_img.shape[0]), borderMode=cv2.BORDER_REPLICATE)
        #     paste_face = cv2.addWeighted(paste_face, self.options.blend_ratio, fake_face, 1.0 - self.options.blend_ratio, 0)
        if upsk_face is not fake_face:
            fake_face = cv2.warpAffine(fake_face, IM, (target_img.shape[1], target_img.shape[0]), borderMode=cv2.BORDER_REPLICATE)
            # Ensure both arrays have the same data type
            paste_face = paste_face.astype(np.float32)
            fake_face = fake_face.astype(np.float32)
            paste_face = cv2.addWeighted(paste_face, self.options.blend_ratio, fake_face, 1.0 - self.options.blend_ratio, 0)
            if paste_face.shape[-1] != 3:
                paste_face = cv2.cvtColor(paste_face, cv2.COLOR_GRAY2BGR)
            if fake_face.shape[-1] != 3:
                fake_face = cv2.cvtColor(fake_face, cv2.COLOR_GRAY2BGR)
            
```

**Comment by zeki0485** [comment]
@kumarvivek1752 

if upsk_face is not fake_face:
            fake_face = cv2.warpAffine(fake_face, IM, (target_img.shape[1], target_img.shape[0]), borderMode=cv2.BORDER_REPLICATE)
            paste_face = paste_face.astype(np.float32)
            fake_face = fake_face.astype(np.float32)
            if paste_face.shape[-1] != 3:
                paste_face = cv2.cvtColor(paste_face, cv2.COLOR_GRAY2BGR)
            if fake_face.shape[-1] != 3:
                fake_face = cv2.cvtColor(fake_face, cv2.COLOR_GRAY2BGR)
            paste_face = cv2.addWeighted(paste_face, self.options.blend_ratio, fake_face, 1.0 - self.options.blend_ratio, 0)

**Comment by kumarvivek1752** [comment]
i added but still same error can you please make a pull request of updated code?

my current code:
```python

            green_color = [0, 255, 0]  # RGB for green
            for i in range(3):  # Apply green color where img_matte is not zero
                green_overlay[:, :, i] = np.where(img_matte > 0, green_color[i], 0)        ##Transform upcaled face back to target_img
        img_matte = np.reshape(img_matte, [img_matte.shape[0],img_matte.shape[1],1]) 
        paste_face = cv2.warpAffine(upsk_face, IM, (target_img.shape[1], target_img.shape[0]), borderMode=cv2.BORDER_REPLICATE)
        # if upsk_face is not fake_face:
        #     fake_face = cv2.warpAffine(fake_face, IM, (target_img.shape[1], target_img.shape[0]), borderMode=cv2.BORDER_REPLICATE)
        #     paste_face = cv2.addWeighted(paste_face, self.options.blend_ratio, fake_face, 1.0 - self.options.blend_ratio, 0)
        if upsk_face is not fake_face:
            fake_face = cv2.warpAffine(fake_face, IM, (target_img.shape[1], target_img.shape[0]), borderMode=cv2.BORDER_REPLICATE)
            paste_face = paste_face.astype(np.float32)
            fake_face = fake_face.astype(np.float32)
            if paste_face.shape[-1] != 3:
                paste_face = cv2.cvtColor(paste_face, cv2.COLOR_GRAY2BGR)
            if fake_face.shape[-1] != 3:
                fake_face = cv2.cvtColor(fake_face, cv2.COLOR_GRAY2BGR)
            paste_face = cv2.addWeighted(paste_face, self.options.blend_ratio, fake_face, 1.0 - self.options.blend_ratio, 0)

        # Re-assemble image
        paste_face = img_matte * paste_face
        paste_face = paste_face + (1-img_matte) * target_img.astype(np.float32)
        if self.options.show_face_area_overlay:
            # Overlay the green overlay on the final image
            paste_face = cv2.addWeighted(paste_face.astype(np.uint8), 1 - 0.5, green_overlay, 0.5, 0)
        return paste_face.astype(np.uint8)
```

**Comment by Dizzy3333** [comment]
I have the same issue. I realized that this happens only if I change anything in the "Select Post Processing" drop down menu. If I keep it to "none", then it works (but of course with a not so good quality).

**Comment by jp7189** [comment]
I agree with Dizzy3333.  This issue only occurs for me with post processing enabled.  It does not seem to matter which post processor is selected.  Perhaps a conflict between the new subsample upscale and post processing?

**Comment by DarienXcom** [comment]
I just noticed it happens when i select any post-processing, when i leave it in None it works but as always, when no post-processing looks low-res very pixelated, although the new feature "subsample upscale" helps to make it better quality

**Comment by C0untFloyd** [comment]
#800
