### ISSUE TITLE
Faceset is not a zip file

### ISSUE THREAD

**Issue by Kingkladzemcr** [C0untFloyd/roop-unleashed#802]
There is still an issue of uploading fsz files and error saying they are not a zip file regardless of size/faces within faceset.

**Comment by Kingkladzemcr** [comment]
recreating facesets in new version seems to rectify the problem. Older facesets made using older version of roop seem to fail

**Comment by C0untFloyd** [comment]
Oh ok, can you tell how old? Very old versions had a bug with face border calculations.

**Comment by Kingkladzemcr** [comment]
original facesets were only created in early june 24
