### ISSUE TITLE
Just Updated to Latest Version - OpenCV Error with Codeformer

### ISSUE THREAD

**Issue by milhouse34521** [C0untFloyd/roop-unleashed#804]
**Describe the bug**
Received this while trying to use Roop

error
OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\arithm.cpp:674: error: (-5:Bad argument) When the input arrays in add/subtract/multiply/divide functions have different types, the output array type must be explicitly specified in function 'cv::arithm_op' 

**To Reproduce**

Open source fsz file.
Open target file
Choose any face method
Choose Codeformer
Click Start

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
Latest as of 2024-07-15

**Comment by milhouse34521** [comment]
Did some more testing and seems to work fine if no post-processor is selected. GFPGAN, Restoreformer++ etc. throw the error.

**Comment by LearningCreator** [comment]
Same as above.

**Comment by Nyikoszoltan** [comment]
Megoldás nagyon érdekelne....

**Comment by xunny007** [comment]
Same as above

**Comment by C0untFloyd** [comment]
#800
