### ISSUE TITLE
Can the next version add facial recognition function

### ISSUE THREAD

**Issue by zhangjinyan888** [C0untFloyd/roop-unleashed#811]
Can the next version add facial recognition function, including mouth teeth, upper lip, lower lip, nose, left eye, right eye, left eyebrow, and right eyebrow

**Comment by zhangjinyan888** [comment]
The main issue is that after tooth replacement, it looks unsightly, and the teeth of the source video character are preserved

**Comment by arthforeign** [comment]
Something like https://github.com/KwaiVGI/LivePortrait ??
