### ISSUE TITLE
Stopped working on both Kaggle and Colab 

### ISSUE THREAD

**Issue by arafatshawon** [C0untFloyd/roop-unleashed#812]
Roop Unleashed stopped working on both Kaggle and Colab few hours ago...

![Screenshohmgt_1](https://github.com/user-attachments/assets/e3ae6e42-3b59-4889-a8b1-b9d7a9a2f69f)

**Comment by Kingkladzemcr** [comment]
Yes I had the same issue come up on paperspace at around 6pm GMT 16/7/24 after it had been working fine that day.

**Comment by lihua202406** [comment]
I can run it on kaggle,with the error Failed to load library libonnxruntime_providers_cuda.so with error: libcufft.so.10: cannot open shared object file: No such file or directory.and it couldn't use gpu to inference.

**Comment by Kingkladzemcr** [comment]
error on colab 

!apt-get -y update
!apt-get -y install cuda-toolkit-11-8
import os
os.environ["LD_LIBRARY_PATH"] += ":" + "/usr/local/cuda-11/lib64"
os.environ["LD_LIBRARY_PATH"] += ":" + "/usr/local/cuda-11.8/lib64"

Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Ign:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:8 https://r2u.stat.illinois.edu/ubuntu jammy Release
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
cuda-toolkit-11-8 is already the newest version (11.8.0-1).
0 upgraded, 0 newly installed, 0 to remove and 48 not upgraded.

!git clone https://github.com/C0untFloyd/roop-unleashed.git
%cd roop-unleashed
!mv config_colab.yaml config.yaml
!pip install pip install -r requirements.txt

!git clone https://github.com/C0untFloyd/roop-unleashed.git
%cd roop-unleashed
!mv config_colab.yaml config.yaml
!pip install pip install -r requirements.txt
Cloning into 'roop-unleashed'...
remote: Enumerating objects: 3018, done.
remote: Counting objects: 100% (37/37), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 3018 (delta 9), reused 30 (delta 5), pack-reused 2981
Receiving objects: 100% (3018/3018), 104.04 MiB | 16.55 MiB/s, done.
Resolving deltas: 100% (1897/1897), done.
/content/roop-unleashed/roop-unleashed
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Ignoring torch: markers 'sys_platform == "darwin"' don't match your environment
Ignoring torchvision: markers 'sys_platform == "darwin"' don't match your environment
Ignoring onnxruntime: markers 'sys_platform == "darwin" and platform_machine != "arm64"' don't match your environment
Ignoring onnxruntime-silicon: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Requirement already satisfied: pip in /usr/local/lib/python3.10/dist-packages (23.1.2)
ERROR: Could not find a version that satisfies the requirement install (from versions: none)
ERROR: No matching distribution found for install

**Comment by lihua202406** [comment]
> error on colab 
> 
> !apt-get -y update
> !apt-get -y install cuda-toolkit-11-8
> import os
> os.environ["LD_LIBRARY_PATH"] += ":" + "/usr/local/cuda-11/lib64"
> os.environ["LD_LIBRARY_PATH"] += ":" + "/usr/local/cuda-11.8/lib64"
> 
> Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
> Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
> Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
> Hit:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
> Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
> Hit:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
> Ign:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
> Hit:8 https://r2u.stat.illinois.edu/ubuntu jammy Release
> Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
> Hit:10 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
> Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
> Reading package lists... Done
> W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> cuda-toolkit-11-8 is already the newest version (11.8.0-1).
> 0 upgraded, 0 newly installed, 0 to remove and 48 not upgraded.
> 
> !git clone https://github.com/C0untFloyd/roop-unleashed.git
> %cd roop-unleashed
> !mv config_colab.yaml config.yaml
> !pip install pip install -r requirements.txt
> 
> Cloning into 'roop-unleashed'...
> remote: Enumerating objects: 3018, done.
> remote: Counting objects: 100% (37/37),o done.ook
> remote: Compressing objects: 100% (30/30), done.
> remote: Total 3018 (delta 9), reused 30 (delta 5), pack-reused 2981
> Receiving objects: 100% (3018/3018), 104.04 MiB | 16.55 MiB/s, done.
> Resolving deltas: 100% (1897/1897), done.
> /content/roop-unleashed/roop-unleashed
> Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
> Ignoring torch: markers 'sys_platform == "darwin"' don't match your environment
> Ignoring torchvision: markers 'sys_platform == "darwin"' don't match your environment
> Ignoring onnxruntime: markers 'sys_platform == "darwin" and platform_machine != "arm64"' don't match your environment
> Ignoring onnxruntime-silicon: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
> Requirement already satisfied: pip in /usr/local/lib/python3.10/dist-packages (23.1.2)
> ERROR: Could not find a version that satisfies the requirement install (from versions: none)
> ERROR: No matching distribution found for install
> 

U can skip this step,the clone repo.run the
`pip install -r requirements.txt`
Install the coda or the libs that aren't installed.
I solved  the problem that I faced successfully.

**Comment by arafatshawon** [comment]
I am not expert on this matter... can u please show me how to fix... Or can u please share me ur notebook file/setup...

**Comment by Kingkladzemcr** [comment]
added !pip install onnxruntime-gpu and seemed to work but not very quick on processing

!git clone https://github.com/C0untFloyd/roop-unleashed.git
%cd roop-unleashed
!mv config_colab.yaml config.yaml
!pip install pip install -r requirements.txt
!pip install onnxruntime-gpu

**Comment by Kingkladzemcr** [comment]
was working earlier now throwing back following error

Traceback (most recent call last):
  File "/content/roop-unleashed/roop-unleashed/run.py", line 3, in <module>
    from roop import core
  File "/content/roop-unleashed/roop-unleashed/roop/core.py", line 22, in <module>
    import roop.utilities as util
  File "/content/roop-unleashed/roop-unleashed/roop/utilities.py", line 11, in <module>
    import gradio
ModuleNotFoundError: No module named 'gradio'

**Comment by Marv761125** [comment]
Same issue.
![Screen](https://github.com/user-attachments/assets/df38a80e-5ed0-47f0-a370-41502b4e46e4)

**Comment by zachysaur** [comment]
https://youtu.be/Pq9tiHp7wDI

**Comment by LaggyN00b** [comment]
same issue here, please help fix

**Comment by C0untFloyd** [comment]
> https://youtu.be/Pq9tiHp7wDI

You know that most of the models prohibit commercial usage? No wonder you've got a cease and desist from face fusion...

**Comment by zachysaur** [comment]
which ones?

**Comment by zachysaur** [comment]
if youhelp me understand so i dont do them things i dont got any knowledge

**Comment by zachysaur** [comment]
facefusion didnt wanted me to post forks videos

**Comment by C0untFloyd** [comment]
> which ones?

Actually most of them and the most important one, the insightface swapper too 😄 
Take a look here:
https://docs.facefusion.io/introduction/licenses

**Comment by zachysaur** [comment]
damn i can feel how hard it is for you to bring up update

**Comment by Marv761125** [comment]
Hi C0untFloyd. 
Is there any chance that this amazing program will be working again on Colab?
Thx.
Marv

**Comment by zachysaur** [comment]
https://youtu.be/Iy0PaElchlg  for google collab being a free user

**Comment by C0untFloyd** [comment]
Tried myself in a free colab session, skipped the first cell (I believe re-installing cuda is not needed anymore) and got it to launch. However Google seems to actively ban swapping apps and I was quickly disconnected from the runtime. It looked like it should work with a premium account.

**Comment by LaggyN00b** [comment]
It works now, just make sure you have google compute units and it will work fine. Thank you C0untyFloud.

**Comment by zachysaur** [comment]
[C0untFloyd]i made a notebook of it its working fine lol with free accounts

**Comment by C0untFloyd** [comment]
@zachysaur Except for the 2 codec lines there's nothing different in "your" notebook. It will run the same as my one...

**Comment by zachysaur** [comment]
yes but as free user  google collab dont allow this code and on kaggle they banned accounts if you run deepfake any software only with rot-13 you can use it .

**Comment by zachysaur** [comment]
is there a way you can add voice cloning to your gui?

**Comment by Kingkladzemcr** [comment]
all working on paperspace now

**Comment by sparking-meteor** [comment]
If any of you still got problems on kaggle you can use the fork i made instead, it's an older version but works fine regardless
