### ISSUE TITLE
何度やってもエラー表示になります、、、Google Colabも 課金したのに、、、

### ISSUE THREAD

**Issue by Mt-Collective** [C0untFloyd/roop-unleashed#815]
![2024-07-17 20 30の画像](https://github.com/user-attachments/assets/dcf4ab59-9022-46a6-b66d-04de51e504c9)
**Describe the bug**

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**

**Screenshots**

**Comment by C0untFloyd** [comment]
#812
