### ISSUE TITLE
select post-processing giving error 

### ISSUE THREAD

**Issue by Hydernyshh** [C0untFloyd/roop-unleashed#817]
Select post processing giving error in Roop unleashed 4.1.0 I have attached error details.

**To Reproduce**
1. Go to 'roop unleashed 4.1.0'
2. Click on 'select GPEN in select post-processing and click start button
![Capture](https://github.com/user-attachments/assets/3f5b4fc8-d7a1-4a48-bef8-062a7e115e7e)

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ 10] Windows 
- [ ] Mac

Are you using a GPU?
- [Yes ] No. CPU FTW
- [ Yes] NVIDIA
- [ Yes] AMD
- [Yes ] Intel
- [ No] Mac

**Which version of roop unleashed are you using?**
4.1.0

**Screenshots**

**Comment by fowgo** [comment]
This error has already been fixed in the new 4.1.1 version. Just upgrade your Roop version.

**Comment by Hydernyshh** [comment]
Dear Fowgo I am getting same issue in 4.1.1 as well. anything else needs to be done?

**Comment by C0untFloyd** [comment]
Yes, answer the update question with y. Latest version is v4.1.4 already
