### ISSUE TITLE
Preview Frame/Fake view scrub bar does not work

### ISSUE THREAD

**Issue by Orchoidizer** [C0untFloyd/roop-unleashed#82]
[roop unleashed 2.7.0](https://github.com/C0untFloyd/roop-unleashed) 
Preview Original Frame/Fake view does not work

**To Reproduce**
1. Go to 'Preview Original Fake/Frame '
2. Click on 'Frame No'
3. Scroll down to 'Scrub bar'
4. Does Not Work

**Details**
What OS are you using?
Windows 11

- [y] NVIDIA RTX3080ti - mobile

**Screenshots**

**Sanity Check**
- [y] I have the latest code from the github repository
- [y] I have followed the installation guide

**Comment by C0untFloyd** [comment]
The file you want to preview needs to be selected to have roop know, which video to preview. You can have multiple files in the listbox for batch processing...

**Comment by Orchoidizer** [comment]
Well yes, the file WAS selected. Why are you mentioning batch processing?
