### ISSUE TITLE
Error when select a post-processing and start the swap

### ISSUE THREAD

**Issue by MarcosdrVinicios** [C0untFloyd/roop-unleashed#824]
**Describe the bug**
Error when select a post-processing and start the swap

**To Reproduce**
1. Add source image and target video
2. Select post-processing (GFPGAN)
3. Start
4. Error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\arithm.cpp:674: error: (-5:Bad argument) When the input arrays in add/subtract/multiply/divide functions have different types, the output array type must be explicitly specified in function 'cv::arithm_op'

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**4.1.1

**Screenshots**
![image](https://github.com/user-attachments/assets/fa2f4ea2-3265-47ce-b670-52ca31bf86fa)

**Comment by C0untFloyd** [comment]
Are you sure? I mean...are you really sure you don't have 2 installations or something?
Take a look here https://github.com/C0untFloyd/roop-unleashed/blob/77ebb3ffaadea5cea4764e00fb615255a6c3e4fb/roop/ProcessMgr.py#L565
If the line in that file doesn't look like this then you're not on v4.1.1

**Comment by MarcosdrVinicios** [comment]
I confirm that I just have one installation and I'm on verion4.1.1 and I have that line(565)
![image](https://github.com/user-attachments/assets/caeace3b-60d6-4a13-8d76-60444935578a)

**Comment by C0untFloyd** [comment]
I'm sorry I can't reproduce this. Do you have any unusual setting? Does this also happen in the preview faceswap? Is this with videos/images? Are you using text masking?

**Comment by MarcosdrVinicios** [comment]
Just happens when I select a post-processing.
This is with a source image and the target is a video. The settings are the default ones, and I don't use text masking.

**Comment by C0untFloyd** [comment]
This is weird. The line I showed above is the only change needed and if you have it, then perhaps the newest source isn't used.
Can you try deleting the subfolders named '__pycache__' inside the roop folder? Perhaps it didn't recompile. You could also try re-installing from scratch. If that also doesn't help I'm out of ideas...
