### ISSUE TITLE
[Errno 2] No such file or directory: 'ffmpeg'

### ISSUE THREAD

**Issue by drfunthing** [C0untFloyd/roop-unleashed#826]
**Describe the bug**
[Errno 2] No such file or directory: 'ffmpeg'

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ x] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ x] Mac

**Which version of roop unleashed are you using?**
[roop unleashed 4.1.1]
**Screenshots**

**Comment by nayan924** [comment]
!apt-get update
!apt-get install ffmpeg -y

**Comment by C0untFloyd** [comment]
#598
