### ISSUE TITLE
So we can't provide --share or --server_share as parameter?

### ISSUE THREAD

**Issue by FurkanGozukara** [C0untFloyd/roop-unleashed#829]
I tried

python app.py --server_share
python app.py --server_share True
python app.py --share 
python app.py --share True 

None working. I am making 1-click installer for Windows, RunPod and Massed Compute

**Comment by C0untFloyd** [comment]
For a long time there are no cmdline arguments but a UI and a config file instead...
![settings](https://github.com/user-attachments/assets/80099d4b-bdc9-4308-adbd-919ef473b2d8)

Inside config.yaml:
`server_share: true`

**Comment by FurkanGozukara** [comment]
@C0untFloyd thanks but it really doesnt help me. i had to modify config, upload somewhere else and make it auto downloaded with installer :(

**Comment by C0untFloyd** [comment]
Is this about Colab/Kaggle Access? If so, there's an extra config_colab.yaml which has server sharing as default setting. Your script would just need to rename this to config.yaml.

**Comment by FurkanGozukara** [comment]
@C0untFloyd it is for runpod and massed compute. surely people can edit and restart but that is extra step :/
