### ISSUE TITLE
Face selection not working properly 

### ISSUE THREAD

**Issue by M4N0J-KUM4R** [C0untFloyd/roop-unleashed#834]
**Describe the bug**
Selected face method is not working properly if I select male face and i try to refresh it's again swapping both male and female face or only the female the selected face is blacklisted I don't know why it giving wierd results instead what it should its a bug. Tried all mens face too but it skips lots of frames even the subject face is clearly visible with no face rotations.

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux(kaggle)

Are you using a GPU?
- [ ] No. CPU FTW
- [ yes ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
Latest
**Screenshots**

**Comment by C0untFloyd** [comment]
Selection by gender is always hit and miss, I would use face similarity instead -> https://github.com/C0untFloyd/roop-unleashed/wiki/Face-Swap-Tab
