### ISSUE TITLE
Issue with post processing

### ISSUE THREAD

**Issue by Stanley154** [C0untFloyd/roop-unleashed#838]
Hey guys, I somehow got roop unleashed to work with my AMD laptop, using CPU coz of low VRAM, but whenever I am trying to use some post processing, it always shows some kind of error, like different errors with each of them, And I want to use it because like the face in the video faceswap gets blurred, here and there, Please help me solve this issue

**Comment by Stanley154** [comment]
> Hi there. Feel free to post some of the errors from the log/terminal to allow people to rely on those infos instead of guessing what could be the case here. Also add some details regarding your system and setup and which steps you already performed.
> 
> **There's basically zero usable information available as of now, so even if people wanted to help/respond, they couldn't.** It's like walking into a repair shop and saying that your last drive felt kinda weird, expecting to receive a proper solution. ;-)

I see, very sorry for that

Here the error I am facing when using codeformer or GPEN or GFPGAN

OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\arithm.cpp:674: error: (-5:Bad argument) When the input arrays in add/subtract/multiply/divide functions have different types, the output array type must be explicitly specified in function 'cv::arithm_op'

Till now I have basically installed roop from installer, and I am using CPU( AMD laptop), somehow got it to work without post processing but when trying to use it I get the above error

Plus I used some other softwares as well but it gives me some other kind of error when using it

**Comment by C0untFloyd** [comment]
You need to update to the latest version, answer the update question with y to get rid of that error.

**Comment by Stanley154** [comment]
> You need to update to the latest version, answer the update question with y to get rid of that error. After that update you need to switch to cpu again in the settings.

Thanks

**Comment by Stanley154** [comment]
> You need to update to the latest version, answer the update question with y to get rid of that error. After that update you need to switch to cpu again in the settings.

Thanks a lot man, it works now, I thought I was on latest version but it still did some updates and now it works, again thank you so much.
