### ISSUE TITLE
can add "1024px" to option "Subsample upscale to" ?

### ISSUE THREAD

**Issue by botong-zhou** [C0untFloyd/roop-unleashed#841]
can add "1024px" to option "Subsample upscale to" ? 
because 512px is not enough, 
or we can add this by ui, like "640px"

**Comment by C0untFloyd** [comment]
512px is my magic number for a good tradeoff between speed and quality. Of course one could increase it but it would again take twice as long without a noticeable quality increase. I'd rather implement some kind of sharpening filter instead.
