### ISSUE TITLE
Roop Install issue please advise

### ISSUE THREAD

**Issue by szlateva** [C0untFloyd/roop-unleashed#843]
Describe the bug
I run the installer in cmd, it goes like i'd expect, once it finishes and tries to launch roop unleashed it says "Conda is not installed... Exiting" repeatedly. I'm attempting to run it on windows 11 and I've checked if conda is in the folder tree and it clearly took the time to download miniconda, and i'm not great at this stuff admittedly but i'm not bad at troubleshooting cmd stuff either, i've gotten deepface labs and faceswap to run fine in the past. However this conda issue has me boggled. I've reinstalled anaconda, miniconda, and double checked the paths and even tried several different paths to assign for conda. Nothing has worked. I have installed visual studio too. Nothing I do seems to get it to launch, in opening a instance of conda and trying to use it to run the installer a second time to run the program it still says conda is not installed. I've managed in using specifically an anaconda prompt and deactivating conda I've managed to get it to not return the error "conda is not installed" but instead of that it just stalls out on "Launching roop-unleashed" and then nothing opens, no gui, no window of visual studio, no browser window, notta, and it doesn't allow any more input in the command line because if i try to enter something new then it does give the not installed and exits.

To Reproduce

unzip - extract to fresh folder
run the windows_run.bat
wait for downloads, all succeed even miniconda
cmd attempts to launch (or if not CMD, miniconda, or anaconda3) and then inevitable "conda is not installed exiting"
Details
What OS are you using?

 Linux
 Linux in WSL
[ x] Windows
 Mac
Are you using a GPU?

 No. CPU FTW
[ x] NVIDIA
 AMD
 Intel
 Mac
Which version of roop unleashed are you using? most recent as of 8/7/24
Screenshots

![Screenshot 2024-08-07 184059](https://github.com/user-attachments/assets/81dc2189-c876-45dd-97c6-e5c56230f4f6)

I tried running as admin. Didn't work.
 This usually shows up but I click "more info" and "run anyway"
![image](https://github.com/user-attachments/assets/32563fd0-24c2-48e6-9e75-c678c64ec8b3)

Unsure as I'm not a programmer. Appreciate your work tho btw. TIA for the help.

**Comment by C0untFloyd** [comment]
Not a code issue -> Discussions
