### ISSUE TITLE
Preview Slider

### ISSUE THREAD

**Issue by C0untFloyd** [C0untFloyd/roop-unleashed#85]
At the bottom of the preview window the slider doesn't move when you try to drag it, you have to type a frame number in the box. Also nice update I'm diggin the way the new GUI looks.

_Originally posted by @TheBigSmokey in https://github.com/C0untFloyd/roop-unleashed/issues/81#issuecomment-1675724466_

**Comment by C0untFloyd** [comment]
Can't reproduce. What about the arrows, do they work? You're using a video or GIF with multiple frames I suppose?

**Comment by eniora** [comment]
Ye I couldn't reproduce this as well, working fine here and tried with multiple videos. And thanks a lot for fixing the auto swapping method mode!

**Comment by Fijitrix** [comment]
Slider isn't working for me either. I can manually enter frame numbers and it'll jump to that frame but I can't scrub through the video with the slider.

**Comment by Fijitrix** [comment]
Arrow keys do nothing for me neither

**Comment by TheBigSmokey** [comment]
> Can't reproduce. What about the arrows, do they work? You're using a video or GIF with multiple frames I suppose?

I had tried with a .mp4 and a .webm neither let me move the slider. I'm using chrome/windows.

**Comment by C0untFloyd** [comment]
What OS are you on and which browser? I could find several issues at gradio:
https://github.com/gradio-app/gradio/issues/4305
https://github.com/gradio-app/gradio/issues/4471

Could you update to the version I committed some minutes ago? Perhaps a small change I made will fix it...

**Comment by TheBigSmokey** [comment]
That appears to fix it. The slider is working for single and multiple videos now. If you remove a target video it does throw an error (see attached .png) but the error doesn't seem to effect any functionality. I think it's just unhappy it's trying to find a file and there isn't one.
![NoneTypeError](https://github.com/C0untFloyd/roop-unleashed/assets/132793936/7842fc60-2466-4e77-a529-7aad15089d17)

**Comment by TheBigSmokey** [comment]
I just ran into this error. If you add multiple targets then remove them and add a single target the preview won't load.  I'm pretty sure that wasn't an issue before that commit but I'm not 100%.
![list index](https://github.com/C0untFloyd/roop-unleashed/assets/132793936/94aa4c7b-0e3d-4809-b386-b7b51ee58d99)

**Comment by eniora** [comment]
@TheBigSmokey I updated to the latest commit and tried to reproduce the issue but I couldn't. You mean adding multiple faces from a video and clicking done, then removing them and adding any other face from another video/image it won't load? tried this and the face loaded fine in preview (tried both from image and video afterwards). Unless you mean another thing.

**Comment by TheBigSmokey** [comment]
@eniora It happens when I add multiple target files (such as two .mp4 files) then remove the target files and try to add a single one. for example I had two videos selected as targets, I used the preview and figured out they wouldn't look good (wonky looking face swap) so I removed them and tried to add a single different .mp4 file. That prompts the list index error. Its something about going from multiple files to a single file in the "target". At least that's what I experienced.

**Comment by eniora** [comment]
Ah ok, anyway I just tried exactly this now, idk no issues here. I added 3 video files as target, played with them and swapped in preview etc. then removed them and added a single MP4 file, was still able to play with it and swap faces in preview.

**Comment by Orchoidizer** [comment]
the preview slider simply does not work. In any way. arrows dont work either. entering a number has no effect. i am using Firefox

**Comment by Orchoidizer** [comment]
All good here! You are amazing sir! Thanks so much for this amazing tool!

**Comment by C0untFloyd** [comment]
@TheBigSmokey perhaps you missed the secret update from yesterday where I secretly fixed
https://user-images.githubusercontent.com/132793936/260249826-7842fc60-2466-4e77-a529-7aad15089d17.png

Closing this as I think it is resolved.

**Comment by will-hill** [comment]
I am having this issue with gradio 4.3.0, gradio_client 0.7.0, python 3.10.2, Chrome browser, Mac OS.  Sliders look great, but are disabled, frozen.
