### ISSUE TITLE
Suggestion pls read

### ISSUE THREAD

**Issue by Michael2Miller** [C0untFloyd/roop-unleashed#850]
In the Rector face swapper we can create a face model based on multiple pictures 
After that the result would be a file which is a face model
The result of putting the face model which we created instead of the source image 
the result would be perfect
I know that this is hard but I wish if you can add some in the interface to create a face model based on multiple pictures
And after that we can put the face model file as the source image
Then the result would be better than any other deep faking applications are programs
I wonder if you can do it I wish

**Comment by papagodzilla** [comment]
i think you didnt explore roop face management tab

**Comment by hacshacdgacs** [comment]
Similar to this so I won't be opening a new issue for it but with reactor those facemodels are saved into a folder that also appears in a dropdown menu, is there any chance of that being implemented? (an example layout would be a dropdown under Input Faces that would host all the facemodels that have been created)
