### ISSUE TITLE
error creating conda enviroment

### ISSUE THREAD

**Issue by adaadaada23** [C0untFloyd/roop-unleashed#851]
Whenever I run the installer I get a message stating: InvalidArchiveError("Error with archive C:\\Users\\user\\Documents\\roop-unleashed_win4.1.1_installer\\roop-unleashed\\installer_files\\conda\\pkgs\\setuptools-72.1.0-py310haa95532_0.conda.  You probably need to delete and re-download or re-create this file.  Message was:\n\nfailed with error: [Errno 2] No such file or directory: 'C:\\\\Users\\\\user\\\\Documents\\\\roop-unleashed_win4.1.1_installer\\\\roop-unleashed\\\\installer_files\\\\conda\\\\pkgs\\\\setuptools-72.1.0-py310haa95532_0\\\\Lib\\\\site-packages\\\\pkg_resources\\\\tests\\\\data\\\\my-test-package_unpacked-egg\\\\my_test_package-1.0-py3.7.egg\\\\EGG-INFO\\\\dependency_links.txt'")

I am using Windows, I recently recovered my computer and have since had this error. I have tried removing all conda related files and reinstalling aswell as redownloading various variants of roop

I am using Nvidia gpu

I have tried every version.

I'd appreciate any help possible.

**Comment by C0untFloyd** [comment]
Did you also try a shorter path? Because that is very likely the problem here.

**Comment by adaadaada23** [comment]
> Did you also try a shorter path? Because that is very likely the problem here.

you're the best i love u

**Comment by lulu3243** [comment]
can u explain @C0untFloyd i have the same error

**Comment by 12-blk** [comment]
i got similar issue, pls how can i solve this?
