### ISSUE TITLE
unused kwarg parameter

### ISSUE THREAD

**Issue by TanvirHafiz** [C0untFloyd/roop-unleashed#852]
Using provider ['CUDAExecutionProvider'] - Device:cuda
F:\roop-unleashed\ui\main.py:60: GradioUnusedKwargWarning: You have unused kwarg parameters in Blocks, please remove them: {'delete_cache': (60, 86400)}
  with gr.Blocks(title=f'{roop.metadata.name} {roop.metadata.version}', theme=roop.globals.CFG.selected_theme, css=mycss, delete_cache=(60, 86400)) as ui:
Traceback (most recent call last):
  File "F:\roop-unleashed\run.py", line 6, in <module>
    core.run()
  File "F:\roop-unleashed\roop\core.py", line 380, in run
    main.run()
  File "F:\roop-unleashed\ui\main.py", line 64, in run
    faceswap_tab()
  File "F:\roop-unleashed\ui\tabs\faceswap_tab.py", line 77, in faceswap_tab
    maskimage = gr.ImageEditor(label="Manual mask Image", sources=["clipboard"], transforms="", type="numpy",
AttributeError: module 'gradio' has no attribute 'ImageEditor'

and then it exits

**Comment by C0untFloyd** [comment]
When you're upgrading to newer versions of roop without using the installer, you need to update to the latest requirements too:
`pip install -r requirements.txt`
