### ISSUE TITLE
Target face not respected in Live Cam

### ISSUE THREAD

**Issue by frosty3907** [C0untFloyd/roop-unleashed#854]
**Describe the bug**
Target face is ignored while in Live Cam but works correctly while processing mp4.

**To Reproduce**
I created a test mp4 of myself, I then hold up a photo of someone else.
I set my face as the Target Face via Use Face from this Frame.
Under Specify face selection for swapping I choose Selected Face.
Processing this video works as expected (my face is swapped, the photo of someone else is not).

However, with the same settings if I then go into Live Cam and hold up the photo, it is also swapped to the Input face.

**Details**
What OS are you using?
Windows

Are you using a GPU?
NVIDIA

**Which version of roop unleashed are you using?**
4.1.1

**Comment by C0untFloyd** [comment]
Livecam swaps every detected face, this can't be changed currently.
