### ISSUE TITLE
In images and videos with multiple people, detected faces are not transferred to the gallery of selected target faces.

### ISSUE THREAD

**Issue by sandrojclic** [C0untFloyd/roop-unleashed#856]
**Describe the bug**
In images and videos with multiple people, detected faces are not transferred to the gallery of selected target faces. With just one person, it does work well.

https://github.com/user-attachments/assets/e2318c6d-b28a-47df-a02c-2c2ed346e18f

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
4 1 4
**Screenshots**

**Comment by C0untFloyd** [comment]
Did you notice the gallery of faces opening at the left bottom page? You need to select the faces you want to swap there.
See https://github.com/C0untFloyd/roop-unleashed/wiki/Face-Swap-Tab#face-selection-dialog

**Comment by sandrojclic** [comment]
You must check, below on the right, "Use selected face". Problem solved.
Thanks a lot.  Congratulations on such an excellent program.
