### ISSUE TITLE
Error when upload a video "cannot convert float NaN to integer"

### ISSUE THREAD

**Issue by CrisisDark** [C0untFloyd/roop-unleashed#858]
**Describe the bug**
In the powershell it appears that the error occurs on line 438, in the "faceswap_tab.py" script, the line says this: milliseconds = (secs - int(secs)) * 1000

The problem causes one to not be able to see any of the video from the interface, because it could never be configured correctly.

I am using Windows 10, I am using a Nvidia gpu
The version of Roop 4.1.4

For images it is working fine, only for videos I have been having problems.

I used miniconda3, and created a virtual environment with python 3.10.6, before this I had installed visual studio community 2022, including the C++ package, I also have cuda 11.8 installed.
Then in this virtual environment, I installed the requirements of this program through that text file "requirements.txt", as a last step, I installed ffmpeg within the environment using the following command, "conda install conda-forge::ffmpeg"

I don't have any clarity on how I could solve this, it is a complex program., please can someone help me, I was very excited, thank you guys.
![Error- cannot convert float](https://github.com/user-attachments/assets/3d95caac-3222-4bf5-ad72-d583e54d408d)

**Comment by C0untFloyd** [comment]
This sounds like a corrupted video or unknown codec because the fps of your video can't be detected. Did you try with different videos/codecs? Seeing that it's only 1 MB, is it possible to upload your video here?
