### ISSUE TITLE
Output File Size 2x to 3x when using post-processing or/and subsample upscale.

### ISSUE THREAD

**Issue by zynx202** [C0untFloyd/roop-unleashed#863]
I have noticed this issue where, when using post-processing or/and subsample upscale the output file size it dramatically increased for both images and videos, for videos one thing that I have noticed is that the bitrate of the output file is way more than the bitrate of the input file. Is there a way to have the output file's size be similar to the input size file?

For example -
Input Video Size = 85.9 MB (Total Bitrate = 6211 kbps)
Output Video Size = 251 MB (Total Bitrate = 18184 kbps)

Also I tested with the original roop's output vs roop unleased with no PP or subsample upscale output. The result is that roop unleashed output are generally more heavy than it's input for both Images and Videos.

**Comment by C0untFloyd** [comment]
Unlike the original roop this can all be adjusted in the settings tab:
![image](https://github.com/user-attachments/assets/81b7de2f-56aa-44b5-82bd-266677e86e48)

and

![image](https://github.com/user-attachments/assets/a1b90a6f-49ba-458b-95b9-d622b4cabba4)
