### ISSUE TITLE
Conda is not installed. Exiting...

### ISSUE THREAD

**Issue by MaxaAI** [C0untFloyd/roop-unleashed#867]
**Describe the bug**
I dowloaded roop unleashed like all the tutorials are telling but everytime i try to start it i just get this error
Launching roop unleashed
Conda is not installed. Exiting...

**To Reproduce**
just start the application

**Details**
What OS are you using?
- [x] Windows 

Are you using a GPU?
- [x] NVIDIA

**Which version of roop unleashed are you using?**
the one that is out right now

**Screenshots**
![image](https://github.com/user-attachments/assets/0088a189-d620-4a2e-9649-2092d446666b)

**Comment by MORELIFET1** [comment]
same does anyone know how to fix this

**Comment by RazwanGazi** [comment]
Same Happened to me

**Comment by n4ckz** [comment]
same for me :(

**Comment by Dcode1999** [comment]
Same for me.

**Comment by Jonalvesilva** [comment]
add the address of the folder where conda is installed to the path in system variables like this: D:\roop-unleashed\installer\installer_files\conda\Scripts

**Comment by Dcode1999** [comment]
@rem activate installer env
    call "%CONDA_ROOT_PREFIX%\condabin\conda.bat" activate "%INSTALL_ENV_DIR%" || ( echo. && echo ERROR: Miniconda hook not found. && goto end )



I was reviewing the .bat file, and I came across a particular line that's generating the mentioned error.

**Comment by sunnav** [comment]
### TRY THIS FIX: https://github.com/C0untFloyd/roop-unleashed/issues/1009#issuecomment-2544227796
