### ISSUE TITLE
How to fully Uninstall?

### ISSUE THREAD

**Issue by simplyexperimental** [C0untFloyd/roop-unleashed#871]
Tried to get this to work but the windows.bat file kept exiting after pressing enter.
The build tools turned out to to install more than 10GB of space and the requirements was installing another 10 I ran out of space!

I hadn't needed to go this deep with other tools like live portrait so I'm going to try another tool but now I can't seem to get the gigabytes I lost back.

I removed the C++ build tool but I'm still missing at least 5GB.
I tried the git rm which removed some files including the roop_unleashed but it did not uninstall the stuff that roop installed.
I'm thinking it must be wheels and cached content but I not very experienced to track them down could you assist?

*Update I used pip cache purge and I got my gigabytes back however I just want to confirm are there any other things that were installed that I should be aware of to remove?

**Comment by C0untFloyd** [comment]
Usually deleting the roop-unleashed folder and clearing the cache (what you did) should be enough.
