### ISSUE TITLE
No Cuda displayed in Settings - Provider

### ISSUE THREAD

**Issue by Cal-DCosta** [C0untFloyd/roop-unleashed#872]
**Describe the bug**

Cannot see a selection for cuda
These are shown in the UI at the top
python: 3.10.14 • torch: 2.4.0+cu118 • gradio: 4.38.1

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x] NVIDIA 4090
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
ver 4.1.4

**Screenshots**
If applicable, add screenshots to help explai
![no cuda](https://github.com/user-attachments/assets/52cb05fc-608b-4879-949a-56e5542dfa2c)
n your problem.

**Comment by lost-in-emotions** [comment]
Word. Maybe it could make a better speed in rendering

**Comment by C0untFloyd** [comment]
Did you install the cuda drivers from NVIDIA as described here -> https://github.com/C0untFloyd/roop-unleashed/wiki/Installation#installation

**Comment by fahadshery** [comment]
> You need to use the 11.8 version, not the latest 12.x btw.

is there a particular reason for it? I am using cuda 12.2 for everything else i.e. A1111, comfiUI, fluxgym etc. etc.

I wrote a new `Dockerfile` and `docker-compose.yaml` which is more secure and running as non-root and I was thinking to create a PR for as well...everything is working but `cuda` is not detected and I am getting:
```
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
```
The `gpu` is detected within the `docker` container as well with no issues whatsoever but roop can't detect it:
```
docker exec -it roop-unleashed /bin/bash
appuser@a28a1a19f106:/app$ nvidia-smi
Tue Sep 24 14:40:27 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.161.08             Driver Version: 535.161.08   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  GRID P40-24Q                   On  | 00000000:01:00.0 Off |                  N/A |
| N/A   N/A    P8              N/A /  N/A |  10838MiB / 24576MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+
```

any pointers?

**Comment by fahadshery** [comment]
I also upgraded the `gradio`, `fastapi` etc. and everything is working as expected except for `cuda` not detected.

**Comment by fahadshery** [comment]
After upgraded packages, here is the screenshot:
<img width="1219" alt="image" src="https://github.com/user-attachments/assets/0ecfd59e-c037-4d65-a56f-4cc014a671c0">

Notice the package versions at the top

**Comment by C0untFloyd** [comment]
Did you install this yourself without using the requirements?

Because
> Notice the package versions at the top

You obviously installed cuda 12.1 and the requirements need cuda 11.8 
torchvision==0.16.2+cu118;

Just re-read your entry and it's very likely a docker-specific problem. There's a whole lengthy discussion here, how to passthrough your gpu and drivers -> https://github.com/C0untFloyd/roop-unleashed/discussions/626
