### ISSUE TITLE
this error shows up when using roop unleashed for face swap.

### ISSUE THREAD

**Issue by BaZeeGiii** [C0untFloyd/roop-unleashed#874]
cv2.error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\arithm.cpp:674: error: (-5:Bad argument) When the input arrays in add/subtract/multiply/divide functions have different types, the output array type must be explicitly specified in function 'cv::arithm_op'
![Screenshot 2024-09-03 014302](https://github.com/user-attachments/assets/f12d5e5d-945d-498b-8fba-3c1e4295a0dd)

**Comment by C0untFloyd** [comment]
Update to the latest version -> #800
