### ISSUE TITLE
error when launching

### ISSUE THREAD

**Issue by dangotnohope** [C0untFloyd/roop-unleashed#879]
#**Describe the bug**
![image](https://github.com/user-attachments/assets/11f35a82-2884-4491-a1e7-bfc2624780d3)
![Screenshot 2024-09-04 095929](https://github.com/user-attachments/assets/ac191682-1962-4d71-baac-37d0401a51bc)

**To Reproduce**
Steps t
**Details**
What OS are you using?
- [ ] Windows 

Are you using a GPU?

- [ ] AMD

**Which version of roop unleashed are you using?**
Latest

**Screenshots**

**Comment by C0untFloyd** [comment]
It looks like either you or one of the platforms had internet problems while downloading. You could try again or download the necessary models manually from this release https://github.com/C0untFloyd/roop-unleashed/releases/tag/v3.9.0
