### ISSUE TITLE
Doesn't support AMD graphics card

### ISSUE THREAD

**Issue by RanaKhan42** [C0untFloyd/roop-unleashed#881]
**Describe the bug**

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [x] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**

**Screenshots**

**Comment by RanaKhan42** [comment]
It doesn't support AMD graphics card

**Comment by RanaKhan42** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Details** What OS are you using?
> 
> * [ ]  Linux
> * [ ]  Linux in WSL
> * [x]  Windows
> * [ ]  Mac
> 
> Are you using a GPU?
> 
> * [ ]  No. CPU FTW
> * [ ]  NVIDIA
> * [x]  AMD
> * [ ]  Intel
> * [ ]  Mac
> 
> **Which version of roop unleashed are you using?**
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.

**Comment by C0untFloyd** [comment]
https://github.com/C0untFloyd/roop-unleashed/wiki/Installation#windows-1-click-installer
https://github.com/C0untFloyd/roop-unleashed/issues/186#issuecomment-1704348275
