### ISSUE TITLE
"connection errored out"

### ISSUE THREAD

**Issue by valmontez** [C0untFloyd/roop-unleashed#888]
**Describe the bug**

Hello, I'm using translation to write this message.

I installed Roop Unleashed last week, and everything was working fine. In the meantime, I formatted my PC. Now, when I follow the steps from this video: https://www.youtube.com/watch?v=0p-mCnhTDNA (the same one I used the first time), I get this error message when I click on DML in the settings. At first, everything seems normal, but I get this error message as soon as I try to change a value in the settings or in the interface. Anyway, thank you for creating this very cool software, I'm having a lot of fun with my family. ^^

P.S.: I'm not a programmer, just a casual tinkerer. Thank you in advance for any help you can provide!

GC : 7900 xtx
CPU : intel 13700 kf
RAM : 32 g DDR 5 7200 mhz

A pretty cool setup for this kind of stuff i think ^^

**To Reproduce**

run the "run.bat"

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [x] AMD
- [ ] Intel
- [ ] Mac

roop unleashed 4.2.1

![bug](https://github.com/user-attachments/assets/7d8e8e8a-0359-4f62-b326-d4ddcb883cfc)
![errored](https://github.com/user-attachments/assets/8f66fb46-0c4c-43df-be7b-22ac74bb0f22)

**Comment by Salimander9** [comment]
I am having the same issue^^^

**Comment by Majd00shka** [comment]
same here after the last version

**Comment by Marv761125** [comment]
Same here (using Colab). Faceset import leads to a "connection errored out". Same error when you try to import single face pictures in the face manager.

**Comment by AlPacino06** [comment]
Salut, j'ai le même problème sur colab des solutions trouvés ? PS: je suis non itinié donc explication simple serait cool haha merci !

**Comment by valmontez** [comment]
Well... I'm happy (or not 😉) to see that I'm not the only one in this situation. Today, I thought I'd try something different. I reformatted my computer to start everything from scratch. I'm going to try two things: updating PowerShell first after installing all the drivers, and trying an older version of Roop. Which version worked for you? I forgot which version I was using initially. Right now, I'm playing taxi for my wife, so I'll get back to you for your feedback. And long live mutual support! 😘
Salut a toi l'autre français 😉

**Comment by C0untFloyd** [comment]
Same Error here but not on every machine 😄 
It's for certain another bug introduced by the latest gradio version, this seems to be the same issue:
https://github.com/gradio-app/gradio/issues/9264

I tried going back to the previous 4.38.1 but I believe it is caused by a library dependency, perhaps again fastapi like the pydantic issue. You see, gradio doesn't seem to specify a version number for its dependencies and therefore going back leaves the new (faulty?) libraries running. Also even installing the old 4.38.1 will install the newer versions of fastapi. This is extremely difficult for testing!

@valmontez I believe you only need to delete your venv and it's definitely not a roop issue. You could try replacing the gradio version 4.42.0 in the requirements with 4.29.0 which I used 4 months ago and where I'm sure it was running perfectly

**Comment by valmontez** [comment]
> Same Error here but not on every machine 😄 It's for certain another bug introduced by the latest gradio version, this seems to be the same issue: [gradio-app/gradio#9264](https://github.com/gradio-app/gradio/issues/9264)
> 
> I tried going back to the previous 4.38.1 but I believe it is caused by a library dependency, perhaps again fastapi like the pydantic issue. You see, gradio doesn't seem to specify a version number for its dependencies and therefore going back leaves the new (faulty?) libraries running. Also even installing the old 4.38.1 will install the newer versions of fastapi. This is extremely difficult for testing!
> 
> @valmontez I believe you only need to delete your venv and it's definitely not a roop issue. You could try replacing the gradio version 4.42.0 in the requirements with 4.29.0 which I used 4 months ago and where I'm sure it was running perfectly

I just got home, I'm going to take care of my kids for a bit, and I'll get back to you to let you know if anything has changed.

**Comment by valmontez** [comment]
everything working for me now. i did something else. ty 4 your help dude ! ;-)

**Comment by guatsapore** [comment]
> everything working for me now. i did something else. ty 4 your help dude ! ;-)

how u fixed it?

**Comment by C0untFloyd** [comment]
It's possibly fixed by the latest update https://github.com/C0untFloyd/roop-unleashed/releases/tag/4.2.3

**Comment by valmontez** [comment]
> It's possibly fixed by the latest update https://github.com/C0untFloyd/roop-unleashed/releases/tag/4.2.3

rhoooooooo ............. interesting ! :-)
 i'll check that !
 Thank you C0untFloyd !

**Comment by valmontez** [comment]
Uh... Guys, I'm a little embarrassed... I think what solved my problem was an update through the Windows Store... I didn’t change ANYTHING in the installation (at least not consciously). So, I encourage you all to update everything on your PC. I didn’t need to edit the "requirements" file to fix my issue. If necessary, I’m willing to reinstall everything to try and figure out where the problem lies! Have a great evening, everyone!

**Comment by C0untFloyd** [comment]
I still get that error with my latest version and gradio 4.43 on slower machines with less VRAM. But if you refresh your browser after this error, everything will work without this error happening again. Weird, but definitely something caused by gradio.

**Comment by dxdate** [comment]
@C0untFloyd 
doesn't work for me. I get exactly the same error(

how to fix it?

**Comment by C0untFloyd** [comment]
The pydantic error or the connection error?

**Comment by dxdate** [comment]
I did a clean install of the latest version.
Oh, I've now run a check for updates and everything is working

**Comment by chrisma2012** [comment]
> It's possibly fixed by the latest update https://github.com/C0untFloyd/roop-unleashed/releases/tag/4.2.3

It did worked for me. 👏
