### ISSUE TITLE
an illegal memory access was encountered

### ISSUE THREAD

**Issue by Majd00shka** [C0untFloyd/roop-unleashed#889]
I'm getting an error in Face Swap
everything was working fine last week but 3 days ago, I start getting this error.

 [E:onnxruntime:Default, cuda_call.cc:116 onnxruntime::CudaCall] CUDA failure 700: an illegal memory access was encountered ; GPU=0 ; hostname=****** ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\gpu_data_transfer.cc ; line=73 ; expr=cudaMemcpyAsync(dst_data, src_data, bytes, cudaMemcpyDeviceToHost, static_cast<cudaStream_t>(stream.GetHandle()));

for photos, I got this error if I use the 512px with high res pictures.
for videos, I got this error always if I use the 512px. with 256px, it works only with small size video.

I tried using 2, 3 and 4 cors, the same error always. everything else kept at default.

CPU 5900x
GPU 4070ti super
RAM 64GB 3600MHz

**Comment by Majd00shka** [comment]
I installed the latest version and now I'm having another issue

**Comment by C0untFloyd** [comment]
Faulty VRAM? Did you do a stress test already?

**Comment by Majd00shka** [comment]
The card is fine. I'm gaming on it and already did couple of benchmarks.

I used furmark last week and everything was good.

**Comment by Majd00shka** [comment]
I just tested the VRAM using memtest_vulkan and passed with no error

**Comment by C0untFloyd** [comment]
Did you check your cpu memory too? Because upscaling doesn't even use the gpu at all.
No idea then, it's a problem specific to you.

**Comment by C0untFloyd** [comment]
There's no tensorflow in this app, upscaling uses numpy on cpu and the error happens deep inside the cuda onnxruntime. It also states "cudaMemcpyAsync(dst_data, src_data, bytes, cudaMemcpyDeviceToHost, static_cast<cudaStream_t>(stream.GetHandle()));"
This seems to be code in the dll which copies data from the gpu over to the standard (host) cpu memory. If there was a general problem more people would complain I guess. If it were a threading problem, it wouldn't happen with just 1 image (1 thread per image). So I'm still convinced this is sort of a hardware/driver issue. Of course I may be wrong but I currently have no explanation for this.

**Comment by Majd00shka** [comment]
Okay I think I know what was the issue. I was overclocking the VRAM.

Clocked down to default speed and works now
