### ISSUE TITLE
No longer able to scroll down if more than 8 faces uploaded.

### ISSUE THREAD

**Issue by adaadaada23** [C0untFloyd/roop-unleashed#894]
No longer able to scroll down if more than 8 faces uploaded.

**Comment by Askanio70** [comment]
Confirmed

**Comment by C0untFloyd** [comment]
https://github.com/C0untFloyd/roop-unleashed/commit/787d976c0d869dcccf5f2afe169a1a3bdf73b503

Should be just a horizontal scrollbar now.
