### ISSUE TITLE
Preview ONLY the first frame... ?

### ISSUE THREAD

**Issue by AlonDan** [C0untFloyd/roop-unleashed#9]
**Describe the bug**
On a fresh launch of Roop Unleashed, Loading Source + Target 
Preview will show the FIRST FRAME but once SCROLLING the face on the preview will change to the original Target.

To temporary "HACK" this you need to select "**Multi Faces**" then Scroll, (even if it's only once face) and then the NEXT target video you will load will be fine while scrolling the Preview.
I'm not a programmer but I guess the Multi Faces - probably REFRESHING the problem so the next load works fine, until you'll re-launch ROOP...

Basically, the FIRST loaded target video doesn't update more than the first frame on the preview.

**To Reproduce**
1. Load Source face image and Target Video
2. Click on PREVIEW
3. Scroll to any other frame in the timeline
4. you will notice the face changed back to the Target

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by C0untFloyd** [comment]
This is fixed in the latest 2.0.0 update

**Comment by AlonDan** [comment]
> This is fixed in the latest 2.0.0 update

I just tested it on the latest version, it works nice on 10% 20% of the video, already better than ONLY the first frame for sure, but then it gets back to the source when I keep scroll ahead in the preview... again I "HACK" it by enable Many Faces... but it's not the best solution if I actually have more than one face and I want a specific one only.

Sadly, I believe it's not yet 100% solved
