### ISSUE TITLE
Roop cam  error 

### ISSUE THREAD

**Issue by mndhfhfjkgnkf** [C0untFloyd/roop-unleashed#900]
**Describe the bug**
[ WARN:0@25.322] global cap_msmf.cpp:1759 CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -2147483638

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows  YES
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x] NVIDIA : I am using NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**

**Screenshots**

**Comment by C0untFloyd** [comment]
Very likely one of these problems:

- your webcam is locked by another app
- your webcam can't use the selected resolution
- something wrong with your webcam drivers

Either way, it's probably an issue with your webcam, not the app.

**Comment by Userbarry73** [comment]
Please I need help with the error i get when i run my roop-cam with start_portable_nvidia.

usage: run.py [-h] [-s SOURCE_PATH] [-t TARGET_PATH] [-o OUTPUT_PATH]
              [--frame-processor FRAME_PROCESSOR [FRAME_PROCESSOR ...]] [--keep-fps] [--keep-audio] [--keep-frames]
              [--many-faces] [--video-encoder {libx264,libx265,libvpx-vp9}] [--video-quality [0-51]]
              [--max-memory MAX_MEMORY] [--execution-provider {dml,cpu} [{dml,cpu} ...]]
              [--execution-threads EXECUTION_THREADS] [-v]
run.py: error: argument --execution-provider: invalid choice: 'cuda' (choose from 'dml', 'cpu')
Press any key to continue . . .
