### ISSUE TITLE
Math Domain Error

### ISSUE THREAD

**Issue by muemar79** [C0untFloyd/roop-unleashed#903]
With the latest update, brand new installation, I always get the error math domain error after loading it in the target tab. I always split my videos with DaVinci Resolve Version 19.0.1. I updates from version 4.1.0 and I never got this problem before, even with bigger files. I do not know, what has changed. I tried different codec variations. Format QuickTime or mp4, different codec h264 or h265. 

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [X ] NVIDIA
- [ ] AMD
- [X ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
Version 4.2.6

**Screenshots**

![Screenshot (129)](https://github.com/user-attachments/assets/e76dfae2-bf62-4ac6-b838-c52800777ea0)

**Comment by spaceymonk** [comment]
It caused by the missing video flags. You can fix it by updating the input video:

```bash
ffmpeg -i input.mp4 -movflags faststart -acodec copy -vcodec copy output.mp4
```

**Comment by muemar79** [comment]
Thx, that seems to work so far. But I wonder why I have to do this now although in the past everything worked without it. Strange. But if it helps I have to make this step before I start with the video.

**Comment by spaceymonk** [comment]
Perhaps this step can be implemented into the `ffmpeg` layer of the application. Because that command completes in milliseconds (just writing some headers for the video).

**Comment by C0untFloyd** [comment]
To clarify, this is after face swapping and creating a new video or is this inside the preview control? The error itself happens inside the UI framework unfurtunately.

**Comment by spaceymonk** [comment]
It occurs as soon as you select a target video.

> To clarify, this is after face swapping and creating a new video or is this inside the preview control? The error itself happens inside the UI framework unfurtunately.

**Comment by muemar79** [comment]
I have tested a little bit. As I told, I am using DaVinci Resolve for splitting big videos in little parts. After face swapping them I put them back together. With older versions of DaVinci Resolve I got sometime this problem with Math Domain Error while loading it in the target video field. Normally I change the video format to mov and then it worked. Now, with the new Version 19 I had it all the time with *.mov,  *.mp4, h264 or h265 codecs. With updating the video parts with the above ffmpeg command it worked.

So looking into DaVinci Resolve I mentioned an option called "Network Optimization"  . Never recognized it before. I googled it and it seems with this option activated, DaVinci Resolve makes the output video file more compatible for Browsers or YouTube cause it put the video header direct in front of the file. I have created a few files so far with this option on and I think this solve the problem with the Math Domain Error. I think with this option in DaVince Resolve makes a similar entry in the files like the ffmpeg command above. 
So after that I think not really an bug of roop unleashed itself.

**Comment by spaceymonk** [comment]
Well, in that case, perhaps a notification or a descripitive error message (if it can be caught) can be displayed when user selects a video that is not compatible.

**Comment by C0untFloyd** [comment]
Can you perhaps provide a tiny short videoclip here with that error? I think I can circumvent the error by using direct show on windows but I need a video to test this (and I don't have DaVinci). You can attach the video to a post here. TIA!

**Comment by muemar79** [comment]
Mmmh, difficult. I made 3 clips, two smaller ones ( 60MB and 266MB in 720p) which works, than I made a longer one with 1,6 GB (1080p). With the bigger one I got the message but I don't think, I should upload 1,6GB ;-) All three files are in mp4 format with h264 codec. I will test a little further, whether the problem appears until the clips reach a certain size. Maybe it is a size limit problem,

**Comment by spaceymonk** [comment]
> Maybe it is a size limit problem.

I doubt it. In my case the problem happened in very short videos (small in size as well).

> ... "Network Optimization" . Never recognized it before. I googled it and it seems with this option activated, DaVinci Resolve makes the output video file more compatible for Browsers or YouTube cause it put the video header direct in front of the file. 

Like you said earlier, the problem arises due to placing metadata at a different location. Perhaps the library or the browser is looking for that specific place.

**Comment by C0untFloyd** [comment]
As spaceymonk said, it has to do with the moov atom position (metadata which describes video properties) and not size. I was thinking you could easily reproduce this with some random short video (using the network optimize option you wrote about).
Well, if not I'll implement this as it seems to be windows exclusive:
https://answers.opencv.org/question/234933/opencv-440modulesvideoiosrccap_msmfcpp-682-cvcapture_msmfinitstream-failed-to-set-mediatype-stream-0-640x480-30-mfvideoformat_rgb24unsupported-media/

**Comment by spaceymonk** [comment]
Nope, I got this error when I was using Firefox on Debian. It is solely related to certain video files. I suggest, at the least, displaying an info box related to this issue ~if the user gets atom position error~.

**Comment by C0untFloyd** [comment]
> Nope, I got this error when I was using Firefox on Debian. It is solely related to certain video files.

The reason is a corrupted videofile, missing the important header data. Your ffmpeg cmd above forces it to be written at the start of the file, which is a lot safer than at the end where the file can have stream errors. Of course the error has nothing to do with windows but also nothing with firefox or any browser. The link above states that this can be worked around using direct show for opening videos. I think it might help @muemar79  and others on windows but without an example to test I can't promise an improvement. Everybody else needs to repair their broken videos. As I said, this happens deep inside the UI framework where I have no means to catch or fix it.

**Comment by C0untFloyd** [comment]
I could reproduce that error by corrupting GIFs. The "fix" I found in the internet doesn't help though. Good news though, I am able to catch it and will display a warning then. This is included in the new release https://github.com/C0untFloyd/roop-unleashed/releases/tag/4.2.8
