### ISSUE TITLE
run.py: error: unrecognized arguments: --execution-provider cuda --frame-processor face_swapper face_enhancer

### ISSUE THREAD

**Issue by SrGrafoasspee** [C0untFloyd/roop-unleashed#905]
Ever since I updated to **v4.2.3** the app won't launch
I get these errors:
>usage: run.py [-h] [--server_share] [--cuda_device_id CUDA_DEVICE_ID]
>run.py: error: unrecognized arguments: --execution-provider cuda --frame-processor face_swapper face_enhancer

>Done!
>Press any key to continue . . .

**Details**
What OS are you using?
Windows

Are you using a GPU?
NVIDIA

**Which version of roop unleashed are you using?**
v4.2.3

**Comment by C0untFloyd** [comment]
From the main page:
![img](https://github.com/user-attachments/assets/c8750298-b3d4-4e64-bf01-62eaec42e9fb)

Remove the unnecessary arguments from your call, they weren't used in this fork for over a year anyway...
