### ISSUE TITLE
Changing fps doesn't change which frames are processed with in-memory processing mode

### ISSUE THREAD

**Issue by Jonseed** [C0untFloyd/roop-unleashed#908]
**Describe the bug**
I have input a video that is 30 fps, but when I change the fps from default (0) to 15 in the UI, it still processes all the frames when using in-memory processing. Shouldn't it process just every other frame, or is that not possible with "in-memory processing" mode (it works as expected in "extract frames" mode, cutting the number of frames processed in half)? The terminal shows it is creating a video of 15 fps, but what it does is make a video of the same length but just plays it at half speed, so it looks like it is slow motion. 

**Details**
What OS are you using?
Windows

Are you using a GPU?
Nvidia

**Which version of roop unleashed are you using?**
4.2.8

**Comment by C0untFloyd** [comment]
Well, you found a use case I didn't even think of 😃 
The fps input is originally for overriding wrongly detected fps values. I had this a lot with gif animations, where the detected fps were a lot faster than perceived. What you're trying to do is a step into the video-editing area, where I would have to smooth between frames and stuff like that. I think I'll leave that up to the specialized tools out there.
