### ISSUE TITLE
Stuttering

### ISSUE THREAD

**Issue by RoopUser** [C0untFloyd/roop-unleashed#910]
**Describe the bug**
Using 4.2.6 and not having changed anything I am getting stuttering on the output videos.
I am using h264_nvenc, but unsure if it has any impacts.

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

![image](https://github.com/user-attachments/assets/c53fc5ef-588f-4e97-bc14-fdb0f55bea33)

**Comment by RoopUser** [comment]
This happens when outputting to libx264, as well.

**Comment by Bigboooy21** [comment]
Dont know if this is related, but for me it happens when I use the "Use last frame" option when no face is detected. When I use "retry rotated" its fine.

**Comment by RoopUser** [comment]
That must be it! I just noticed it happening too since the release (when I started using the option). Will confirm...

**Comment by C0untFloyd** [comment]
Most likely that option. This inserts the previous frame if no face was detected. This prevents face flickering but introduces noticeable stuttering if there is no face for a longer time. I think the number of frames to re-use the old should be exposed to the user (currently 15 if I'm not mistaken).
