### ISSUE TITLE
cannot import name 'preserve_channel_dim' from 'albucore.utils' when executing sh runMacOS.sh

### ISSUE THREAD

**Issue by dlmarston** [C0untFloyd/roop-unleashed#915]
**Describe the bug**
Error message: ImportError: cannot import name 'preserve_channel_dim' from 'albucore.utils' (/Users/dave/roop-unleashed/.venv/lib/python3.11/site-packages/albucore/utils.py)
after running sh runMacOS.sh

**To Reproduce**
after running : /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/PJF16/roop-unleashed/master/installer/macOSinstaller.sh)
side note - this requires a " added to the end of the line
then running sh runMacOS.sh

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [X] Mac

Are you using a GPU?
- [] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [X] Mac

**Which version of roop unleashed are you using?**
4.28

**Screenshots**

**Comment by dlmarston** [comment]
Running the run.py script...
Traceback (most recent call last):
  File "/Users/dave/roop-unleashed/run.py", line 3, in <module>
    from roop import core
  File "/Users/dave/roop-unleashed/roop/core.py", line 25, in <module>
    import ui.main as main
  File "/Users/dave/roop-unleashed/ui/main.py", line 9, in <module>
    from ui.tabs.faceswap_tab import faceswap_tab
  File "/Users/dave/roop-unleashed/ui/tabs/faceswap_tab.py", line 8, in <module>
    from roop.face_util import extract_face_images, create_blank_image
  File "/Users/dave/roop-unleashed/roop/face_util.py", line 3, in <module>
    import insightface
  File "/Users/dave/roop-unleashed/.venv/lib/python3.11/site-packages/insightface/__init__.py", line 18, in <module>
    from . import app
  File "/Users/dave/roop-unleashed/.venv/lib/python3.11/site-packages/insightface/app/__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "/Users/dave/roop-unleashed/.venv/lib/python3.11/site-packages/insightface/app/mask_renderer.py", line 4, in <module>
    import albumentations as A
  File "/Users/dave/roop-unleashed/.venv/lib/python3.11/site-packages/albumentations/__init__.py", line 6, in <module>
    from .augmentations import *
  File "/Users/dave/roop-unleashed/.venv/lib/python3.11/site-packages/albumentations/augmentations/__init__.py", line 1, in <module>
    from .blur.functional import *
  File "/Users/dave/roop-unleashed/.venv/lib/python3.11/site-packages/albumentations/augmentations/blur/__init__.py", line 1, in <module>
    from .functional import *
  File "/Users/dave/roop-unleashed/.venv/lib/python3.11/site-packages/albumentations/augmentations/blur/functional.py", line 9, in <module>
    from albucore.utils import clipped, maybe_process_in_chunks, preserve_channel_dim
ImportError: cannot import name 'preserve_channel_dim' from 'albucore.utils' (/Users/dave/roop-unleashed/.venv/lib/python3.11/site-packages/albucore/utils.py)
Deactivating the virtual environment...

**Comment by dlmarston** [comment]
related?

https://www.reddit.com/r/comfyui/comments/1flnwmt/reactor_node_seems_to_be_broken_fix_inside/

**Comment by dlmarston** [comment]
added albucore==0.0.16 to requirements.txt and it seems to get past the error

**Comment by sumansid** [comment]
> added albucore==0.0.16 to requirements.txt and it seems to get past the error

@dlmarston Hmm, installing to 0.0.16 didn't fix for me :(

**Comment by Kingkladzemcr** [comment]
Having same issue on paperspace 
Running ok on colab pro though

**Comment by samedii** [comment]
Downgrading also worked for me.

albucore = "^0.0.16"

**Comment by Matiasfx** [comment]
> added albucore==0.0.16 to requirements.txt and it seems to get past the error

Can somebody explain step by step how to do this? thnx

**Comment by poepoeng** [comment]
Im ask CGPT to fix this error downgrade albumentations , i think its because insight or albumentations update :
pip install albumentations==1.1.0
its work for me

**Comment by siikdUde** [comment]
> > added albucore==0.0.16 to requirements.txt and it seems to get past the error
> 
> Can somebody explain step by step how to do this? thnx

![roop help 1](https://github.com/user-attachments/assets/411ed984-fcd1-4d56-9ea2-59677a209b29)
![roop help 2](https://github.com/user-attachments/assets/1fc6d86f-b57d-4b1a-b1ed-f33fd664a38b)

**Comment by Matiasfx** [comment]
> > > added albucore==0.0.16 to requirements.txt and it seems to get past the error
> > 
> > 
> > Can somebody explain step by step how to do this? thnx
> 
> ![roop help 1](https://private-user-images.githubusercontent.com/10148714/369645736-411ed984-fcd1-4d56-9ea2-59677a209b29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NTg1NjgsIm5iZiI6MTcyNjk1ODI2OCwicGF0aCI6Ii8xMDE0ODcxNC8zNjk2NDU3MzYtNDExZWQ5ODQtZmNkMS00ZDU2LTllYTItNTk2NzdhMjA5YjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDIyMzc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4NDljMjZjYzlhODBmNGRjMGY3OWE1NjQ4ZGMwNDhmMWNlMWZjMGIwMmQ2NzZkYTEzYTE1MmJlMjhkZmEyNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7CL6A9sdSLqHCnAvGS0BLM4MPvbT2cs23KlrvbkVgzo) ![roop help 2](https://private-user-images.githubusercontent.com/10148714/369645737-1fc6d86f-b57d-4b1a-b1ed-f33fd664a38b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NTg1NjgsIm5iZiI6MTcyNjk1ODI2OCwicGF0aCI6Ii8xMDE0ODcxNC8zNjk2NDU3MzctMWZjNmQ4NmYtYjU3ZC00YjFhLWIxZWQtZjMzZmQ2NjRhMzhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDIyMzc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzM2UzMDJmMDczNGU3MTBlNmMwNTNlZjRmYTM2OGIxY2Q0NTE3NmUyMjRjMTAwYjYyNTc3ZTE0YTc3MGM5NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ihMubevYsQ_MEkQ6BY8V0VtWMJhksirI3zo2TUwt5zI)

I tried and it didnt work. I'm new to all this. Do I change the txt and save and thats it, then just open the installer or do I have to run a comand? I tried both. Went to powershell and run the pip install -r requirements.txt but then when I tried the installer it was still in error. Thanks.

**Comment by Divitjal** [comment]
> > > added albucore==0.0.16 to requirements.txt and it seems to get past the error
> > 
> > 
> > Can somebody explain step by step how to do this? thnx
> 
> ![roop help 1](https://private-user-images.githubusercontent.com/10148714/369645736-411ed984-fcd1-4d56-9ea2-59677a209b29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NjE1ODYsIm5iZiI6MTcyNjk2MTI4NiwicGF0aCI6Ii8xMDE0ODcxNC8zNjk2NDU3MzYtNDExZWQ5ODQtZmNkMS00ZDU2LTllYTItNTk2NzdhMjA5YjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDIzMjgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhZDg2NTdlNTJmNDQ5NTdjM2QzYTM4NGUzNGJkZjVlNTJiZjIwMTQ3MzY5MjIzMDUyMzQ5MjkzMzRkMmRiMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7zKiIDKbdazfjBJzpX_a6iCU31lHouBNvWfeAaeDWzI) ![roop help 2](https://private-user-images.githubusercontent.com/10148714/369645737-1fc6d86f-b57d-4b1a-b1ed-f33fd664a38b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NjE1ODYsIm5iZiI6MTcyNjk2MTI4NiwicGF0aCI6Ii8xMDE0ODcxNC8zNjk2NDU3MzctMWZjNmQ4NmYtYjU3ZC00YjFhLWIxZWQtZjMzZmQ2NjRhMzhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDIzMjgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ODRmNjc3NDc5ZmY0MDdlNjBlZTRjNjE5Mzk5MzNjMDQ0MDc3NTZiMGJkNjk1MDY3M2VmNTkxODVjNDk5MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FPUsucTHw0GlKs34cFgldUneuYmHANTJzMHKro1Ot2M)

didnt work it is for mac or windows?

**Comment by Divitjal** [comment]
> added albucore==0.0.16 to requirements.txt and it seems to get past the error

do u have to reinstall after doing this?

**Comment by abhishekdev-beelogical** [comment]
> Im ask CGPT to fix this error downgrade albumentations , i think its because insight or albumentations update : pip install albumentations==1.1.0 its work for me

This did not work for me. Can you please provide step-by-step instructions?

**Comment by C0untFloyd** [comment]
It seems to be not limited to Mac but a general problem with the latest version of it. Googling it, also Comfy and some others seem to have the same problem. I downgraded the requirements to the last known working version.
Please everybody who has this problem, update your installation or do this automatically using the respective installer and tell me if it's working now.

**Comment by Matiasfx** [comment]
> It seems to be not limited to Mac but a general problem with the latest version of the albucore package. Googling it, also Comfy and some others seem to have the same problem. I downgraded the requirements to the last known working version. Please everybody who has this problem, update your installation or do this automatically using the respective installer and tell me if it's working now.

that fixed it. thnx

**Comment by VanHellsyng-23** [comment]
It works for me! Thaks dude :)

**Comment by C0untFloyd** [comment]
Nice. Closing this issue for good.
