### ISSUE TITLE
ImportError: cannot import name 'preserve_channel_dim' from 'albucore.utils' (D:\Download\roop-unleashed\installer_files\env\lib\site-packages\albucore\utils.py) with windows_run.bat

### ISSUE THREAD

**Issue by YashaRektr** [C0untFloyd/roop-unleashed#916]
**Describe the bug**
ImportError: cannot import name 'preserve_channel_dim' from 'albucore.utils' (D:\Download\roop-unleashed\installer_files\env\lib\site-packages\albucore\utils.py) wihen running with windows_run.bat

**To Reproduce**
1. Go to 'roop-unleashed'
2. Click on 'windows_run.bat'

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [1] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [1] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
4.2.8

**Screenshots**
![image](https://github.com/user-attachments/assets/fc692216-18d6-4116-9657-6f38dd92e467)

**Comment by Matiasfx** [comment]
I have the same problem.

**Comment by GooseBBB** [comment]
same

**Comment by SveSop** [comment]
Right.. so its not only me 😄

**Comment by zappityzap** [comment]
https://github.com/albumentations-team/albumentations/issues/1945

workaround: `pip install albucore==0.0.16`

**Comment by Divitjal** [comment]
> [albumentations-team/albumentations#1945](https://github.com/albumentations-team/albumentations/issues/1945)
> 
> workaround: `pip install albucore==0.0.16`

what if u have downloaded from one click installer what to do then?

**Comment by zappityzap** [comment]
> > [albumentations-team/albumentations#1945](https://github.com/albumentations-team/albumentations/issues/1945)
> > workaround: `pip install albucore==0.0.16`
> 
> what if u have downloaded from one click installer what to do then?

try this: https://github.com/C0untFloyd/roop-unleashed/issues/915#issuecomment-2365305997

**Comment by YashaRektr** [comment]
> [albumentations-team/albumentations#1945](https://github.com/albumentations-team/albumentations/issues/1945)
> 
> workaround: `pip install albucore==0.0.16`

sorrry, i already did that, manually install albucore 0.0.16 and the requirements.txt doesnt work

**Comment by Divitjal** [comment]
> > [albumentations-team/albumentations#1945](https://github.com/albumentations-team/albumentations/issues/1945)
> > workaround: `pip install albucore==0.0.16`
> 
> sorrry, i already did that, manually install albucore 0.0.16 and the requirements.txt doesnt work

yeah same I dont know what to do honestly

**Comment by SveSop** [comment]
Interestingly enough it seemed to work with this pip install...

Now, this was in no way really "self explanatory" for those that use this for the first time on windows, as its no "just open cmd and type pip install".

Following the `windows_run.bat` file, i figured out if i entered (this would be different depending on where you installed it tho) `c:\roop-unleashed\installer_files\conda` ran `_conda create --no-shortcuts -y -k --prefix "c:\roop-unleashed\installer_files\env" python=3.10`

Then i did `pip install albucore==0.0.16`. Then i did `conda deactivate`

Upon running the installer and answering Y to check for updates, it seemed to download a bit more files than previously, and actually start. Hopefully this could help someone getting this to work 😄 

PS. Just updating the `requirements.txt` file will ofc not work when you check for updates, as GIT will just overwrite this with the one from the repo...

**Comment by YashaRektr** [comment]
> Interestingly enough it seemed to work with this pip install...
> 
> Now, this was in no way really "self explanatory" for those that use this for the first time on windows, as its no "just open cmd and type pip install".
> 
> Following the `windows_run.bat` file, i figured out if i entered (this would be different depending on where you installed it tho) `c:\roop-unleashed\installer_files\conda` ran `_conda create --no-shortcuts -y -k --prefix "c:\roop-unleashed\installer_files\env" python=3.10`
> 
> Then i did `pip install albucore==0.0.16`. Then i did `conda deactivate`
> 
> Upon running the installer and answering Y to check for updates, it seemed to download a bit more files than previously, and actually start. Hopefully this could help someone getting this to work 😄
> 
> PS. Just updating the `requirements.txt` file will ofc not work when you check for updates, as GIT will just overwrite this with the one from the repo...

Thanks this is valuable, it seems work and launched RoopUl, but now ffmpeg not detected and it keeps downloading ffmpeg file everytime i run the windows_bat.
should i make new issues?

**Comment by Matiasfx** [comment]
> Interestingly enough it seemed to work with this pip install...
> 
> Now, this was in no way really "self explanatory" for those that use this for the first time on windows, as its no "just open cmd and type pip install".
> 
> Following the `windows_run.bat` file, i figured out if i entered (this would be different depending on where you installed it tho) `c:\roop-unleashed\installer_files\conda` ran `_conda create --no-shortcuts -y -k --prefix "c:\roop-unleashed\installer_files\env" python=3.10`
> 
> Then i did `pip install albucore==0.0.16`. Then i did `conda deactivate`
> 
> Upon running the installer and answering Y to check for updates, it seemed to download a bit more files than previously, and actually start. Hopefully this could help someone getting this to work 😄
> 
> PS. Just updating the `requirements.txt` file will ofc not work when you check for updates, as GIT will just overwrite this with the one from the repo...

I opened cmd and did all that just fine including  `pip install albucore==0.0.16`. but then when I type the comand `conda deactivate` nothing happens. Could you elaborate further or if Im missing something?

thanks

**Comment by SveSop** [comment]
> I opened cmd and did all that just fine including `pip install albucore==0.0.16`. but then when I type the comand `conda deactivate` nothing happens. Could you elaborate further or if Im missing something?
> 
> thanks

I dont remember if i got any "confirmation" that something happened, but you are supposed to run the `windows_run.bat` file again.
