### ISSUE TITLE
google.protobuf.message.DecodeError: Error parsing message with type 'onnx.ModelProto'

### ISSUE THREAD

**Issue by YashaRektr** [C0untFloyd/roop-unleashed#919]
**Describe the bug**
google.protobuf.message.DecodeError: Error parsing message with type 'onnx.ModelProto'

**To Reproduce**
Run the start button

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
4.2.8
windows with nvidia gpu

**Screenshots**
![image](https://github.com/user-attachments/assets/d4f2643e-5bd2-48fb-a741-7cee1990c226)

**Comment by C0untFloyd** [comment]
Very likely that one of the models got corrupted during download. You could try downloading them manually from this release:
https://github.com/C0untFloyd/roop-unleashed/releases/tag/v3.9.0

**Comment by akshat732** [comment]
where to paste it
