### ISSUE TITLE
Feature Request: Restore Original Eye Area

### ISSUE THREAD

**Issue by SrGrafoasspee** [C0untFloyd/roop-unleashed#923]
Sometimes when swapping a video, in scenes where the eyes are closed, it starts showing eyes in the output.
Also, when swapping still images, the eyes get messed up when the eye color differs from the source.
Just like the **restore original mouth area** option a restore original eye area option will be great.

**Comment by C0untFloyd** [comment]
I'm not sure that would be an option I would use at all. Even the mouth restore thing very much destroys the face likeness and even more if changing the eyes. Did you try using https://github.com/KwaiVGI/LivePortrait for this?
