### ISSUE TITLE
Detected: PUA:Win32/FRProxy

### ISSUE THREAD

**Issue by OneNiNE87** [C0untFloyd/roop-unleashed#924]
![image](https://github.com/user-attachments/assets/e0f878b9-351b-4901-83fe-27353574a603)

Why?

**Comment by zappityzap** [comment]
False positive. It's a library used by Gradio to allow sharing a public link (share=True).

https://github.com/gradio-app/gradio/issues/3230

**Comment by OneNiNE87** [comment]
Ahh, I see. Thanks, you saved me some Ghidra Time, lol.
