### ISSUE TITLE
Edge error

### ISSUE THREAD

**Issue by wangke8023** [C0untFloyd/roop-unleashed#928]
**Describe the bug**
Can't do any clicks

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ✅] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ✅] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac
![image](https://github.com/user-attachments/assets/29e94b02-a2cc-41b1-9cb0-f1322e97d63c)

**Comment by PJF16** [comment]
Did you disable GPU acceleration in your browser?

**Comment by wangke8023** [comment]
> -----------谷歌翻译-----------您是否在浏览器中禁用了 GPU 加速？

Thank you. With GPU acceleration on, there you go
