### ISSUE TITLE
GIF Support?

### ISSUE THREAD

**Issue by C0untFloyd** [C0untFloyd/roop-unleashed#93]
### Discussed in https://github.com/C0untFloyd/roop-unleashed/discussions/90

<div type='discussions-op-text'>

<sup>Originally posted by **TrickleDownClown** August 12, 2023</sup>
Whenever I load up a GIF to test I get the following error when pressing "Start"

Error
[WinError 2] The system cannot find the file specified.

What am I doing wrong?</div>

**Comment by eniora** [comment]
Just tested multiple gifs, all work fine here with successful swapping. One of the reasons I liked web ui unleashed is its ability to fully support gifs.
I also just tested to add a gif on both source (to extract face) and for target, all fine.
@TrickleDownClown maybe you have some codec pack installed that's conflicting with roop and its ability to use gifs?

**Comment by TrickleDownClown** [comment]
Thanks for the replies guys.  Count, your link is broken so I can't see the possible solution.

**Comment by C0untFloyd** [comment]
Created a new issue from your discussion, that's why the link is broken.
