### ISSUE TITLE
Really slow performance

### ISSUE THREAD

**Issue by talbertj20** [C0untFloyd/roop-unleashed#931]
I'm not sure what is going on but I am getting errors in the following sections and really poor performance. It takes forever even to just launch ROOP Unleashed. I have been issue free for several months and this just recently started.

Any type of swapping or enhancing is now painfully slow.

There are no other errors or issues that i can see other than what is in the screenshots. All of the rest  are "Requirement already satisfied".

System Specs:
Windows 11
AMD Ryzen 7 5800X3D
32GB RAM
NVIDIA GeForce RTX 4070 Ti SUPER OC Edition
CUDA 11.8 Installed
roop unleashed 4.2.8
ROOP-Unleashed installed on ExFat Volume
Provider = cuda

![image](https://github.com/user-attachments/assets/64d351b7-4eb4-4834-bcae-eeeccd46fe35)

![image](https://github.com/user-attachments/assets/d37b7c09-0954-4648-a0ac-01f651f271b9)

**Comment by C0untFloyd** [comment]
As the error above says, this is dubious. You installed the app onto a drive you're not allowed to (you're not the owner). Is the "X" drive a network drive or something you've mounted? I believe this could be a reason for the poor performance. You can easily test if this is the reason by moving/running the whole roop-unleashed-main folder to a different drive. Everything else looks ok to me and a 4070 RTX should be quite fast.

**Comment by talbertj20** [comment]
It is a mounted exfat volume. I have had my install on this volume for months with no performance issues until recently. 

What are the errors about "darwin" and "arm64" not matching my environment?

**Comment by C0untFloyd** [comment]
> I have had my install on this volume for months with no performance issues until recently.

It's easy to test if that's the reason isn't it?

> What are the errors about "darwin" and "arm64" not matching my environment?

It says 'ignoring' not error. The installer ignores those packages because they are not for your windows os.
