### ISSUE TITLE
ModuleNotFoundError: No module named 'encodings'

### ISSUE THREAD

**Issue by Dcode1999** [C0untFloyd/roop-unleashed#933]
Downloading Miniconda from https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe to F:\AI-DEEP\roop-unleashed-main\installer\installer_files\miniconda_installer.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 85.5M  100 85.5M    0     0  6135k      0  0:00:14  0:00:14 --:--:-- 6050k
Installing Miniconda to F:\AI-DEEP\roop-unleashed-main\installer\installer_files\conda
Miniconda version:
conda 24.7.1
Creating Conda Environment
Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: F:\AI-DEEP\roop-unleashed-main\installer\installer_files\env

  added / updated specs:
    - python=3.10

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-3.0.15             |       h827c3e9_0         7.8 MB
    pip-24.2                   |  py310haa95532_0         2.5 MB
    python-3.10.14             |       he1021f5_1        15.9 MB
    setuptools-75.1.0          |  py310haa95532_0         1.6 MB
    vc-14.40                   |       h2eaa2aa_1          10 KB
    vs2015_runtime-14.40.33807 |       h98bb1dd_1         1.3 MB
    wheel-0.44.0               |  py310haa95532_0         138 KB
    ------------------------------------------------------------
                                           Total:        29.2 MB

The following NEW packages will be INSTALLED:

  bzip2              pkgs/main/win-64::bzip2-1.0.8-h2bbff1b_6
  ca-certificates    pkgs/main/win-64::ca-certificates-2024.7.2-haa95532_0
  libffi             pkgs/main/win-64::libffi-3.4.4-hd77b12b_1
  openssl            pkgs/main/win-64::openssl-3.0.15-h827c3e9_0
  pip                pkgs/main/win-64::pip-24.2-py310haa95532_0
  python             pkgs/main/win-64::python-3.10.14-he1021f5_1
  setuptools         pkgs/main/win-64::setuptools-75.1.0-py310haa95532_0
  sqlite             pkgs/main/win-64::sqlite-3.45.3-h2bbff1b_0
  tk                 pkgs/main/win-64::tk-8.6.14-h0416ee5_0
  tzdata             pkgs/main/noarch::tzdata-2024a-h04d1e81_0
  vc                 pkgs/main/win-64::vc-14.40-h2eaa2aa_1
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.40.33807-h98bb1dd_1
  wheel              pkgs/main/win-64::wheel-0.44.0-py310haa95532_0
  xz                 pkgs/main/win-64::xz-5.4.6-h8cc25b3_1
  zlib               pkgs/main/win-64::zlib-1.2.13-h8cc25b3_1

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate F:\AI-DEEP\roop-unleashed-main\installer\installer_files\env
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Python path configuration:
  PYTHONHOME = 'C:\Users\Digamber\AppData\Local\Programs\Python\Python310'
  PYTHONPATH = (not set)
  program name = 'F:\AI-DEEP\roop-unleashed-main\installer\installer_files\conda\python.exe'
  isolated = 0
  environment = 1
  user site = 1
  safe_path = 0
  import site = 1
  is in build tree = 0
  stdlib dir = 'C:\Users\Digamber\AppData\Local\Programs\Python\Python310\Lib'
  sys._base_executable = 'F:\\AI-DEEP\\roop-unleashed-main\\installer\\installer_files\\conda\\python.exe'
  sys.base_prefix = 'C:\\Users\\Digamber\\AppData\\Local\\Programs\\Python\\Python310'
  sys.base_exec_prefix = 'C:\\Users\\Digamber\\AppData\\Local\\Programs\\Python\\Python310'
  sys.platlibdir = 'DLLs'
  sys.executable = 'F:\\AI-DEEP\\roop-unleashed-main\\installer\\installer_files\\conda\\python.exe'
  sys.prefix = 'C:\\Users\\Digamber\\AppData\\Local\\Programs\\Python\\Python310'
  sys.exec_prefix = 'C:\\Users\\Digamber\\AppData\\Local\\Programs\\Python\\Python310'
  sys.path = [
    'F:\\AI-DEEP\\roop-unleashed-main\\installer\\installer_files\\conda\\python312.zip',
    'C:\\Users\\Digamber\\AppData\\Local\\Programs\\Python\\Python310\\DLLs',
    'C:\\Users\\Digamber\\AppData\\Local\\Programs\\Python\\Python310\\Lib',
    'F:\\AI-DEEP\\roop-unleashed-main\\installer\\installer_files\\conda',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000020f8 (most recent call first):
  <no Python frame>

ERROR: Miniconda hook not found.
Press any key to continue . . .

**Comment by C0untFloyd** [comment]
Googling shows that might be caused by several python installations and/or an already set Python PATH. I can't really help you with that, I'm sorry.

**Comment by Dcode1999** [comment]
@rem activate installer env
    call "%CONDA_ROOT_PREFIX%\condabin\conda.bat" activate "%INSTALL_ENV_DIR%" || ( echo. && echo ERROR: Miniconda hook not found. && goto end )



I was reviewing the .bat file, and I came across a particular line that's generating the mentioned error.
