### ISSUE TITLE
Feature request - please put latest versions of installer.py and windows_run.bat in the main repo

### ISSUE THREAD

**Issue by SoftologyPro** [C0untFloyd/roop-unleashed#934]
The lastest installer.py and windows_run.bat used to be in the main git repo.
Now they are updated only in the installer zip files?
Please update the repo with the latest versions.

I include support for Roop-Unleashed in Visions of Chaos.  Having the latest in the repository allows any user to easily upgrade to the latest version of Roop-Unleashed.  With the versioned zip files for the install files I need to make tweaks every time you make an update.

You could still distribute versioned zips for people who want an older version, but the git should always be the latest.

**Comment by C0untFloyd** [comment]
Done. Besides, you can always update to the latest version even when using a very old installer or isn't it included in your repo?
Good job on visions of chaos, I know it from years ago when it was "only" a cool Julia/Mandelbrot Generator.

**Comment by SoftologyPro** [comment]
Thanks.  The way I handle the install from Visions of Chaos is to git clone the repository and run the windows_run.bat from there.  Now that the main git repo is updated I don't have to worry about the extra installer zips again.
