### ISSUE TITLE
good morning

### ISSUE THREAD

**Issue by SoulCZ** [C0untFloyd/roop-unleashed#938]
Hello, I have an amd 6700xt GPU and for God's sake I can't run the program on the GPU.. I already installed ubuntu through the terminal to find the path and everything around .. But I'm stuck on ROCm .. for God's sake I can't install .. I've been installing all day together with CHATGPT and I uninstall everything possible and nothing.. does anyone have experience with this? How to get it working on AMD 6700xt .. Thanks for your reply

**Comment by C0untFloyd** [comment]
> I've been installing all day together with CHATGPT

So much for having AGI in some years 🤣 
Anyway, for AMD Users DirectML is the thing to use https://github.com/C0untFloyd/roop-unleashed/wiki/Installation#installation
https://github.com/C0untFloyd/roop-unleashed/discussions/428
Note that it will still read "Using CPU" but processing will be a lot faster...
