### ISSUE TITLE
All input faces    Renforcement

### ISSUE THREAD

**Issue by Didier-Eloy** [C0untFloyd/roop-unleashed#940]
Hello, thank you for this new function: "All input faces", it's really great 

After running a number of tests, we could further improve the ergonomics to make it easier to move input faces. Here are a few suggestions: 

1.  When you select an input face and move it to the left, for example, using the "Move" windows, the input face moves but does not remain selected, so if you want to move it again you have to reselect it. In addition, it is no longer centred in the face window. 

Suggested modifications 1:   
The face should remain selected, centred in the window, so that it moves each time it is clicked in the "Move" window. 

Suggested modifications 2 would be even more ergonomic : 
. Hold the face selection with the left mouse click
. Move left or right by moving to the edge of the window 
. Release the left mouse click.  The selected face is moved and the other faces are shifted to the right. 

This more intuitive method makes it possible to eliminate the 4 "Move" windows, as this method can also be applied to the "Target faces setting". 

Thank you for all your hard work.

**Comment by C0untFloyd** [comment]
Thanks for your suggestion and I certainly would have made it that way if it would be possible.
You could addressfunctionality like that to the guys developing the web ui framework -> https://www.gradio.app/

**Comment by Didier-Eloy** [comment]
Good evening, thank you for your feedback. 

I didn't know this was a limitation of the Gradio interface.

I'll submit the idea to them

Have a nice evening





----- Mail original -----
De: "C0untFloyd" ***@***.***>
À: "C0untFloyd/roop-unleashed" ***@***.***>
Cc: "Didier-Eloy" ***@***.***>, "Author" ***@***.***>
Envoyé: Mardi 1 Octobre 2024 17:40:52
Objet: Re: [C0untFloyd/roop-unleashed] All input faces    Renforcement (Issue #940)





Thanks for your suggestion and I certainly would have made it that way if it would be possible. 
You could addressfunctionality like that to the guys developing the web ui framework -> https://www.gradio.app/
