### ISSUE TITLE
[Docker] - Failed to load library libonnxruntime_providers_cuda.so with error: libcurand.so.10: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by fahadshery** [C0untFloyd/roop-unleashed#941]
**Describe the bug**
Used your `Dockerfile` to build and run image...

It works fine but I see the following error in the logs:
```
2024-10-01 14:01:48.248135370 [E:onnxruntime:Default, provider_bridge_ort.cc:1548 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1209 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcurand.so.10: cannot open shared object file: No such file or directory
```

**To Reproduce**
1. Clone the repo
2. docker run

**Details**
What OS are you using?
- [ ] Linux

Are you using a GPU?
- [ ] NVIDIA Tesla P40

**Which version of roop unleashed are you using?**
latest??

**Screenshots**
![image](https://github.com/user-attachments/assets/fe0c9041-d14a-4f36-9129-0948fa253721)

**Comment by fahadshery** [comment]
When I tried with a small video, it's not even using GPU:
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/762e8a73-57f2-4c96-b27e-2e0113b3b92a">

However, when I exec into the container, I can see my GPU from `inside` the container:
<img width="947" alt="image" src="https://github.com/user-attachments/assets/315e3c47-c2e1-4db1-a603-83ecf0e7a4eb">

**Comment by C0untFloyd** [comment]
AFAIK (the docker image isn't by me) this image is created for running on cpu-only. Feel free to change this to support cuda cpus too, I'd happily include it.
