### ISSUE TITLE
Problem with picture face swap

### ISSUE THREAD

**Issue by ChristopherBeaurain** [C0untFloyd/roop-unleashed#942]
**Describe the bug**

**To Reproduce**
Just try to swap face a picture

**Details**
What OS are you using?
- [ ] Windows 

Are you using a GPU?
- [ ] NVIDIA

**Which version of roop unleashed are you using?**
the last version

Previously, everything was working well. When I try to swap faces in a video, everything functions correctly. However, with an image, the program tells me the work is finished, but I don't receive any output. The problem occurs every time after I attempted to perform face swaps on four images at once. I have tried reinstalling everything multiple times, but it still doesn't work. I have a powerful PC.

**Comment by C0untFloyd** [comment]
Please show your terminal output. I'm happily swapping faces almost every day, I know it's working.

**Comment by ChristopherBeaurain** [comment]
Hi, the terminal just say : Processing: 100%|█████████████████████████| 1/1 [00:09<00:00,  9.49s/frame, memory_usage=01.18GB, execution_threads=30]
Finished

i tried with the previous version now and same problem

**Comment by C0untFloyd** [comment]
What about previewing? Does that work? Did you have a look into the output folder?

> execution_threads=30

This has nothing to do with your issue but running 30 threads is very likely about 22 threads too many.

**Comment by ChristopherBeaurain** [comment]
The previewing work, and no file in output folder, do you think it's useles to put 30 thread if i can ? i have a 4090

**Comment by ChristopherBeaurain** [comment]
And thank you a lot for your reply, only previewing work for picture. But for video everything is fine

**Comment by C0untFloyd** [comment]
Is it in the list of processed files at the end? Is it displayed when you click on the name?
What's your setting in the settings tab? Mine looks like this
![setting](https://github.com/user-attachments/assets/dd8618b7-5f7c-4fe6-90f7-84e80043d81a)

Are you updating roop manually? If so, do you remember to update packages by doing 'pip install -r requirements.txt'?

**Comment by ChristopherBeaurain** [comment]
I tried everything, for real, i tried all settings possible, reinstall everything, take an old version, nothing work for the output of swaping picture :'(

**Comment by C0untFloyd** [comment]
Well, you can always save the image from the preview, there's no difference at all.
You didn't answer my question ->s it in the list of processed files at the end? Is it displayed when you click on the name?

**Comment by C0untFloyd** [comment]
Could it be a filename problem like #947 ?
