### ISSUE TITLE
Privacy Risks Need for Review

### ISSUE THREAD

**Issue by albu-ali** [C0untFloyd/roop-unleashed#944]
**Describe the bug**
This issue highlights privacy concerns with software connecting to domains like **cloudflare.com** and **fonts.gstatic.com** while using the local loopback address (127.0.0.1). These connections can expose the user's IP address, revealing their location and ISP, which increases vulnerability to targeted attacks. To mitigate these risks, it is essential to remove any unnecessary software that makes these connections to ensure a safer browsing experience.

**To Reproduce**
1. Go to 'http://127.0.0.1:7860/'
2. Install the NoScript extension  
3. Click on the NoScript extension icon  
4. You will see all the script and it's domains  

**Screenshots**
![roop-domains](https://github.com/user-attachments/assets/6c051f24-952f-40db-b640-3a7dcadf1473)

**Comment by C0untFloyd** [comment]
Ok, this might be interesting for the gradio devs. You can send them security concerns here -> https://github.com/gradio-app/gradio/security/advisories/new

(I'm only using their networking and web UI API)
