### ISSUE TITLE
Images will not be saved successfully if Chinese characters or special characters are encountered during the conversion.

### ISSUE THREAD

**Issue by newlife0007** [C0untFloyd/roop-unleashed#947]
The video and image have the same name. The video can be successfully generated in the output, but the image cannot be successfully generated in the output.

Image console output:
Sorting videos/images
Processing image(s)
Processing: 100%|██████████████████████████| 1/1 [00:17<00:00, 17.30s/frame, memory_usage=01.98GB, execution_threads=8]
Finished

Video console output:
Processing 希望你梦里有我 http___t.cn_A6EvR-我是小花花1331-20240918-Oxw5F2Eun_21-34-11.mp4 took 74.12 secs, 3.71 frames/s
Finished

The file names are:

希望你梦里有我 http___t.cn_A6EvR-我是小花花1331-20240918-Oxw5F2Eun.jpg
希望你梦里有我 http___t.cn_A6EvR-我是小花花1331-20240918-Oxw5F2Eun.mp4

**Comment by C0untFloyd** [comment]
I'm hoping I fixed this with https://github.com/C0untFloyd/roop-unleashed/commit/f0950c276adaa404392cfed0c33e030c163eb5b4

Please test and give me some feedback!

**Comment by newlife0007** [comment]
After testing, this bug has been fixed. Thank you.
