### ISSUE TITLE
Deepfake "remaining" face when obstacles are in the way?

### ISSUE THREAD

**Issue by tamerkalieh** [C0untFloyd/roop-unleashed#950]
Hello,

The problem happens when using a live camera or simply using it on videos. When any object hits the face, even if it's just a tiny object that covers the face by 2-10%, a wider area around the obstacle bugs out, and it looks like two layers (old and new faces) are on top of each other.

Is there a way to fix it?

Using:
roop unleashed 4.1.4
python: 3.10.14 • torch: 2.1.2+cu118 • gradio: 4.38.1
Codeformer as post-processing

A great example where I experience it is when using a video where I pet a dog and the dog licks over the face or covers it by a tiny bit.

**Comment by C0untFloyd** [comment]
Activate xseg masking in the faceswap tab.
