### ISSUE TITLE
DMDNet - Shows tile edges (box) around the head

### ISSUE THREAD

**Issue by AlonDan** [C0untFloyd/roop-unleashed#96]
**Describe the bug**
When using DMDNet post-processing it shows tile edges (box) around the head

**To Reproduce**
Just use DMDNet and preview to see the issue

**Details**
What OS are you using?
- [x] Windows 

Are you using a GPU?
- [x] NVIDIA

**Which version of roop unleashed are you using?**
Latest main 2.7.2 (gradio)

**Screenshots**
![DMDNet - box tiled on edges](https://github.com/C0untFloyd/roop-unleashed/assets/21152334/6b901902-c6de-48ed-a2ca-2ac7c75ff90e)

**Comment by C0untFloyd** [comment]
Yeah DMDNet is still WIP and this is just the generic version. But at least it's fast! 😉

**Comment by C0untFloyd** [comment]
#161
