### ISSUE TITLE
Video - teeth are always distorted and deformed... 

### ISSUE THREAD

**Issue by kashish3333** [C0untFloyd/roop-unleashed#960]
**Describe the bug**

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**

**Screenshots**

**Comment by sparking-meteor** [comment]
This is the best and most detailed issue I've ever seen

**Comment by kashish3333** [comment]
sorry you're right, however title says it all. No matter which post-processing i select, the software just can't generate normal looking teeth

> This is the best and most detailed issue I've ever seen

**Comment by C0untFloyd** [comment]
https://github.com/C0untFloyd/roop-unleashed/discussions/875
