### ISSUE TITLE
Refuses to upload image

### ISSUE THREAD

**Issue by Franznatayada** [C0untFloyd/roop-unleashed#962]
**Describe the bug**

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [✓ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ✓] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

Roop unleased 4.3.3

Refuses to upload image, I can't upload, please help

![Capture](https://github.com/user-attachments/assets/21a4dd6e-b609-4a7b-bba7-ad941f9a4cde)

**Comment by C0untFloyd** [comment]
Addblocker, NoScript Addon, tried a different Browser?
