### ISSUE TITLE
Albumentations issue on colab and paperspace

### ISSUE THREAD

**Issue by Kingkladzemcr** [C0untFloyd/roop-unleashed#966]
running colab notebook on both colab and paperspace is showing the following with no link to gradio:

"/usr/local/lib/python3.10/dist-packages/albumentations/__init__.py:13: UserWarning: A new version of Albumentations is available: 1.4.20 (you have 1.4.15). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()
Downloading https://huggingface.co/countfloyd/deepfake/resolve/main/inswapper_128.onnx: 529MB [00:04, 131MB/s]               
Downloading https://huggingface.co/countfloyd/deepfake/resolve/main/GFPGANv1.4.onnx: 325MB [00:01, 177MB/s]               
Downloading https://github.com/csxmli2016/DMDNet/releases/download/v1/DMDNet.pth: 576MB [00:04, 125MB/s]               
Downloading https://huggingface.co/countfloyd/deepfake/resolve/main/GPEN-BFR-512.onnx: 271MB [00:02, 98.7MB/s]              
Downloading https://huggingface.co/countfloyd/deepfake/resolve/main/restoreformer_plus_plus.onnx: 281MB [00:01, 170MB/s]               
Downloading https://huggingface.co/countfloyd/deepfake/resolve/main/xseg.onnx: 67.1MB [00:00, 89.5MB/s]                
Downloading https://huggingface.co/countfloyd/deepfake/resolve/main/rd64-uni-refined.pth: 4.52MB [00:00, 9.29MB/s]                
Downloading https://huggingface.co/countfloyd/deepfake/resolve/main/CodeFormerv0.1.onnx: 359MB [00:02, 182MB/s]               
Downloading https://huggingface.co/countfloyd/deepfake/resolve/main/deoldify_artistic.onnx: 243MB [00:01, 161MB/s]               
Downloading https://huggingface.co/countfloyd/deepfake/resolve/main/deoldify_stable.onnx: 833MB [00:07, 115MB/s]               
Downloading https://huggingface.co/countfloyd/deepfake/resolve/main/isnet-general-use.onnx: 170MB [00:01, 120MB/s]               
Downloading https://huggingface.co/countfloyd/deepfake/resolve/main/real_esrgan_x4.onnx: 66.3MB [00:00, 88.5MB/s]               
Downloading https://huggingface.co/countfloyd/deepfake/resolve/main/real_esrgan_x2.onnx: 66.3MB [00:00, 83.5MB/s]               
Downloading https://huggingface.co/countfloyd/deepfake/resolve/main/lsdir_x4.onnx: 63.9MB [00:00, 87.3MB/s]                
Number of CUDA devices: 1 Currently used Id: 0 Device Name: Tesla T4
Using provider [('CUDAExecutionProvider', {'device_id': 0})] - Device:cuda
Form data requires "python-multipart" to be installed. 
You can install "python-multipart" with: 

pip install python-multipart

Traceback (most recent call last):
  File "/content/roop-unleashed/run.py", line 6, in <module>
    core.run()
  File "/content/roop-unleashed/roop/core.py", line 404, in run
    main.run()
  File "/content/roop-unleashed/ui/main.py", line 66, in run
    with gr.Blocks(title=f'{roop.metadata.name} {roop.metadata.version}', theme=roop.globals.CFG.selected_theme, css=mycss, delete_cache=(60, 86400)) as ui:
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1082, in __init__
    self.queue()
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 2149, in queue
    self.app = routes.App.create_app(self)
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 347, in create_app
    def login(form_data: OAuth2PasswordRequestForm = Depends()):
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 992, in decorator
    self.add_api_route(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 931, in add_api_route
    route = route_class(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 552, in __init__
    self.dependant = get_dependant(path=self.path_format, call=self.endpoint)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 273, in get_dependant
    sub_dependant = get_param_sub_dependant(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 116, in get_param_sub_dependant
    return get_sub_dependant(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 152, in get_sub_dependant
    sub_dependant = get_dependant(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 266, in get_dependant
    param_details = analyze_param(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 461, in analyze_param
    ensure_multipart_is_installed()
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 105, in ensure_multipart_is_installed
    raise RuntimeError(multipart_not_installed_error) from None
RuntimeError: Form data requires "python-multipart" to be installed. 
You can install "python-multipart" with: 

pip install python-multipart"

**Comment by C0untFloyd** [comment]
Gradio issue again:
https://github.com/gradio-app/gradio/issues/9774

**Comment by Kingkladzemcr** [comment]
Was working all ok yesterday 26/10/24

**Comment by C0untFloyd** [comment]
Did you even bother to read the issue?

**Comment by Kingkladzemcr** [comment]
All I was pointing out was the issue surfaced yesterday. I was trying to
highlight the issue and give you more information. No need to be a dick

**Comment by C0untFloyd** [comment]
@Kingkladzemcr Not trying to be a dick but that linked issue clearly states a gradio problem, where I can't do nothing about it. 

In the meantime they believe it fixed:
https://www.gradio.app/changelog#5-4-0

For the time being local installs could change the requirements, on colab you could do a
`pip uninstall gradio`
followed by
`pip install gradio`
to get the latest

**Comment by Kingkladzemcr** [comment]
thanks for the update👍
