### ISSUE TITLE
 Roop Unleashed not launching after installation. Showing a error 

### ISSUE THREAD

**Issue by Spikedocson** [C0untFloyd/roop-unleashed#968]
I don't know much about technicalities but I am getting this error please anyone suggest me what to do
![IMG_20241027_191416_848](https://github.com/user-attachments/assets/d916ccf9-d00b-47a5-b970-add0aa6f598d)

**Comment by SteveH486** [comment]
Tried the
You can install "python-multipart' pip install python-multipart

But did not help, (on RunPod with Stable Diffusion docker image). Was working until 2 days ago. 

Thanks for any help.

**Comment by C0untFloyd** [comment]
#966

**Comment by sunnav** [comment]
### Try This : https://github.com/C0untFloyd/roop-unleashed/issues/1009#issuecomment-2544227796
