### ISSUE TITLE
Heads/Faces on 90+ degrees = Bad Results

### ISSUE THREAD

**Issue by AlonDan** [C0untFloyd/roop-unleashed#97]
**Describe the bug**
If the target head/face is rotate to 90 degrees (or more) the results are bad.
This could be noticeable more if using GFPGAN or any of the other enhancers.
I'm not sure if it's a fixt hat need to be done before post or after, but it's there for a while now.

I suspect it doesn't recognize the face correct on some rotation degrees because sometimes the results could cut the chin or some of the forehead etc..

**To Reproduce**
1. Use any target image with Head rotate to 90 degrees or more.
2. Preview with and without GFPGAN (or any other post-process)

**Details**
What OS are you using?
- [x] Windows 

Are you using a GPU?
- [x] NVIDIA

**Which version of roop unleashed are you using?**
Latest main 2.7.2

**Comment by C0untFloyd** [comment]
Nothing I can do about. The insightface model just doesn't know much about gymnasts doing handstands.
I *could* implement some logic to flip the image if a face is not detected and after swapping flip back, but this is such a border case...I dunno.
