### ISSUE TITLE
TENSORRT is completely unavailable / dependencies torch 2.1.2, onnxruntime-gpu 1.15.1 are fully deprecated

### ISSUE THREAD

**Issue by cdag98** [C0untFloyd/roop-unleashed#973]
Maybe I'm stupid but based on the files available to me online (public files via google) onnxruntime is so much further along in development currently that the files for 1.15.1 are not fully functional any more as they rely on a similarly-outdated torch 2.1.2. I'm assuming TensorRT only works with these file versions, what can I do?

**Comment by kurtn2005** [comment]
> Maybe I'm stupid but based on the files available to me online (public files via google) onnxruntime is so much further along in development currently that the files for 1.15.1 are not fully functional any more as they rely on a similarly-outdated torch 2.1.2. I'm assuming TensorRT only works with these file versions, what can I do?

Use CUDA instead, that's what I do. ;)

**Comment by Maku-Kim** [comment]
> Maybe I'm stupid but based on the files available to me online (public files via google) onnxruntime is so much further along in development currently that the files for 1.15.1 are not fully functional any more as they rely on a similarly-outdated torch 2.1.2. I'm assuming TensorRT only works with these file versions, what can I do?

Please refer my related pip list under Conda with py 3.10.14. @ win10
- onnxruntime-gpu   1.19.2
- tensorrt   10.0.1
- tensorrt-cu12   10.5.0
- tensorrt-cu12_bindings   10.5.0
- tensorrt-cu12_libs   10.5.0
- torch   2.5.0+cu124
- torchaudio   2.5.0+cu124
- torchvision   0.20.0+cu124
